Repository OCA/stock-logistics-warehouse, pull requests merged in 2018-12, with the labels that each got.

#475 [10.0] stock_quant_merge: add ability to disable it on some calls
  stock_quant_merge/__manifest__.py
  stock_quant_merge/models/stock_move.py
Labels: enhancement

#516 [10.0] Migrate stock_location_lockdown
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/readme/CONTRIBUTORS.rst
  stock_location_lockdown/readme/DESCRIPTION.rst
  stock_location_lockdown/readme/USAGE.rst
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: approved, needs review, ready to merge

#476 [9.0][ADD] module stock_location_lockdown for version 9
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__openerp__.py
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/readme/CONTRIBUTORS.rst
  stock_location_lockdown/readme/DESCRIPTION.rst
  stock_location_lockdown/readme/USAGE.rst
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: approved, needs review

#514 [12.0][MIG] account_move_line_stock_info
  account_move_line_stock_info/README.rst
  account_move_line_stock_info/__init__.py
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/i18n/account_move_line_stock_info.pot
  account_move_line_stock_info/i18n/ar.po
  account_move_line_stock_info/i18n/bs.po
  account_move_line_stock_info/i18n/ca.po
  account_move_line_stock_info/i18n/cs.po
  account_move_line_stock_info/i18n/cs_CZ.po
  account_move_line_stock_info/i18n/de.po
  account_move_line_stock_info/i18n/en_GB.po
  account_move_line_stock_info/i18n/es.po
  account_move_line_stock_info/i18n/es_CR.po
  account_move_line_stock_info/i18n/es_EC.po
  account_move_line_stock_info/i18n/es_MX.po
  account_move_line_stock_info/i18n/fi.po
  account_move_line_stock_info/i18n/fr.po
  account_move_line_stock_info/i18n/fr_CH.po
  account_move_line_stock_info/i18n/gl.po
  account_move_line_stock_info/i18n/hr.po
  account_move_line_stock_info/i18n/hr_HR.po
  account_move_line_stock_info/i18n/hu.po
  account_move_line_stock_info/i18n/it.po
  account_move_line_stock_info/i18n/ja.po
  account_move_line_stock_info/i18n/lt.po
  account_move_line_stock_info/i18n/mk.po
  account_move_line_stock_info/i18n/mn.po
  account_move_line_stock_info/i18n/nb.po
  account_move_line_stock_info/i18n/nb_NO.po
  account_move_line_stock_info/i18n/nl.po
  account_move_line_stock_info/i18n/nl_BE.po
  account_move_line_stock_info/i18n/nl_NL.po
  account_move_line_stock_info/i18n/pt.po
  account_move_line_stock_info/i18n/pt_BR.po
  account_move_line_stock_info/i18n/pt_PT.po
  account_move_line_stock_info/i18n/ro.po
  account_move_line_stock_info/i18n/ru.po
  account_move_line_stock_info/i18n/sl.po
  account_move_line_stock_info/i18n/sv.po
  account_move_line_stock_info/i18n/tr.po
  account_move_line_stock_info/i18n/tr_TR.po
  account_move_line_stock_info/i18n/vi_VN.po
  account_move_line_stock_info/i18n/zh_CN.po
  account_move_line_stock_info/i18n/zh_TW.po
  account_move_line_stock_info/models/__init__.py
  account_move_line_stock_info/models/account_move_line.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/readme/CONTRIBUTORS.rst
  account_move_line_stock_info/readme/DESCRIPTION.rst
  account_move_line_stock_info/readme/USAGE.rst
  account_move_line_stock_info/security/ir.model.access.csv
  account_move_line_stock_info/static/description/icon.png
  account_move_line_stock_info/static/description/index.html
  account_move_line_stock_info/tests/__init__.py
  account_move_line_stock_info/tests/test_account_move_line_stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
  account_move_line_stock_info/views/stock_move_view.xml
Labels: approved, needs review, ready to merge

#512 [12.0][MIG] account_move_line_product
  account_move_line_product/README.rst
  account_move_line_product/__init__.py
  account_move_line_product/__manifest__.py
  account_move_line_product/i18n/account_move_line_product.pot
  account_move_line_product/i18n/ca.po
  account_move_line_product/i18n/cs_CZ.po
  account_move_line_product/i18n/de.po
  account_move_line_product/i18n/el_GR.po
  account_move_line_product/i18n/es.po
  account_move_line_product/i18n/es_ES.po
  account_move_line_product/i18n/eu.po
  account_move_line_product/i18n/fi.po
  account_move_line_product/i18n/fr.po
  account_move_line_product/i18n/fr_CH.po
  account_move_line_product/i18n/fr_FR.po
  account_move_line_product/i18n/gl.po
  account_move_line_product/i18n/hr.po
  account_move_line_product/i18n/hr_HR.po
  account_move_line_product/i18n/it.po
  account_move_line_product/i18n/nl.po
  account_move_line_product/i18n/nl_NL.po
  account_move_line_product/i18n/pt.po
  account_move_line_product/i18n/pt_BR.po
  account_move_line_product/i18n/ro.po
  account_move_line_product/i18n/ru.po
  account_move_line_product/i18n/sl.po
  account_move_line_product/i18n/tr.po
  account_move_line_product/i18n/tr_TR.po
  account_move_line_product/i18n/vi_VN.po
  account_move_line_product/i18n/zh_CN.po
  account_move_line_product/readme/CONTRIBUTORS.rst
  account_move_line_product/readme/DESCRIPTION.rst
  account_move_line_product/static/description/icon.png
  account_move_line_product/static/description/index.html
  account_move_line_product/views/account_move_line_view.xml
Labels: approved, needs review, ready to merge

#448 [WIP][ADD] stock_picking_procure_method: New module
  stock_picking_procure_method/README.rst
  stock_picking_procure_method/__init__.py
  stock_picking_procure_method/__manifest__.py
  stock_picking_procure_method/models/__init__.py
  stock_picking_procure_method/models/stock_picking.py
  stock_picking_procure_method/readme/CONFIGURE.rst
  stock_picking_procure_method/readme/CONTRIBUTORS.rst
  stock_picking_procure_method/readme/DESCRIPTION.rst
  stock_picking_procure_method/readme/INSTALL.rst
  stock_picking_procure_method/readme/USAGE.rst
  stock_picking_procure_method/tests/__init__.py
  stock_picking_procure_method/tests/test_stock_picking_procure_method.py
  stock_picking_procure_method/views/stock_picking_views.xml
Labels: approved, ready to merge
