Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-07, with the labels that each got.

#614 [11.0][IMP] procurement_auto_create_group: ensure that the procurement group is only created in the procurment process.
  procurement_auto_create_group/models/procurement_group.py
Labels: approved, ready to merge, work in progress

#645 [FIX] stock_request: Allow users to delete stock requests
  stock_request/README.rst
  stock_request/readme/CONFIGURE.rst
  stock_request/readme/DESCRIPTION.rst
  stock_request/readme/USAGE.rst
  stock_request/security/ir.model.access.csv
  stock_request/static/description/index.html
Labels: approved, enhancement, needs review

#652 [IMP] stock_request: Allow to set to draft multiple records
  stock_request/models/stock_request.py
Labels: approved, enhancement, needs review

#658 [12.0][IMP] dependencies
  stock_orderpoint_manual_procurement/__manifest__.py
  stock_orderpoint_uom/__manifest__.py
Labels: approved

#660 [12.0][FIX] stock_request_purchase: remove sudo
  stock_request_purchase/models/stock_request.py
  stock_request_purchase/models/stock_request_order.py
  stock_request_purchase/views/purchase_order_views.xml
  stock_request_purchase/views/stock_request_order_views.xml
  stock_request_purchase/views/stock_request_views.xml
Labels: approved

#666 [FIX] stock_request: add missing expected_date value on tests
  stock_request/tests/test_stock_request.py
Labels: approved, merged 🎉

#667 [FIX] stock_request_purchase: add missing expected_date value on tests
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved

#665 [FIX] stock_request: Losing partner_id and origin (#664)
  stock_request/__manifest__.py
  stock_request/models/__init__.py
  stock_request/models/procurement_group.py
  stock_request/tests/test_stock_request.py
Labels: approved, bug, needs review

#663 [ADD] stock_inventory_cost_info: new module
  stock_inventory_cost_info/README.rst
  stock_inventory_cost_info/__init__.py
  stock_inventory_cost_info/__manifest__.py
  stock_inventory_cost_info/hooks.py
  stock_inventory_cost_info/i18n/es.po
  stock_inventory_cost_info/models/__init__.py
  stock_inventory_cost_info/models/stock_inventory.py
  stock_inventory_cost_info/readme/CONTRIBUTORS.rst
  stock_inventory_cost_info/readme/DESCRIPTION.rst
  stock_inventory_cost_info/readme/INSTALL.rst
  stock_inventory_cost_info/readme/USAGE.rst
  stock_inventory_cost_info/static/description/index.html
  stock_inventory_cost_info/tests/__init__.py
  stock_inventory_cost_info/tests/test_stock_inventory_cost_info.py
  stock_inventory_cost_info/views/report_stockinventory.xml
  stock_inventory_cost_info/views/stock_inventory_views.xml
Labels: approved, ready to merge

#670 [12.0] stock_request: Add order desc for SR and SRO
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
Labels: approved

#529 [11.0][stock_account_inventory_force_date]
  stock_account_inventory_force_date/__init__.py
  stock_account_inventory_force_date/__manifest__.py
  stock_account_inventory_force_date/models/__init__.py
  stock_account_inventory_force_date/models/res_company.py
  stock_account_inventory_force_date/models/stock_inventory.py
  stock_account_inventory_force_date/models/stock_inventory_line.py
  stock_account_inventory_force_date/models/stock_move.py
  stock_account_inventory_force_date/models/stock_move_line.py
  stock_account_inventory_force_date/security/stock_account_inventory_force_date_security.xml
  stock_account_inventory_force_date/tests/__init__.py
  stock_account_inventory_force_date/tests/test_stock_inventory_force_date.py
  stock_account_inventory_force_date/views/res_company_view.xml
  stock_account_inventory_force_date/views/stock_inventory_view.xml
Labels: approved
