Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-12, with the labels that each got.

#764 [11.0][IMP] stock_orderpoint_generator: auto values
  stock_orderpoint_generator/README.rst
  stock_orderpoint_generator/__manifest__.py
  stock_orderpoint_generator/i18n/es.po
  stock_orderpoint_generator/i18n/stock_orderpoint_generator.pot
  stock_orderpoint_generator/models/orderpoint_template.py
  stock_orderpoint_generator/models/product.py
  stock_orderpoint_generator/readme/CONTRIBUTORS.rst
  stock_orderpoint_generator/readme/USAGE.rst
  stock_orderpoint_generator/static/description/index.html
  stock_orderpoint_generator/tests/test_orderpoint_generator.py
  stock_orderpoint_generator/views/orderpoint_template_views.xml
  stock_orderpoint_generator/wizard/orderpoint_generator.py
Labels: approved, enhancement, ready to merge

#775 [10.0] Add missing index
  stock_mts_mto_rule/model/procurement.py
Labels: approved, needs review

#776 [8.0] Add missing index
  stock_mts_mto_rule/model/procurement.py
Labels: 8.0, approved, needs review

#784 Revert "[IMP] stock_available_mrp: Easier and faster BoM finding"
  stock_available_mrp/models/product_product.py
Labels: approved

#777 [9.0] Add missing index
  stock_mts_mto_rule/__openerp__.py
  stock_mts_mto_rule/model/procurement.py
Labels: approved, needs review

#809 [12.0][UPD] stock_available_unreserved: update copyright/license
  stock_available_unreserved/README.rst
  stock_available_unreserved/__init__.py
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/models/__init__.py
  stock_available_unreserved/models/product.py
  stock_available_unreserved/models/quant.py
  stock_available_unreserved/readme/CONTRIBUTORS.rst
  stock_available_unreserved/readme/DESCRIPTION.rst
  stock_available_unreserved/static/description/index.html
  stock_available_unreserved/tests/__init__.py
  stock_available_unreserved/tests/test_stock_available_unreserved.py
Labels: approved
