Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-08, with the labels that each got.

#672 [ADD] stock_request_direction
  stock_request_direction/README.rst
  stock_request_direction/__init__.py
  stock_request_direction/__manifest__.py
  stock_request_direction/models/__init__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
  stock_request_direction/readme/CONTRIBUTORS.rst
  stock_request_direction/readme/DESCRIPTION.rst
  stock_request_direction/readme/USAGE.rst
  stock_request_direction/static/description/icon.png
  stock_request_direction/views/res_config_settings.xml
  stock_request_direction/views/stock_request_order_views.xml
  stock_request_direction/views/stock_request_views.xml
Labels: approved, enhancement, needs review

#679 [FIX] stock_request_direction: Method Name
  stock_request_direction/models/stock_request_order.py
Labels: approved, bug, needs review

#686 [FIX] stock_request: Unable to activate the virtual locations
  stock_request/__manifest__.py
  stock_request/models/res_config_settings.py
  stock_request/views/res_config_settings_views.xml
Labels: approved, bug, needs review

#579 [11.0][IMP] stock_orderpoint_move_link
  stock_orderpoint_move_link/README.rst
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/models/__init__.py
  stock_orderpoint_move_link/models/procurement_group.py
  stock_orderpoint_move_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_move_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_move_link/readme/DESCRIPTION.rst
  stock_orderpoint_move_link/static/description/index.html
  stock_orderpoint_move_link/tests/__init__.py
  stock_orderpoint_move_link/tests/test_stock_orderpoint_move_link.py
  stock_orderpoint_move_link/views/stock_move_views.xml
Labels: approved, enhancement
