Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-02, with the labels that each got.

#538 [FIX+IMP] stock_inventory_exclude_sublocation: Don't mess inheritance
  stock_inventory_exclude_sublocation/README.rst
  stock_inventory_exclude_sublocation/__manifest__.py
  stock_inventory_exclude_sublocation/models/stock_inventory.py
  stock_inventory_exclude_sublocation/static/description/index.html
  stock_inventory_exclude_sublocation/views/stock_inventory_view.xml
Labels: enhancement, needs review

#541 [FIX] stock_move_location: fix the 'group_lines()' method
  stock_move_location/__manifest__.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
Labels: approved, enhancement

#542 [10.0][FIX] purchase_packaging: Improve tests
  purchase_packaging/__manifest__.py
  purchase_packaging/tests/test_procurement_order.py
Labels: needs review

#280 [10.0][MIG] port stock_available_mrp to 10.0
  setup/stock_available_mrp/odoo/__init__.py
  setup/stock_available_mrp/odoo/addons/__init__.py
  setup/stock_available_mrp/odoo/addons/stock_available_mrp
  setup/stock_available_mrp/setup.py
  stock_available_mrp/README.rst
  stock_available_mrp/__manifest__.py
  stock_available_mrp/demo/mrp_bom.yml
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/models/product_product.py
  stock_available_mrp/models/product_template.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_available_mrp/views/product_template_view.xml
Labels: needs review

#524 [11.0] [IMP] stock_change_qty_reason
  stock_change_qty_reason/README.rst
  stock_change_qty_reason/__manifest__.py
  stock_change_qty_reason/models/__init__.py
  stock_change_qty_reason/models/res_config_settings.py
  stock_change_qty_reason/models/stock_inventory_line.py
  stock_change_qty_reason/models/stock_inventory_line_reason.py
  stock_change_qty_reason/models/stock_move.py
  stock_change_qty_reason/readme/CONFIGURE.rst
  stock_change_qty_reason/readme/CONTRIBUTORS.rst
  stock_change_qty_reason/readme/DESCRIPTION.rst
  stock_change_qty_reason/security/ir.model.access.csv
  stock_change_qty_reason/security/stock_security.xml
  stock_change_qty_reason/static/description/index.html
  stock_change_qty_reason/tests/test_stock_change_qty_reason.py
  stock_change_qty_reason/views/base_config_view.xml
  stock_change_qty_reason/views/stock_inventory_line_reason_view.xml
  stock_change_qty_reason/views/stock_inventory_line_view.xml
  stock_change_qty_reason/wizard/stock_change_product_qty.py
  stock_change_qty_reason/wizard/stock_product_change_qty.xml
Labels: approved, enhancement, needs review, ready to merge

#477 [11.0][NEW] stock_secondary_unit: New module for get stock in a secondary unit
  oca_dependencies.txt
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/procurement_rule.py
  stock_secondary_unit/models/product.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, needs review

#545 [11.0][FIX] stock_secondary_unit: Remove procurement_rule move. Fix dependencies
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/procurement_rule.py
Labels: approved, enhancement

#543 [11.0][ADD] stock_orderpoint_mrp_link
  stock_orderpoint_mrp_link/README.rst
  stock_orderpoint_mrp_link/__init__.py
  stock_orderpoint_mrp_link/__manifest__.py
  stock_orderpoint_mrp_link/models/__init__.py
  stock_orderpoint_mrp_link/models/mrp_production.py
  stock_orderpoint_mrp_link/models/procurement_rule.py
  stock_orderpoint_mrp_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_mrp_link/readme/DESCRIPTION.rst
  stock_orderpoint_mrp_link/static/description/icon.png
  stock_orderpoint_mrp_link/static/description/index.html
  stock_orderpoint_mrp_link/tests/__init__.py
  stock_orderpoint_mrp_link/tests/test_stock_orderpoint_mrp_link.py
Labels: approved, needs review
