Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-10, with the labels that each got.

#547 [10.0] [FIX] purchase_packaging avoid conversion error when using uom not in units category
  purchase_packaging/models/procurement_order.py
  purchase_packaging/tests/test_procurement_order.py
Labels: approved, enhancement, ready to merge

#504 [10.0][ADD] packaging_uom_view
  packaging_uom_view/README.rst
  packaging_uom_view/__init__.py
  packaging_uom_view/__manifest__.py
  packaging_uom_view/readme/CONTRIBUTORS.rst
  packaging_uom_view/readme/DESCRIPTION.rst
  packaging_uom_view/readme/USAGE.rst
  packaging_uom_view/static/description/icon.png
  packaging_uom_view/static/description/index.html
  packaging_uom_view/views/product_template.xml
  setup/packaging_uom_view/odoo/__init__.py
  setup/packaging_uom_view/odoo/addons/__init__.py
  setup/packaging_uom_view/odoo/addons/packaging_uom_view
  setup/packaging_uom_view/setup.py
Labels: approved, needs review, ready to merge

#730 [8.0][FIX] .travis: Update to latest template
  .travis.yml
Labels: enhancement

#583 [10.0] stock_product_putaway add wizard to mass update putaway on products
  stock_putaway_product/README.rst
  stock_putaway_product/__manifest__.py
  stock_putaway_product/static/description/default_loc.png
  stock_putaway_product/wizard/__init__.py
  stock_putaway_product/wizard/quick_add_location.py
  stock_putaway_product/wizard/quick_add_location.xml
Labels: approved, needs review

#611 [IMP] stock_available_mrp: Easier and faster BoM finding
  stock_available_mrp/models/product_product.py
Labels: approved, ready to merge

#705 [12.0][FIX] stock_request: Remove Inventory User bypass, not needed in v12
  stock_request/security/stock_request_security.xml
Labels: approved, ready to merge

#734 [Fix] use the same view id for differnt view using in product and pro…
  stock_available/views/product_product_view.xml
  stock_available/views/product_template_view.xml
Labels: approved

#687 [ADD][12.0] create stock_serial_batch_receive
  stock_serial_batch_receive/README.rst
  stock_serial_batch_receive/__init__.py
  stock_serial_batch_receive/__manifest__.py
  stock_serial_batch_receive/models/__init__.py
  stock_serial_batch_receive/models/stock_move.py
  stock_serial_batch_receive/readme/CONTRIBUTORS.rst
  stock_serial_batch_receive/readme/DESCRIPTION.rst
  stock_serial_batch_receive/readme/ROADMAP.rst
  stock_serial_batch_receive/tests/__init__.py
  stock_serial_batch_receive/tests/test_stock_serial_batch.py
  stock_serial_batch_receive/views/stock_move.xml
  stock_serial_batch_receive/wizard/__init__.py
  stock_serial_batch_receive/wizard/stock_move_line_serial_generator.py
  stock_serial_batch_receive/wizard/stock_move_line_serial_generator.xml
Labels: approved, needs review

#735 [11.0][FIX] stock_orderpoint_generator singleton
  stock_orderpoint_generator/models/orderpoint_template.py
Labels: approved, ready to merge
