Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-09, with the labels that each got.

#704 [11.0][FIX] stock_request: force_domain missing on Inventory User bypass
  stock_request/security/stock_request_security.xml
Labels: approved, enhancement, ready to merge

#716 [11.0][FIX] stock_inventory_lockdown: don't check in any case of inventory adjustments
  stock_inventory_lockdown/models/stock_move.py
Labels: approved, ready to merge

#717 [12.0][FIX] stock_inventory_lockdown: don't check in any case of inventory adjustments
  stock_inventory_lockdown/models/stock_move.py
Labels: approved, ready to merge

#726 [12.0][FIX] stock_request: stock request lines were not being copied when duplicating a stock request order
  stock_request/models/stock_request_order.py
Labels: approved

#490 [IMP] account_move_line_product: The product position on the line loo
  account_move_line_product/views/account_move_line_view.xml
Labels: enhancement, needs review

#729 [10.0][FIX] .travis: Update to latest template
  .travis.yml
Labels: enhancement
