Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-04, with the labels that each got.

#550 [12.0][MIG] stock_orderpoint_move_link
  stock_orderpoint_move_link/README.rst
  stock_orderpoint_move_link/__init__.py
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/i18n/stock_orderpoint_move_link.pot
  stock_orderpoint_move_link/models/__init__.py
  stock_orderpoint_move_link/models/stock.py
  stock_orderpoint_move_link/models/stock_move.py
  stock_orderpoint_move_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_move_link/readme/DESCRIPTION.rst
  stock_orderpoint_move_link/static/description/icon.png
  stock_orderpoint_move_link/static/description/index.html
  stock_orderpoint_move_link/tests/__init__.py
  stock_orderpoint_move_link/tests/test_stock_orderpoint_move_link.py
  stock_orderpoint_move_link/views/stock_move_views.xml
Labels: approved, needs review

#568 [12.0][MIG] stock_orderpoint_uom
  stock_orderpoint_uom/README.rst
  stock_orderpoint_uom/__init__.py
  stock_orderpoint_uom/__manifest__.py
  stock_orderpoint_uom/i18n/ca.po
  stock_orderpoint_uom/i18n/de.po
  stock_orderpoint_uom/i18n/es.po
  stock_orderpoint_uom/i18n/es_ES.po
  stock_orderpoint_uom/i18n/es_MX.po
  stock_orderpoint_uom/i18n/fi.po
  stock_orderpoint_uom/i18n/fr.po
  stock_orderpoint_uom/i18n/fr_CH.po
  stock_orderpoint_uom/i18n/hr.po
  stock_orderpoint_uom/i18n/hr_HR.po
  stock_orderpoint_uom/i18n/it.po
  stock_orderpoint_uom/i18n/nl.po
  stock_orderpoint_uom/i18n/nl_NL.po
  stock_orderpoint_uom/i18n/pt_BR.po
  stock_orderpoint_uom/i18n/pt_PT.po
  stock_orderpoint_uom/i18n/ro.po
  stock_orderpoint_uom/i18n/sl.po
  stock_orderpoint_uom/i18n/stock_orderpoint_uom.pot
  stock_orderpoint_uom/i18n/tr.po
  stock_orderpoint_uom/i18n/tr_TR.po
  stock_orderpoint_uom/i18n/vi_VN.po
  stock_orderpoint_uom/i18n/zh_CN.po
  stock_orderpoint_uom/models/__init__.py
  stock_orderpoint_uom/models/procurement_group.py
  stock_orderpoint_uom/models/product_template.py
  stock_orderpoint_uom/models/stock_warehouse_orderpoint.py
  stock_orderpoint_uom/readme/CONFIGURE.rst
  stock_orderpoint_uom/readme/CONTRIBUTORS.rst
  stock_orderpoint_uom/readme/DESCRIPTION.rst
  stock_orderpoint_uom/readme/USAGE.rst
  stock_orderpoint_uom/static/description/index.html
  stock_orderpoint_uom/tests/__init__.py
  stock_orderpoint_uom/tests/test_stock_orderpoint_procure_uom.py
  stock_orderpoint_uom/views/stock_warehouse_orderpoint_view.xml
Labels: approved

#557 [12.0][MIG] stock_orderpoint_manual_procurement
  stock_orderpoint_manual_procurement/README.rst
  stock_orderpoint_manual_procurement/__init__.py
  stock_orderpoint_manual_procurement/__manifest__.py
  stock_orderpoint_manual_procurement/demo/product.xml
  stock_orderpoint_manual_procurement/i18n/stock_orderpoint_manual_procurement.pot
  stock_orderpoint_manual_procurement/models/__init__.py
  stock_orderpoint_manual_procurement/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement/readme/CONFIGURE.rst
  stock_orderpoint_manual_procurement/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement/readme/USAGE.rst
  stock_orderpoint_manual_procurement/security/stock_orderpoint_manual_procurement_security.xml
  stock_orderpoint_manual_procurement/static/description/icon.png
  stock_orderpoint_manual_procurement/static/description/index.html
  stock_orderpoint_manual_procurement/tests/__init__.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement/views/stock_warehouse_orderpoint_view.xml
  stock_orderpoint_manual_procurement/wizards/__init__.py
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint.py
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint_view.xml
Labels: approved, ready to merge

#554 [12.0][MIG] stock_orderpoint_purchase_link
  stock_orderpoint_purchase_link/README.rst
  stock_orderpoint_purchase_link/__init__.py
  stock_orderpoint_purchase_link/__manifest__.py
  stock_orderpoint_purchase_link/models/__init__.py
  stock_orderpoint_purchase_link/models/purchase_order_line.py
  stock_orderpoint_purchase_link/models/stock_rule.py
  stock_orderpoint_purchase_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_purchase_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_purchase_link/readme/DESCRIPTION.rst
  stock_orderpoint_purchase_link/static/description/icon.png
  stock_orderpoint_purchase_link/static/description/index.html
  stock_orderpoint_purchase_link/tests/__init__.py
  stock_orderpoint_purchase_link/tests/test_stock_orderpoint_purchase_link.py
  stock_orderpoint_purchase_link/views/purchase_order_views.xml
Labels: approved, needs review, ready to merge

#556 [12.0][MIG] stock_request: Migrated.
  stock_request/README.rst
  stock_request/__init__.py
  stock_request/__manifest__.py
  stock_request/data/stock_request_sequence_data.xml
  stock_request/i18n/ca.po
  stock_request/i18n/de.po
  stock_request/i18n/el_GR.po
  stock_request/i18n/es.po
  stock_request/i18n/es_ES.po
  stock_request/i18n/eu.po
  stock_request/i18n/fi.po
  stock_request/i18n/fr.po
  stock_request/i18n/fr_CH.po
  stock_request/i18n/fr_FR.po
  stock_request/i18n/gl.po
  stock_request/i18n/hr.po
  stock_request/i18n/hr_HR.po
  stock_request/i18n/it.po
  stock_request/i18n/nl.po
  stock_request/i18n/nl_NL.po
  stock_request/i18n/pt.po
  stock_request/i18n/pt_BR.po
  stock_request/i18n/ro.po
  stock_request/i18n/ru.po
  stock_request/i18n/sl.po
  stock_request/i18n/stock_request.pot
  stock_request/i18n/tr.po
  stock_request/i18n/tr_TR.po
  stock_request/i18n/vi_VN.po
  stock_request/i18n/zh_CN.po
  stock_request/models/__init__.py
  stock_request/models/res_company.py
  stock_request/models/res_config_settings.py
  stock_request/models/stock_location.py
  stock_request/models/stock_location_route.py
  stock_request/models/stock_move.py
  stock_request/models/stock_move_line.py
  stock_request/models/stock_picking.py
  stock_request/models/stock_request.py
  stock_request/models/stock_request_abstract.py
  stock_request/models/stock_request_allocation.py
  stock_request/models/stock_request_order.py
  stock_request/models/stock_rule.py
  stock_request/models/stock_warehouse.py
  stock_request/security/ir.model.access.csv
  stock_request/security/stock_request_security.xml
  stock_request/static/description/icon.png
  stock_request/tests/__init__.py
  stock_request/tests/test_stock_request.py
  stock_request/views/product.xml
  stock_request/views/res_config_settings_views.xml
  stock_request/views/stock_move_views.xml
  stock_request/views/stock_picking_views.xml
  stock_request/views/stock_request_allocation_views.xml
  stock_request/views/stock_request_menu.xml
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: needs review

#571 [12.0][MIG] stock_secondary_unit
  oca_dependencies.txt
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, ready to merge

#526 MIG 12.0 stock available unreserved
  stock_available_unreserved/README.rst
  stock_available_unreserved/__init__.py
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/i18n/ar.po
  stock_available_unreserved/i18n/ca.po
  stock_available_unreserved/i18n/de.po
  stock_available_unreserved/i18n/el_GR.po
  stock_available_unreserved/i18n/es.po
  stock_available_unreserved/i18n/es_ES.po
  stock_available_unreserved/i18n/es_MX.po
  stock_available_unreserved/i18n/eu.po
  stock_available_unreserved/i18n/fi.po
  stock_available_unreserved/i18n/fr.po
  stock_available_unreserved/i18n/fr_CH.po
  stock_available_unreserved/i18n/fr_FR.po
  stock_available_unreserved/i18n/gl.po
  stock_available_unreserved/i18n/hr.po
  stock_available_unreserved/i18n/hr_HR.po
  stock_available_unreserved/i18n/it.po
  stock_available_unreserved/i18n/nl.po
  stock_available_unreserved/i18n/nl_NL.po
  stock_available_unreserved/i18n/pt.po
  stock_available_unreserved/i18n/pt_BR.po
  stock_available_unreserved/i18n/ro.po
  stock_available_unreserved/i18n/ru.po
  stock_available_unreserved/i18n/sl.po
  stock_available_unreserved/i18n/stock_available_unreserved.pot
  stock_available_unreserved/i18n/tr.po
  stock_available_unreserved/i18n/tr_TR.po
  stock_available_unreserved/i18n/vi_VN.po
  stock_available_unreserved/i18n/zh_CN.po
  stock_available_unreserved/models/__init__.py
  stock_available_unreserved/models/product.py
  stock_available_unreserved/models/quant.py
  stock_available_unreserved/static/description/icon.png
  stock_available_unreserved/tests/__init__.py
  stock_available_unreserved/tests/test_stock_available_unreserved.py
  stock_available_unreserved/views/product_view.xml
  stock_available_unreserved/views/stock_quant_view.xml
Labels: approved

#564 [12.0][MIG] stock_warehouse_calendar
  stock_warehouse_calendar/README.rst
  stock_warehouse_calendar/__init__.py
  stock_warehouse_calendar/__manifest__.py
  stock_warehouse_calendar/i18n/stock_warehouse_calendar.pot
  stock_warehouse_calendar/models/__init__.py
  stock_warehouse_calendar/models/stock_rule.py
  stock_warehouse_calendar/models/stock_warehouse.py
  stock_warehouse_calendar/readme/CONFIGURE.rst
  stock_warehouse_calendar/readme/CONTRIBUTORS.rst
  stock_warehouse_calendar/readme/DESCRIPTION.rst
  stock_warehouse_calendar/readme/USAGE.rst
  stock_warehouse_calendar/static/description/icon.png
  stock_warehouse_calendar/static/description/index.html
  stock_warehouse_calendar/tests/__init__.py
  stock_warehouse_calendar/tests/test_stock_warehouse_calendar.py
  stock_warehouse_calendar/views/stock_warehouse_views.xml
Labels: approved, needs review, ready to merge

#561 [MIG] stock_warehouse_orderpoint_stock_info: Migration to 12.0
  stock_warehouse_orderpoint_stock_info/README.rst
  stock_warehouse_orderpoint_stock_info/__init__.py
  stock_warehouse_orderpoint_stock_info/__manifest__.py
  stock_warehouse_orderpoint_stock_info/i18n/ca.po
  stock_warehouse_orderpoint_stock_info/i18n/cs_CZ.po
  stock_warehouse_orderpoint_stock_info/i18n/de.po
  stock_warehouse_orderpoint_stock_info/i18n/el_GR.po
  stock_warehouse_orderpoint_stock_info/i18n/es.po
  stock_warehouse_orderpoint_stock_info/i18n/es_ES.po
  stock_warehouse_orderpoint_stock_info/i18n/es_MX.po
  stock_warehouse_orderpoint_stock_info/i18n/eu.po
  stock_warehouse_orderpoint_stock_info/i18n/fi.po
  stock_warehouse_orderpoint_stock_info/i18n/fr.po
  stock_warehouse_orderpoint_stock_info/i18n/fr_CH.po
  stock_warehouse_orderpoint_stock_info/i18n/fr_FR.po
  stock_warehouse_orderpoint_stock_info/i18n/gl.po
  stock_warehouse_orderpoint_stock_info/i18n/hr.po
  stock_warehouse_orderpoint_stock_info/i18n/hr_HR.po
  stock_warehouse_orderpoint_stock_info/i18n/it.po
  stock_warehouse_orderpoint_stock_info/i18n/nl.po
  stock_warehouse_orderpoint_stock_info/i18n/nl_NL.po
  stock_warehouse_orderpoint_stock_info/i18n/pt.po
  stock_warehouse_orderpoint_stock_info/i18n/pt_BR.po
  stock_warehouse_orderpoint_stock_info/i18n/ro.po
  stock_warehouse_orderpoint_stock_info/i18n/ru.po
  stock_warehouse_orderpoint_stock_info/i18n/sl.po
  stock_warehouse_orderpoint_stock_info/i18n/stock_warehouse_orderpoint_stock_info.pot
  stock_warehouse_orderpoint_stock_info/i18n/tr.po
  stock_warehouse_orderpoint_stock_info/i18n/tr_TR.po
  stock_warehouse_orderpoint_stock_info/i18n/vi_VN.po
  stock_warehouse_orderpoint_stock_info/i18n/zh_CN.po
  stock_warehouse_orderpoint_stock_info/models/__init__.py
  stock_warehouse_orderpoint_stock_info/models/stock_warehouse_orderpoint.py
  stock_warehouse_orderpoint_stock_info/readme/CONTRIBUTORS.rst
  stock_warehouse_orderpoint_stock_info/readme/DESCRIPTION.rst
  stock_warehouse_orderpoint_stock_info/static/description/icon.png
  stock_warehouse_orderpoint_stock_info/static/description/index.html
  stock_warehouse_orderpoint_stock_info/tests/__init__.py
  stock_warehouse_orderpoint_stock_info/tests/test_stock_warehouse_orderpoint.py
  stock_warehouse_orderpoint_stock_info/views/stock_warehouse_orderpoint_view.xml
Labels: needs review

#574 [11.0][IMP] stock_move_location: Allow move products from one location to another directly from selected quants
  stock_move_location/README.rst
  stock_move_location/__manifest__.py
  stock_move_location/data/stock_quant_view.xml
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/DESCRIPTION.rst
  stock_move_location/readme/USAGE.rst
  stock_move_location/static/description/index.html
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
Labels: approved, ready to merge

#573 [11.0][IMP] stock_secondary_unit: Add security group
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/migrations/11.0.1.0.2/post-migration.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, ready to merge

#576 [9.0] [BACKPORT] Packaging UOM
  .gitignore
  packaging_uom/README.rst
  packaging_uom/__init__.py
  packaging_uom/__openerp__.py
  packaging_uom/i18n/cs_CZ.po
  packaging_uom/i18n/de.po
  packaging_uom/i18n/es.po
  packaging_uom/i18n/fi.po
  packaging_uom/i18n/fr.po
  packaging_uom/i18n/hr.po
  packaging_uom/i18n/hr_HR.po
  packaging_uom/i18n/it.po
  packaging_uom/i18n/nl.po
  packaging_uom/i18n/packaging_uom.pot
  packaging_uom/i18n/pt.po
  packaging_uom/i18n/pt_BR.po
  packaging_uom/i18n/sl.po
  packaging_uom/models/__init__.py
  packaging_uom/models/product_packaging.py
  packaging_uom/readme/CONFIGURE.rst
  packaging_uom/readme/CONTRIBUTORS.rst
  packaging_uom/readme/DESCRIPTION.rst
  packaging_uom/readme/INSTALLATION.rst
  packaging_uom/static/description/icon.png
  packaging_uom/static/description/index.html
  packaging_uom/tests/__init__.py
  packaging_uom/tests/test_product_packaging.py
  packaging_uom/views/product_packaging_views.xml
  setup/packaging_uom/odoo_addons/__init__.py
  setup/packaging_uom/odoo_addons/packaging_uom
  setup/packaging_uom/setup.py
Labels: approved, ready to merge

#558 [12.0][MIG] stock_orderpoint_manual_procurement_uom
  stock_orderpoint_manual_procurement_uom/README.rst
  stock_orderpoint_manual_procurement_uom/__init__.py
  stock_orderpoint_manual_procurement_uom/__manifest__.py
  stock_orderpoint_manual_procurement_uom/i18n/stock_orderpoint_manual_procurement_uom.pot
  stock_orderpoint_manual_procurement_uom/models/__init__.py
  stock_orderpoint_manual_procurement_uom/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement_uom/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement_uom/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement_uom/readme/USAGE.rst
  stock_orderpoint_manual_procurement_uom/static/description/icon.png
  stock_orderpoint_manual_procurement_uom/static/description/index.html
  stock_orderpoint_manual_procurement_uom/tests/__init__.py
  stock_orderpoint_manual_procurement_uom/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement_uom/wizards/__init__.py
  stock_orderpoint_manual_procurement_uom/wizards/make_procurement_orderpoint.py
Labels: approved, ready to merge

#569 [12.0][MIG] stock_picking_procure_method
  stock_picking_procure_method/README.rst
  stock_picking_procure_method/__init__.py
  stock_picking_procure_method/__manifest__.py
  stock_picking_procure_method/i18n/stock_picking_procure_method.pot
  stock_picking_procure_method/models/__init__.py
  stock_picking_procure_method/models/stock_picking.py
  stock_picking_procure_method/readme/CONFIGURE.rst
  stock_picking_procure_method/readme/CONTRIBUTORS.rst
  stock_picking_procure_method/readme/DESCRIPTION.rst
  stock_picking_procure_method/readme/INSTALL.rst
  stock_picking_procure_method/readme/USAGE.rst
  stock_picking_procure_method/static/description/index.html
  stock_picking_procure_method/tests/__init__.py
  stock_picking_procure_method/tests/test_stock_picking_procure_method.py
  stock_picking_procure_method/views/stock_picking_views.xml
Labels: approved, needs review, ready to merge

#562 [MIG] stock_warehouse_orderpoint_stock_info_unreserved: Migration to 12.0
  stock_warehouse_orderpoint_stock_info_unreserved/README.rst
  stock_warehouse_orderpoint_stock_info_unreserved/__init__.py
  stock_warehouse_orderpoint_stock_info_unreserved/__manifest__.py
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/de.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/es.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/es_ES.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/pt_BR.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/sl.po
  stock_warehouse_orderpoint_stock_info_unreserved/i18n/stock_warehouse_orderpoint_stock_info_unreserved.pot
  stock_warehouse_orderpoint_stock_info_unreserved/models/__init__.py
  stock_warehouse_orderpoint_stock_info_unreserved/models/stock_warehouse_orderpoint.py
  stock_warehouse_orderpoint_stock_info_unreserved/readme/CONTRIBUTORS.rst
  stock_warehouse_orderpoint_stock_info_unreserved/readme/DESCRIPTION.rst
  stock_warehouse_orderpoint_stock_info_unreserved/static/description/icon.png
  stock_warehouse_orderpoint_stock_info_unreserved/static/description/index.html
  stock_warehouse_orderpoint_stock_info_unreserved/tests/__init__.py
  stock_warehouse_orderpoint_stock_info_unreserved/tests/test_stock_warehouse_orderpoint.py
  stock_warehouse_orderpoint_stock_info_unreserved/views/stock_warehouse_orderpoint_view.xml
Labels: approved, needs review, ready to merge
