Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-05, with the labels that each got.

#581 [IMP] Stock_request_kanban: Set barcode configuration on parameters
  stock_request_kanban/README.rst
  stock_request_kanban/__manifest__.py
  stock_request_kanban/models/stock_request_kanban.py
  stock_request_kanban/readme/CONFIGURE.rst
  stock_request_kanban/readme/CONTRIBUTORS.rst
  stock_request_kanban/readme/DESCRIPTION.rst
  stock_request_kanban/readme/USAGE.rst
  stock_request_kanban/report/stock_request_kanban_templates.xml
  stock_request_kanban/static/description/index.html
  stock_request_kanban/tests/test_kanban.py
Labels: approved, enhancement, ready to merge

#580 [11.0][IMP] stock_orderpoint_mrp_link
  stock_orderpoint_mrp_link/__manifest__.py
  stock_orderpoint_mrp_link/models/__init__.py
  stock_orderpoint_mrp_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_mrp_link/readme/DESCRIPTION.rst
  stock_orderpoint_mrp_link/tests/test_stock_orderpoint_mrp_link.py
  stock_orderpoint_mrp_link/views/stock_orderpoint_views.xml
Labels: approved, enhancement

#584 [11.0][FIX] stock_request_tier_validation: update tier definitions
  stock_request_tier_validation/__manifest__.py
  stock_request_tier_validation/data/stock_request_tier_definition.xml
  stock_request_tier_validation/views/stock_request_order_view.xml
  stock_request_tier_validation/views/stock_request_view.xml
Labels: approved, enhancement, needs review

#590 [ADD] stock_request_picking_type
  stock_request_picking_type/README.rst
  stock_request_picking_type/__init__.py
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/data/stock_picking_type.xml
  stock_request_picking_type/models/__init__.py
  stock_request_picking_type/models/stock_picking_type.py
  stock_request_picking_type/models/stock_request.py
  stock_request_picking_type/readme/CONTRIBUTORS.rst
  stock_request_picking_type/readme/DESCRIPTION.rst
  stock_request_picking_type/readme/USAGE.rst
  stock_request_picking_type/static/description/icon.png
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_views.xml
Labels: needs review

#592 [11.0][FIX] stock_request_tier_validation: small typos and missing name.
  stock_request_tier_validation/data/stock_request_tier_definition.xml
  stock_request_tier_validation/views/stock_request_order_view.xml
  stock_request_tier_validation/views/stock_request_view.xml
Labels: approved, enhancement

#591 [11.0][IMP] Stock Request Views
  stock_request/__manifest__.py
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: approved, enhancement, ready to merge

#190 Stock reserve sale port 9.0
  stock_reserve_sale/__openerp__.py
  stock_reserve_sale/model/sale.py
  stock_reserve_sale/model/stock_reserve.py
  stock_reserve_sale/security/ir.model.access.csv
  stock_reserve_sale/test/sale_line_reserve.yml
  stock_reserve_sale/test/sale_reserve.yml
  stock_reserve_sale/view/sale.xml
  stock_reserve_sale/wizard/sale_stock_reserve.py
  stock_reserve_sale/wizard/sale_stock_reserve_view.xml
Labels: needs review

#598 [11.0][FIX] stock_move_location: Not check availability when do immediate transfer.
  stock_move_location/wizard/stock_move_location.py
Labels: approved

#607 [12.0][MIG] stock_account_change_qty_reason
  stock_account_change_qty_reason/README.rst
  stock_account_change_qty_reason/__init__.py
  stock_account_change_qty_reason/__manifest__.py
  stock_account_change_qty_reason/i18n/stock_account_change_qty_reason.pot
  stock_account_change_qty_reason/models/__init__.py
  stock_account_change_qty_reason/models/stock_inventory_line_reason.py
  stock_account_change_qty_reason/models/stock_move.py
  stock_account_change_qty_reason/readme/CONFIGURE.rst
  stock_account_change_qty_reason/readme/CONTRIBUTORS.rst
  stock_account_change_qty_reason/readme/DESCRIPTION.rst
  stock_account_change_qty_reason/static/description/index.html
  stock_account_change_qty_reason/tests/__init__.py
  stock_account_change_qty_reason/tests/test_stock_account_change_qty_reason.py
  stock_account_change_qty_reason/views/stock_inventory_line_reason_view.xml
  stock_account_change_qty_reason/views/stock_move_view.xml
Labels: approved, needs review

#608 [12.0][MIG] stock_request_tier_validation
  stock_request_tier_validation/README.rst
  stock_request_tier_validation/__init__.py
  stock_request_tier_validation/__manifest__.py
  stock_request_tier_validation/data/stock_request_tier_definition.xml
  stock_request_tier_validation/i18n/es.po
  stock_request_tier_validation/i18n/stock_request_tier_validation.pot
  stock_request_tier_validation/models/__init__.py
  stock_request_tier_validation/models/stock_request.py
  stock_request_tier_validation/models/stock_request_order.py
  stock_request_tier_validation/models/tier_definition.py
  stock_request_tier_validation/readme/CONFIGURE.rst
  stock_request_tier_validation/readme/CONTRIBUTORS.rst
  stock_request_tier_validation/readme/CREDITS.rst
  stock_request_tier_validation/readme/DESCRIPTION.rst
  stock_request_tier_validation/readme/INSTALL.rst
  stock_request_tier_validation/readme/USAGE.rst
  stock_request_tier_validation/static/description/icon.png
  stock_request_tier_validation/static/description/index.html
  stock_request_tier_validation/tests/__init__.py
  stock_request_tier_validation/tests/test_stock_request_tier_validation.py
  stock_request_tier_validation/views/stock_request_order_view.xml
  stock_request_tier_validation/views/stock_request_view.xml
Labels: approved, needs review
