Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-11, with the labels that each got.

#740 [FIX] stock_move_location: fix compute show_details_visible
  stock_move_location/models/stock_move.py
Labels: approved, enhancement

#752 [11.0][FIX] stock_secondary_unit: move line create round
  stock_secondary_unit/models/stock_move.py
Labels: approved

#754 [11.0][FIX] Stock Request Order purchase button fix
  stock_request_purchase/models/stock_request_order.py
Labels: approved, enhancement

#759 [11.0][IMP] stock_request: new icon
  stock_request/static/description/icon.png
  stock_request/static/description/icon.svg
Labels: approved

#761 [12.0] stock_request: new icon
  stock_request/static/description/icon.png
  stock_request/static/description/icon.svg
Labels: approved

#757 [12.0][FIX] Stock Request Order purchase button fix
  stock_request_purchase/models/stock_request_order.py
Labels: approved, enhancement

#767 [FIX] stock_mts_mto_rule: add mts_rule_id and mto_rule_id on stock ru…
  stock_mts_mto_rule/view/pull_rule.xml
Labels: approved, enhancement, ready to merge

#781 [11.0][FIX] stock_request: security restrictions error in onchange_warehouse_id
  stock_request/models/stock_request_abstract.py
  stock_request/models/stock_request_order.py
Labels: approved
