Repository OCA/stock-logistics-warehouse, pull requests merged in 2019-03, with the labels that each got.

#525 [11.0] [ADD] stock_account_change_qty_reason
  stock_account_change_qty_reason/README.rst
  stock_account_change_qty_reason/__init__.py
  stock_account_change_qty_reason/__manifest__.py
  stock_account_change_qty_reason/models/__init__.py
  stock_account_change_qty_reason/models/stock_inventory_line_reason.py
  stock_account_change_qty_reason/models/stock_move.py
  stock_account_change_qty_reason/readme/CONFIGURE.rst
  stock_account_change_qty_reason/readme/CONTRIBUTORS.rst
  stock_account_change_qty_reason/readme/DESCRIPTION.rst
  stock_account_change_qty_reason/static/description/index.html
  stock_account_change_qty_reason/tests/__init__.py
  stock_account_change_qty_reason/tests/test_stock_account_change_qty_reason.py
  stock_account_change_qty_reason/views/stock_inventory_line_reason_view.xml
  stock_account_change_qty_reason/views/stock_move_view.xml
Labels: approved, needs review, ready to merge

#549 [ADD] Use same decorator on product.product as on product.template tree view.
  stock_available/__manifest__.py
  stock_available/views/product_product_view.xml
Labels: approved, enhancement, ready to merge

#546 [11.0][FIX] stock_request: sudoing
  stock_request/models/stock_request.py
  stock_request/security/ir.model.access.csv
Labels: approved, enhancement

#567 [10.0][FIX] stock_orderpoint_uom, stock_quant_manual_assign
  stock_orderpoint_uom/__manifest__.py
  stock_orderpoint_uom/models/stock_warehouse_orderpoint.py
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: enhancement, needs review

#555 [10.0] Fix mts+mto rules creation on warehouse creation
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/model/warehouse.py
  stock_mts_mto_rule/tests/test_mto_mts_route.py
Labels: approved, enhancement, needs review, ready to merge

#520 [11.0][ADD] stock_request_purchase_analytic
  stock_request_purchase_analytic/README.rst
  stock_request_purchase_analytic/__init__.py
  stock_request_purchase_analytic/__manifest__.py
  stock_request_purchase_analytic/models/__init__.py
  stock_request_purchase_analytic/models/procurement_rule.py
  stock_request_purchase_analytic/static/description/icon.png
  stock_request_purchase_analytic/tests/__init__.py
  stock_request_purchase_analytic/tests/test_stock_request_purchase_analytic.py
Labels: approved, needs review, ready to merge
