Repository OCA/stock-logistics-warehouse, pull requests merged in 2020-10, with the labels that each got.

#987 [13.0][FIX] stock_location_tray: Fix exceptions message in tests
  stock_location_tray/tests/test_location.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#977 [12.0][ADD] stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/odoo/addons/stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/setup.py
  stock_production_lot_quantity_tree/README.rst
  stock_production_lot_quantity_tree/__init__.py
  stock_production_lot_quantity_tree/__manifest__.py
  stock_production_lot_quantity_tree/readme/CONTRIBUTORS.rst
  stock_production_lot_quantity_tree/readme/DESCRIPTION.rst
  stock_production_lot_quantity_tree/static/description/icon.png
  stock_production_lot_quantity_tree/static/description/index.html
  stock_production_lot_quantity_tree/views/stock_production_lot.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#866 [13.0][MIG] stock_request_submit
  setup/stock_request_submit/odoo/addons/stock_request_submit
  setup/stock_request_submit/setup.py
  stock_request_submit/README.rst
  stock_request_submit/__init__.py
  stock_request_submit/__manifest__.py
  stock_request_submit/i18n/es.po
  stock_request_submit/i18n/stock_request_submit.pot
  stock_request_submit/i18n/zh_CN.po
  stock_request_submit/models/__init__.py
  stock_request_submit/models/stock_request.py
  stock_request_submit/models/stock_request_order.py
  stock_request_submit/readme/CONTRIBUTORS.rst
  stock_request_submit/readme/DESCRIPTION.rst
  stock_request_submit/static/description/icon.png
  stock_request_submit/static/description/index.html
  stock_request_submit/tests/__init__.py
  stock_request_submit/tests/test_stock_request_submit.py
  stock_request_submit/uninstall_hook.py
  stock_request_submit/views/stock_request_order_views.xml
  stock_request_submit/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#865 [13.0][MIG] stock_request_direction
  setup/stock_request_direction/odoo/addons/stock_request_direction
  setup/stock_request_direction/setup.py
  stock_request_direction/README.rst
  stock_request_direction/__init__.py
  stock_request_direction/__manifest__.py
  stock_request_direction/i18n/es.po
  stock_request_direction/i18n/stock_request_direction.pot
  stock_request_direction/i18n/zh_CN.po
  stock_request_direction/models/__init__.py
  stock_request_direction/models/stock_request.py
  stock_request_direction/models/stock_request_order.py
  stock_request_direction/readme/CONTRIBUTORS.rst
  stock_request_direction/readme/DESCRIPTION.rst
  stock_request_direction/readme/USAGE.rst
  stock_request_direction/static/description/icon.png
  stock_request_direction/static/description/index.html
  stock_request_direction/views/res_config_settings.xml
  stock_request_direction/views/stock_request_order_views.xml
  stock_request_direction/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#983 FIX: assign value to field compute always
  stock_request/models/stock_request_abstract.py
Labels: approved, bot is merging ⏳

#860 [13.0][MIG] stock_orderpoint_manual_procurement_uom
  setup/stock_orderpoint_manual_procurement_uom/odoo/addons/stock_orderpoint_manual_procurement_uom
  setup/stock_orderpoint_manual_procurement_uom/setup.py
  stock_orderpoint_manual_procurement_uom/README.rst
  stock_orderpoint_manual_procurement_uom/__init__.py
  stock_orderpoint_manual_procurement_uom/__manifest__.py
  stock_orderpoint_manual_procurement_uom/i18n/stock_orderpoint_manual_procurement_uom.pot
  stock_orderpoint_manual_procurement_uom/i18n/zh_CN.po
  stock_orderpoint_manual_procurement_uom/models/__init__.py
  stock_orderpoint_manual_procurement_uom/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement_uom/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement_uom/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement_uom/readme/USAGE.rst
  stock_orderpoint_manual_procurement_uom/static/description/icon.png
  stock_orderpoint_manual_procurement_uom/static/description/index.html
  stock_orderpoint_manual_procurement_uom/tests/__init__.py
  stock_orderpoint_manual_procurement_uom/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement_uom/wizards/__init__.py
  stock_orderpoint_manual_procurement_uom/wizards/make_procurement_orderpoint.py
Labels: bot is merging ⏳, needs review

#786 [10.0][ADD] stock_lot_note: Add notes field to Lots
  setup/stock_lot_note/.eggs/README.txt
  setup/stock_lot_note/odoo/__init__.py
  setup/stock_lot_note/odoo/addons/__init__.py
  setup/stock_lot_note/odoo/addons/stock_lot_note
  setup/stock_lot_note/setup.py
  stock_lot_note/README.rst
  stock_lot_note/__init__.py
  stock_lot_note/__manifest__.py
  stock_lot_note/models/__init__.py
  stock_lot_note/models/stock_production_lot.py
  stock_lot_note/readme/CONTRIBUTORS.rst
  stock_lot_note/readme/DESCRIPTION.rst
  stock_lot_note/readme/USAGE.rst
  stock_lot_note/static/description/icon.png
  stock_lot_note/static/description/index.html
  stock_lot_note/views/stock_production_lot.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#994 [12.0][FIX] stock_pull_list: send company recordset to _get_rule
  stock_pull_list/wizards/stock_pull_list_wizard.py
Labels: approved, bot is merging ⏳

#971 [10.0] [ADD] stock_location_product_restriction: Prevent to mix different products into the same stock location
  setup/stock_location_product_restriction/odoo/__init__.py
  setup/stock_location_product_restriction/odoo/addons/__init__.py
  setup/stock_location_product_restriction/odoo/addons/stock_location_product_restriction
  setup/stock_location_product_restriction/setup.py
  stock_location_product_restriction/README.rst
  stock_location_product_restriction/__init__.py
  stock_location_product_restriction/__manifest__.py
  stock_location_product_restriction/hooks.py
  stock_location_product_restriction/i18n/fr.po
  stock_location_product_restriction/models/__init__.py
  stock_location_product_restriction/models/stock_location.py
  stock_location_product_restriction/models/stock_move.py
  stock_location_product_restriction/readme/CONTRIBUTORS.rst
  stock_location_product_restriction/readme/CREDITS.rst
  stock_location_product_restriction/readme/DESCRIPTION.rst
  stock_location_product_restriction/readme/HISTORY.rst
  stock_location_product_restriction/readme/USAGE.rst
  stock_location_product_restriction/readme/newsfragments/.gitkeep
  stock_location_product_restriction/static/description/icon.png
  stock_location_product_restriction/static/description/index.html
  stock_location_product_restriction/tests/__init__.py
  stock_location_product_restriction/tests/test_stock_location.py
  stock_location_product_restriction/tests/test_stock_move.py
  stock_location_product_restriction/views/stock_location.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1000 [13.0] Remove _order override in stock.location
  stock_inventory_lockdown/models/stock_location.py
Labels: approved, bot is merging ⏳

#997 [13.0] Improve put-away release in vertical lift
  stock_vertical_lift/models/vertical_lift_operation_put.py
Labels: approved, bot is merging ⏳, enhancement

#952 [12.0][IMP] stock_inventory_verification_request
  stock_inventory_verification_request/__manifest__.py
  stock_inventory_verification_request/data/slot_verification_request_sequence.xml
  stock_inventory_verification_request/models/__init__.py
  stock_inventory_verification_request/models/stock_inventory.py
  stock_inventory_verification_request/models/stock_location.py
  stock_inventory_verification_request/models/stock_slot_verification_request.py
  stock_inventory_verification_request/readme/CONTRIBUTORS.rst
  stock_inventory_verification_request/readme/DESCRIPTION.rst
  stock_inventory_verification_request/readme/USAGE.rst
  stock_inventory_verification_request/security/stock_security.xml
  stock_inventory_verification_request/tests/test_verification_request.py
  stock_inventory_verification_request/views/stock_inventory_view.xml
  stock_inventory_verification_request/views/stock_location_view.xml
  stock_inventory_verification_request/views/stock_slot_verification_request_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#993 [13.0][ADD] stock_inventory_line_open
  setup/stock_inventory_line_open/odoo/addons/stock_inventory_line_open
  setup/stock_inventory_line_open/setup.py
  stock_inventory_line_open/README.rst
  stock_inventory_line_open/__init__.py
  stock_inventory_line_open/__manifest__.py
  stock_inventory_line_open/models/__init__.py
  stock_inventory_line_open/models/stock_inventory.py
  stock_inventory_line_open/readme/CONTRIBUTORS.rst
  stock_inventory_line_open/readme/DESCRIPTION.rst
  stock_inventory_line_open/static/description/icon.png
  stock_inventory_line_open/static/description/index.html
  stock_inventory_line_open/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳, needs review
