Repository OCA/stock-logistics-warehouse, pull requests merged in 2020-09, with the labels that each got.

#884 [13.0][IMP] stock_cubiscan: Handle unit without packaging
  stock_cubiscan/__manifest__.py
  stock_cubiscan/data/uom.xml
  stock_cubiscan/readme/ROADMAP.rst
  stock_cubiscan/tests/test_cubiscan_wizard.py
  stock_cubiscan/wizard/cubiscan_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#941 [13.0] Add stock_picking_consolidation_priority
  setup/stock_picking_consolidation_priority/odoo/addons/stock_picking_consolidation_priority
  setup/stock_picking_consolidation_priority/setup.py
  stock_picking_consolidation_priority/__init__.py
  stock_picking_consolidation_priority/__manifest__.py
  stock_picking_consolidation_priority/models/__init__.py
  stock_picking_consolidation_priority/models/stock_move.py
  stock_picking_consolidation_priority/models/stock_picking_type.py
  stock_picking_consolidation_priority/readme/CONFIGURATION.rst
  stock_picking_consolidation_priority/readme/CONTRIBUTORS.rst
  stock_picking_consolidation_priority/readme/DESCRIPTION.rst
  stock_picking_consolidation_priority/readme/ROADMAP.rst
  stock_picking_consolidation_priority/tests/__init__.py
  stock_picking_consolidation_priority/tests/test_consolidation_priority.py
Labels: approved, bot is merging ⏳, ready to merge

#959 [FIX][13.0][stock_inventory_preparation_filter] Remove migration scripts
  stock_inventory_preparation_filter/migrations/13.0.1.0.0/post-migration.py
  stock_inventory_preparation_filter/migrations/13.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#964 [13.0][MIG] procurement_auto_create_group
  procurement_auto_create_group/README.rst
  procurement_auto_create_group/__init__.py
  procurement_auto_create_group/__manifest__.py
  procurement_auto_create_group/i18n/cs_CZ.po
  procurement_auto_create_group/i18n/de.po
  procurement_auto_create_group/i18n/es.po
  procurement_auto_create_group/i18n/es_MX.po
  procurement_auto_create_group/i18n/fr.po
  procurement_auto_create_group/i18n/hr.po
  procurement_auto_create_group/i18n/it.po
  procurement_auto_create_group/i18n/procurement_auto_create_group.pot
  procurement_auto_create_group/i18n/pt_BR.po
  procurement_auto_create_group/i18n/pt_PT.po
  procurement_auto_create_group/i18n/ro.po
  procurement_auto_create_group/i18n/sk.po
  procurement_auto_create_group/i18n/sl.po
  procurement_auto_create_group/i18n/tr_TR.po
  procurement_auto_create_group/i18n/vi_VN.po
  procurement_auto_create_group/i18n/zh_CN.po
  procurement_auto_create_group/models/__init__.py
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/readme/CONFIGURE.rst
  procurement_auto_create_group/readme/CONTRIBUTORS.rst
  procurement_auto_create_group/readme/DESCRIPTION.rst
  procurement_auto_create_group/readme/USAGE.rst
  procurement_auto_create_group/static/description/icon.png
  procurement_auto_create_group/static/description/index.html
  procurement_auto_create_group/tests/__init__.py
  procurement_auto_create_group/tests/test_auto_create.py
  procurement_auto_create_group/views/procurement_view.xml
  setup/procurement_auto_create_group/odoo/addons/procurement_auto_create_group
  setup/procurement_auto_create_group/setup.py
Labels: approved, bot is merging ⏳

#864 [13.0][ADD] stock_request_mrp
  setup/stock_request_mrp/odoo/addons/stock_request_mrp
  setup/stock_request_mrp/setup.py
  stock_request/models/res_config_settings.py
  stock_request/views/res_config_settings_views.xml
  stock_request_mrp/README.rst
  stock_request_mrp/__init__.py
  stock_request_mrp/__manifest__.py
  stock_request_mrp/hooks.py
  stock_request_mrp/models/__init__.py
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/models/stock_request.py
  stock_request_mrp/models/stock_request_order.py
  stock_request_mrp/models/stock_rule.py
  stock_request_mrp/readme/CONTRIBUTORS.rst
  stock_request_mrp/readme/DESCRIPTION.rst
  stock_request_mrp/readme/ROADMAP.rst
  stock_request_mrp/readme/USAGE.rst
  stock_request_mrp/security/ir.model.access.csv
  stock_request_mrp/static/description/icon.png
  stock_request_mrp/static/description/index.html
  stock_request_mrp/tests/__init__.py
  stock_request_mrp/tests/test_stock_request_mrp.py
  stock_request_mrp/views/mrp_production_views.xml
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, needs review

#840 [ADD] 12.0: stock_putaway_product_form
  requirements.txt
  stock_putaway_product_form/README.rst
  stock_putaway_product_form/__init__.py
  stock_putaway_product_form/__manifest__.py
  stock_putaway_product_form/demo/putaway_strategies.xml
  stock_putaway_product_form/hooks.py
  stock_putaway_product_form/models/__init__.py
  stock_putaway_product_form/models/product_product.py
  stock_putaway_product_form/models/product_template.py
  stock_putaway_product_form/models/putaway_strategy.py
  stock_putaway_product_form/readme/CONTRIBUTORS.rst
  stock_putaway_product_form/readme/DESCRIPTION.rst
  stock_putaway_product_form/readme/USAGE.rst
  stock_putaway_product_form/static/description/icon.png
  stock_putaway_product_form/static/description/index.html
  stock_putaway_product_form/tests/__init__.py
  stock_putaway_product_form/tests/test_product_putaway.py
  stock_putaway_product_form/views/product.xml
Labels: bot is merging ⏳, needs review

#845 [MIG][13.0] stock_inventory_cost_info: Migration to v13.0
  setup/stock_inventory_cost_info/odoo/addons/stock_inventory_cost_info
  setup/stock_inventory_cost_info/setup.py
  stock_inventory_cost_info/README.rst
  stock_inventory_cost_info/__init__.py
  stock_inventory_cost_info/__manifest__.py
  stock_inventory_cost_info/hooks.py
  stock_inventory_cost_info/i18n/es.po
  stock_inventory_cost_info/i18n/stock_inventory_cost_info.pot
  stock_inventory_cost_info/models/__init__.py
  stock_inventory_cost_info/models/stock_inventory.py
  stock_inventory_cost_info/readme/CONTRIBUTORS.rst
  stock_inventory_cost_info/readme/DESCRIPTION.rst
  stock_inventory_cost_info/readme/INSTALL.rst
  stock_inventory_cost_info/readme/USAGE.rst
  stock_inventory_cost_info/static/description/icon.png
  stock_inventory_cost_info/static/description/index.html
  stock_inventory_cost_info/tests/__init__.py
  stock_inventory_cost_info/tests/test_stock_inventory_cost_info.py
  stock_inventory_cost_info/views/report_stockinventory.xml
  stock_inventory_cost_info/views/stock_inventory_views.xml
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#970 [IMP] stock_secondary_unit: Display info only for inventory users
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/migrations/13.0.1.0.1/post-migration.py
  stock_secondary_unit/views/product_views.xml
Labels: approved, bot is merging ⏳

#893 [10.0][ADD] stock_available_base_exclude_location
  requirements.txt
  setup/stock_available_base_exclude_location/.eggs/README.txt
  setup/stock_available_base_exclude_location/odoo/__init__.py
  setup/stock_available_base_exclude_location/odoo/addons/__init__.py
  setup/stock_available_base_exclude_location/odoo/addons/stock_available_base_exclude_location
  setup/stock_available_base_exclude_location/setup.py
  stock_available_base_exclude_location/README.rst
  stock_available_base_exclude_location/__init__.py
  stock_available_base_exclude_location/__manifest__.py
  stock_available_base_exclude_location/models/__init__.py
  stock_available_base_exclude_location/models/product_product.py
  stock_available_base_exclude_location/models/stock_exclude_location_mixin.py
  stock_available_base_exclude_location/readme/CONTRIBUTORS.rst
  stock_available_base_exclude_location/readme/DESCRIPTION.rst
  stock_available_base_exclude_location/readme/USAGE.rst
  stock_available_base_exclude_location/static/description/icon.png
  stock_available_base_exclude_location/static/description/index.html
  stock_available_base_exclude_location/tests/__init__.py
  stock_available_base_exclude_location/tests/common.py
  stock_available_base_exclude_location/tests/test_stock_exclude_location.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, needs review, ready to merge

#846 [13.0][ADD] product_quantity_update_force_inventory
  product_quantity_update_force_inventory/README.rst
  product_quantity_update_force_inventory/__init__.py
  product_quantity_update_force_inventory/__manifest__.py
  product_quantity_update_force_inventory/models/__init__.py
  product_quantity_update_force_inventory/models/product.py
  product_quantity_update_force_inventory/models/stock_quant.py
  product_quantity_update_force_inventory/readme/CONTRIBUTORS.rst
  product_quantity_update_force_inventory/readme/DESCRIPTION.rst
  product_quantity_update_force_inventory/static/description/index.html
  product_quantity_update_force_inventory/tests/__init__.py
  product_quantity_update_force_inventory/tests/test_stock_quant_editable_view_block.py
  product_quantity_update_force_inventory/views/product_views.xml
  setup/product_quantity_update_force_inventory/odoo/addons/product_quantity_update_force_inventory
  setup/product_quantity_update_force_inventory/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#973 Revert "Merge PR #696 into 12.0"
  oca_dependencies.txt
  stock_move_location_dest_constraint_base/__init__.py
  stock_move_location_dest_constraint_base/__manifest__.py
  stock_move_location_dest_constraint_base/data/stock_location.xml
  stock_move_location_dest_constraint_base/models/__init__.py
  stock_move_location_dest_constraint_base/models/product_strategy.py
  stock_move_location_dest_constraint_base/models/stock_location.py
  stock_move_location_dest_constraint_base/models/stock_move.py
  stock_move_location_dest_constraint_base/readme/CONFIGURE.rst
  stock_move_location_dest_constraint_base/readme/CONTRIBUTORS.rst
  stock_move_location_dest_constraint_base/readme/DESCRIPTION.rst
  stock_move_location_dest_constraint_base/readme/USAGE.rst
  stock_move_location_dest_constraint_base/views/stock_location.xml
Labels: approved, ready to merge
