Repository OCA/stock-logistics-warehouse, pull requests merged in 2020-05, with the labels that each got.

#899 [IMP] stock_request: pivot view
  stock_request/views/stock_request_views.xml
Labels: approved, bot is merging ⏳

#901 [IMP] stock_location_template: inheritability
  stock_location_template/models/stock_location.py
Labels: approved, bot is merging ⏳

#896 [12.0][IMP] Stock Request Views
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#902 [13.0][FIX] Broken pre-commit: E741 ambiguous variable name 'l'
  stock_inventory_lockdown/models/stock_move.py
Labels: approved, bot is merging ⏳

#900 [IMP] stock_location_limit_product
  stock_location_limit_product/__manifest__.py
  stock_location_limit_product/models/__init__.py
  stock_location_limit_product/models/product_template.py
  stock_location_limit_product/views/product_template.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#903 [13.0][IMP] stock_request: improve views
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#908 [FIX] stock_location_limit_product
  stock_location_limit_product/__manifest__.py
  stock_location_limit_product/readme/CONFIGURE.rst
  stock_location_limit_product/readme/DESCRIPTION.rst
  stock_location_limit_product/readme/USAGE.rst
  stock_location_limit_product/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, bug, needs review

#904 [FIX] stock_inventory_lockdown: Permission issue and SO confirmation
  stock_inventory_lockdown/models/stock_move.py
Labels: approved, bot is merging ⏳, bug, ready to merge

#696 [WMS][12.0] Add stock_move_location_dest_constraint_base - alpha version
  oca_dependencies.txt
  stock_move_location_dest_constraint_base/README.rst
  stock_move_location_dest_constraint_base/__init__.py
  stock_move_location_dest_constraint_base/__manifest__.py
  stock_move_location_dest_constraint_base/data/stock_location.xml
  stock_move_location_dest_constraint_base/models/__init__.py
  stock_move_location_dest_constraint_base/models/product_strategy.py
  stock_move_location_dest_constraint_base/models/stock_location.py
  stock_move_location_dest_constraint_base/models/stock_move.py
  stock_move_location_dest_constraint_base/readme/CONFIGURE.rst
  stock_move_location_dest_constraint_base/readme/CONTRIBUTORS.rst
  stock_move_location_dest_constraint_base/readme/DESCRIPTION.rst
  stock_move_location_dest_constraint_base/readme/USAGE.rst
  stock_move_location_dest_constraint_base/static/description/index.html
  stock_move_location_dest_constraint_base/views/stock_location.xml
Labels: merged 🎉

#806 [13.0] stock_location_bin_name migration to 13.0
  setup/stock_location_bin_name/odoo/addons/stock_location_bin_name
  setup/stock_location_bin_name/setup.py
  stock_location_bin_name/__init__.py
  stock_location_bin_name/__manifest__.py
  stock_location_bin_name/models/__init__.py
  stock_location_bin_name/models/stock_location.py
  stock_location_bin_name/readme/CONTRIBUTORS.rst
  stock_location_bin_name/readme/DESCRIPTION.rst
  stock_location_bin_name/views/stock_location.xml
Labels: approved, merged 🎉, migration, needs review

#790 [WMS][13.0] Add stock_reserve_rule
  setup/stock_reserve_rule/odoo/addons/stock_reserve_rule
  setup/stock_reserve_rule/setup.py
  stock_reserve_rule/README.rst
  stock_reserve_rule/__init__.py
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/demo/product_demo.xml
  stock_reserve_rule/demo/stock_inventory_demo.xml
  stock_reserve_rule/demo/stock_location_demo.xml
  stock_reserve_rule/demo/stock_picking_demo.xml
  stock_reserve_rule/demo/stock_reserve_rule_demo.xml
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_location.py
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_quant.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/readme/CONFIGURE.rst
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/readme/DESCRIPTION.rst
  stock_reserve_rule/readme/USAGE.rst
  stock_reserve_rule/security/ir.model.access.csv
  stock_reserve_rule/security/stock_reserve_rule_security.xml
  stock_reserve_rule/static/description/index.html
  stock_reserve_rule/tests/__init__.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_reserve_rule/views/stock_reserve_rule_views.xml
Labels: merged 🎉, needs review
