Repository OCA/stock-logistics-warehouse, pull requests merged in 2020-04, with the labels that each got.

#770 [11.0][ADD] Scrap reason code module
  scrap_reason_code/README.rst
  scrap_reason_code/__init__.py
  scrap_reason_code/__manifest__.py
  scrap_reason_code/models/__init__.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONFIGURE.rst
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/readme/CREDITS.rst
  scrap_reason_code/readme/DESCRIPTION.rst
  scrap_reason_code/readme/ROADMAP.rst
  scrap_reason_code/readme/USAGE.rst
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/static/description/icon.png
  scrap_reason_code/static/description/index.html
  scrap_reason_code/tests/__init__.py
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_move_views.xml
  scrap_reason_code/views/stock_scrap_views.xml
Labels: approved, bot is merging ⏳, needs review

#876 [ADD] stock_inventory_valuation_location: add module to warehouse
  stock_inventory_valuation_location/README.rst
  stock_inventory_valuation_location/__init__.py
  stock_inventory_valuation_location/__manifest__.py
  stock_inventory_valuation_location/i18n/es.po
  stock_inventory_valuation_location/i18n/stock_inventory_valuation_location.pot
  stock_inventory_valuation_location/models/__init__.py
  stock_inventory_valuation_location/models/stock_quant.py
  stock_inventory_valuation_location/readme/CONTRIBUTORS.rst
  stock_inventory_valuation_location/readme/DESCRIPTION.rst
  stock_inventory_valuation_location/readme/USAGE.rst
  stock_inventory_valuation_location/tests/__init__.py
  stock_inventory_valuation_location/tests/test_stockvaluation.py
  stock_inventory_valuation_location/views/stock_quant_views.xml
Labels: bot is merging ⏳, needs review

#875 [13.0][CHG] model name from reason.code to scrap.reason.code
  scrap_reason_code/__manifest__.py
  scrap_reason_code/migrations/13.0.1.1.0/pre-migration.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONFIGURE.rst
  scrap_reason_code/readme/USAGE.rst
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#861 [13.0] Add module stock_move_common_dest
  setup/stock_move_common_dest/odoo/addons/stock_move_common_dest
  setup/stock_move_common_dest/setup.py
  stock_move_common_dest/README.rst
  stock_move_common_dest/__init__.py
  stock_move_common_dest/__manifest__.py
  stock_move_common_dest/models/__init__.py
  stock_move_common_dest/models/stock_move.py
  stock_move_common_dest/readme/CONTRIBUTORS.rst
  stock_move_common_dest/readme/DESCRIPTION.rst
  stock_move_common_dest/static/description/index.html
  stock_move_common_dest/tests/__init__.py
  stock_move_common_dest/tests/test_move_common_dest.py
  stock_move_common_dest/views/stock_move.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#879 [12.0][FIX] user can delete lines
  stock_request/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, enhancement, needs review

#888 [12.0][ADD] stock_location_template
  stock_location_template/README.rst
  stock_location_template/__init__.py
  stock_location_template/__manifest__.py
  stock_location_template/models/__init__.py
  stock_location_template/models/stock_location.py
  stock_location_template/models/stock_location_template.py
  stock_location_template/readme/CONTRIBUTORS.rst
  stock_location_template/readme/DESCRIPTION.rst
  stock_location_template/readme/USAGE.rst
  stock_location_template/security/ir.model.access.csv
  stock_location_template/static/description/index.html
  stock_location_template/tests/__init__.py
  stock_location_template/tests/test_stock_location_template.py
  stock_location_template/views/stock_location_template_views.xml
  stock_location_template/views/stock_location_views.xml
Labels: approved, bot is merging ⏳, needs review

#874 [IMP] stock_request_direction (Warehouse On Change)
  stock_request_direction/models/stock_request_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#849 [ADD] [13.0] stock_inventory_include_exhausted:New module to create inventory lines including exhausted products
  setup/stock_inventory_include_exhausted/odoo/addons/stock_inventory_include_exhausted
  setup/stock_inventory_include_exhausted/setup.py
  stock_inventory_include_exhausted/README.rst
  stock_inventory_include_exhausted/__init__.py
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/i18n/es.po
  stock_inventory_include_exhausted/i18n/stock_inventory_include_exhausted.pot
  stock_inventory_include_exhausted/models/__init__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/readme/CONTRIBUTORS.rst
  stock_inventory_include_exhausted/readme/DESCRIPTION.rst
  stock_inventory_include_exhausted/readme/USAGE.rst
  stock_inventory_include_exhausted/static/description/icon.png
  stock_inventory_include_exhausted/static/description/index.html
  stock_inventory_include_exhausted/tests/__init__.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
  stock_inventory_include_exhausted/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#887 [12.0][ADD] sale_stock_info_popup: new module
  sale_stock_info_popup/README.rst
  sale_stock_info_popup/__init__.py
  sale_stock_info_popup/__manifest__.py
  sale_stock_info_popup/models/__init__.py
  sale_stock_info_popup/models/product.py
  sale_stock_info_popup/models/sale_order.py
  sale_stock_info_popup/readme/CONTRIBUTORS.rst
  sale_stock_info_popup/readme/DESCRIPTION.rst
  sale_stock_info_popup/readme/USAGE.rst
  sale_stock_info_popup/static/description/index.html
  sale_stock_info_popup/static/src/img/info-circle-solid.png
  sale_stock_info_popup/static/src/js/qty_at_date_widget.js
  sale_stock_info_popup/static/src/xml/qty_at_date.xml
  sale_stock_info_popup/tests/__init__.py
  sale_stock_info_popup/tests/test_sale_stock_info_popup.py
  sale_stock_info_popup/views/assets.xml
  sale_stock_info_popup/views/sale_order_views.xml
Labels: bot is merging ⏳, needs review

#889 [ADD] sale_stock_available_info_popup: new module
  sale_stock_available_info_popup/README.rst
  sale_stock_available_info_popup/__init__.py
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/i18n/es.po
  sale_stock_available_info_popup/i18n/sale_stock_available_info_popup.pot
  sale_stock_available_info_popup/models/__init__.py
  sale_stock_available_info_popup/models/sale_order.py
  sale_stock_available_info_popup/readme/CONTRIBUTORS.rst
  sale_stock_available_info_popup/readme/DESCRIPTION.rst
  sale_stock_available_info_popup/readme/USAGE.rst
  sale_stock_available_info_popup/static/description/index.html
  sale_stock_available_info_popup/static/src/xml/qty_at_date.xml
  sale_stock_available_info_popup/tests/__init__.py
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
  sale_stock_available_info_popup/views/sale_order_views.xml
Labels: approved, bot is merging ⏳, needs review

#895 [12.0][IMP] stock_request: Improve cancellation detection
  stock_request/models/stock_move.py
  stock_request/models/stock_move_line.py
  stock_request/models/stock_request.py
  stock_request/models/stock_request_allocation.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
  stock_request/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review
