Repository OCA/stock-logistics-warehouse, pull requests merged in 2020-08, with the labels that each got.

#949 stock_packaging_calculator: fix sorting, improve value handling
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/tests/test_packaging_calc.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#950 [13.0][IMP] README.md: Show Weblate status
  README.md
Labels: bot is merging ⏳, enhancement

#951 [12.0][FIX] stock_available_unreserved
  stock_available_unreserved/__init__.py
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/hooks.py
  stock_available_unreserved/models/product.py
  stock_available_unreserved/models/quant.py
  stock_available_unreserved/views/stock_quant_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#954 [12.0][IMP] README.md: Show Weblate status
  README.md
Labels: bot is merging ⏳

#802 [13.0][MIG] stock_available
  setup/stock_available/odoo/addons/stock_available
  setup/stock_available/setup.py
  stock_available/README.rst
  stock_available/__init__.py
  stock_available/__manifest__.py
  stock_available/i18n/ar.po
  stock_available/i18n/ca.po
  stock_available/i18n/cs_CZ.po
  stock_available/i18n/de.po
  stock_available/i18n/el_GR.po
  stock_available/i18n/es.po
  stock_available/i18n/es_ES.po
  stock_available/i18n/es_MX.po
  stock_available/i18n/eu.po
  stock_available/i18n/fi.po
  stock_available/i18n/fr.po
  stock_available/i18n/fr_CH.po
  stock_available/i18n/fr_FR.po
  stock_available/i18n/gl.po
  stock_available/i18n/hr.po
  stock_available/i18n/hr_HR.po
  stock_available/i18n/it.po
  stock_available/i18n/nl.po
  stock_available/i18n/nl_NL.po
  stock_available/i18n/pt.po
  stock_available/i18n/pt_BR.po
  stock_available/i18n/ro.po
  stock_available/i18n/ru.po
  stock_available/i18n/sl.po
  stock_available/i18n/stock_available.pot
  stock_available/i18n/tr.po
  stock_available/i18n/tr_TR.po
  stock_available/i18n/vi_VN.po
  stock_available/i18n/zh_CN.po
  stock_available/models/__init__.py
  stock_available/models/product_product.py
  stock_available/models/product_template.py
  stock_available/models/res_config_settings.py
  stock_available/readme/CONFIGURE.rst
  stock_available/readme/CONTRIBUTORS.rst
  stock_available/readme/DESCRIPTION.rst
  stock_available/readme/USAGE.rst
  stock_available/static/description/icon.png
  stock_available/static/description/index.html
  stock_available/tests/__init__.py
  stock_available/tests/test_stock_available.py
  stock_available/views/product_product_view.xml
  stock_available/views/product_template_view.xml
  stock_available/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#955 [11.0][IMP] README.md: Show Weblate status
  README.md
Labels: bot is merging ⏳

#956 [10.0][IMP] README.md: Show Weblate status
  README.md
Labels: bot is merging ⏳

#747 [12.0][IMP] Use many2many_tags widgets for lots on inventory adjustment
  stock_inventory_preparation_filter/README.rst
  stock_inventory_preparation_filter/readme/DESCRIPTION.rst
  stock_inventory_preparation_filter/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
