Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-06, with the labels that each got.

#1160 [12.0][IMP] stock_inventory_discrepancy: centralize logic for over discrepancy assessment and ease extension.
  stock_inventory_discrepancy/models/stock_inventory.py
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1159 [12.0][IMP] stock_cycle_count: auto link inventories to planned cycle counts
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/reports/report_stock_location_accuracy.py
  stock_cycle_count/tests/test_stock_cycle_count.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1165 [13.0][IMP] stock_inventory_discrepancy: centralize logic for over discrepancy assessment and ease extension.
  stock_inventory_discrepancy/models/stock_inventory.py
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_inventory_view.xml
Labels: bot is merging ⏳

#1162 [14.0][MIG] stock_available_mrp
  setup/stock_available_mrp/odoo/addons/stock_available_mrp
  setup/stock_available_mrp/setup.py
  stock_available_mrp/README.rst
  stock_available_mrp/__init__.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/DESCRIPTION.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/static/description/icon.png
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/__init__.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1167 [13.0] s_packaging_calculator: misc fix/imp
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
Labels: approved, bot is merging ⏳

#1170 [12.0][IMP] stock_mts_mto_rule: Improve inheritance
  stock_mts_mto_rule/README.rst
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/readme/CONFIGURE.rst
  stock_mts_mto_rule/readme/CONTRIBUTORS.rst
  stock_mts_mto_rule/readme/DESCRIPTION.rst
  stock_mts_mto_rule/readme/ROADMAP.rst
  stock_mts_mto_rule/readme/USAGE.rst
  stock_mts_mto_rule/static/description/index.html
Labels: approved, bot is merging ⏳

#1161 [12.0][ADD] stock_account_inventory_discrepancy
  stock_account_inventory_discrepancy/README.rst
  stock_account_inventory_discrepancy/__init__.py
  stock_account_inventory_discrepancy/__manifest__.py
  stock_account_inventory_discrepancy/models/__init__.py
  stock_account_inventory_discrepancy/models/stock_inventory_line.py
  stock_account_inventory_discrepancy/models/stock_location.py
  stock_account_inventory_discrepancy/models/stock_warehouse.py
  stock_account_inventory_discrepancy/readme/CONFIGURE.rst
  stock_account_inventory_discrepancy/readme/CONTRIBUTORS.rst
  stock_account_inventory_discrepancy/readme/DESCRIPTION.rst
  stock_account_inventory_discrepancy/static/description/icon.png
  stock_account_inventory_discrepancy/static/description/index.html
  stock_account_inventory_discrepancy/tests/__init__.py
  stock_account_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_account_inventory_discrepancy/views/stock_inventory_view.xml
  stock_account_inventory_discrepancy/views/stock_location_view.xml
  stock_account_inventory_discrepancy/views/stock_warehouse_view.xml
Labels: bot is merging ⏳

#1174 [FIX] - stock_available_mrp: local variable referenced before assignment
  stock_available_mrp/models/product_product.py
Labels: bot is merging ⏳

#1166 [13.0][IMP] stock_cycle_count: auto link inventories to planned cycle counts
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/reports/report_stock_location_accuracy.py
  stock_cycle_count/tests/test_stock_cycle_count.py
Labels: approved, bot is merging ⏳

#1168 [13.0] Add glue modules for displaying qty by packaging
  setup/stock_packaging_calculator_packaging_type/odoo/addons/stock_packaging_calculator_packaging_type
  setup/stock_packaging_calculator_packaging_type/setup.py
  setup/stock_product_qty_by_packaging/odoo/addons/stock_product_qty_by_packaging
  setup/stock_product_qty_by_packaging/setup.py
  setup/stock_vertical_lift_qty_by_packaging/odoo/addons/stock_vertical_lift_qty_by_packaging
  setup/stock_vertical_lift_qty_by_packaging/setup.py
  stock_packaging_calculator_packaging_type/README.rst
  stock_packaging_calculator_packaging_type/__init__.py
  stock_packaging_calculator_packaging_type/__manifest__.py
  stock_packaging_calculator_packaging_type/models/__init__.py
  stock_packaging_calculator_packaging_type/models/product.py
  stock_packaging_calculator_packaging_type/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator_packaging_type/readme/CONTRIBUTORS.rst
  stock_packaging_calculator_packaging_type/readme/DESCRIPTION.rst
  stock_packaging_calculator_packaging_type/tests/__init__.py
  stock_packaging_calculator_packaging_type/tests/test_packaging_by_qty.py
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__init__.py
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/tests/__init__.py
  stock_product_qty_by_packaging/tests/test_stock.py
  stock_product_qty_by_packaging/views/stock_picking.xml
  stock_vertical_lift_kardex/proxy/README.rst
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
  stock_vertical_lift_qty_by_packaging/README.rst
  stock_vertical_lift_qty_by_packaging/__init__.py
  stock_vertical_lift_qty_by_packaging/__manifest__.py
  stock_vertical_lift_qty_by_packaging/models/__init__.py
  stock_vertical_lift_qty_by_packaging/models/vertical_lift_operation_base.py
  stock_vertical_lift_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_vertical_lift_qty_by_packaging/readme/DESCRIPTION.rst
  stock_vertical_lift_qty_by_packaging/views/vertical_lift_operation_base_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1175 s_product_qty_by_packaging: minor fixes
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#1137 [14.0][ADD] stock_picking_cancel_confirm
  setup/stock_picking_cancel_confirm/odoo/addons/stock_picking_cancel_confirm
  setup/stock_picking_cancel_confirm/setup.py
  stock_picking_cancel_confirm/__init__.py
  stock_picking_cancel_confirm/__manifest__.py
  stock_picking_cancel_confirm/models/__init__.py
  stock_picking_cancel_confirm/models/stock_picking.py
  stock_picking_cancel_confirm/readme/CONTRIBUTORS.rst
  stock_picking_cancel_confirm/readme/DESCRIPTION.rst
  stock_picking_cancel_confirm/static/description/icon.png
  stock_picking_cancel_confirm/static/description/index.html
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1178 [13.0] [FIX] stock_request: Fix multi-company rule.
  stock_request/security/stock_request_security.xml
Labels: bot is merging ⏳, enhancement, needs review

#1181 [13.0][FIX] stock_move_location: Improve tests to reflect real usage
  stock_move_location/tests/test_common.py
Labels: approved, bot is merging ⏳

#1186 [FIX] stock_request, stock_reserve_rule: Fix rule because multicompany scheme change
  stock_request/__manifest__.py
  stock_request/security/stock_request_security.xml
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/security/stock_reserve_rule_security.xml
Labels: bot is merging ⏳

#1182 [13.0][FIX] stock_secondary_unit: Allow use secondary units in form view for mobile views
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, ready to merge
