Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-02, with the labels that each got.

#1063 [13.0][ADD] stock_location_last_inventory_date
  stock_location_last_inventory_date/README.rst
  stock_location_last_inventory_date/__init__.py
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/i18n/stock_location_last_inventory_date.pot
  stock_location_last_inventory_date/models/__init__.py
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/readme/CONTRIBUTORS.rst
  stock_location_last_inventory_date/readme/DESCRIPTION.rst
  stock_location_last_inventory_date/static/description/icon.png
  stock_location_last_inventory_date/static/description/index.html
  stock_location_last_inventory_date/tests/__init__.py
  stock_location_last_inventory_date/tests/test_stock_location.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1053 [13.0][IMP] stock_secondary_unit: Use secondary units directly in pickings
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/stock_picking_views.xml
Labels: bot is merging ⏳

#1050 14.0 mig stock packaging calculator
  setup/stock_packaging_calculator/odoo/addons/stock_packaging_calculator
  setup/stock_packaging_calculator/setup.py
  stock_packaging_calculator/README.rst
  stock_packaging_calculator/__init__.py
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/readme/CONTRIBUTORS.rst
  stock_packaging_calculator/readme/DESCRIPTION.rst
  stock_packaging_calculator/readme/ROADMAP.rst
  stock_packaging_calculator/readme/USAGE.rst
  stock_packaging_calculator/static/description/icon.png
  stock_packaging_calculator/static/description/index.html
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/test_packaging_calc.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1067 [13.0] stock_move_auto_assign: Fix concurrency race condition on picking state
  stock_move_auto_assign/__manifest__.py
  stock_move_auto_assign/data/queue_job_channel_data.xml
  stock_move_auto_assign/data/queue_job_function_data.xml
  stock_move_auto_assign/models/product_product.py
  stock_move_auto_assign/tests/common.py
  stock_move_auto_assign/tests/test_auto_assign.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1037 [14.0][MIG] stock_available
  setup/stock_available/odoo/addons/stock_available
  setup/stock_available/setup.py
  stock_available/README.rst
  stock_available/__init__.py
  stock_available/__manifest__.py
  stock_available/i18n/ar.po
  stock_available/i18n/ca.po
  stock_available/i18n/cs_CZ.po
  stock_available/i18n/de.po
  stock_available/i18n/el_GR.po
  stock_available/i18n/es.po
  stock_available/i18n/es_ES.po
  stock_available/i18n/es_MX.po
  stock_available/i18n/eu.po
  stock_available/i18n/fi.po
  stock_available/i18n/fr.po
  stock_available/i18n/fr_CH.po
  stock_available/i18n/fr_FR.po
  stock_available/i18n/gl.po
  stock_available/i18n/hr.po
  stock_available/i18n/hr_HR.po
  stock_available/i18n/it.po
  stock_available/i18n/nl.po
  stock_available/i18n/nl_NL.po
  stock_available/i18n/pt.po
  stock_available/i18n/pt_BR.po
  stock_available/i18n/ro.po
  stock_available/i18n/ru.po
  stock_available/i18n/sl.po
  stock_available/i18n/stock_available.pot
  stock_available/i18n/tr.po
  stock_available/i18n/tr_TR.po
  stock_available/i18n/vi_VN.po
  stock_available/i18n/zh_CN.po
  stock_available/models/__init__.py
  stock_available/models/product_product.py
  stock_available/models/product_template.py
  stock_available/models/res_config_settings.py
  stock_available/readme/CONFIGURE.rst
  stock_available/readme/CONTRIBUTORS.rst
  stock_available/readme/DESCRIPTION.rst
  stock_available/readme/USAGE.rst
  stock_available/static/description/icon.png
  stock_available/static/description/index.html
  stock_available/tests/__init__.py
  stock_available/tests/test_stock_available.py
  stock_available/views/product_product_view.xml
  stock_available/views/product_template_view.xml
  stock_available/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1073 [13.0] Add stock_helper: share common code used by stock modules
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_location.py
Labels: approved, bot is merging ⏳

#1081 [12.0][FIX] stock_secondary_unit: Fix smart button off-frame displayed.
  stock_secondary_unit/views/product_views.xml
Labels: approved, bot is merging ⏳

#1001 [13.0][MIG] stock_putaway_product_template: Migration to 13.0
  setup/stock_putaway_product_template/odoo/addons/stock_putaway_product_template
  setup/stock_putaway_product_template/setup.py
  stock_putaway_product_template/README.rst
  stock_putaway_product_template/__init__.py
  stock_putaway_product_template/__manifest__.py
  stock_putaway_product_template/i18n/stock_putaway_product_template.pot
  stock_putaway_product_template/models/__init__.py
  stock_putaway_product_template/models/product.py
  stock_putaway_product_template/models/stock_location.py
  stock_putaway_product_template/models/stock_putaway_rule.py
  stock_putaway_product_template/readme/CONTRIBUTORS.rst
  stock_putaway_product_template/readme/DESCRIPTION.rst
  stock_putaway_product_template/readme/USAGE.rst
  stock_putaway_product_template/static/description/icon.png
  stock_putaway_product_template/static/description/index.html
  stock_putaway_product_template/tests/__init__.py
  stock_putaway_product_template/tests/test_stock_putaway_rule.py
  stock_putaway_product_template/views/stock_putaway_rule_views.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1043 [14.0][MIG] stock_warehouse_calendar
  setup/stock_warehouse_calendar/odoo/addons/stock_warehouse_calendar
  setup/stock_warehouse_calendar/setup.py
  stock_warehouse_calendar/README.rst
  stock_warehouse_calendar/__init__.py
  stock_warehouse_calendar/__manifest__.py
  stock_warehouse_calendar/i18n/stock_warehouse_calendar.pot
  stock_warehouse_calendar/i18n/zh_CN.po
  stock_warehouse_calendar/models/__init__.py
  stock_warehouse_calendar/models/stock_rule.py
  stock_warehouse_calendar/models/stock_warehouse.py
  stock_warehouse_calendar/readme/CONFIGURE.rst
  stock_warehouse_calendar/readme/CONTRIBUTORS.rst
  stock_warehouse_calendar/readme/DESCRIPTION.rst
  stock_warehouse_calendar/readme/USAGE.rst
  stock_warehouse_calendar/static/description/icon.png
  stock_warehouse_calendar/static/description/index.html
  stock_warehouse_calendar/tests/__init__.py
  stock_warehouse_calendar/tests/test_stock_warehouse_calendar.py
  stock_warehouse_calendar/views/stock_warehouse_views.xml
Labels: approved, bot is merging ⏳, migration, needs review

#1057 [13.0][MIG] stock_archive_constraint: Migration to 13.0
  setup/stock_archive_constraint/odoo/addons/stock_archive_constraint
  setup/stock_archive_constraint/setup.py
  stock_archive_constraint/README.rst
  stock_archive_constraint/__init__.py
  stock_archive_constraint/__manifest__.py
  stock_archive_constraint/i18n/es.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/__init__.py
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/product_template.py
  stock_archive_constraint/models/stock_location.py
  stock_archive_constraint/readme/CONTRIBUTORS.rst
  stock_archive_constraint/readme/DESCRIPTION.rst
  stock_archive_constraint/readme/USAGE.rst
  stock_archive_constraint/static/description/icon.png
  stock_archive_constraint/static/description/index.html
  stock_archive_constraint/tests/__init__.py
  stock_archive_constraint/tests/test_location_archive_constraint.py
Labels: approved, bot is merging ⏳, ready to merge

#1031 [14][MIG] stock_location_lockdown
  setup/stock_location_lockdown/odoo/addons/stock_location_lockdown
  setup/stock_location_lockdown/setup.py
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/pt.po
  stock_location_lockdown/i18n/stock_location_lockdown.pot
  stock_location_lockdown/i18n/zh_CN.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/readme/CONTRIBUTORS.rst
  stock_location_lockdown/readme/DESCRIPTION.rst
  stock_location_lockdown/readme/USAGE.rst
  stock_location_lockdown/static/description/icon.png
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: approved, bot is merging ⏳, ready to merge

#1080 [14.0][MIG] stock_location_children
  setup/stock_location_children/odoo/addons/stock_location_children
  setup/stock_location_children/setup.py
  stock_location_children/README.rst
  stock_location_children/__init__.py
  stock_location_children/__manifest__.py
  stock_location_children/i18n/stock_location_children.pot
  stock_location_children/models/__init__.py
  stock_location_children/models/stock_location.py
  stock_location_children/readme/CONTRIBUTORS.rst
  stock_location_children/readme/DESCRIPTION.rst
  stock_location_children/static/description/icon.png
  stock_location_children/static/description/index.html
  stock_location_children/tests/__init__.py
  stock_location_children/tests/test_stock_location_children.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1086 [13.0][MIG] sale_stock_available_info_popup: Migration to 13.0
  sale_stock_available_info_popup/README.rst
  sale_stock_available_info_popup/__init__.py
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/i18n/es.po
  sale_stock_available_info_popup/i18n/sale_stock_available_info_popup.pot
  sale_stock_available_info_popup/i18n/sl.po
  sale_stock_available_info_popup/models/__init__.py
  sale_stock_available_info_popup/models/sale_order.py
  sale_stock_available_info_popup/readme/CONTRIBUTORS.rst
  sale_stock_available_info_popup/readme/DESCRIPTION.rst
  sale_stock_available_info_popup/readme/USAGE.rst
  sale_stock_available_info_popup/static/description/icon.png
  sale_stock_available_info_popup/static/description/index.html
  sale_stock_available_info_popup/static/src/xml/qty_at_date.xml
  sale_stock_available_info_popup/tests/__init__.py
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
  sale_stock_available_info_popup/views/sale_order_views.xml
  setup/sale_stock_available_info_popup/odoo/addons/sale_stock_available_info_popup
  setup/sale_stock_available_info_popup/setup.py
Labels: approved, bot is merging ⏳

#1087 [13.0][FIX] stock_vertical_lift: skip button is only for pick operation
  stock_vertical_lift/views/vertical_lift_operation_base_views.xml
  stock_vertical_lift/views/vertical_lift_operation_pick_views.xml
Labels: approved, bot is merging ⏳

#999 [13.0][MIG] stock_pull_list
  setup/stock_pull_list/odoo/addons/stock_pull_list
  setup/stock_pull_list/setup.py
  stock_pull_list/README.rst
  stock_pull_list/__init__.py
  stock_pull_list/__manifest__.py
  stock_pull_list/i18n/stock_pull_list.pot
  stock_pull_list/readme/CONTRIBUTORS.rst
  stock_pull_list/readme/DESCRIPTION.rst
  stock_pull_list/readme/ROADMAP.rst
  stock_pull_list/readme/USAGE.rst
  stock_pull_list/static/description/icon.png
  stock_pull_list/static/description/index.html
  stock_pull_list/tests/__init__.py
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/wizards/__init__.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
  stock_pull_list/wizards/stock_pull_list_wizard.xml
Labels: approved, bot is merging ⏳, migration

#1099 [FIX] stock_available_mrp: upstream compatibility
  stock_available_mrp/tests/test_potential_qty.py
Labels: approved, bot is merging ⏳
