Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-11, with the labels that each got.

#1293 [11.0][FIX] stock_request: tests
  stock_request/tests/test_stock_request.py
Labels: bot is merging ⏳

#1011 [11.0][ADD]stock_orderpoint_procure_location
  stock_orderpoint_procure_location/README.rst
  stock_orderpoint_procure_location/__init__.py
  stock_orderpoint_procure_location/__manifest__.py
  stock_orderpoint_procure_location/models/__init__.py
  stock_orderpoint_procure_location/models/procurement_group.py
  stock_orderpoint_procure_location/models/stock_warehouse_orderpoint.py
  stock_orderpoint_procure_location/static/description/icon.png
  stock_orderpoint_procure_location/tests/__init__.py
  stock_orderpoint_procure_location/tests/test_stock_orderpoint_procure_location.py
  stock_orderpoint_procure_location/views/stock_warehouse_orderpoint_view.xml
Labels: bot is merging ⏳

#1294 [14.0][stock_pull_list][imp] add sequence for procurement groups created from the pull list
  stock_pull_list/__manifest__.py
  stock_pull_list/data/stock_pull_list_sequence_data.xml
  stock_pull_list/wizards/stock_pull_list_wizard.py
Labels: approved, bot is merging ⏳

#1258 [14.0][ADD] stock_location_warehouse
  setup/stock_location_warehouse/odoo/addons/stock_location_warehouse
  setup/stock_location_warehouse/setup.py
  stock_location_warehouse/README.rst
  stock_location_warehouse/__init__.py
  stock_location_warehouse/__manifest__.py
  stock_location_warehouse/models/__init__.py
  stock_location_warehouse/models/stock_location.py
  stock_location_warehouse/readme/CONFIGURE.rst
  stock_location_warehouse/readme/CONTRIBUTORS.rst
  stock_location_warehouse/readme/DESCRIPTION.rst
  stock_location_warehouse/readme/USAGE.rst
  stock_location_warehouse/tests/__init__.py
  stock_location_warehouse/tests/test_location_warehouse.py
  stock_location_warehouse/views/stock_location.xml
Labels: approved, ready to merge, bot is merging ⏳

#1300 [15.0][MIG] procurement_auto_create_group
  procurement_auto_create_group/README.rst
  procurement_auto_create_group/__init__.py
  procurement_auto_create_group/__manifest__.py
  procurement_auto_create_group/i18n/cs_CZ.po
  procurement_auto_create_group/i18n/de.po
  procurement_auto_create_group/i18n/es.po
  procurement_auto_create_group/i18n/es_MX.po
  procurement_auto_create_group/i18n/fr.po
  procurement_auto_create_group/i18n/hr.po
  procurement_auto_create_group/i18n/it.po
  procurement_auto_create_group/i18n/procurement_auto_create_group.pot
  procurement_auto_create_group/i18n/pt_BR.po
  procurement_auto_create_group/i18n/pt_PT.po
  procurement_auto_create_group/i18n/ro.po
  procurement_auto_create_group/i18n/sk.po
  procurement_auto_create_group/i18n/sl.po
  procurement_auto_create_group/i18n/tr_TR.po
  procurement_auto_create_group/i18n/vi_VN.po
  procurement_auto_create_group/i18n/zh_CN.po
  procurement_auto_create_group/models/__init__.py
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/readme/CONFIGURE.rst
  procurement_auto_create_group/readme/CONTRIBUTORS.rst
  procurement_auto_create_group/readme/DESCRIPTION.rst
  procurement_auto_create_group/readme/USAGE.rst
  procurement_auto_create_group/static/description/icon.png
  procurement_auto_create_group/static/description/index.html
  procurement_auto_create_group/tests/__init__.py
  procurement_auto_create_group/tests/test_auto_create.py
  procurement_auto_create_group/views/procurement_view.xml
  setup/procurement_auto_create_group/odoo/addons/procurement_auto_create_group
  setup/procurement_auto_create_group/setup.py
Labels: approved, bot is merging ⏳

#711 [WMS][12.0] rework stock_location_zone
  stock_location_zone/__manifest__.py
  stock_location_zone/models/__init__.py
  stock_location_zone/models/stock_location.py
  stock_location_zone/models/stock_picking_zone.py
  stock_location_zone/readme/CONFIGURE.rst
  stock_location_zone/readme/CONTRIBUTORS.rst
  stock_location_zone/readme/DESCRIPTION.rst
  stock_location_zone/security/ir.model.access.csv
  stock_location_zone/views/stock_location.xml
  stock_location_zone/views/stock_picking_zone.xml
Labels: bot is merging ⏳

#1307 [14.0][MIG] stock_putaway_product_template: Migration to 14.0
  setup/stock_putaway_product_template/odoo/addons/stock_putaway_product_template
  setup/stock_putaway_product_template/setup.py
  stock_putaway_product_template/README.rst
  stock_putaway_product_template/__init__.py
  stock_putaway_product_template/__manifest__.py
  stock_putaway_product_template/i18n/es.po
  stock_putaway_product_template/i18n/stock_putaway_product_template.pot
  stock_putaway_product_template/models/__init__.py
  stock_putaway_product_template/models/product.py
  stock_putaway_product_template/models/stock_location.py
  stock_putaway_product_template/models/stock_putaway_rule.py
  stock_putaway_product_template/readme/CONTRIBUTORS.rst
  stock_putaway_product_template/readme/DESCRIPTION.rst
  stock_putaway_product_template/readme/USAGE.rst
  stock_putaway_product_template/static/description/icon.png
  stock_putaway_product_template/static/description/index.html
  stock_putaway_product_template/tests/__init__.py
  stock_putaway_product_template/tests/test_stock_putaway_rule.py
  stock_putaway_product_template/views/stock_putaway_rule_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1306 [14.0][MIG] stock_inventory_cost_info: Migration to 14.0
  setup/stock_inventory_cost_info/odoo/addons/stock_inventory_cost_info
  setup/stock_inventory_cost_info/setup.py
  stock_inventory_cost_info/README.rst
  stock_inventory_cost_info/__init__.py
  stock_inventory_cost_info/__manifest__.py
  stock_inventory_cost_info/hooks.py
  stock_inventory_cost_info/i18n/es.po
  stock_inventory_cost_info/i18n/stock_inventory_cost_info.pot
  stock_inventory_cost_info/models/__init__.py
  stock_inventory_cost_info/models/stock_inventory.py
  stock_inventory_cost_info/readme/CONTRIBUTORS.rst
  stock_inventory_cost_info/readme/DESCRIPTION.rst
  stock_inventory_cost_info/readme/INSTALL.rst
  stock_inventory_cost_info/readme/USAGE.rst
  stock_inventory_cost_info/static/description/icon.png
  stock_inventory_cost_info/static/description/index.html
  stock_inventory_cost_info/tests/__init__.py
  stock_inventory_cost_info/tests/test_stock_inventory_cost_info.py
  stock_inventory_cost_info/views/report_stockinventory.xml
  stock_inventory_cost_info/views/stock_inventory_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1309 [13.0][FIX] stock_secondary_unit: Prevent move_line_ids_without_package field is not editable.
  stock_secondary_unit/tests/test_stock_secondary_unit.py
Labels: approved

#1291 [14.0][imp] discrepancy by product avg
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/views/stock_inventory_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1310 [14.0][IMP] procurement_auto_create_group: auto_create_group for push rules
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/readme/CONFIGURE.rst
  procurement_auto_create_group/readme/CONTRIBUTORS.rst
  procurement_auto_create_group/readme/USAGE.rst
  procurement_auto_create_group/tests/test_auto_create.py
  procurement_auto_create_group/views/procurement_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1230 [14.0] [MIG] stock_orderpoint_manual_procurement_uom
  setup/stock_orderpoint_manual_procurement_uom/odoo/addons/stock_orderpoint_manual_procurement_uom
  setup/stock_orderpoint_manual_procurement_uom/setup.py
  stock_orderpoint_manual_procurement_uom/README.rst
  stock_orderpoint_manual_procurement_uom/__init__.py
  stock_orderpoint_manual_procurement_uom/__manifest__.py
  stock_orderpoint_manual_procurement_uom/i18n/stock_orderpoint_manual_procurement_uom.pot
  stock_orderpoint_manual_procurement_uom/i18n/zh_CN.po
  stock_orderpoint_manual_procurement_uom/models/__init__.py
  stock_orderpoint_manual_procurement_uom/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement_uom/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement_uom/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement_uom/readme/USAGE.rst
  stock_orderpoint_manual_procurement_uom/static/description/icon.png
  stock_orderpoint_manual_procurement_uom/static/description/index.html
  stock_orderpoint_manual_procurement_uom/tests/__init__.py
  stock_orderpoint_manual_procurement_uom/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement_uom/wizards/__init__.py
  stock_orderpoint_manual_procurement_uom/wizards/make_procurement_orderpoint.py
Labels: approved, ready to merge, bot is merging ⏳

#1191 [14.0][ADD] stock_inventory_line_product_cost
  setup/stock_inventory_line_product_cost/odoo/addons/stock_inventory_line_product_cost
  setup/stock_inventory_line_product_cost/setup.py
  stock_inventory_line_product_cost/README.rst
  stock_inventory_line_product_cost/__init__.py
  stock_inventory_line_product_cost/__manifest__.py
  stock_inventory_line_product_cost/models/__init__.py
  stock_inventory_line_product_cost/models/stock_inventory_line.py
  stock_inventory_line_product_cost/views/stock_inventory_line_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1224 [14.0][ADD] stock_inventory_preparation_filter_pos: filter inventory on POS categs
  setup/stock_inventory_preparation_filter_pos/odoo/addons/stock_inventory_preparation_filter_pos
  setup/stock_inventory_preparation_filter_pos/setup.py
  stock_inventory_preparation_filter/models/stock_inventory.py
  stock_inventory_preparation_filter/views/stock_inventory_view.xml
  stock_inventory_preparation_filter_pos/README.rst
  stock_inventory_preparation_filter_pos/__init__.py
  stock_inventory_preparation_filter_pos/__manifest__.py
  stock_inventory_preparation_filter_pos/models/__init__.py
  stock_inventory_preparation_filter_pos/models/stock_inventory.py
  stock_inventory_preparation_filter_pos/readme/CONTRIBUTORS.rst
  stock_inventory_preparation_filter_pos/readme/DESCRIPTION.rst
  stock_inventory_preparation_filter_pos/readme/USAGE.rst
  stock_inventory_preparation_filter_pos/tests/__init__.py
  stock_inventory_preparation_filter_pos/tests/test_preparation_filter_pos.py
  stock_inventory_preparation_filter_pos/views/stock_inventory.xml
Labels: needs review, bot is merging ⏳

#1318 [13.0][IMP] stock_request: fixes the company selection on the procurement
  stock_request/models/stock_request.py
Labels: approved, bot is merging ⏳
