Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-07, with the labels that each got.

#1158 [14.0][MIG] stock request picking type
  setup/stock_request_picking_type/odoo/addons/stock_request_picking_type
  setup/stock_request_picking_type/setup.py
  stock_request_picking_type/README.rst
  stock_request_picking_type/__init__.py
  stock_request_picking_type/__manifest__.py
  stock_request_picking_type/data/stock_picking_type.xml
  stock_request_picking_type/i18n/es.po
  stock_request_picking_type/i18n/pt_BR.po
  stock_request_picking_type/i18n/stock_request_picking_type.pot
  stock_request_picking_type/i18n/zh_CN.po
  stock_request_picking_type/migrations/12.0.2.0.0/post-migration.py
  stock_request_picking_type/models/__init__.py
  stock_request_picking_type/models/stock_picking_type.py
  stock_request_picking_type/models/stock_request_order.py
  stock_request_picking_type/readme/CONTRIBUTORS.rst
  stock_request_picking_type/readme/DESCRIPTION.rst
  stock_request_picking_type/readme/USAGE.rst
  stock_request_picking_type/static/description/icon.png
  stock_request_picking_type/static/description/index.html
  stock_request_picking_type/tests/__init__.py
  stock_request_picking_type/tests/test_stock_picking_type.py
  stock_request_picking_type/tests/test_stock_request.py
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1154 [13.0][FIX] stock_request_picking_type - fixing stock.picking.type.kanban view
  stock_request_picking_type/views/stock_picking_views.xml
  stock_request_picking_type/views/stock_request_order_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1151 [ADD] stock_search_supplierinfo_code
  stock_search_supplierinfo_code/__init__.py
  stock_search_supplierinfo_code/__manifest__.py
  stock_search_supplierinfo_code/readme/CONTRIBUTORS.rst
  stock_search_supplierinfo_code/readme/DESCRIPTION.rst
  stock_search_supplierinfo_code/views/stock_picking.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1176 s_packaging_calculator: include units when units only (on demand)
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator_packaging_type/tests/test_packaging_by_qty.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#969 [13.0][FIX]make reason fields read-only if in done state
  stock_change_qty_reason/models/stock_inventory.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1148 [12.0][FIX][IMP] stock_available_unreserved: can contain wrong value …
  stock_available_unreserved/models/quant.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1190 [13.0] [FIX] stock_inventory_include_exhausted: Filtered with product…
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
Labels: bot is merging ⏳, enhancement, needs review

#1199 s_packaging_calculator: improve test util
  stock_packaging_calculator/tests/utils.py
Labels: bot is merging ⏳

#1197 [ADD] stock_move_packaging_qty
  stock_move_packaging_qty/__init__.py
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/models/__init__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/readme/CONTRIBUTORS.rst
  stock_move_packaging_qty/readme/DESCRIPTION.rst
  stock_move_packaging_qty/tests/__init__.py
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/stock_move_tree_view.xml
  stock_move_packaging_qty/views/stock_picking_form_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1164 [14.0] [MIG] stock_orderpoint _move_link
  setup/stock_orderpoint_move_link/odoo/addons/stock_orderpoint_move_link
  setup/stock_orderpoint_move_link/setup.py
  stock_orderpoint_move_link/README.rst
  stock_orderpoint_move_link/__init__.py
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_move_link/i18n/stock_orderpoint_move_link.pot
  stock_orderpoint_move_link/i18n/zh_CN.po
  stock_orderpoint_move_link/models/__init__.py
  stock_orderpoint_move_link/models/stock.py
  stock_orderpoint_move_link/models/stock_move.py
  stock_orderpoint_move_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_move_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_move_link/readme/DESCRIPTION.rst
  stock_orderpoint_move_link/static/description/icon.png
  stock_orderpoint_move_link/static/description/index.html
  stock_orderpoint_move_link/tests/__init__.py
  stock_orderpoint_move_link/tests/test_stock_orderpoint_move_link.py
  stock_orderpoint_move_link/views/stock_move_views.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1198 [13.0][ADD] stock_move_packaging_qty
  setup/stock_move_packaging_qty/odoo/addons/stock_move_packaging_qty
  setup/stock_move_packaging_qty/setup.py
  stock_move_packaging_qty/__init__.py
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/models/__init__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/readme/CONTRIBUTORS.rst
  stock_move_packaging_qty/readme/DESCRIPTION.rst
  stock_move_packaging_qty/tests/__init__.py
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/stock_move_tree_view.xml
  stock_move_packaging_qty/views/stock_picking_form_view.xml
Labels: approved, bot is merging ⏳

#1192 [12.0][IMP] stock_secondary_unit: Use secondary units directly in pickings
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1205 [14.0][IMP] stock_quant_manual_assign: make qty_done fill optional
  stock_quant_manual_assign/__init__.py
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/models/__init__.py
  stock_quant_manual_assign/models/stock_picking_type.py
  stock_quant_manual_assign/readme/CONFIGURATION.rst
  stock_quant_manual_assign/tests/test_stock_quant_manual_assign.py
  stock_quant_manual_assign/views/stock_picking_type_views.xml
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1204 [13.0][IMP] stock_quant_manual_assign: make qty_done fill optional
  stock_quant_manual_assign/__init__.py
  stock_quant_manual_assign/__manifest__.py
  stock_quant_manual_assign/models/__init__.py
  stock_quant_manual_assign/models/stock_picking_type.py
  stock_quant_manual_assign/readme/CONFIGURATION.rst
  stock_quant_manual_assign/tests/test_stock_quant_manual_assign.py
  stock_quant_manual_assign/views/stock_picking_type_views.xml
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳

#1208 [13.0][FIX] stock_move_packaging_qty: Warning on runbot
  stock_move_packaging_qty/models/stock_move.py
Labels: approved, bot is merging ⏳

#1206 [13.0][ADD] stock_inventory_line package quantity
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_inventory_line.py
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/views/stock_inventory_line.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#1047 [MIG] 14.0 stock_generate_putaway_from_inventory
  setup/stock_generate_putaway_from_inventory/odoo/addons/stock_generate_putaway_from_inventory
  setup/stock_generate_putaway_from_inventory/setup.py
  stock_generate_putaway_from_inventory/README.rst
  stock_generate_putaway_from_inventory/__init__.py
  stock_generate_putaway_from_inventory/__manifest__.py
  stock_generate_putaway_from_inventory/i18n/fr.po
  stock_generate_putaway_from_inventory/i18n/stock_generate_putaway_from_inventory.pot
  stock_generate_putaway_from_inventory/models/__init__.py
  stock_generate_putaway_from_inventory/models/stock_inventory.py
  stock_generate_putaway_from_inventory/readme/CONTRIBUTORS.rst
  stock_generate_putaway_from_inventory/readme/DESCRIPTION.rst
  stock_generate_putaway_from_inventory/readme/USAGE.rst
  stock_generate_putaway_from_inventory/static/description/icon.png
  stock_generate_putaway_from_inventory/static/description/index.html
  stock_generate_putaway_from_inventory/tests/__init__.py
  stock_generate_putaway_from_inventory/tests/test_generate_putaway.py
  stock_generate_putaway_from_inventory/views/stock_inventory.xml
Labels: approved, bot is merging ⏳, ready to merge
