Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-01, with the labels that each got.

#1021 [13.0][FIX] stock_vertical_lift: handles multiple move lines on pick
  stock_vertical_lift/demo/stock_inventory_demo.xml
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/tests/common.py
  stock_vertical_lift/tests/test_pick.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#885 [IMP][12.0] stock_move_location: add posibility empty location with stock.picking
  stock_move_location/__init__.py
  stock_move_location/__manifest__.py
  stock_move_location/i18n/fr_BE.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/models/__init__.py
  stock_move_location/models/stock_picking.py
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/USAGE.rst
  stock_move_location/tests/__init__.py
  stock_move_location/tests/test_stock_fillwithstock.py
  stock_move_location/views/stock_picking.xml
  stock_move_location/wizard/stock_move_location.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1045 Revert "[13.0][FIX] stock_vertical_lift: Error in tests"
  stock_vertical_lift/models/vertical_lift_shuttle.py
Labels: bot is merging ⏳, needs review

#1049 14.0 mig stock inventory include exhausted
  setup/stock_inventory_include_exhausted/odoo/addons/stock_inventory_include_exhausted
  setup/stock_inventory_include_exhausted/setup.py
  stock_inventory_include_exhausted/README.rst
  stock_inventory_include_exhausted/__init__.py
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/i18n/es.po
  stock_inventory_include_exhausted/i18n/stock_inventory_include_exhausted.pot
  stock_inventory_include_exhausted/models/__init__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/readme/CONTRIBUTORS.rst
  stock_inventory_include_exhausted/readme/DESCRIPTION.rst
  stock_inventory_include_exhausted/readme/USAGE.rst
  stock_inventory_include_exhausted/static/description/icon.png
  stock_inventory_include_exhausted/static/description/index.html
  stock_inventory_include_exhausted/tests/__init__.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
  stock_inventory_include_exhausted/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳, migration, needs review

#1040 [12.0][FIX] stock_request: fix archived search view
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1051 [13.0] stock_available: Fix creation of product variants in tests
  stock_available/tests/test_stock_available.py
Labels: bot is merging ⏳

#1046 [13.0] stock_reserve_rule: ensure fifo/fefo order first
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: approved, bot is merging ⏳

#855 [13.0] Create module stock_location_children
  setup/stock_location_children/odoo/addons/stock_location_children
  setup/stock_location_children/setup.py
  stock_location_children/__init__.py
  stock_location_children/__manifest__.py
  stock_location_children/models/__init__.py
  stock_location_children/models/stock_location.py
  stock_location_children/readme/CONTRIBUTORS.rst
  stock_location_children/readme/DESCRIPTION.rst
  stock_location_children/tests/__init__.py
  stock_location_children/tests/test_stock_location_children.py
Labels: approved, bot is merging ⏳

#1056 [FIX] stock_mts_mto_rule: Installation across companies
  stock_mts_mto_rule/data/stock_data.xml
Labels: approved, bot is merging ⏳

#1019 [12.0][ADD] stock_archive_constraint: Allows to block archiving products and locations
  stock_archive_constraint/README.rst
  stock_archive_constraint/__init__.py
  stock_archive_constraint/__manifest__.py
  stock_archive_constraint/i18n/es.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/__init__.py
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/product_template.py
  stock_archive_constraint/models/stock_location.py
  stock_archive_constraint/readme/CONTRIBUTORS.rst
  stock_archive_constraint/readme/DESCRIPTION.rst
  stock_archive_constraint/readme/USAGE.rst
  stock_archive_constraint/static/description/icon.png
  stock_archive_constraint/tests/__init__.py
  stock_archive_constraint/tests/test_location_archive_constraint.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1059 [FIX] sale_stock_available_info: ensure test line order
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
Labels: approved, bot is merging ⏳

#1062 [13.0][IMP] stock_vertical_lift: Add skip operation to vertical lift shuttles
  stock_vertical_lift/README.rst
  stock_vertical_lift/images/O-BTN.skip.svg
  stock_vertical_lift/models/stock_move_line.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/readme/CONFIGURE.rst
  stock_vertical_lift/readme/DEVELOP.rst
  stock_vertical_lift/static/description/index.html
  stock_vertical_lift/tests/test_pick.py
  stock_vertical_lift/views/vertical_lift_operation_base_views.xml
Labels: approved, bot is merging ⏳

#1042 [14.0][ADD] stock_free_quantity
  setup/stock_free_quantity/odoo/addons/stock_free_quantity
  setup/stock_free_quantity/setup.py
  stock_free_quantity/__init__.py
  stock_free_quantity/__manifest__.py
  stock_free_quantity/models/__init__.py
  stock_free_quantity/models/product_template.py
  stock_free_quantity/readme/CONTRIBUTORS.rst
  stock_free_quantity/readme/DESCRIPTION.rst
  stock_free_quantity/tests/__init__.py
  stock_free_quantity/tests/test_template_free_qty.py
  stock_free_quantity/views/product_product_view.xml
  stock_free_quantity/views/product_template_view.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1068 [12.0] [FIX] stock_archive_constraint: Test bug product_uom_qty is a read-only field
  stock_archive_constraint/tests/test_location_archive_constraint.py
Labels: approved, bot is merging ⏳
