Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-05, with the labels that each got.

#1143 [12.0][FIX] stock_account_inventory_force_date search category
  stock_account_inventory_force_date/models/stock_inventory.py
Labels: approved, bot is merging ⏳, ready to merge

#1075 [13.0][FIX] stock_cubiscan: Default packaging quantity
  stock_cubiscan/wizard/cubiscan_wizard.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1076 [MIG] stock_location_position: Migration to 14.0
  setup/stock_location_position/odoo/addons/stock_location_position
  setup/stock_location_position/setup.py
  stock_location_position/README.rst
  stock_location_position/__init__.py
  stock_location_position/__manifest__.py
  stock_location_position/i18n/stock_location_position.pot
  stock_location_position/models/__init__.py
  stock_location_position/models/stock_location.py
  stock_location_position/readme/CONTRIBUTORS.rst
  stock_location_position/readme/CREDITS.rst
  stock_location_position/readme/DESCRIPTION.rst
  stock_location_position/static/description/icon.png
  stock_location_position/static/description/index.html
  stock_location_position/views/stock_location.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1150 s_packaging_calculator: include barcode
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/utils.py
Labels: bot is merging ⏳

#1144 [13.0] stock_measuring_device improvements
  stock_measuring_device/__manifest__.py
  stock_measuring_device/models/measuring_device.py
  stock_measuring_device/models/product_packaging.py
  stock_measuring_device/static/src/js/measuring_wizard.js
  stock_measuring_device/views/assets.xml
  stock_measuring_device/wizard/measuring_wizard.py
  stock_measuring_device/wizard/measuring_wizard.xml
  stock_measuring_device/wizard/measuring_wizard_line.py
  stock_measuring_device_zippcube/components/zippcube_device_component.py
Labels: bot is merging ⏳, enhancement, needs review

#1146 [13.0] [ADD] stock_lot_filter_available: New module to filter lots on stock
  setup/stock_lot_filter_available/odoo/addons/stock_lot_filter_available
  setup/stock_lot_filter_available/setup.py
  stock_lot_filter_available/README.rst
  stock_lot_filter_available/__init__.py
  stock_lot_filter_available/__manifest__.py
  stock_lot_filter_available/i18n/es.po
  stock_lot_filter_available/i18n/stock_lot_filter_available.pot
  stock_lot_filter_available/models/__init__.py
  stock_lot_filter_available/models/stock_production_lot.py
  stock_lot_filter_available/readme/CONTRIBUTORS.rst
  stock_lot_filter_available/readme/DESCRIPTION.rst
  stock_lot_filter_available/readme/USAGE.rst
  stock_lot_filter_available/static/description/index.html
  stock_lot_filter_available/tests/__init__.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
  stock_lot_filter_available/views/stock_production_lot_views.xml
Labels: approved, bot is merging ⏳

#1152 [13.0][MIG] stock_available_mrp: Migration to 13.0
  setup/stock_available_mrp/odoo/addons/stock_available_mrp
  setup/stock_available_mrp/setup.py
  stock_available_mrp/README.rst
  stock_available_mrp/__init__.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/DESCRIPTION.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/static/description/icon.png
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/__init__.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: approved, bot is merging ⏳, ready to merge

#1156 [13.0][FIX] account_move_line_stock_info: minor fix in picking form view inherit
  account_move_line_stock_info/views/stock_move_view.xml
Labels: approved, bot is merging ⏳
