Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-09, with the labels that each got.

#1231 [FIX] stock_mts_mto_rule: don't update route
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/data/stock_data.xml
  stock_mts_mto_rule/migrations/13.0.1.3.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1219 [14.0][FIX] stock_request: Stock Request User can delete Stock Request
  stock_request/security/ir.model.access.csv
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1113 [13.0][MIG] stock_production_lot_quantity_tree: Migration to 13.0
  setup/stock_production_lot_quantity_tree/odoo/addons/stock_production_lot_quantity_tree
  setup/stock_production_lot_quantity_tree/setup.py
  stock_production_lot_quantity_tree/README.rst
  stock_production_lot_quantity_tree/__init__.py
  stock_production_lot_quantity_tree/__manifest__.py
  stock_production_lot_quantity_tree/i18n/stock_production_lot_quantity_tree.pot
  stock_production_lot_quantity_tree/readme/CONTRIBUTORS.rst
  stock_production_lot_quantity_tree/readme/DESCRIPTION.rst
  stock_production_lot_quantity_tree/static/description/icon.png
  stock_production_lot_quantity_tree/static/description/index.html
  stock_production_lot_quantity_tree/views/stock_production_lot.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1169 [14.0][MIG] - stock_available_unreserved
  setup/stock_available_unreserved/odoo/addons/stock_available_unreserved
  setup/stock_available_unreserved/setup.py
  stock_available_unreserved/README.rst
  stock_available_unreserved/__init__.py
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/i18n/ar.po
  stock_available_unreserved/i18n/ca.po
  stock_available_unreserved/i18n/de.po
  stock_available_unreserved/i18n/el_GR.po
  stock_available_unreserved/i18n/es.po
  stock_available_unreserved/i18n/es_ES.po
  stock_available_unreserved/i18n/es_MX.po
  stock_available_unreserved/i18n/eu.po
  stock_available_unreserved/i18n/fi.po
  stock_available_unreserved/i18n/fr.po
  stock_available_unreserved/i18n/fr_CH.po
  stock_available_unreserved/i18n/fr_FR.po
  stock_available_unreserved/i18n/gl.po
  stock_available_unreserved/i18n/hr.po
  stock_available_unreserved/i18n/hr_HR.po
  stock_available_unreserved/i18n/it.po
  stock_available_unreserved/i18n/nl.po
  stock_available_unreserved/i18n/nl_NL.po
  stock_available_unreserved/i18n/pt.po
  stock_available_unreserved/i18n/pt_BR.po
  stock_available_unreserved/i18n/ro.po
  stock_available_unreserved/i18n/ru.po
  stock_available_unreserved/i18n/sl.po
  stock_available_unreserved/i18n/stock_available_unreserved.pot
  stock_available_unreserved/i18n/tr.po
  stock_available_unreserved/i18n/tr_TR.po
  stock_available_unreserved/i18n/vi_VN.po
  stock_available_unreserved/i18n/zh_CN.po
  stock_available_unreserved/models/__init__.py
  stock_available_unreserved/models/product_product.py
  stock_available_unreserved/models/product_template.py
  stock_available_unreserved/models/stock_quant.py
  stock_available_unreserved/readme/CONTRIBUTORS.rst
  stock_available_unreserved/readme/DESCRIPTION.rst
  stock_available_unreserved/static/description/icon.png
  stock_available_unreserved/static/description/index.html
  stock_available_unreserved/tests/__init__.py
  stock_available_unreserved/tests/test_stock_available_unreserved.py
  stock_available_unreserved/views/product_view.xml
  stock_available_unreserved/views/stock_quant_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1216 [13.0] [ADD] sale_automatic_workflow_reserve_sale_stock: New module to allow make automatic reserves
  oca_dependencies.txt
  sale_automatic_workflow_reserve_sale_stock/README.rst
  sale_automatic_workflow_reserve_sale_stock/__init__.py
  sale_automatic_workflow_reserve_sale_stock/__manifest__.py
  sale_automatic_workflow_reserve_sale_stock/i18n/es.po
  sale_automatic_workflow_reserve_sale_stock/i18n/sale_automatic_workflow_stock_reserve.pot
  sale_automatic_workflow_reserve_sale_stock/models/__init__.py
  sale_automatic_workflow_reserve_sale_stock/models/automatic_workflow_job.py
  sale_automatic_workflow_reserve_sale_stock/models/sale_workflow_process.py
  sale_automatic_workflow_reserve_sale_stock/readme/CONFIGURE.rst
  sale_automatic_workflow_reserve_sale_stock/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_reserve_sale_stock/readme/DESCRIPTION.rst
  sale_automatic_workflow_reserve_sale_stock/readme/USAGE.rst
  sale_automatic_workflow_reserve_sale_stock/static/description/index.html
  sale_automatic_workflow_reserve_sale_stock/tests/__init__.py
  sale_automatic_workflow_reserve_sale_stock/tests/test_sale_automatic_workflow_stock_reserve.py
  sale_automatic_workflow_reserve_sale_stock/views/sale_workflow_process_view.xml
  setup/sale_automatic_workflow_reserve_sale_stock/odoo/addons/sale_automatic_workflow_reserve_sale_stock
  setup/sale_automatic_workflow_reserve_sale_stock/setup.py
Labels: approved, bot is merging ⏳

#1077 [MIG] stock_location_zone: Migration to 14.0
  setup/stock_location_zone/odoo/addons/stock_location_zone
  setup/stock_location_zone/setup.py
  stock_location_zone/README.rst
  stock_location_zone/__init__.py
  stock_location_zone/__manifest__.py
  stock_location_zone/i18n/stock_location_zone.pot
  stock_location_zone/i18n/zh_CN.po
  stock_location_zone/models/__init__.py
  stock_location_zone/models/stock_location.py
  stock_location_zone/readme/CONTRIBUTORS.rst
  stock_location_zone/readme/CREDITS.rst
  stock_location_zone/readme/DESCRIPTION.rst
  stock_location_zone/static/description/icon.png
  stock_location_zone/static/description/index.html
  stock_location_zone/views/stock_location.xml
Labels: approved, bot is merging ⏳

#1079 [MIG] stock_location_tray: Migration to 14.0
  setup/stock_location_tray/odoo/addons/stock_location_tray
  setup/stock_location_tray/setup.py
  stock_location_tray/README.rst
  stock_location_tray/__init__.py
  stock_location_tray/__manifest__.py
  stock_location_tray/demo/stock_location_demo.xml
  stock_location_tray/demo/stock_location_tray_type_demo.xml
  stock_location_tray/i18n/stock_location_tray.pot
  stock_location_tray/models/__init__.py
  stock_location_tray/models/stock_location.py
  stock_location_tray/models/stock_location_tray_type.py
  stock_location_tray/models/stock_move_line.py
  stock_location_tray/readme/CONFIGURE.rst
  stock_location_tray/readme/CONTRIBUTORS.rst
  stock_location_tray/readme/CREDITS.rst
  stock_location_tray/readme/DESCRIPTION.rst
  stock_location_tray/readme/ROADMAP.rst
  stock_location_tray/security/ir.model.access.csv
  stock_location_tray/static/description/icon.png
  stock_location_tray/static/description/index.html
  stock_location_tray/static/description/location-tray.png
  stock_location_tray/static/src/js/stock_location_tray.js
  stock_location_tray/static/src/scss/stock_location_tray.scss
  stock_location_tray/tests/__init__.py
  stock_location_tray/tests/common.py
  stock_location_tray/tests/test_location.py
  stock_location_tray/tests/test_stock_move_line.py
  stock_location_tray/tests/test_tray_type.py
  stock_location_tray/views/stock_location_tray_templates.xml
  stock_location_tray/views/stock_location_tray_type_views.xml
  stock_location_tray/views/stock_location_views.xml
  stock_location_tray/views/stock_move_line_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1242 [14.0][MIG] stock_measuring_device
  setup/stock_measuring_device/odoo/addons/stock_measuring_device
  setup/stock_measuring_device/setup.py
  stock_measuring_device/README.rst
  stock_measuring_device/__init__.py
  stock_measuring_device/__manifest__.py
  stock_measuring_device/components/__init__.py
  stock_measuring_device/components/measuring_device_component.py
  stock_measuring_device/data/uom.xml
  stock_measuring_device/i18n/stock_measuring_device.pot
  stock_measuring_device/models/__init__.py
  stock_measuring_device/models/measuring_device.py
  stock_measuring_device/models/product_packaging.py
  stock_measuring_device/models/stock_warehouse.py
  stock_measuring_device/readme/CONFIGURE.rst
  stock_measuring_device/readme/CONTRIBUTORS.rst
  stock_measuring_device/readme/CREDITS.rst
  stock_measuring_device/readme/DESCRIPTION.rst
  stock_measuring_device/readme/INSTALL.rst
  stock_measuring_device/readme/ROADMAP.rst
  stock_measuring_device/readme/USAGE.rst
  stock_measuring_device/security/ir.model.access.csv
  stock_measuring_device/static/description/icon.png
  stock_measuring_device/static/description/index.html
  stock_measuring_device/static/src/js/measuring_wizard.js
  stock_measuring_device/static/src/scss/measuring_wizard.scss
  stock_measuring_device/views/assets.xml
  stock_measuring_device/views/measuring_device_view.xml
  stock_measuring_device/views/menu.xml
  stock_measuring_device/wizard/__init__.py
  stock_measuring_device/wizard/measuring_wizard.py
  stock_measuring_device/wizard/measuring_wizard.xml
  stock_measuring_device/wizard/measuring_wizard_line.py
Labels: approved, bot is merging ⏳

#1243 [14.0][MIG] stock_measuring_device_zippcube
  setup/stock_measuring_device_zippcube/odoo/addons/stock_measuring_device_zippcube
  setup/stock_measuring_device_zippcube/setup.py
  stock_measuring_device_zippcube/README.rst
  stock_measuring_device_zippcube/__init__.py
  stock_measuring_device_zippcube/__manifest__.py
  stock_measuring_device_zippcube/components/__init__.py
  stock_measuring_device_zippcube/components/zippcube_device_component.py
  stock_measuring_device_zippcube/controllers/__init__.py
  stock_measuring_device_zippcube/controllers/main.py
  stock_measuring_device_zippcube/i18n/stock_measuring_device_zippcube.pot
  stock_measuring_device_zippcube/models/__init__.py
  stock_measuring_device_zippcube/models/measuring_device.py
  stock_measuring_device_zippcube/readme/CONFIGURE.rst
  stock_measuring_device_zippcube/readme/CONTRIBUTORS.rst
  stock_measuring_device_zippcube/readme/CREDITS.rst
  stock_measuring_device_zippcube/readme/DESCRIPTION.rst
  stock_measuring_device_zippcube/readme/INSTALL.rst
  stock_measuring_device_zippcube/readme/ROADMAP.rst
  stock_measuring_device_zippcube/readme/USAGE.rst
  stock_measuring_device_zippcube/scripts/measurement.sh
  stock_measuring_device_zippcube/static/description/icon.png
  stock_measuring_device_zippcube/static/description/index.html
  stock_measuring_device_zippcube/tests/__init__.py
  stock_measuring_device_zippcube/tests/test_zippcube_wizard.py
Labels: bot is merging ⏳

#1248 [13.0][FIX] stock_available_mrp: variable referenced before assignment
  stock_available_mrp/models/product_product.py
Labels: approved

#1247 [12.0][FIX] stock_secondary_unit, update secondary_uom_qty on move line
  stock_secondary_unit/models/stock_move.py
Labels: approved, bot is merging ⏳

#1090 [MIG] stock_vertical_lift: Migration to 14.0
  setup/stock_vertical_lift/odoo/addons/stock_vertical_lift
  setup/stock_vertical_lift/setup.py
  stock_vertical_lift/README.rst
  stock_vertical_lift/__init__.py
  stock_vertical_lift/__manifest__.py
  stock_vertical_lift/controllers/__init__.py
  stock_vertical_lift/controllers/main.py
  stock_vertical_lift/data/ir_sequence.xml
  stock_vertical_lift/demo/product_demo.xml
  stock_vertical_lift/demo/stock_inventory_demo.xml
  stock_vertical_lift/demo/stock_location_demo.xml
  stock_vertical_lift/demo/stock_picking_demo.xml
  stock_vertical_lift/demo/vertical_lift_shuttle_demo.xml
  stock_vertical_lift/i18n/stock_vertical_lift.pot
  stock_vertical_lift/images/O-BTN.release.svg
  stock_vertical_lift/images/O-BTN.save.svg
  stock_vertical_lift/images/O-BTN.skip.svg
  stock_vertical_lift/models/__init__.py
  stock_vertical_lift/models/stock_inventory.py
  stock_vertical_lift/models/stock_location.py
  stock_vertical_lift/models/stock_move.py
  stock_vertical_lift/models/stock_move_line.py
  stock_vertical_lift/models/stock_quant.py
  stock_vertical_lift/models/vertical_lift_command.py
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_inventory.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
  stock_vertical_lift/models/vertical_lift_shuttle.py
  stock_vertical_lift/readme/CONFIGURE.rst
  stock_vertical_lift/readme/CONTRIBUTORS.rst
  stock_vertical_lift/readme/CREDITS.rst
  stock_vertical_lift/readme/DESCRIPTION.rst
  stock_vertical_lift/readme/DEVELOP.rst
  stock_vertical_lift/readme/ROADMAP.rst
  stock_vertical_lift/security/ir.model.access.csv
  stock_vertical_lift/static/description/icon.png
  stock_vertical_lift/static/description/index.html
  stock_vertical_lift/static/src/js/vertical_lift.js
  stock_vertical_lift/static/src/scss/vertical_lift.scss
  stock_vertical_lift/tests/__init__.py
  stock_vertical_lift/tests/common.py
  stock_vertical_lift/tests/test_inventory.py
  stock_vertical_lift/tests/test_lift_command.py
  stock_vertical_lift/tests/test_location.py
  stock_vertical_lift/tests/test_pick.py
  stock_vertical_lift/tests/test_put.py
  stock_vertical_lift/views/shuttle_screen_templates.xml
  stock_vertical_lift/views/stock_location_views.xml
  stock_vertical_lift/views/stock_move_line_views.xml
  stock_vertical_lift/views/stock_vertical_lift_templates.xml
  stock_vertical_lift/views/vertical_lift_operation_base_views.xml
  stock_vertical_lift/views/vertical_lift_operation_inventory_views.xml
  stock_vertical_lift/views/vertical_lift_operation_pick_views.xml
  stock_vertical_lift/views/vertical_lift_operation_put_views.xml
  stock_vertical_lift/views/vertical_lift_shuttle_views.xml
  stock_vertical_lift/wizards/__init__.py
  stock_vertical_lift/wizards/vertical_lift_shuttle_manual_barcode.py
Labels: needs review, approved, migration, bot is merging ⏳

#1244 [IMP] stock_cycle: save field readonly(warehouse_ids)
  stock_cycle_count/views/stock_cycle_count_rule_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1078 [MIG] stock_location_bin_name: Migration to 14.0
  setup/stock_location_bin_name/odoo/addons/stock_location_bin_name
  setup/stock_location_bin_name/setup.py
  stock_location_bin_name/README.rst
  stock_location_bin_name/__init__.py
  stock_location_bin_name/__manifest__.py
  stock_location_bin_name/i18n/stock_location_bin_name.pot
  stock_location_bin_name/models/__init__.py
  stock_location_bin_name/models/stock_location.py
  stock_location_bin_name/readme/CONTRIBUTORS.rst
  stock_location_bin_name/readme/CREDITS.rst
  stock_location_bin_name/readme/DESCRIPTION.rst
  stock_location_bin_name/static/description/icon.png
  stock_location_bin_name/static/description/index.html
  stock_location_bin_name/views/stock_location.xml
Labels: approved, ready to merge, bot is merging ⏳

#1252 [12.0][FIX] stock_available_info_popup: warehouse context
  sale_stock_available_info_popup/models/sale_order.py
Labels: approved, bot is merging ⏳

#1091 [MIG] stock_vertical_lift_kardex: Migration to 14.0
  setup/stock_vertical_lift_kardex/odoo/addons/stock_vertical_lift_kardex
  setup/stock_vertical_lift_kardex/setup.py
  stock_vertical_lift_kardex/README.rst
  stock_vertical_lift_kardex/__init__.py
  stock_vertical_lift_kardex/__manifest__.py
  stock_vertical_lift_kardex/i18n/stock_vertical_lift_kardex.pot
  stock_vertical_lift_kardex/models/__init__.py
  stock_vertical_lift_kardex/models/stock_location.py
  stock_vertical_lift_kardex/models/vertical_lift_shuttle.py
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
  stock_vertical_lift_kardex/proxy/requirements.txt
  stock_vertical_lift_kardex/proxy/test.py
  stock_vertical_lift_kardex/readme/CONTRIBUTORS.rst
  stock_vertical_lift_kardex/readme/CREDITS.rst
  stock_vertical_lift_kardex/readme/DESCRIPTION.rst
  stock_vertical_lift_kardex/readme/ROADMAP.rst
  stock_vertical_lift_kardex/requirements.txt
  stock_vertical_lift_kardex/static/description/icon.png
  stock_vertical_lift_kardex/static/description/index.html
Labels: approved, bot is merging ⏳

#1245 [14.0] [IMP] stock_packaging_calculator - forward port
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator/tests/utils.py
Labels: enhancement, needs review, bot is merging ⏳

#1251 [14.0][MIG] stock_vertical_lift_server_env
  setup/stock_vertical_lift_server_env/odoo/addons/stock_vertical_lift_server_env
  setup/stock_vertical_lift_server_env/setup.py
  stock_vertical_lift_server_env/README.rst
  stock_vertical_lift_server_env/__init__.py
  stock_vertical_lift_server_env/__manifest__.py
  stock_vertical_lift_server_env/i18n/stock_vertical_lift_server_env.pot
  stock_vertical_lift_server_env/models/__init__.py
  stock_vertical_lift_server_env/models/vertical_lift_shuttle.py
  stock_vertical_lift_server_env/readme/CONTRIBUTORS.rst
  stock_vertical_lift_server_env/readme/CREDITS.rst
  stock_vertical_lift_server_env/readme/DESCRIPTION.rst
  stock_vertical_lift_server_env/static/description/icon.png
  stock_vertical_lift_server_env/static/description/index.html
Labels: approved, bot is merging ⏳

#1254 [MIG] stock_orderpoint_purchase_link: Migration to 14.0
  setup/stock_orderpoint_purchase_link/odoo/addons/stock_orderpoint_purchase_link
  setup/stock_orderpoint_purchase_link/setup.py
  stock_orderpoint_purchase_link/README.rst
  stock_orderpoint_purchase_link/__init__.py
  stock_orderpoint_purchase_link/__manifest__.py
  stock_orderpoint_purchase_link/i18n/stock_orderpoint_purchase_link.pot
  stock_orderpoint_purchase_link/i18n/zh_CN.po
  stock_orderpoint_purchase_link/models/__init__.py
  stock_orderpoint_purchase_link/models/purchase_order_line.py
  stock_orderpoint_purchase_link/models/stock_rule.py
  stock_orderpoint_purchase_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_purchase_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_purchase_link/readme/CREDITS.rst
  stock_orderpoint_purchase_link/readme/DESCRIPTION.rst
  stock_orderpoint_purchase_link/static/description/icon.png
  stock_orderpoint_purchase_link/static/description/index.html
  stock_orderpoint_purchase_link/tests/__init__.py
  stock_orderpoint_purchase_link/tests/test_stock_orderpoint_purchase_link.py
  stock_orderpoint_purchase_link/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1246 [13.0][IMP] stock_lot_filter_available: Add more conditions to avoid errors
  stock_lot_filter_available/models/stock_production_lot.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
Labels: bot is merging ⏳

#1257 [14.0][MIG] stock_vertical_lift_storage_type
  setup/stock_vertical_lift_storage_type/odoo/addons/stock_vertical_lift_storage_type
  setup/stock_vertical_lift_storage_type/setup.py
  stock_vertical_lift_storage_type/README.rst
  stock_vertical_lift_storage_type/__init__.py
  stock_vertical_lift_storage_type/__manifest__.py
  stock_vertical_lift_storage_type/i18n/stock_vertical_lift_storage_type.pot
  stock_vertical_lift_storage_type/models/__init__.py
  stock_vertical_lift_storage_type/models/stock_location.py
  stock_vertical_lift_storage_type/models/stock_location_tray_type.py
  stock_vertical_lift_storage_type/models/stock_quant.py
  stock_vertical_lift_storage_type/models/vertical_lift_operation_put.py
  stock_vertical_lift_storage_type/readme/CONTRIBUTORS.rst
  stock_vertical_lift_storage_type/readme/CREDITS.rst
  stock_vertical_lift_storage_type/readme/DESCRIPTION.rst
  stock_vertical_lift_storage_type/static/description/icon.png
  stock_vertical_lift_storage_type/static/description/index.html
  stock_vertical_lift_storage_type/tests/__init__.py
  stock_vertical_lift_storage_type/tests/common.py
  stock_vertical_lift_storage_type/tests/test_put.py
  stock_vertical_lift_storage_type/tests/test_stock_location.py
  stock_vertical_lift_storage_type/tests/test_tray_type.py
  stock_vertical_lift_storage_type/views/stock_location_tray_type_views.xml
  stock_vertical_lift_storage_type/views/stock_location_views.xml
Labels: approved, bot is merging ⏳

#1238 [13.0][FIX] stock_location_last_inventory_date
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/tests/test_stock_location.py
  stock_location_last_inventory_date/views/stock_location_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1256 [14.0][MIG] stock_product_qty_by_packaging: Migration to 14.0
  setup/stock_product_qty_by_packaging/odoo/addons/stock_product_qty_by_packaging
  setup/stock_product_qty_by_packaging/setup.py
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__init__.py
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/i18n/stock_product_qty_by_packaging.pot
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_inventory_line.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/CREDITS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/icon.png
  stock_product_qty_by_packaging/static/description/index.html
  stock_product_qty_by_packaging/tests/__init__.py
  stock_product_qty_by_packaging/tests/test_stock.py
  stock_product_qty_by_packaging/views/stock_inventory_line.xml
  stock_product_qty_by_packaging/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#1261 [14.0][MIG] stock_location_last_inventory_date
  setup/stock_location_last_inventory_date/odoo/addons/stock_location_last_inventory_date
  setup/stock_location_last_inventory_date/setup.py
  stock_location_last_inventory_date/README.rst
  stock_location_last_inventory_date/__init__.py
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/i18n/stock_location_last_inventory_date.pot
  stock_location_last_inventory_date/models/__init__.py
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/readme/CONTRIBUTORS.rst
  stock_location_last_inventory_date/readme/CREDITS.rst
  stock_location_last_inventory_date/readme/DESCRIPTION.rst
  stock_location_last_inventory_date/static/description/icon.png
  stock_location_last_inventory_date/static/description/index.html
  stock_location_last_inventory_date/tests/__init__.py
  stock_location_last_inventory_date/tests/test_stock_location.py
  stock_location_last_inventory_date/views/stock_location_views.xml
Labels: approved, migration, bot is merging ⏳

#1255 [14.0][MIG] stock_packaging_calculator_packaging_type: Migration to 14.0
  setup/stock_packaging_calculator_packaging_type/odoo/addons/stock_packaging_calculator_packaging_type
  setup/stock_packaging_calculator_packaging_type/setup.py
  stock_packaging_calculator_packaging_type/README.rst
  stock_packaging_calculator_packaging_type/__init__.py
  stock_packaging_calculator_packaging_type/__manifest__.py
  stock_packaging_calculator_packaging_type/i18n/stock_packaging_calculator_packaging_type.pot
  stock_packaging_calculator_packaging_type/models/__init__.py
  stock_packaging_calculator_packaging_type/models/product.py
  stock_packaging_calculator_packaging_type/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator_packaging_type/readme/CONTRIBUTORS.rst
  stock_packaging_calculator_packaging_type/readme/CREDITS.rst
  stock_packaging_calculator_packaging_type/readme/DESCRIPTION.rst
  stock_packaging_calculator_packaging_type/static/description/icon.png
  stock_packaging_calculator_packaging_type/static/description/index.html
  stock_packaging_calculator_packaging_type/tests/__init__.py
  stock_packaging_calculator_packaging_type/tests/test_packaging_by_qty.py
Labels: approved, migration, bot is merging ⏳

#1262 [14.0][FIX] stock_request: default value should not depend on another field
  stock_request/models/stock_request.py
Labels: bot is merging ⏳

#1249 [14.0][MIG] stock_orderpoint_route: Migration to 14.0
  setup/stock_orderpoint_route/odoo/addons/stock_orderpoint_route
  setup/stock_orderpoint_route/setup.py
  stock_orderpoint_route/README.rst
  stock_orderpoint_route/__init__.py
  stock_orderpoint_route/__manifest__.py
  stock_orderpoint_route/i18n/stock_orderpoint_route.pot
  stock_orderpoint_route/models/__init__.py
  stock_orderpoint_route/models/stock_warehouse_orderpoint.py
  stock_orderpoint_route/readme/CONTRIBUTORS.rst
  stock_orderpoint_route/readme/CREDITS.rst
  stock_orderpoint_route/readme/DESCRIPTION.rst
  stock_orderpoint_route/readme/USAGE.rst
  stock_orderpoint_route/static/description/icon.png
  stock_orderpoint_route/static/description/index.html
  stock_orderpoint_route/tests/__init__.py
  stock_orderpoint_route/tests/test_stock_orderpoint_route.py
  stock_orderpoint_route/views/stock_warehouse_orderpoint_views.xml
Labels: bot is merging ⏳

#1185 [13.0] stock_cycle_count error on location_id
  stock_cycle_count/models/stock_location.py
Labels: approved, bot is merging ⏳
