Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-03, with the labels that each got.

#1085 [13.0][MIG] stock_available_immediately: Migration to 13.0
  setup/stock_available_immediately/odoo/addons/stock_available_immediately
  setup/stock_available_immediately/setup.py
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/readme/CONTRIBUTORS.rst
  stock_available_immediately/readme/DESCRIPTION.rst
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: approved, bot is merging ⏳, ready to merge

#1093 [FIX] stock_orderpoint_generator: stock history initial value
  stock_orderpoint_generator/models/product.py
  stock_orderpoint_generator/tests/test_orderpoint_generator.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1103 [14.0][REM] stock_inventory_include_exhausted: Module added to Odoo 14
  setup/stock_inventory_include_exhausted/odoo/addons/stock_inventory_include_exhausted
  setup/stock_inventory_include_exhausted/setup.py
  stock_inventory_include_exhausted/README.rst
  stock_inventory_include_exhausted/__init__.py
  stock_inventory_include_exhausted/__manifest__.py
  stock_inventory_include_exhausted/i18n/es.po
  stock_inventory_include_exhausted/i18n/stock_inventory_include_exhausted.pot
  stock_inventory_include_exhausted/models/__init__.py
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/readme/CONTRIBUTORS.rst
  stock_inventory_include_exhausted/readme/DESCRIPTION.rst
  stock_inventory_include_exhausted/readme/USAGE.rst
  stock_inventory_include_exhausted/static/description/icon.png
  stock_inventory_include_exhausted/static/description/index.html
  stock_inventory_include_exhausted/tests/__init__.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
  stock_inventory_include_exhausted/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳

#1084 [14.0] [MIG] scrap_reason_code: Migrated the module in v14.
  scrap_reason_code/README.rst
  scrap_reason_code/__init__.py
  scrap_reason_code/__manifest__.py
  scrap_reason_code/i18n/scrap_reason_code.pot
  scrap_reason_code/models/__init__.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONFIGURE.rst
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/readme/CREDITS.rst
  scrap_reason_code/readme/DESCRIPTION.rst
  scrap_reason_code/readme/ROADMAP.rst
  scrap_reason_code/readme/USAGE.rst
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/static/description/icon.png
  scrap_reason_code/static/description/index.html
  scrap_reason_code/tests/__init__.py
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_move_views.xml
  scrap_reason_code/views/stock_scrap_views.xml
  setup/scrap_reason_code/odoo/addons/scrap_reason_code
  setup/scrap_reason_code/setup.py
Labels: bot is merging ⏳

#1028 [12.0][ADD] stock_location_position
  setup/stock_location_position/odoo/addons/stock_location_position
  setup/stock_location_position/setup.py
  stock_location_position/README.rst
  stock_location_position/__init__.py
  stock_location_position/__manifest__.py
  stock_location_position/models/__init__.py
  stock_location_position/models/stock_location.py
  stock_location_position/readme/CONTRIBUTORS.rst
  stock_location_position/readme/DESCRIPTION.rst
  stock_location_position/static/description/icon.png
  stock_location_position/static/description/index.html
  stock_location_position/views/stock_location.xml
Labels: approved, bot is merging ⏳, ready to merge

#693 [WMS][12.0] Add stock_picking_completion_info - alpha version
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/readme/CONTRIBUTORS.rst
  stock_picking_completion_info/readme/DESCRIPTION.rst
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#1044 [13.0][ADD] stock_inventory_justification
  setup/stock_inventory_justification/.eggs/README.txt
  setup/stock_inventory_justification/odoo/addons/stock_inventory_justification
  setup/stock_inventory_justification/setup.py
  stock_inventory_justification/README.rst
  stock_inventory_justification/__init__.py
  stock_inventory_justification/__manifest__.py
  stock_inventory_justification/models/__init__.py
  stock_inventory_justification/models/stock_inventory.py
  stock_inventory_justification/models/stock_inventory_justification.py
  stock_inventory_justification/readme/CONTRIBUTORS.rst
  stock_inventory_justification/readme/DESCRIPTION.rst
  stock_inventory_justification/readme/USAGE.rst
  stock_inventory_justification/security/security.xml
  stock_inventory_justification/static/description/icon.png
  stock_inventory_justification/static/description/index.html
  stock_inventory_justification/views/stock_inventory.xml
  stock_inventory_justification/views/stock_inventory_justification.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1105 [12.0][IMP] stock_request_analytic + stock_request_purchase: Add Analytic Tags and propagate to PO
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1107 [12.0][FIX] stock_request_purchase: Check if fields exists previously and prevent error about it
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved, bot is merging ⏳

#1106 [13.0][ADD] stock_vertical_lift_empty_tray_check: is the tray empty?
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
  stock_vertical_lift_empty_tray_check/__init__.py
  stock_vertical_lift_empty_tray_check/__manifest__.py
  stock_vertical_lift_empty_tray_check/models/__init__.py
  stock_vertical_lift_empty_tray_check/models/res_config_settings.py
  stock_vertical_lift_empty_tray_check/models/vertical_lift_operation_pick.py
  stock_vertical_lift_empty_tray_check/models/vertical_lift_operation_pick_zero_check.py
  stock_vertical_lift_empty_tray_check/readme/CONFIGURE.rst
  stock_vertical_lift_empty_tray_check/readme/CONTRIBUTORS.rst
  stock_vertical_lift_empty_tray_check/readme/DESCRIPTION.rst
  stock_vertical_lift_empty_tray_check/tests/__init__.py
  stock_vertical_lift_empty_tray_check/tests/test_pick.py
  stock_vertical_lift_empty_tray_check/views/res_config_setting_views.xml
  stock_vertical_lift_empty_tray_check/views/vertical_lift_operation_pick_zero_check_views.xml
Labels: approved, bot is merging ⏳

#1039 [14.0][MIG] stock_available_immediately
  setup/stock_available_immediately/odoo/addons/stock_available_immediately
  setup/stock_available_immediately/setup.py
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/readme/CONTRIBUTORS.rst
  stock_available_immediately/readme/DESCRIPTION.rst
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: approved, bot is merging ⏳

#1098 [14.0][MIG] stock_pull_list
  setup/stock_pull_list/odoo/addons/stock_pull_list
  setup/stock_pull_list/setup.py
  stock_pull_list/README.rst
  stock_pull_list/__init__.py
  stock_pull_list/__manifest__.py
  stock_pull_list/i18n/stock_pull_list.pot
  stock_pull_list/readme/CONTRIBUTORS.rst
  stock_pull_list/readme/DESCRIPTION.rst
  stock_pull_list/readme/ROADMAP.rst
  stock_pull_list/readme/USAGE.rst
  stock_pull_list/security/ir.model.access.csv
  stock_pull_list/static/description/icon.png
  stock_pull_list/static/description/index.html
  stock_pull_list/tests/__init__.py
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/wizards/__init__.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
  stock_pull_list/wizards/stock_pull_list_wizard.xml
Labels: approved, bot is merging ⏳, migration, needs review

#1100 [14.0] [MIG] stock_demand_estimate_matrix
  setup/stock_demand_estimate_matrix/odoo/addons/stock_demand_estimate_matrix
  setup/stock_demand_estimate_matrix/setup.py
  stock_demand_estimate_matrix/README.rst
  stock_demand_estimate_matrix/__init__.py
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/i18n/stock_demand_estimate_matrix.pot
  stock_demand_estimate_matrix/models/__init__.py
  stock_demand_estimate_matrix/models/date_range.py
  stock_demand_estimate_matrix/models/stock_demand_estimate.py
  stock_demand_estimate_matrix/readme/CONTRIBUTORS.rst
  stock_demand_estimate_matrix/readme/DESCRIPTION.rst
  stock_demand_estimate_matrix/readme/INSTALL.rst
  stock_demand_estimate_matrix/readme/USAGE.rst
  stock_demand_estimate_matrix/security/ir.model.access.csv
  stock_demand_estimate_matrix/static/description/icon.png
  stock_demand_estimate_matrix/static/description/index.html
  stock_demand_estimate_matrix/tests/__init__.py
  stock_demand_estimate_matrix/tests/test_stock_demand_estimate.py
  stock_demand_estimate_matrix/views/date_range.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/wizards/__init__.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet_line.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard_view.xml
Labels: bot is merging ⏳, migration, needs review

#1108 [14.0[ [MIG] stock_helper
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
Labels: approved, bot is merging ⏳
