Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-10, with the labels that each got.

#1240 [14.0][MIG] stock_inventory_exclude_sublocation
  setup/stock_inventory_exclude_sublocation/odoo/addons/stock_inventory_exclude_sublocation
  setup/stock_inventory_exclude_sublocation/setup.py
  stock_inventory_exclude_sublocation/README.rst
  stock_inventory_exclude_sublocation/__init__.py
  stock_inventory_exclude_sublocation/__manifest__.py
  stock_inventory_exclude_sublocation/i18n/cs_CZ.po
  stock_inventory_exclude_sublocation/i18n/de.po
  stock_inventory_exclude_sublocation/i18n/es.po
  stock_inventory_exclude_sublocation/i18n/es_ES.po
  stock_inventory_exclude_sublocation/i18n/fr.po
  stock_inventory_exclude_sublocation/i18n/it.po
  stock_inventory_exclude_sublocation/i18n/pt_BR.po
  stock_inventory_exclude_sublocation/i18n/sl.po
  stock_inventory_exclude_sublocation/i18n/stock_inventory_exclude_sublocation.pot
  stock_inventory_exclude_sublocation/i18n/zh_CN.po
  stock_inventory_exclude_sublocation/models/__init__.py
  stock_inventory_exclude_sublocation/models/stock_inventory.py
  stock_inventory_exclude_sublocation/readme/CONTRIBUTORS.rst
  stock_inventory_exclude_sublocation/readme/DESCRIPTION.rst
  stock_inventory_exclude_sublocation/readme/USAGE.rst
  stock_inventory_exclude_sublocation/static/description/icon.png
  stock_inventory_exclude_sublocation/static/description/index.html
  stock_inventory_exclude_sublocation/tests/__init__.py
  stock_inventory_exclude_sublocation/tests/test_exclude_sublocation.py
  stock_inventory_exclude_sublocation/views/stock_inventory_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1180 [14.0] [MIG] procurement_auto_create_group
  procurement_auto_create_group/README.rst
  procurement_auto_create_group/__init__.py
  procurement_auto_create_group/__manifest__.py
  procurement_auto_create_group/i18n/cs_CZ.po
  procurement_auto_create_group/i18n/de.po
  procurement_auto_create_group/i18n/es.po
  procurement_auto_create_group/i18n/es_MX.po
  procurement_auto_create_group/i18n/fr.po
  procurement_auto_create_group/i18n/hr.po
  procurement_auto_create_group/i18n/it.po
  procurement_auto_create_group/i18n/procurement_auto_create_group.pot
  procurement_auto_create_group/i18n/pt_BR.po
  procurement_auto_create_group/i18n/pt_PT.po
  procurement_auto_create_group/i18n/ro.po
  procurement_auto_create_group/i18n/sk.po
  procurement_auto_create_group/i18n/sl.po
  procurement_auto_create_group/i18n/tr_TR.po
  procurement_auto_create_group/i18n/vi_VN.po
  procurement_auto_create_group/i18n/zh_CN.po
  procurement_auto_create_group/models/__init__.py
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/readme/CONFIGURE.rst
  procurement_auto_create_group/readme/CONTRIBUTORS.rst
  procurement_auto_create_group/readme/DESCRIPTION.rst
  procurement_auto_create_group/readme/USAGE.rst
  procurement_auto_create_group/static/description/icon.png
  procurement_auto_create_group/static/description/index.html
  procurement_auto_create_group/tests/__init__.py
  procurement_auto_create_group/tests/test_auto_create.py
  procurement_auto_create_group/views/procurement_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1266 [FIX] stock_orderpoint_route: avoid missing route_ids field issue
  stock_orderpoint_route/views/stock_warehouse_orderpoint_views.xml
Labels: bot is merging ⏳

#1239 [14.0][MIG] stock_inventory_discrepancy
  setup/stock_inventory_discrepancy/odoo/addons/stock_inventory_discrepancy
  setup/stock_inventory_discrepancy/setup.py
  stock_inventory_discrepancy/README.rst
  stock_inventory_discrepancy/__init__.py
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/hooks.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/__init__.py
  stock_inventory_discrepancy/models/stock_inventory.py
  stock_inventory_discrepancy/models/stock_inventory_line.py
  stock_inventory_discrepancy/models/stock_location.py
  stock_inventory_discrepancy/models/stock_warehouse.py
  stock_inventory_discrepancy/readme/CONFIGURE.rst
  stock_inventory_discrepancy/readme/CONTRIBUTORS.rst
  stock_inventory_discrepancy/readme/DESCRIPTION.rst
  stock_inventory_discrepancy/readme/USAGE.rst
  stock_inventory_discrepancy/security/stock_inventory_discrepancy_security.xml
  stock_inventory_discrepancy/static/description/icon.png
  stock_inventory_discrepancy/static/description/index.html
  stock_inventory_discrepancy/static/src/js/inventory_validate_button_controller.js
  stock_inventory_discrepancy/tests/__init__.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/assets_backend.xml
  stock_inventory_discrepancy/views/stock_inventory_view.xml
  stock_inventory_discrepancy/views/stock_location_view.xml
  stock_inventory_discrepancy/views/stock_warehouse_view.xml
Labels: needs review, migration, bot is merging ⏳

#1054 [14.0][MIG] stock_orderpoint_manual_procurement
  setup/stock_orderpoint_manual_procurement/odoo/addons/stock_orderpoint_manual_procurement
  setup/stock_orderpoint_manual_procurement/setup.py
  stock_orderpoint_manual_procurement/README.rst
  stock_orderpoint_manual_procurement/__init__.py
  stock_orderpoint_manual_procurement/__manifest__.py
  stock_orderpoint_manual_procurement/demo/product.xml
  stock_orderpoint_manual_procurement/i18n/stock_orderpoint_manual_procurement.pot
  stock_orderpoint_manual_procurement/i18n/zh_CN.po
  stock_orderpoint_manual_procurement/models/__init__.py
  stock_orderpoint_manual_procurement/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement/readme/CONFIGURE.rst
  stock_orderpoint_manual_procurement/readme/CONTRIBUTORS.rst
  stock_orderpoint_manual_procurement/readme/CREDITS.rst
  stock_orderpoint_manual_procurement/readme/DESCRIPTION.rst
  stock_orderpoint_manual_procurement/readme/USAGE.rst
  stock_orderpoint_manual_procurement/security/ir.model.access.csv
  stock_orderpoint_manual_procurement/security/stock_orderpoint_manual_procurement_security.xml
  stock_orderpoint_manual_procurement/static/description/icon.png
  stock_orderpoint_manual_procurement/static/description/index.html
  stock_orderpoint_manual_procurement/tests/__init__.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement/views/stock_warehouse_orderpoint_view.xml
  stock_orderpoint_manual_procurement/wizards/__init__.py
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint.py
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1270 [FIX] stock_request: add delete permission to group_stock_request_user
  stock_request/security/ir.model.access.csv
Labels: approved, bot is merging ⏳
