Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-08, with the labels that each got.

#1201 [FIX] add OCA repos for dependencies
  oca_dependencies.txt
Labels: approved, ready to merge

#1212 [14.0][MIG] stock_reserve_rule
  setup/stock_reserve_rule/odoo/addons/stock_reserve_rule
  setup/stock_reserve_rule/setup.py
  stock_reserve_rule/README.rst
  stock_reserve_rule/__init__.py
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/demo/product_demo.xml
  stock_reserve_rule/demo/stock_inventory_demo.xml
  stock_reserve_rule/demo/stock_location_demo.xml
  stock_reserve_rule/demo/stock_picking_demo.xml
  stock_reserve_rule/demo/stock_reserve_rule_demo.xml
  stock_reserve_rule/i18n/stock_reserve_rule.pot
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_picking_type.py
  stock_reserve_rule/models/stock_quant.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/readme/CONFIGURE.rst
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/readme/DESCRIPTION.rst
  stock_reserve_rule/readme/USAGE.rst
  stock_reserve_rule/security/ir.model.access.csv
  stock_reserve_rule/security/stock_reserve_rule_security.xml
  stock_reserve_rule/static/description/icon.png
  stock_reserve_rule/static/description/index.html
  stock_reserve_rule/tests/__init__.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_reserve_rule/views/stock_reserve_rule_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1193 [14.0][MIG] stock_putaway_method
  setup/stock_putaway_method/odoo/addons/stock_putaway_method
  setup/stock_putaway_method/setup.py
  stock_putaway_method/README.rst
  stock_putaway_method/__init__.py
  stock_putaway_method/__manifest__.py
  stock_putaway_method/i18n/cs_CZ.po
  stock_putaway_method/i18n/fr.po
  stock_putaway_method/i18n/stock_putaway_method.pot
  stock_putaway_method/models/__init__.py
  stock_putaway_method/models/product_strategy.py
  stock_putaway_method/readme/CONTRIBUTORS.rst
  stock_putaway_method/readme/DESCRIPTION.rst
  stock_putaway_method/readme/USAGE.rst
  stock_putaway_method/static/description/icon.png
  stock_putaway_method/static/description/index.html
  stock_putaway_method/tests/__init__.py
  stock_putaway_method/tests/test_putaway_method.py
  stock_putaway_method/views/product_strategy_views.xml
Labels: needs review, needs fixing, approved, migration, ready to merge, bot is merging ⏳

#1209 [13.0][FIX] s_o_manual_procurement: handle NewId
  stock_orderpoint_manual_procurement/models/stock_warehouse_orderpoint.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
Labels: bug, approved, bot is merging ⏳

#1207 [13.0] [MIG] stock_reserve_sale: Migration to v13.0
  setup/stock_reserve_sale/odoo/addons/stock_reserve_sale
  setup/stock_reserve_sale/setup.py
  stock_reserve_sale/README.rst
  stock_reserve_sale/__init__.py
  stock_reserve_sale/__manifest__.py
  stock_reserve_sale/i18n/es.po
  stock_reserve_sale/i18n/fi.po
  stock_reserve_sale/i18n/fr.po
  stock_reserve_sale/i18n/stock_reserve_sale.pot
  stock_reserve_sale/model/__init__.py
  stock_reserve_sale/model/sale.py
  stock_reserve_sale/model/stock_reserve.py
  stock_reserve_sale/readme/CONTRIBUTORS.rst
  stock_reserve_sale/readme/DESCRIPTION.rst
  stock_reserve_sale/readme/USAGE.rst
  stock_reserve_sale/static/description/index.html
  stock_reserve_sale/tests/__init__.py
  stock_reserve_sale/tests/test_stock_reserve_sale.py
  stock_reserve_sale/view/sale.xml
  stock_reserve_sale/view/stock_reserve.xml
  stock_reserve_sale/wizard/__init__.py
  stock_reserve_sale/wizard/sale_stock_reserve.py
  stock_reserve_sale/wizard/sale_stock_reserve_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1218 Change parent of model category Stock Request
  stock_request/security/stock_request_security.xml
Labels: approved, bot is merging ⏳

#1171 [13.0][IMP] stock_mts_mto_rule: Improve inheritance
  stock_mts_mto_rule/README.rst
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/readme/CONFIGURE.rst
  stock_mts_mto_rule/readme/CONTRIBUTORS.rst
  stock_mts_mto_rule/readme/DESCRIPTION.rst
  stock_mts_mto_rule/readme/ROADMAP.rst
  stock_mts_mto_rule/readme/USAGE.rst
  stock_mts_mto_rule/static/description/index.html
Labels: enhancement, needs review, approved, bot is merging ⏳

#1012 [FIX] stock_vertical_lift_kardex proxy
  stock_vertical_lift_kardex/proxy/README.rst
  stock_vertical_lift_kardex/proxy/kardex-proxy.py
Labels: bot is merging ⏳

#1213 [14.0] [MIG] stock_archive_constraint
  setup/stock_archive_constraint/odoo/addons/stock_archive_constraint
  setup/stock_archive_constraint/setup.py
  stock_archive_constraint/README.rst
  stock_archive_constraint/__init__.py
  stock_archive_constraint/__manifest__.py
  stock_archive_constraint/i18n/es.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/__init__.py
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/product_template.py
  stock_archive_constraint/models/stock_location.py
  stock_archive_constraint/readme/CONTRIBUTORS.rst
  stock_archive_constraint/readme/DESCRIPTION.rst
  stock_archive_constraint/readme/USAGE.rst
  stock_archive_constraint/static/description/icon.png
  stock_archive_constraint/static/description/index.html
  stock_archive_constraint/tests/__init__.py
  stock_archive_constraint/tests/test_location_archive_constraint.py
Labels: bot is merging ⏳
