Repository OCA/stock-logistics-warehouse, pull requests merged in 2021-12, with the labels that each got.

#1319 [13.0][FIX] stock_available_mrp: non storable components
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: approved, bot is merging ⏳

#1315 [14.0][FW] stock_vertical_lift: multiple ports from 13.0
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
  stock_vertical_lift/tests/test_inventory.py
  stock_vertical_lift/tests/test_pick.py
  stock_vertical_lift/wizards/vertical_lift_shuttle_manual_barcode.py
Labels: bot is merging ⏳

#1020 [13.0] add stock_quant_view_reservation
  setup/stock_quant_view_reservation/odoo/addons/stock_quant_view_reservation
  setup/stock_quant_view_reservation/setup.py
  stock_quant_view_reservation/README.rst
  stock_quant_view_reservation/__init__.py
  stock_quant_view_reservation/__manifest__.py
  stock_quant_view_reservation/models/__init__.py
  stock_quant_view_reservation/models/stock_quant.py
  stock_quant_view_reservation/readme/CONTRIBUTORS.rst
  stock_quant_view_reservation/readme/DESCRIPTION.rst
  stock_quant_view_reservation/readme/USAGE.rst
  stock_quant_view_reservation/static/description/icon.png
  stock_quant_view_reservation/views/stock_move_line_views.xml
  stock_quant_view_reservation/views/stock_quant.xml
Labels: needs review, bot is merging ⏳

#1311 [14.0][FIX] stock_location_tray: crash when creating a stock.location
  stock_location_tray/models/stock_location.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#1114 [13.0][ADD] New module stock_quant_expiration_date_tree
  setup/stock_quant_expiration_date_tree/odoo/addons/stock_quant_expiration_date_tree
  setup/stock_quant_expiration_date_tree/setup.py
  stock_quant_expiration_date_tree/README.rst
  stock_quant_expiration_date_tree/__init__.py
  stock_quant_expiration_date_tree/__manifest__.py
  stock_quant_expiration_date_tree/i18n/es.po
  stock_quant_expiration_date_tree/i18n/stock_quant_expiration_date_tree.pot
  stock_quant_expiration_date_tree/models/__init__.py
  stock_quant_expiration_date_tree/models/stock_quant.py
  stock_quant_expiration_date_tree/readme/CONTRIBUTORS.rst
  stock_quant_expiration_date_tree/readme/DESCRIPTION.rst
  stock_quant_expiration_date_tree/static/description/icon.png
  stock_quant_expiration_date_tree/static/description/index.html
  stock_quant_expiration_date_tree/views/stock_quant.xml
Labels: needs review, bot is merging ⏳

#1267 [14.0][REF] stock_available addons: various perfomance improvements
  stock_available/models/product_product.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: enhancement, needs review, bot is merging ⏳

#1325 [14.0][FIX] stock_location_tray: fix access on act_window in v14
  stock_location_tray/models/stock_location.py
  stock_location_tray/models/stock_location_tray_type.py
Labels: bug, bot is merging ⏳

#1326 [14.0][FIX] adapt syntax for act_window lookup
  stock_cycle_count/models/stock_cycle_count.py
  stock_cycle_count/models/stock_location.py
  stock_move_location/models/stock_picking_type.py
  stock_move_location/wizard/stock_move_location.py
  stock_orderpoint_move_link/models/stock_warehouse_orderpoint.py
  stock_request/models/stock_picking.py
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
  stock_vertical_lift/models/vertical_lift_shuttle.py
Labels: bug, approved, bot is merging ⏳

#1317 [14.0][MIG] stock_request_analytic
  setup/stock_request_analytic/odoo/addons/stock_request_analytic
  setup/stock_request_analytic/setup.py
  stock_request_analytic/README.rst
  stock_request_analytic/__init__.py
  stock_request_analytic/__manifest__.py
  stock_request_analytic/i18n/pt_BR.po
  stock_request_analytic/i18n/stock_request_analytic.pot
  stock_request_analytic/i18n/zh_CN.po
  stock_request_analytic/models/__init__.py
  stock_request_analytic/models/analytic.py
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/readme/CONTRIBUTORS.rst
  stock_request_analytic/readme/DESCRIPTION.rst
  stock_request_analytic/readme/ROADMAP.rst
  stock_request_analytic/readme/USAGE.rst
  stock_request_analytic/security/ir.model.access.csv
  stock_request_analytic/static/description/icon.png
  stock_request_analytic/static/description/index.html
  stock_request_analytic/tests/__init__.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/analytic_views.xml
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1308 [14.0][FIX] stock_order_point_move_link get move values
  stock_orderpoint_move_link/models/stock.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1333 [14.0][UPD] stock_warehouse_calendar: development status to stable.
  stock_warehouse_calendar/__manifest__.py
Labels: bot is merging ⏳

#1334 [14.0][IMP] stock_cycle_count: check modify
  stock_cycle_count/models/stock_inventory.py
Labels: bot is merging ⏳

#1290 [13.0][ADD] stock_picking_package_grouped: New module to create package from pickings depending on grouping criteria
  setup/stock_picking_package_grouped/odoo/addons/stock_picking_package_grouped
  setup/stock_picking_package_grouped/setup.py
  stock_picking_package_grouped/README.rst
  stock_picking_package_grouped/__init__.py
  stock_picking_package_grouped/__manifest__.py
  stock_picking_package_grouped/i18n/es.po
  stock_picking_package_grouped/i18n/stock_picking_package_grouped.pot
  stock_picking_package_grouped/models/__init__.py
  stock_picking_package_grouped/models/stock_picking.py
  stock_picking_package_grouped/models/stock_picking_type.py
  stock_picking_package_grouped/readme/CONFIGURE.rst
  stock_picking_package_grouped/readme/CONTRIBUTORS.rst
  stock_picking_package_grouped/readme/DESCRIPTION.rst
  stock_picking_package_grouped/readme/USAGE.rst
  stock_picking_package_grouped/static/description/icon.png
  stock_picking_package_grouped/static/description/index.html
  stock_picking_package_grouped/tests/__init__.py
  stock_picking_package_grouped/tests/test_stock_picking_package_grouped.py
  stock_picking_package_grouped/views/stock_picking_type_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1324 [15.0][MIG] stock_helper
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
Labels: needs review, approved, migration, bot is merging ⏳

#1330 [14.0][FIX] stock_reserve_rule: rule matching
  stock_reserve_rule/README.rst
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: bug, bot is merging ⏳
