Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-02, with the labels that each got.

#1365 [14.0][FIX] Fix access right issues when using actions
  product_quantity_update_force_inventory/models/product.py
  stock_available_unreserved/models/product_template.py
  stock_request_analytic/models/analytic.py
  stock_request_analytic/models/stock_request_order.py
Labels: bug, approved, bot is merging ⏳

#1217 [12.0][IMP] stock_move_location: add option to propose available quantities
  stock_move_location/models/stock_picking_type.py
  stock_move_location/readme/CONFIGURE.rst
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/tests/test_move_location.py
  stock_move_location/views/stock_picking_type_views.xml
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: approved, bot is merging ⏳

#1368 [14.0][FIX] stock_orderpoint_manual_procurement: wrong parameter in _prepare_procurement_values
  stock_orderpoint_manual_procurement/wizards/make_procurement_orderpoint.py
Labels: approved, bot is merging ⏳

#1153 [14.0][MIG] stock_request_submit (Version 13.0 to 14.0)
  stock_request_submit/README.rst
  stock_request_submit/__init__.py
  stock_request_submit/__manifest__.py
  stock_request_submit/hooks.py
  stock_request_submit/i18n/es.po
  stock_request_submit/i18n/stock_request_submit.pot
  stock_request_submit/i18n/zh_CN.po
  stock_request_submit/models/__init__.py
  stock_request_submit/models/stock_request.py
  stock_request_submit/models/stock_request_order.py
  stock_request_submit/readme/CONTRIBUTORS.rst
  stock_request_submit/readme/DESCRIPTION.rst
  stock_request_submit/static/description/icon.png
  stock_request_submit/static/description/index.html
  stock_request_submit/tests/__init__.py
  stock_request_submit/tests/test_stock_request_submit.py
  stock_request_submit/views/stock_request_order_views.xml
  stock_request_submit/views/stock_request_views.xml
Labels: needs review, migration, bot is merging ⏳

#1371 [13.0][FIX] stock_secondary_unit: Not copy default stock secondary unit.
  stock_secondary_unit/models/product.py
Labels: approved, bot is merging ⏳

#1362 [13.0] [IMP] stock_inventory_include_exhausted: Use the locations in the stock inventory for exhausted.
  stock_inventory_include_exhausted/models/stock_inventory.py
  stock_inventory_include_exhausted/tests/test_stock_inventory_include_exhausted.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1337 [15.0][MIG] stock_orderpoint_purchase_link
  setup/stock_orderpoint_purchase_link/odoo/addons/stock_orderpoint_purchase_link
  setup/stock_orderpoint_purchase_link/setup.py
  stock_orderpoint_purchase_link/README.rst
  stock_orderpoint_purchase_link/__init__.py
  stock_orderpoint_purchase_link/__manifest__.py
  stock_orderpoint_purchase_link/i18n/stock_orderpoint_purchase_link.pot
  stock_orderpoint_purchase_link/i18n/zh_CN.po
  stock_orderpoint_purchase_link/models/__init__.py
  stock_orderpoint_purchase_link/models/purchase_order_line.py
  stock_orderpoint_purchase_link/models/stock_rule.py
  stock_orderpoint_purchase_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_purchase_link/readme/CONTRIBUTORS.rst
  stock_orderpoint_purchase_link/readme/CREDITS.rst
  stock_orderpoint_purchase_link/readme/DESCRIPTION.rst
  stock_orderpoint_purchase_link/static/description/icon.png
  stock_orderpoint_purchase_link/static/description/index.html
  stock_orderpoint_purchase_link/tests/__init__.py
  stock_orderpoint_purchase_link/tests/test_stock_orderpoint_purchase_link.py
  stock_orderpoint_purchase_link/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1370 [14.0][FIX] stock_pull_list: do not show any lines when there's no quantity needed
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
Labels: approved, bot is merging ⏳

#1375 [13.0][FIX] stock_inventory_preparation_filter: Filtering by lots is adding all lots of products
  stock_inventory_preparation_filter/README.rst
  stock_inventory_preparation_filter/models/stock_inventory.py
  stock_inventory_preparation_filter/readme/CONTRIBUTORS.rst
  stock_inventory_preparation_filter/static/description/index.html
Labels: approved, bot is merging ⏳

#1374 [15.0][MIG] stock_demand_estimate_ matrix
  setup/stock_demand_estimate_matrix/odoo/addons/stock_demand_estimate_matrix
  setup/stock_demand_estimate_matrix/setup.py
  stock_demand_estimate_matrix/README.rst
  stock_demand_estimate_matrix/__init__.py
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/i18n/stock_demand_estimate_matrix.pot
  stock_demand_estimate_matrix/models/__init__.py
  stock_demand_estimate_matrix/models/date_range.py
  stock_demand_estimate_matrix/models/stock_demand_estimate.py
  stock_demand_estimate_matrix/readme/CONTRIBUTORS.rst
  stock_demand_estimate_matrix/readme/DESCRIPTION.rst
  stock_demand_estimate_matrix/readme/INSTALL.rst
  stock_demand_estimate_matrix/readme/USAGE.rst
  stock_demand_estimate_matrix/security/ir.model.access.csv
  stock_demand_estimate_matrix/static/description/icon.png
  stock_demand_estimate_matrix/static/description/index.html
  stock_demand_estimate_matrix/tests/__init__.py
  stock_demand_estimate_matrix/tests/test_stock_demand_estimate.py
  stock_demand_estimate_matrix/views/date_range.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/wizards/__init__.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet_line.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard_view.xml
Labels: approved, bot is merging ⏳

#1376 [IMP] stock_inventory_preparation_filter: Filtering by lots is adding all lots of products
  stock_inventory_preparation_filter/README.rst
  stock_inventory_preparation_filter/models/stock_inventory.py
  stock_inventory_preparation_filter/readme/CONTRIBUTORS.rst
  stock_inventory_preparation_filter/static/description/index.html
Labels: bot is merging ⏳

#1335 [MIG][15.0] stock_orderpoint_uom
  setup/stock_orderpoint_uom/odoo/addons/stock_orderpoint_uom
  setup/stock_orderpoint_uom/setup.py
  stock_orderpoint_uom/README.rst
  stock_orderpoint_uom/__init__.py
  stock_orderpoint_uom/__manifest__.py
  stock_orderpoint_uom/i18n/ca.po
  stock_orderpoint_uom/i18n/de.po
  stock_orderpoint_uom/i18n/es.po
  stock_orderpoint_uom/i18n/es_ES.po
  stock_orderpoint_uom/i18n/es_MX.po
  stock_orderpoint_uom/i18n/fi.po
  stock_orderpoint_uom/i18n/fr.po
  stock_orderpoint_uom/i18n/fr_CH.po
  stock_orderpoint_uom/i18n/hr.po
  stock_orderpoint_uom/i18n/hr_HR.po
  stock_orderpoint_uom/i18n/it.po
  stock_orderpoint_uom/i18n/nl.po
  stock_orderpoint_uom/i18n/nl_NL.po
  stock_orderpoint_uom/i18n/pt_BR.po
  stock_orderpoint_uom/i18n/pt_PT.po
  stock_orderpoint_uom/i18n/ro.po
  stock_orderpoint_uom/i18n/sl.po
  stock_orderpoint_uom/i18n/stock_orderpoint_uom.pot
  stock_orderpoint_uom/i18n/tr.po
  stock_orderpoint_uom/i18n/tr_TR.po
  stock_orderpoint_uom/i18n/vi_VN.po
  stock_orderpoint_uom/i18n/zh_CN.po
  stock_orderpoint_uom/models/__init__.py
  stock_orderpoint_uom/models/procurement_group.py
  stock_orderpoint_uom/models/product_template.py
  stock_orderpoint_uom/models/stock_warehouse_orderpoint.py
  stock_orderpoint_uom/readme/CONFIGURE.rst
  stock_orderpoint_uom/readme/CONTRIBUTORS.rst
  stock_orderpoint_uom/readme/DESCRIPTION.rst
  stock_orderpoint_uom/readme/USAGE.rst
  stock_orderpoint_uom/static/description/icon.png
  stock_orderpoint_uom/static/description/index.html
  stock_orderpoint_uom/tests/__init__.py
  stock_orderpoint_uom/tests/test_stock_orderpoint_procure_uom.py
  stock_orderpoint_uom/views/stock_warehouse_orderpoint_view.xml
Labels: approved, migration, ready to merge, bot is merging ⏳
