Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-04, with the labels that each got.

#785 [ADD][MIG][12.0] stock_orderpoint_route
  setup/stock_orderpoint_route/odoo/addons/stock_orderpoint_route
  setup/stock_orderpoint_route/setup.py
  stock_orderpoint_route/README.rst
  stock_orderpoint_route/__init__.py
  stock_orderpoint_route/__manifest__.py
  stock_orderpoint_route/models/__init__.py
  stock_orderpoint_route/models/stock_warehouse_orderpoint.py
  stock_orderpoint_route/readme/CONTRIBUTORS.rst
  stock_orderpoint_route/readme/DESCRIPTION.rst
  stock_orderpoint_route/readme/USAGE.rst
  stock_orderpoint_route/static/description/icon.png
  stock_orderpoint_route/static/description/index.html
  stock_orderpoint_route/tests/__init__.py
  stock_orderpoint_route/tests/test_stock_orderpoint_route.py
  stock_orderpoint_route/views/stock_warehouse_orderpoint_views.xml
Labels: needs review, bot is merging ⏳, stale

#1403 [FIX] stock_available_mrp: normal BoM available to promise
  stock_available_mrp/README.rst
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/mrp_bom.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/readme/USAGE.rst
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/test_potential_qty.py
  stock_available_mrp/views/mrp_bom_views.xml
Labels: approved, bot is merging ⏳

#1407 [14.0][IMP] stock_packaging_calculator: improve performance
  stock_packaging_calculator/models/product.py
Labels: enhancement, approved, bot is merging ⏳

#1302 [15.0] stock_mts_mto_rule Migration to V15
  setup/stock_mts_mto_rule/odoo/addons/stock_mts_mto_rule
  setup/stock_mts_mto_rule/setup.py
  stock_mts_mto_rule/README.rst
  stock_mts_mto_rule/__init__.py
  stock_mts_mto_rule/__manifest__.py
  stock_mts_mto_rule/data/stock_data.xml
  stock_mts_mto_rule/i18n/cs_CZ.po
  stock_mts_mto_rule/i18n/de.po
  stock_mts_mto_rule/i18n/es.po
  stock_mts_mto_rule/i18n/es_MX.po
  stock_mts_mto_rule/i18n/fr.po
  stock_mts_mto_rule/i18n/fr_FR.po
  stock_mts_mto_rule/i18n/hr.po
  stock_mts_mto_rule/i18n/it.po
  stock_mts_mto_rule/i18n/nl.po
  stock_mts_mto_rule/i18n/nl_NL.po
  stock_mts_mto_rule/i18n/pt_BR.po
  stock_mts_mto_rule/i18n/pt_PT.po
  stock_mts_mto_rule/i18n/ro.po
  stock_mts_mto_rule/i18n/sk.po
  stock_mts_mto_rule/i18n/sl.po
  stock_mts_mto_rule/i18n/stock_mts_mto_rule.pot
  stock_mts_mto_rule/i18n/tr_TR.po
  stock_mts_mto_rule/i18n/vi_VN.po
  stock_mts_mto_rule/i18n/zh_CN.po
  stock_mts_mto_rule/models/__init__.py
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/models/stock_warehouse.py
  stock_mts_mto_rule/readme/CONFIGURE.rst
  stock_mts_mto_rule/readme/CONTRIBUTORS.rst
  stock_mts_mto_rule/readme/DESCRIPTION.rst
  stock_mts_mto_rule/readme/USAGE.rst
  stock_mts_mto_rule/static/description/icon.png
  stock_mts_mto_rule/static/description/index.html
  stock_mts_mto_rule/tests/__init__.py
  stock_mts_mto_rule/tests/test_mto_mts_route.py
  stock_mts_mto_rule/view/pull_rule.xml
  stock_mts_mto_rule/view/warehouse.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1354 [15.0][MIG] stock_request_purchase
  setup/stock_request_purchase/odoo/addons/stock_request_purchase
  setup/stock_request_purchase/setup.py
  stock_request_purchase/README.rst
  stock_request_purchase/__init__.py
  stock_request_purchase/__manifest__.py
  stock_request_purchase/i18n/de.po
  stock_request_purchase/i18n/es.po
  stock_request_purchase/i18n/stock_request_purchase.pot
  stock_request_purchase/i18n/zh_CN.po
  stock_request_purchase/models/__init__.py
  stock_request_purchase/models/purchase_order.py
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/models/stock_request.py
  stock_request_purchase/models/stock_request_order.py
  stock_request_purchase/models/stock_rule.py
  stock_request_purchase/readme/CONTRIBUTORS.rst
  stock_request_purchase/readme/DESCRIPTION.rst
  stock_request_purchase/readme/ROADMAP.rst
  stock_request_purchase/readme/USAGE.rst
  stock_request_purchase/security/ir.model.access.csv
  stock_request_purchase/static/description/icon.png
  stock_request_purchase/static/description/index.html
  stock_request_purchase/tests/__init__.py
  stock_request_purchase/tests/test_stock_request_purchase.py
  stock_request_purchase/views/purchase_order_views.xml
  stock_request_purchase/views/stock_request_order_views.xml
  stock_request_purchase/views/stock_request_views.xml
Labels: needs review, approved, migration, bot is merging ⏳
