Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-11, with the labels that each got.

#1530 [15.0][FIX] stock_demand_estimate: Change SavepointCase to TransactionCase
  stock_demand_estimate/tests/test_stock_demand_estimate.py
  stock_demand_estimate_matrix/tests/test_stock_demand_estimate.py
Labels: approved, bot is merging ⏳

#1522 [15.0][MIG] sale_stock_available_info_popup: Migration to 15.0
  sale_stock_available_info_popup/README.rst
  sale_stock_available_info_popup/__init__.py
  sale_stock_available_info_popup/__manifest__.py
  sale_stock_available_info_popup/i18n/es.po
  sale_stock_available_info_popup/i18n/sale_stock_available_info_popup.pot
  sale_stock_available_info_popup/i18n/sl.po
  sale_stock_available_info_popup/models/__init__.py
  sale_stock_available_info_popup/models/sale_order.py
  sale_stock_available_info_popup/readme/CONTRIBUTORS.rst
  sale_stock_available_info_popup/readme/DESCRIPTION.rst
  sale_stock_available_info_popup/readme/USAGE.rst
  sale_stock_available_info_popup/static/description/icon.png
  sale_stock_available_info_popup/static/description/index.html
  sale_stock_available_info_popup/static/src/xml/qty_at_date.xml
  sale_stock_available_info_popup/tests/__init__.py
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
  sale_stock_available_info_popup/views/sale_order_views.xml
  setup/sale_stock_available_info_popup/odoo/addons/sale_stock_available_info_popup
  setup/sale_stock_available_info_popup/setup.py
Labels: approved, bot is merging ⏳

#1519 [REM] stock_package_type_button_box: Make it uninstallable as in core
  .pre-commit-config.yaml
  setup/stock_package_type_button_box/odoo/addons/stock_package_type_button_box
  setup/stock_package_type_button_box/setup.py
  stock_package_type_button_box/__manifest__.py
Labels: approved, bot is merging ⏳

#1510 [16.0][MIG] stock_location_product_restriction
  setup/stock_location_product_restriction/odoo/addons/stock_location_product_restriction
  setup/stock_location_product_restriction/setup.py
  stock_location_product_restriction/README.rst
  stock_location_product_restriction/__init__.py
  stock_location_product_restriction/__manifest__.py
  stock_location_product_restriction/hooks.py
  stock_location_product_restriction/i18n/fr.po
  stock_location_product_restriction/i18n/stock_location_product_restriction.pot
  stock_location_product_restriction/models/__init__.py
  stock_location_product_restriction/models/stock_location.py
  stock_location_product_restriction/models/stock_move.py
  stock_location_product_restriction/readme/CONTRIBUTORS.rst
  stock_location_product_restriction/readme/CREDITS.rst
  stock_location_product_restriction/readme/DESCRIPTION.rst
  stock_location_product_restriction/readme/HISTORY.rst
  stock_location_product_restriction/readme/USAGE.rst
  stock_location_product_restriction/readme/newsfragments/.gitkeep
  stock_location_product_restriction/static/description/icon.png
  stock_location_product_restriction/static/description/index.html
  stock_location_product_restriction/tests/__init__.py
  stock_location_product_restriction/tests/test_stock_location.py
  stock_location_product_restriction/tests/test_stock_move.py
  stock_location_product_restriction/views/stock_location.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1501 [16.0] [MIG] stock_warehouse_calendar
  setup/stock_warehouse_calendar/odoo/addons/stock_warehouse_calendar
  setup/stock_warehouse_calendar/setup.py
  stock_warehouse_calendar/README.rst
  stock_warehouse_calendar/__init__.py
  stock_warehouse_calendar/__manifest__.py
  stock_warehouse_calendar/i18n/ca.po
  stock_warehouse_calendar/i18n/it.po
  stock_warehouse_calendar/i18n/stock_warehouse_calendar.pot
  stock_warehouse_calendar/i18n/zh_CN.po
  stock_warehouse_calendar/models/__init__.py
  stock_warehouse_calendar/models/stock_rule.py
  stock_warehouse_calendar/models/stock_warehouse.py
  stock_warehouse_calendar/readme/CONFIGURE.rst
  stock_warehouse_calendar/readme/CONTRIBUTORS.rst
  stock_warehouse_calendar/readme/DESCRIPTION.rst
  stock_warehouse_calendar/readme/USAGE.rst
  stock_warehouse_calendar/static/description/icon.png
  stock_warehouse_calendar/static/description/index.html
  stock_warehouse_calendar/tests/__init__.py
  stock_warehouse_calendar/tests/test_stock_warehouse_calendar.py
  stock_warehouse_calendar/views/stock_warehouse_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1535 [14.0][IMP] stock_cycle_count: Implement constrains in inventory adjustment.
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/tests/test_stock_cycle_count.py
Labels: approved, bot is merging ⏳

#1448 [15.0][MIG] stock_putaway_product_template: Migration to 15.0
  setup/stock_putaway_product_template/odoo/addons/stock_putaway_product_template
  setup/stock_putaway_product_template/setup.py
  stock_putaway_product_template/README.rst
  stock_putaway_product_template/__init__.py
  stock_putaway_product_template/__manifest__.py
  stock_putaway_product_template/i18n/es.po
  stock_putaway_product_template/i18n/stock_putaway_product_template.pot
  stock_putaway_product_template/models/__init__.py
  stock_putaway_product_template/models/product.py
  stock_putaway_product_template/models/stock_location.py
  stock_putaway_product_template/models/stock_putaway_rule.py
  stock_putaway_product_template/readme/CONTRIBUTORS.rst
  stock_putaway_product_template/readme/DESCRIPTION.rst
  stock_putaway_product_template/readme/USAGE.rst
  stock_putaway_product_template/static/description/icon.png
  stock_putaway_product_template/static/description/index.html
  stock_putaway_product_template/tests/__init__.py
  stock_putaway_product_template/tests/test_stock_putaway_rule.py
  stock_putaway_product_template/views/stock_putaway_rule_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1523 [15.0][MIG] stock_lot_filter_available: Migration to version 15.0
  setup/stock_lot_filter_available/odoo/addons/stock_lot_filter_available
  setup/stock_lot_filter_available/setup.py
  stock_lot_filter_available/README.rst
  stock_lot_filter_available/__init__.py
  stock_lot_filter_available/__manifest__.py
  stock_lot_filter_available/i18n/es.po
  stock_lot_filter_available/i18n/stock_lot_filter_available.pot
  stock_lot_filter_available/models/__init__.py
  stock_lot_filter_available/models/stock_production_lot.py
  stock_lot_filter_available/readme/CONTRIBUTORS.rst
  stock_lot_filter_available/readme/DESCRIPTION.rst
  stock_lot_filter_available/readme/USAGE.rst
  stock_lot_filter_available/static/description/icon.png
  stock_lot_filter_available/static/description/index.html
  stock_lot_filter_available/tests/__init__.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
  stock_lot_filter_available/views/stock_production_lot_views.xml
Labels: approved, bot is merging ⏳

#1504 [MIG] scrap_reason_code: Migration to 15.0
  scrap_reason_code/README.rst
  scrap_reason_code/__init__.py
  scrap_reason_code/__manifest__.py
  scrap_reason_code/i18n/es.po
  scrap_reason_code/i18n/fr.po
  scrap_reason_code/i18n/scrap_reason_code.pot
  scrap_reason_code/models/__init__.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONFIGURE.rst
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/readme/CREDITS.rst
  scrap_reason_code/readme/DESCRIPTION.rst
  scrap_reason_code/readme/ROADMAP.rst
  scrap_reason_code/readme/USAGE.rst
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/static/description/icon.png
  scrap_reason_code/static/description/index.html
  scrap_reason_code/tests/__init__.py
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_move_views.xml
  scrap_reason_code/views/stock_scrap_views.xml
  setup/scrap_reason_code/odoo/addons/scrap_reason_code
  setup/scrap_reason_code/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1538 [14.0][IMP] stock_cycle_count: add auto start adjustment option
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/__init__.py
  stock_cycle_count/models/res_company.py
  stock_cycle_count/models/res_config_settings.py
  stock_cycle_count/models/stock_cycle_count.py
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#1542 [14.0][IMP] stock_quant_reservation_info_mrp: add link in form view
  stock_quant_reservation_info_mrp/views/stock_move_line.xml
Labels: approved, bot is merging ⏳

#1539 [16.0] [MIG] stock_helper
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
Labels: needs review, approved, migration, bot is merging ⏳

#1550 [14.0][IMP] stock_quant_manual_assign: reserved field as readonly
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳

#1466 [14.0] stock_helper: add get_closest_warehouse method to stock.location
  stock_helper/README.rst
  stock_helper/__manifest__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/tests/__init__.py
  stock_helper/tests/test_location_get_closest_warehouse.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1551 [15.0][IMP] stock_quant_manual_assign: field reserved as readonly
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳

#1552 [14.0][FIX] stock_reserve_rule: fix _apply_strategy_empty_bin
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: bug, approved, bot is merging ⏳

#1556 [REF] copier update
  .copier-answers.yml
  .pre-commit-config.yaml
  stock_inventory_discrepancy/static/src/js/inventory_validate_button_controller.js
Labels: bot is merging ⏳

#1561 [UPD] Copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1557 [14.0][FIX] stock_cycle_count: related field can't redefine selection list
  stock_cycle_count/models/res_config_settings.py
Labels: approved, bot is merging ⏳

#1459 [14.0][IMP] stock_move_location: packages support
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1562 [15.0][FIX] stock_putaway_product_template: Change SavepointCase to TransactionCase
  stock_putaway_product_template/tests/test_stock_putaway_rule.py
Labels: bot is merging ⏳
