Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-05, with the labels that each got.

#1410 [14.0] stock_vertical_lift: fixes
  stock_vertical_lift/controllers/main.py
  stock_vertical_lift/tests/__init__.py
  stock_vertical_lift/tests/test_controller.py
Labels: approved, bot is merging ⏳

#1413 [14.0][FIX] stock_available_mrp: normal BoM available to promise
  stock_available_mrp/README.rst
  stock_available_mrp/__manifest__.py
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/mrp_bom.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/readme/ROADMAP.rst
  stock_available_mrp/readme/USAGE.rst
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/test_potential_qty.py
  stock_available_mrp/views/mrp_bom_views.xml
Labels: approved, bot is merging ⏳

#1417 [14.0][IMP] scrap_reason_code (Error fix and test coverage)
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/tests/test_scrap_reason_code.py
Labels: needs review, approved, bot is merging ⏳

#1418 [IMP] Update templates with copier
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
  account_move_line_stock_info/tests/test_account_move_line_stock_move.py
  stock_change_qty_reason/views/stock_inventory_line_view.xml
  stock_change_qty_reason/views/stock_inventory_view.xml
  stock_measuring_device/wizard/measuring_wizard_line.py
  stock_measuring_device_zippcube/tests/test_zippcube_wizard.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement_uom/tests/test_stock_orderpoint_manual_procurement.py
  stock_request/models/stock_request_abstract.py
  stock_vertical_lift_empty_tray_check/tests/test_pick.py
Labels: bot is merging ⏳

#1348 [14.0][MIG] stock_request_kanban
  setup/stock_request_kanban/odoo/addons/stock_request_kanban
  setup/stock_request_kanban/setup.py
  stock_request_kanban/README.rst
  stock_request_kanban/__init__.py
  stock_request_kanban/__manifest__.py
  stock_request_kanban/data/stock_request_sequence_data.xml
  stock_request_kanban/i18n/es.po
  stock_request_kanban/i18n/stock_request_kanban.pot
  stock_request_kanban/i18n/zh_CN.po
  stock_request_kanban/models/__init__.py
  stock_request_kanban/models/product.py
  stock_request_kanban/models/stock_inventory_kanban.py
  stock_request_kanban/models/stock_request.py
  stock_request_kanban/models/stock_request_kanban.py
  stock_request_kanban/readme/CONFIGURE.rst
  stock_request_kanban/readme/CONTRIBUTORS.rst
  stock_request_kanban/readme/DESCRIPTION.rst
  stock_request_kanban/readme/USAGE.rst
  stock_request_kanban/report/report_paper_format.xml
  stock_request_kanban/report/stock_request_kanban_templates.xml
  stock_request_kanban/security/ir.model.access.csv
  stock_request_kanban/static/description/icon.png
  stock_request_kanban/static/description/index.html
  stock_request_kanban/static/src/js/stock_request_kanban_scan_controller.js
  stock_request_kanban/static/src/js/stock_request_kanban_scan_view.js
  stock_request_kanban/static/src/xml/stock_request_kanban_scan.xml
  stock_request_kanban/tests/__init__.py
  stock_request_kanban/tests/base_test.py
  stock_request_kanban/tests/test_inventory_kanban.py
  stock_request_kanban/tests/test_kanban.py
  stock_request_kanban/views/product_views.xml
  stock_request_kanban/views/stock_inventory_kanban_views.xml
  stock_request_kanban/views/stock_request_kanban_views.xml
  stock_request_kanban/views/stock_request_menu.xml
  stock_request_kanban/views/stock_request_order_views.xml
  stock_request_kanban/views/stock_request_views.xml
  stock_request_kanban/wizard/__init__.py
  stock_request_kanban/wizard/wizard_stock_inventory_kanban.py
  stock_request_kanban/wizard/wizard_stock_inventory_kanban_views.xml
  stock_request_kanban/wizard/wizard_stock_request_kanban.py
  stock_request_kanban/wizard/wizard_stock_request_kanban_abstract.py
  stock_request_kanban/wizard/wizard_stock_request_kanban_views.xml
  stock_request_kanban/wizard/wizard_stock_request_order_kanban.py
  stock_request_kanban/wizard/wizard_stock_request_order_kanban_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1424 [13.0][FIX] stock_available: Not duplicate the product attribute name for avoid to crash the tests
  stock_available/tests/test_stock_available.py
Labels: approved, bot is merging ⏳
