Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-06, with the labels that each got.

#1359 [12.0][FIX] stock_available_unreserved: pre_init_hook
  stock_available_unreserved/hooks.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1439 [14.0][MIG] stock_inventory_line_open
  setup/stock_inventory_line_open/odoo/addons/stock_inventory_line_open
  setup/stock_inventory_line_open/setup.py
  stock_inventory_line_open/README.rst
  stock_inventory_line_open/__init__.py
  stock_inventory_line_open/__manifest__.py
  stock_inventory_line_open/i18n/stock_inventory_line_open.pot
  stock_inventory_line_open/models/__init__.py
  stock_inventory_line_open/models/stock_inventory.py
  stock_inventory_line_open/readme/CONTRIBUTORS.rst
  stock_inventory_line_open/readme/DESCRIPTION.rst
  stock_inventory_line_open/static/description/icon.png
  stock_inventory_line_open/static/description/index.html
  stock_inventory_line_open/views/stock_inventory_view.xml
Labels: approved, bot is merging ⏳

#1430 [13.0][ADD] stock_picking_manual_package: New module to select or create the package to do "put in pack"
  setup/stock_picking_manual_package/odoo/addons/stock_picking_manual_package
  setup/stock_picking_manual_package/setup.py
  stock_picking_manual_package/README.rst
  stock_picking_manual_package/__init__.py
  stock_picking_manual_package/__manifest__.py
  stock_picking_manual_package/i18n/es.po
  stock_picking_manual_package/i18n/stock_picking_manual_package.pot
  stock_picking_manual_package/models/__init__.py
  stock_picking_manual_package/models/stock_picking.py
  stock_picking_manual_package/models/stock_quant_package.py
  stock_picking_manual_package/readme/CONTRIBUTORS.rst
  stock_picking_manual_package/readme/DESCRIPTION.rst
  stock_picking_manual_package/readme/USAGE.rst
  stock_picking_manual_package/static/description/icon.png
  stock_picking_manual_package/static/description/index.html
  stock_picking_manual_package/tests/__init__.py
  stock_picking_manual_package/tests/test_stock_picking_manual_package.py
  stock_picking_manual_package/wizards/__init__.py
  stock_picking_manual_package/wizards/stock_picking_manual_package_wiz.py
  stock_picking_manual_package/wizards/stock_picking_manual_package_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1440 [13.0][REM] Move stock_picking_manual_package to stock-logistics-tracking
  setup/stock_picking_manual_package/odoo/addons/stock_picking_manual_package
  setup/stock_picking_manual_package/setup.py
  stock_picking_manual_package/README.rst
  stock_picking_manual_package/__init__.py
  stock_picking_manual_package/__manifest__.py
  stock_picking_manual_package/i18n/es.po
  stock_picking_manual_package/i18n/stock_picking_manual_package.pot
  stock_picking_manual_package/models/__init__.py
  stock_picking_manual_package/models/stock_picking.py
  stock_picking_manual_package/models/stock_quant_package.py
  stock_picking_manual_package/readme/CONTRIBUTORS.rst
  stock_picking_manual_package/readme/DESCRIPTION.rst
  stock_picking_manual_package/readme/USAGE.rst
  stock_picking_manual_package/static/description/icon.png
  stock_picking_manual_package/static/description/index.html
  stock_picking_manual_package/tests/__init__.py
  stock_picking_manual_package/tests/test_stock_picking_manual_package.py
  stock_picking_manual_package/wizards/__init__.py
  stock_picking_manual_package/wizards/stock_picking_manual_package_wiz.py
  stock_picking_manual_package/wizards/stock_picking_manual_package_wizard_view.xml
Labels: bot is merging ⏳

#968 [13.0]Multi company support for stock change qty reason
  stock_change_qty_reason/models/stock_inventory_line_reason.py
  stock_change_qty_reason/security/stock_security.xml
  stock_change_qty_reason/views/stock_inventory_line_reason_view.xml
  stock_change_qty_reason/views/stock_inventory_line_view.xml
  stock_change_qty_reason/views/stock_inventory_view.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#1441 [14.0][IMP] stock_quant_manual_assign: make several columns sortable in wizard
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳

#1445 [15.0][IMP] stock_quant_manual_assign: make several columns sortable in wizard
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳

#1444 [ADD][14.0] stock_picking_show_linked: Add to 14.0
  setup/stock_picking_show_linked/odoo/addons/stock_picking_show_linked
  setup/stock_picking_show_linked/setup.py
  stock_picking_show_linked/README.rst
  stock_picking_show_linked/__init__.py
  stock_picking_show_linked/__manifest__.py
  stock_picking_show_linked/models/__init__.py
  stock_picking_show_linked/models/stock_picking.py
  stock_picking_show_linked/readme/CONTRIBUTORS.rst
  stock_picking_show_linked/readme/DESCRIPTION.rst
  stock_picking_show_linked/static/description/index.html
  stock_picking_show_linked/views/stock_picking.xml
Labels: needs review, bot is merging ⏳

#1432 [15.0][MIG] stock_secondary_unit: Migration to 15.0
  setup/stock_secondary_unit/odoo/addons/stock_secondary_unit
  setup/stock_secondary_unit/setup.py
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1395 [13.0][FIX] sale_stock_available_info_popup: right context
  sale_stock_available_info_popup/models/sale_order.py
  sale_stock_available_info_popup/tests/test_sale_stock_available_info_popup.py
Labels: approved, bot is merging ⏳
