Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-07, with the labels that each got.

#1449 [13.0][IMP] stock_demand_estimate_matrix: Allow edit demand estimate tree view
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: bot is merging ⏳

#1451 [15.0][FIX] stock_quant_manual_assign: fix access error issues
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: bot is merging ⏳

#1452 [14.0][IMP] stock_demand_estimate_matrix: Allow edit demand estimate tree view
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: bot is merging ⏳

#1454 [15.0][IMP] stock_demand_estimate_matrix: Allow edit demand estimate tree view
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: bot is merging ⏳

#1428 [15.0][MIG] account_move_line_product
  account_move_line_product/README.rst
  account_move_line_product/__init__.py
  account_move_line_product/__manifest__.py
  account_move_line_product/i18n/account_move_line_product.pot
  account_move_line_product/i18n/ca.po
  account_move_line_product/i18n/cs_CZ.po
  account_move_line_product/i18n/de.po
  account_move_line_product/i18n/el_GR.po
  account_move_line_product/i18n/es.po
  account_move_line_product/i18n/es_ES.po
  account_move_line_product/i18n/eu.po
  account_move_line_product/i18n/fi.po
  account_move_line_product/i18n/fr.po
  account_move_line_product/i18n/fr_CH.po
  account_move_line_product/i18n/fr_FR.po
  account_move_line_product/i18n/gl.po
  account_move_line_product/i18n/hr.po
  account_move_line_product/i18n/hr_HR.po
  account_move_line_product/i18n/it.po
  account_move_line_product/i18n/nl.po
  account_move_line_product/i18n/nl_NL.po
  account_move_line_product/i18n/pt.po
  account_move_line_product/i18n/pt_BR.po
  account_move_line_product/i18n/ro.po
  account_move_line_product/i18n/ru.po
  account_move_line_product/i18n/sl.po
  account_move_line_product/i18n/tr.po
  account_move_line_product/i18n/tr_TR.po
  account_move_line_product/i18n/vi_VN.po
  account_move_line_product/i18n/zh_CN.po
  account_move_line_product/readme/CONTRIBUTORS.rst
  account_move_line_product/readme/DESCRIPTION.rst
  account_move_line_product/static/description/icon.png
  account_move_line_product/static/description/index.html
  account_move_line_product/views/account_move_line_view.xml
  setup/account_move_line_product/odoo/addons/account_move_line_product
  setup/account_move_line_product/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1447 [13.0][PORT]stock_picking_show_linked: Backport to 13.0
  setup/stock_picking_show_linked/odoo/addons/stock_picking_show_linked
  setup/stock_picking_show_linked/setup.py
  stock_picking_show_linked/README.rst
  stock_picking_show_linked/__init__.py
  stock_picking_show_linked/__manifest__.py
  stock_picking_show_linked/i18n/stock_picking_show_linked.pot
  stock_picking_show_linked/models/__init__.py
  stock_picking_show_linked/models/stock_picking.py
  stock_picking_show_linked/readme/CONTRIBUTORS.rst
  stock_picking_show_linked/readme/DESCRIPTION.rst
  stock_picking_show_linked/static/description/icon.png
  stock_picking_show_linked/static/description/index.html
  stock_picking_show_linked/views/stock_picking.xml
Labels: approved, bot is merging ⏳
