Repository OCA/stock-logistics-warehouse, pull requests merged in 2022-09, with the labels that each got.

#1400 Updated from template - Switch to Github actions
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .travis.yml
  README.md
  stock_cycle_count/__manifest__.py
  stock_location_bin_name/__manifest__.py
  stock_pull_list/__manifest__.py
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
  stock_pull_list/wizards/stock_pull_list_wizard.xml
  stock_request_analytic/__manifest__.py
  stock_request_analytic/models/analytic.py
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/analytic_views.xml
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
  stock_vertical_lift_qty_by_packaging/__manifest__.py
  stock_vertical_lift_qty_by_packaging/models/vertical_lift_operation_base.py
Labels: enhancement, bot is merging ⏳

#1473 [10.0][UPD] Switch to Github Actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_move_line_product/__manifest__.py
  base_product_merge/__manifest__.py
  business_product_location/__manifest__.py
  configurable_stock_level/__manifest__.py
  packaging_uom/__manifest__.py
  packaging_uom_view/__manifest__.py
  partner_location_auto_create/__manifest__.py
  purchase_packaging/__manifest__.py
  requirements.txt
  sale_packaging/__manifest__.py
  stock_account_quant_merge/__manifest__.py
  stock_available/__manifest__.py
  stock_available_immediately/__manifest__.py
  stock_available_mrp/__manifest__.py
  stock_available_sale/__manifest__.py
  stock_available_unreserved/__manifest__.py
  stock_change_qty_reason/__manifest__.py
  stock_demand_estimate/__manifest__.py
  stock_inventory_lockdown/__manifest__.py
  stock_inventory_preparation_filter/__manifest__.py
  stock_inventory_revaluation/__manifest__.py
  stock_location_area_data/__manifest__.py
  stock_location_area_management/__manifest__.py
  stock_location_ownership/__manifest__.py
  stock_location_product_restriction/__manifest__.py
  stock_location_restrict_procurement_group/__manifest__.py
  stock_lot_sale_tracking/__manifest__.py
  stock_lot_valuation/__manifest__.py
  stock_move_location/__manifest__.py
  stock_mts_mto_rule/__manifest__.py
  stock_operation_package_mandatory/__manifest__.py
  stock_optional_valuation/__manifest__.py
  stock_orderpoint_automatic_creation/__manifest__.py
  stock_orderpoint_creator/__manifest__.py
  stock_orderpoint_uom/__manifest__.py
  stock_partner_lot/__manifest__.py
  stock_putaway_product/__manifest__.py
  stock_putaway_product/i18n/es.po
  stock_putaway_product/i18n/nl_NL.po
  stock_putaway_product/i18n/sl.po
  stock_quant_manual_assign/__manifest__.py
  stock_reord_rule/__manifest__.py
  stock_reserve/__manifest__.py
  stock_reserve_sale/__manifest__.py
  stock_warehouse_orderpoint_stock_info/__manifest__.py
Labels: bot is merging ⏳

#1117 [10.0] backport stock_helper from 13.0
  setup/stock_helper/.eggs/README.txt
  setup/stock_helper/odoo/__init__.py
  setup/stock_helper/odoo/addons/__init__.py
  setup/stock_helper/odoo/addons/stock_helper
  setup/stock_helper/setup.py
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/readme/CONTRIBUTORS.rst
  stock_helper/readme/DESCRIPTION.rst
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
Labels: needs review, bot is merging ⏳

#1118 [10.0] backport stock_move_common_dest from 13.0
  setup/stock_move_common_dest/.eggs/README.txt
  setup/stock_move_common_dest/odoo/__init__.py
  setup/stock_move_common_dest/odoo/addons/__init__.py
  setup/stock_move_common_dest/odoo/addons/stock_move_common_dest
  setup/stock_move_common_dest/setup.py
  stock_move_common_dest/README.rst
  stock_move_common_dest/__init__.py
  stock_move_common_dest/__manifest__.py
  stock_move_common_dest/i18n/stock_move_common_dest.pot
  stock_move_common_dest/models/__init__.py
  stock_move_common_dest/models/stock_move.py
  stock_move_common_dest/readme/CONTRIBUTORS.rst
  stock_move_common_dest/readme/DESCRIPTION.rst
  stock_move_common_dest/static/description/icon.png
  stock_move_common_dest/static/description/index.html
  stock_move_common_dest/tests/__init__.py
  stock_move_common_dest/tests/test_move_common_dest.py
  stock_move_common_dest/views/stock_move.xml
Labels: needs review, bot is merging ⏳

#1104 12.0 mig stock orderpoint automatic creation
  stock_orderpoint_automatic_creation/README.rst
  stock_orderpoint_automatic_creation/__init__.py
  stock_orderpoint_automatic_creation/__manifest__.py
  stock_orderpoint_automatic_creation/i18n/ca.po
  stock_orderpoint_automatic_creation/i18n/cs_CZ.po
  stock_orderpoint_automatic_creation/i18n/de.po
  stock_orderpoint_automatic_creation/i18n/el_GR.po
  stock_orderpoint_automatic_creation/i18n/es.po
  stock_orderpoint_automatic_creation/i18n/es_ES.po
  stock_orderpoint_automatic_creation/i18n/es_MX.po
  stock_orderpoint_automatic_creation/i18n/eu.po
  stock_orderpoint_automatic_creation/i18n/fi.po
  stock_orderpoint_automatic_creation/i18n/fr.po
  stock_orderpoint_automatic_creation/i18n/fr_CH.po
  stock_orderpoint_automatic_creation/i18n/fr_FR.po
  stock_orderpoint_automatic_creation/i18n/gl.po
  stock_orderpoint_automatic_creation/i18n/hr.po
  stock_orderpoint_automatic_creation/i18n/hr_HR.po
  stock_orderpoint_automatic_creation/i18n/it.po
  stock_orderpoint_automatic_creation/i18n/nl.po
  stock_orderpoint_automatic_creation/i18n/nl_NL.po
  stock_orderpoint_automatic_creation/i18n/pt.po
  stock_orderpoint_automatic_creation/i18n/pt_BR.po
  stock_orderpoint_automatic_creation/i18n/ro.po
  stock_orderpoint_automatic_creation/i18n/ru.po
  stock_orderpoint_automatic_creation/i18n/sl.po
  stock_orderpoint_automatic_creation/i18n/stock_orderpoint_automatic_creation.pot
  stock_orderpoint_automatic_creation/i18n/tr.po
  stock_orderpoint_automatic_creation/i18n/tr_TR.po
  stock_orderpoint_automatic_creation/i18n/vi_VN.po
  stock_orderpoint_automatic_creation/i18n/zh_CN.po
  stock_orderpoint_automatic_creation/models/__init__.py
  stock_orderpoint_automatic_creation/models/product_category.py
  stock_orderpoint_automatic_creation/models/product_product.py
  stock_orderpoint_automatic_creation/models/product_template.py
  stock_orderpoint_automatic_creation/models/res_company.py
  stock_orderpoint_automatic_creation/readme/CONFIGURE.rst
  stock_orderpoint_automatic_creation/readme/CONTRIBUTORS.rst
  stock_orderpoint_automatic_creation/readme/DESCRIPTION.rst
  stock_orderpoint_automatic_creation/static/description/icon.png
  stock_orderpoint_automatic_creation/tests/__init__.py
  stock_orderpoint_automatic_creation/tests/test_stock_orderpoint_at_creation.py
  stock_orderpoint_automatic_creation/views/product_views.xml
  stock_orderpoint_automatic_creation/views/res_company_views.xml
Labels: needs review, migration, bot is merging ⏳

#1474 [14.0][FIX] stock_move_location: Remove update of assigned moves location
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
Labels: bug, approved, bot is merging ⏳

#1119 [10.0] backport stock_picking_completion_info from 13.0
  setup/stock_picking_completion_info/.eggs/README.txt
  setup/stock_picking_completion_info/odoo/__init__.py
  setup/stock_picking_completion_info/odoo/addons/__init__.py
  setup/stock_picking_completion_info/odoo/addons/stock_picking_completion_info
  setup/stock_picking_completion_info/setup.py
  stock_picking_completion_info/README.rst
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/i18n/stock_picking_completion_info.pot
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/readme/CONTRIBUTORS.rst
  stock_picking_completion_info/readme/DESCRIPTION.rst
  stock_picking_completion_info/static/description/icon.png
  stock_picking_completion_info/static/description/index.html
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
Labels: needs review, bot is merging ⏳

#1476 [12.0][UPD] Switch to Github Actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_move_line_product/__manifest__.py
  requirements.txt
  stock_archive_constraint/__manifest__.py
  stock_available_immediately/__manifest__.py
  stock_cycle_count/__manifest__.py
  stock_generate_putaway_from_inventory/__manifest__.py
  stock_inventory_preparation_filter/__manifest__.py
  stock_inventory_revaluation/i18n/de.po
  stock_inventory_revaluation/i18n/nl.po
  stock_inventory_verification_request/__manifest__.py
  stock_orderpoint_automatic_creation/__manifest__.py
  stock_orderpoint_move_link/__manifest__.py
  stock_orderpoint_route/__manifest__.py
  stock_packaging/__manifest__.py
  stock_request_analytic/__manifest__.py
  stock_request_analytic/models/analytic.py
  stock_request_analytic/models/stock_request.py
  stock_request_analytic/models/stock_request_order.py
  stock_request_analytic/models/stock_rule.py
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/analytic_views.xml
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
  stock_request_picking_type/__manifest__.py
  stock_request_purchase/__manifest__.py
  stock_request_submit/__manifest__.py
  stock_serial_batch_receive/__manifest__.py
  stock_warehouse_calendar/__manifest__.py
Labels: bot is merging ⏳

#1183 [14.0][MIG] stock available base exclude location xbo
  setup/stock_available_base_exclude_location/odoo/addons/stock_available_base_exclude_location
  setup/stock_available_base_exclude_location/setup.py
  stock_available_base_exclude_location/README.rst
  stock_available_base_exclude_location/__init__.py
  stock_available_base_exclude_location/__manifest__.py
  stock_available_base_exclude_location/i18n/stock_available_base_exclude_location.pot
  stock_available_base_exclude_location/models/__init__.py
  stock_available_base_exclude_location/models/product_product.py
  stock_available_base_exclude_location/models/stock_exclude_location_mixin.py
  stock_available_base_exclude_location/readme/CONTRIBUTORS.rst
  stock_available_base_exclude_location/readme/DESCRIPTION.rst
  stock_available_base_exclude_location/readme/USAGE.rst
  stock_available_base_exclude_location/static/description/icon.png
  stock_available_base_exclude_location/static/description/index.html
  stock_available_base_exclude_location/tests/__init__.py
  stock_available_base_exclude_location/tests/common.py
  stock_available_base_exclude_location/tests/test_stock_exclude_location.py
  test-requirements.txt
Labels: needs review, migration, bot is merging ⏳

#1064 [12.0][IMP] stock_quant_manual_assign: make quant search flexible
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: enhancement, needs review, bot is merging ⏳, stale

#1237 [14.0][FIX] stock_move_location : onchange picking_type_id
  stock_move_location/wizard/stock_move_location.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1265 [10.0][IMP] purchase_packaging: Add a test for multiple orderpoints
  purchase_packaging/tests/__init__.py
  purchase_packaging/tests/test_procurement_advanced_routes.py
  purchase_packaging/tests/test_procurement_order.py
  purchase_packaging/tests/test_purchase_order_line.py
Labels: bot is merging ⏳

#1303 [14.0][IMP] stock_available_unreserved: Add hooks
  stock_available_unreserved/models/product_product.py
Labels: enhancement, needs review, bot is merging ⏳

#1372 [10.0] stock_quant_merge: add company_id and owner_id in merge domain
  stock_quant_merge/models/stock_quant.py
Labels: enhancement, bot is merging ⏳

#1422 change evaluation company_id
  stock_move_location/wizard/stock_move_location.py
Labels: enhancement, needs review, bot is merging ⏳

#1467 [14.0][MIG] stock_picking_procure_method: Migration to version 14.0
  setup/stock_picking_procure_method/odoo/addons/stock_picking_procure_method
  setup/stock_picking_procure_method/setup.py
  stock_picking_procure_method/README.rst
  stock_picking_procure_method/__init__.py
  stock_picking_procure_method/__manifest__.py
  stock_picking_procure_method/i18n/pt_BR.po
  stock_picking_procure_method/i18n/stock_picking_procure_method.pot
  stock_picking_procure_method/i18n/zh_CN.po
  stock_picking_procure_method/models/__init__.py
  stock_picking_procure_method/models/stock_picking.py
  stock_picking_procure_method/readme/CONFIGURE.rst
  stock_picking_procure_method/readme/CONTRIBUTORS.rst
  stock_picking_procure_method/readme/DESCRIPTION.rst
  stock_picking_procure_method/readme/INSTALL.rst
  stock_picking_procure_method/readme/USAGE.rst
  stock_picking_procure_method/static/description/icon.png
  stock_picking_procure_method/static/description/index.html
  stock_picking_procure_method/tests/__init__.py
  stock_picking_procure_method/tests/test_stock_picking_procure_method.py
  stock_picking_procure_method/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1284 [12.0][ADD] stock_realign_move_and_quants
  setup/stock_realign_move_and_quants/odoo/addons/stock_realign_move_and_quants
  setup/stock_realign_move_and_quants/setup.py
  stock_realign_move_and_quants/README.rst
  stock_realign_move_and_quants/__init__.py
  stock_realign_move_and_quants/__manifest__.py
  stock_realign_move_and_quants/models/__init__.py
  stock_realign_move_and_quants/models/stock_quant.py
  stock_realign_move_and_quants/readme/CONTRIBUTORS.rst
  stock_realign_move_and_quants/readme/DESCRIPTION.rst
  stock_realign_move_and_quants/readme/ROADMAP.rst
  stock_realign_move_and_quants/readme/USAGE.rst
  stock_realign_move_and_quants/security/ir.model.access.csv
  stock_realign_move_and_quants/static/description/index.html
  stock_realign_move_and_quants/wizard/__init__.py
  stock_realign_move_and_quants/wizard/align_move_quant_wizard.py
  stock_realign_move_and_quants/wizard/align_move_quant_wizard_views.xml
Labels: needs review, bot is merging ⏳

#1479 [13.0][IMP] stock_quant_manual_assign: make quant search flexible
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, bot is merging ⏳

#1477 [12.0][MIG] stock_orderpoint_procure_location
  setup/stock_orderpoint_procure_location/odoo/addons/stock_orderpoint_procure_location
  setup/stock_orderpoint_procure_location/setup.py
  stock_orderpoint_procure_location/README.rst
  stock_orderpoint_procure_location/__init__.py
  stock_orderpoint_procure_location/__manifest__.py
  stock_orderpoint_procure_location/i18n/stock_orderpoint_procure_location.pot
  stock_orderpoint_procure_location/models/__init__.py
  stock_orderpoint_procure_location/models/procurement_group.py
  stock_orderpoint_procure_location/models/stock_warehouse_orderpoint.py
  stock_orderpoint_procure_location/static/description/icon.png
  stock_orderpoint_procure_location/tests/__init__.py
  stock_orderpoint_procure_location/tests/test_stock_orderpoint_procure_location.py
  stock_orderpoint_procure_location/views/stock_warehouse_orderpoint_view.xml
Labels: approved, migration, bot is merging ⏳

#1483 [14.0][DCK] stock_packaging_calculator: Change development_status key to Beta
  stock_packaging_calculator/__manifest__.py
Labels: approved, bot is merging ⏳

#1489 [13.0][IMP] stock_reserve_sale: Show Reserve Stock button in sent orders.
  stock_reserve_sale/__manifest__.py
  stock_reserve_sale/migrations/13.0.1.1.0/post-migration.py
  stock_reserve_sale/model/sale.py
Labels: approved, ready to merge, bot is merging ⏳

#1491 [13.0][IMP] stock_orderpoint_purchase_link: Add smart-button on orderpoints
  stock_orderpoint_purchase_link/__manifest__.py
  stock_orderpoint_purchase_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_purchase_link/tests/test_stock_orderpoint_purchase_link.py
  stock_orderpoint_purchase_link/views/stock_warehouse_orderpoint_views.xml
Labels: approved, bot is merging ⏳

#1480 [14.0][IMP] stock_quant_manual_assign: make quant search flexible
  stock_quant_manual_assign/wizard/assign_manual_quants.py
Labels: approved, ready to merge, bot is merging ⏳

#1492 [14.0][IMP] stock_orderpoint_purchase_link: Add smart-button on orderpoints
  stock_orderpoint_purchase_link/__manifest__.py
  stock_orderpoint_purchase_link/models/stock_warehouse_orderpoint.py
  stock_orderpoint_purchase_link/tests/test_stock_orderpoint_purchase_link.py
  stock_orderpoint_purchase_link/views/stock_warehouse_orderpoint_views.xml
Labels: approved, bot is merging ⏳

#1487 [14.0][ADD] stock_quant_reservation_info
  setup/stock_quant_reservation_info/odoo/addons/stock_quant_reservation_info
  setup/stock_quant_reservation_info/setup.py
  stock_quant_reservation_info/README.rst
  stock_quant_reservation_info/__init__.py
  stock_quant_reservation_info/__manifest__.py
  stock_quant_reservation_info/models/__init__.py
  stock_quant_reservation_info/models/stock_move_line.py
  stock_quant_reservation_info/models/stock_quant.py
  stock_quant_reservation_info/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info/readme/DESCRIPTION.rst
  stock_quant_reservation_info/readme/USAGE.rst
  stock_quant_reservation_info/views/stock_move_line.xml
  stock_quant_reservation_info/views/stock_quant.xml
Labels: approved, ready to merge, bot is merging ⏳
