Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-09, with the labels that each got.

#1822 [14.0][IMP] stock_request: Convert the state field of stock.request.order as compute store to complete all use cases
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
Labels: approved, ready to merge, bot is merging ⏳

#1722 [14.0][IMP] stock_request: Add option to use stock available
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/models/res_company.py
  stock_request/models/res_config_settings.py
  stock_request/models/stock_request.py
  stock_request/tests/test_stock_request.py
  stock_request/views/res_config_settings_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1832 [14.0][FIX] stock_request: Change to free_qty field to use stock
  stock_request/models/stock_request.py
Labels: approved, bot is merging ⏳

#1833 [IMP] stock_move_packaging_qty: display in PDF reports
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/readme/DESCRIPTION.rst
  stock_move_packaging_qty/views/report_stock_picking.xml
Labels: bot is merging ⏳

#1607 [14.0][FIX] stock_move_location: wrong destination location
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1838 [15.0][IMP] stock_request: Convert the state field of stock.request.order as compute store to complete all use cases
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
Labels: approved, bot is merging ⏳

#1839 [14.0][FIX] stock_request_*: Change to the correct icon
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
  stock_request_purchase/views/stock_request_order_views.xml
  stock_request_purchase/views/stock_request_views.xml
Labels: bot is merging ⏳

#1840 [15.0][FIX] stock_request_*: Change to the correct icon
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
  stock_request_purchase/views/stock_request_order_views.xml
  stock_request_purchase/views/stock_request_views.xml
Labels: approved, bot is merging ⏳

#1595 [15.0][MIG] stock_request_tier_validation
  setup/stock_request_tier_validation/odoo/addons/stock_request_tier_validation
  setup/stock_request_tier_validation/setup.py
  stock_request_tier_validation/README.rst
  stock_request_tier_validation/__init__.py
  stock_request_tier_validation/__manifest__.py
  stock_request_tier_validation/data/stock_request_tier_definition.xml
  stock_request_tier_validation/i18n/es.po
  stock_request_tier_validation/i18n/stock_request_tier_validation.pot
  stock_request_tier_validation/i18n/zh_CN.po
  stock_request_tier_validation/models/__init__.py
  stock_request_tier_validation/models/stock_request.py
  stock_request_tier_validation/models/stock_request_order.py
  stock_request_tier_validation/models/tier_definition.py
  stock_request_tier_validation/readme/CONFIGURE.rst
  stock_request_tier_validation/readme/CONTRIBUTORS.rst
  stock_request_tier_validation/readme/CREDITS.rst
  stock_request_tier_validation/readme/DESCRIPTION.rst
  stock_request_tier_validation/readme/INSTALL.rst
  stock_request_tier_validation/readme/USAGE.rst
  stock_request_tier_validation/static/description/icon.png
  stock_request_tier_validation/static/description/index.html
  stock_request_tier_validation/tests/__init__.py
  stock_request_tier_validation/tests/test_stock_request_tier_validation.py
  stock_request_tier_validation/views/stock_request_order_view.xml
  stock_request_tier_validation/views/stock_request_view.xml
Labels: approved, migration, ready to merge, bot is merging ⏳, stale

#1846 [16.0][MIG] stock_putaway_product_template: Migration to version 16.0
  setup/stock_putaway_product_template/odoo/addons/stock_putaway_product_template
  setup/stock_putaway_product_template/setup.py
  stock_putaway_product_template/README.rst
  stock_putaway_product_template/__init__.py
  stock_putaway_product_template/__manifest__.py
  stock_putaway_product_template/i18n/es.po
  stock_putaway_product_template/i18n/stock_putaway_product_template.pot
  stock_putaway_product_template/models/__init__.py
  stock_putaway_product_template/models/product.py
  stock_putaway_product_template/models/stock_location.py
  stock_putaway_product_template/models/stock_putaway_rule.py
  stock_putaway_product_template/readme/CONTRIBUTORS.rst
  stock_putaway_product_template/readme/DESCRIPTION.rst
  stock_putaway_product_template/readme/USAGE.rst
  stock_putaway_product_template/static/description/icon.png
  stock_putaway_product_template/static/description/index.html
  stock_putaway_product_template/tests/__init__.py
  stock_putaway_product_template/tests/test_stock_putaway_rule.py
  stock_putaway_product_template/views/stock_putaway_rule_views.xml
Labels: approved, bot is merging ⏳

#1842 [14.0][FIX] stock_move_location: Fix onchange and make editable
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
Labels: bot is merging ⏳

#1805 [MIG] 16.0: stock_picking_procure_method
  setup/stock_picking_procure_method/odoo/addons/stock_picking_procure_method
  setup/stock_picking_procure_method/setup.py
  stock_picking_procure_method/README.rst
  stock_picking_procure_method/__init__.py
  stock_picking_procure_method/__manifest__.py
  stock_picking_procure_method/i18n/pt_BR.po
  stock_picking_procure_method/i18n/stock_picking_procure_method.pot
  stock_picking_procure_method/i18n/zh_CN.po
  stock_picking_procure_method/models/__init__.py
  stock_picking_procure_method/models/stock_picking.py
  stock_picking_procure_method/readme/CONFIGURE.rst
  stock_picking_procure_method/readme/CONTRIBUTORS.rst
  stock_picking_procure_method/readme/DESCRIPTION.rst
  stock_picking_procure_method/readme/INSTALL.rst
  stock_picking_procure_method/readme/USAGE.rst
  stock_picking_procure_method/static/description/icon.png
  stock_picking_procure_method/static/description/index.html
  stock_picking_procure_method/tests/__init__.py
  stock_picking_procure_method/tests/test_stock_picking_procure_method.py
  stock_picking_procure_method/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1841 [16.0][MIG] stock_inventory_discrepancy: Migration to version 16.0
  setup/stock_inventory_discrepancy/odoo/addons/stock_inventory_discrepancy
  setup/stock_inventory_discrepancy/setup.py
  stock_inventory_discrepancy/README.rst
  stock_inventory_discrepancy/__init__.py
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/hooks.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/__init__.py
  stock_inventory_discrepancy/models/stock_location.py
  stock_inventory_discrepancy/models/stock_quant.py
  stock_inventory_discrepancy/models/stock_warehouse.py
  stock_inventory_discrepancy/readme/CONFIGURE.rst
  stock_inventory_discrepancy/readme/CONTRIBUTORS.rst
  stock_inventory_discrepancy/readme/DESCRIPTION.rst
  stock_inventory_discrepancy/readme/USAGE.rst
  stock_inventory_discrepancy/security/ir.model.access.csv
  stock_inventory_discrepancy/security/stock_inventory_discrepancy_security.xml
  stock_inventory_discrepancy/static/description/icon.png
  stock_inventory_discrepancy/static/description/index.html
  stock_inventory_discrepancy/tests/__init__.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_location_view.xml
  stock_inventory_discrepancy/views/stock_quant_view.xml
  stock_inventory_discrepancy/views/stock_warehouse_view.xml
  stock_inventory_discrepancy/wizards/__init__.py
  stock_inventory_discrepancy/wizards/confirm_discrepancy_wiz.py
  stock_inventory_discrepancy/wizards/confirm_discrepancy_wiz.xml
Labels: approved, ready to merge, bot is merging ⏳
