Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-03, with the labels that each got.

#1649 [13.0][FIX] stock_archive_constraint: ValidationError message not displaying correctly
  stock_archive_constraint/i18n/es_ES.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/stock_location.py
Labels: bot is merging ⏳

#1638 [15.0][FIX] stock_request_kanban: fix read
  stock_request_kanban/models/product.py
Labels: approved, bot is merging ⏳

#1647 [14.0][FIX] stock_request: Set with cancelled state the stock moves that are cancelled.
  stock_request/models/stock_move.py
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
  stock_request_mrp/tests/test_stock_request_mrp.py
Labels: approved, ready to merge, bot is merging ⏳

#1626 [16.0][ADD] stock_picking_volume
  setup/stock_picking_volume/odoo/addons/stock_picking_volume
  setup/stock_picking_volume/setup.py
  stock_picking_volume/README.rst
  stock_picking_volume/__init__.py
  stock_picking_volume/__manifest__.py
  stock_picking_volume/hooks.py
  stock_picking_volume/models/__init__.py
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/models/stock_picking.py
  stock_picking_volume/readme/CONTRIBUTORS.rst
  stock_picking_volume/readme/CREDITS.rst
  stock_picking_volume/readme/DESCRIPTION.rst
  stock_picking_volume/readme/USAGE.rst
  stock_picking_volume/static/description/icon.png
  stock_picking_volume/static/description/index.html
  stock_picking_volume/tests/__init__.py
  stock_picking_volume/tests/test_stock_picking_volume.py
  stock_picking_volume/views/stock_move.xml
  stock_picking_volume/views/stock_picking.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1529 [14.0][ADD] stock_available_portal
  setup/stock_available_portal/odoo/addons/stock_available_portal
  setup/stock_available_portal/setup.py
  stock_available_portal/README.rst
  stock_available_portal/__init__.py
  stock_available_portal/__manifest__.py
  stock_available_portal/controllers/__init__.py
  stock_available_portal/controllers/portal.py
  stock_available_portal/models/__init__.py
  stock_available_portal/models/product_product.py
  stock_available_portal/models/res_config_settings.py
  stock_available_portal/readme/CONFIGURE.rst
  stock_available_portal/readme/CONTRIBUTORS.rst
  stock_available_portal/readme/DESCRIPTION.rst
  stock_available_portal/readme/USAGE.rst
  stock_available_portal/tests/__init__.py
  stock_available_portal/tests/test_portal_product.py
  stock_available_portal/tests/test_product_product.py
  stock_available_portal/views/product_portal_templates.xml
  stock_available_portal/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#1656 [13.0][IMP] stock_demand_estimate: enhance views
  stock_demand_estimate/models/stock_demand_estimate.py
  stock_demand_estimate/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1657 [14.0][FW-PORT] stock_demand_estimate: enhance views
  stock_demand_estimate/models/stock_demand_estimate.py
  stock_demand_estimate/views/stock_demand_estimate_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1659 [14.0][FW-PORT] stock_demand_estimate_matrix: remove action extension
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: bot is merging ⏳

#1658 [15.0][IMP] stock_demand_estimate: enhance views
  stock_demand_estimate/models/stock_demand_estimate.py
  stock_demand_estimate/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
Labels: bot is merging ⏳
