Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-05, with the labels that each got.

#1702 [15.0][FIX] stock_move_location: No read on actions
  stock_move_location/models/stock_picking_type.py
  stock_move_location/wizard/stock_move_location.py
Labels: bot is merging ⏳

#1703 [16.0][MIG] stock_quant_cost_info: Migration to version 16.0
  setup/stock_quant_cost_info/odoo/addons/stock_quant_cost_info
  setup/stock_quant_cost_info/setup.py
  stock_quant_cost_info/README.rst
  stock_quant_cost_info/__init__.py
  stock_quant_cost_info/__manifest__.py
  stock_quant_cost_info/hooks.py
  stock_quant_cost_info/i18n/es.po
  stock_quant_cost_info/i18n/stock_quant_cost_info.pot
  stock_quant_cost_info/models/__init__.py
  stock_quant_cost_info/models/stock_quant.py
  stock_quant_cost_info/readme/CONTRIBUTORS.rst
  stock_quant_cost_info/readme/DESCRIPTION.rst
  stock_quant_cost_info/readme/INSTALL.rst
  stock_quant_cost_info/readme/USAGE.rst
  stock_quant_cost_info/static/description/icon.png
  stock_quant_cost_info/static/description/index.html
  stock_quant_cost_info/tests/__init__.py
  stock_quant_cost_info/tests/test_stock_quant_cost_info.py
  stock_quant_cost_info/views/report_stockinventory.xml
  stock_quant_cost_info/views/stock_inventory_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1706 [13.0][ADD]stock_picking_orig_dest_link
  setup/stock_picking_orig_dest_link/odoo/addons/stock_picking_orig_dest_link
  setup/stock_picking_orig_dest_link/setup.py
  stock_picking_orig_dest_link/__init__.py
  stock_picking_orig_dest_link/__manifest__.py
  stock_picking_orig_dest_link/hooks.py
  stock_picking_orig_dest_link/models/__init__.py
  stock_picking_orig_dest_link/models/stock_picking.py
  stock_picking_orig_dest_link/readme/CONTRIBUTORS.rst
  stock_picking_orig_dest_link/readme/DESCRIPTION.rst
  stock_picking_orig_dest_link/readme/ROADMAP.rst
  stock_picking_orig_dest_link/tests/__init__.py
  stock_picking_orig_dest_link/tests/test_stock_picking_orig_dest_link.py
  stock_picking_orig_dest_link/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1712 [14.0][FIX] stock_request: Do not change stock.group_stock_user to avoid in consistency
  stock_request/security/stock_request_security.xml
Labels: bot is merging ⏳

#1714 [15.0][FIX] stock_request: Do not change stock.group_stock_user to avoid in consistency
  stock_request/security/stock_request_security.xml
Labels: approved, bot is merging ⏳

#1629 [16.0][ADD] stock_picking_volume_packaging
  setup/stock_picking_volume_packaging/odoo/addons/stock_picking_volume_packaging
  setup/stock_picking_volume_packaging/setup.py
  stock_picking_volume_packaging/README.rst
  stock_picking_volume_packaging/__init__.py
  stock_picking_volume_packaging/__manifest__.py
  stock_picking_volume_packaging/models/__init__.py
  stock_picking_volume_packaging/models/stock_move.py
  stock_picking_volume_packaging/readme/CONTRIBUTORS.rst
  stock_picking_volume_packaging/readme/CREDITS.rst
  stock_picking_volume_packaging/readme/DESCRIPTION.rst
  stock_picking_volume_packaging/readme/USAGE.rst
  stock_picking_volume_packaging/static/description/icon.png
  stock_picking_volume_packaging/static/description/index.html
  stock_picking_volume_packaging/tests/__init__.py
  stock_picking_volume_packaging/tests/test_stock_move_volume.py
Labels: approved, ready to merge, bot is merging ⏳

#1710 [14.0][IMP] stock_request_purchase: Propagate the cancellation of related purchases
  stock_request_purchase/models/stock_request.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved, bot is merging ⏳

#1715 [14.0][FIX] stock_quant_reservation_info
  stock_quant_reservation_info/models/stock_quant.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1718 [14.0][IMP] stock_request_purchase: Filter purchases that are linked only to requests
  stock_request_purchase/models/stock_request.py
Labels: bot is merging ⏳

#1719 [14.0][FIX] stock_quant_reservation_info_mrp: incorrect key in manifest
  stock_quant_reservation_info_mrp/__manifest__.py
Labels: bot is merging ⏳

#1520 [FIX] stock_request: add sudo to allow stock ops without stock request access
  stock_request/models/stock_move.py
Labels: approved, bot is merging ⏳, stale

#1713 [14.0][IMP] scrap_reason_code: define product categories allowed for each code
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_scrap_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1723 [15.0][IMP] scrap_reason_code: define product categories allowed for each code
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_scrap_views.xml
Labels: approved, bot is merging ⏳

#1724 [16.0][IMP] scrap_reason_code: define product categories allowed for each code
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/readme/CONTRIBUTORS.rst
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_scrap_views.xml
Labels: approved, bot is merging ⏳

#1725 [15.0][MIG] stock_picking_orig_dest_link
  setup/stock_picking_orig_dest_link/odoo/addons/stock_picking_orig_dest_link
  setup/stock_picking_orig_dest_link/setup.py
  stock_picking_orig_dest_link/README.rst
  stock_picking_orig_dest_link/__init__.py
  stock_picking_orig_dest_link/__manifest__.py
  stock_picking_orig_dest_link/hooks.py
  stock_picking_orig_dest_link/i18n/stock_picking_orig_dest_link.pot
  stock_picking_orig_dest_link/models/__init__.py
  stock_picking_orig_dest_link/models/stock_picking.py
  stock_picking_orig_dest_link/readme/CONTRIBUTORS.rst
  stock_picking_orig_dest_link/readme/DESCRIPTION.rst
  stock_picking_orig_dest_link/readme/ROADMAP.rst
  stock_picking_orig_dest_link/static/description/icon.png
  stock_picking_orig_dest_link/static/description/index.html
  stock_picking_orig_dest_link/tests/__init__.py
  stock_picking_orig_dest_link/tests/test_stock_picking_orig_dest_link.py
  stock_picking_orig_dest_link/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1717 [15.0][IMP] stock_quant_cost_info: Hide field for non inventory_quantity_set
  stock_quant_cost_info/models/stock_quant.py
  stock_quant_cost_info/views/stock_inventory_views.xml
Labels: approved, bot is merging ⏳

#1726 [14.0][ADD] stock_location_package_restriction
  setup/stock_location_package_restriction/odoo/addons/stock_location_package_restriction
  setup/stock_location_package_restriction/setup.py
  stock_location_package_restriction/README.rst
  stock_location_package_restriction/__init__.py
  stock_location_package_restriction/__manifest__.py
  stock_location_package_restriction/models/__init__.py
  stock_location_package_restriction/models/stock_location.py
  stock_location_package_restriction/models/stock_move.py
  stock_location_package_restriction/readme/CONTRIBUTORS.rst
  stock_location_package_restriction/readme/DESCRIPTION.rst
  stock_location_package_restriction/readme/USAGE.rst
  stock_location_package_restriction/tests/__init__.py
  stock_location_package_restriction/tests/test_stock_move.py
  stock_location_package_restriction/views/stock_location.xml
Labels: approved, bot is merging ⏳
