Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-01, with the labels that each got.

#1600 [14.0][IMP] stock_move_location: change location domain
  stock_move_location/wizard/stock_move_location.py
Labels: enhancement, approved, bot is merging ⏳

#1597 [14.0][FIX] stock_move_location: stock_move_location_line_ids
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1515 [14.0] [MIG] stock_inventory_lockdown: Migration to 14.0
  setup/stock_inventory_lockdown/odoo/addons/stock_inventory_lockdown
  setup/stock_inventory_lockdown/setup.py
  stock_inventory_lockdown/README.rst
  stock_inventory_lockdown/__init__.py
  stock_inventory_lockdown/__manifest__.py
  stock_inventory_lockdown/i18n/ca.po
  stock_inventory_lockdown/i18n/cs_CZ.po
  stock_inventory_lockdown/i18n/de.po
  stock_inventory_lockdown/i18n/es.po
  stock_inventory_lockdown/i18n/es_ES.po
  stock_inventory_lockdown/i18n/es_MX.po
  stock_inventory_lockdown/i18n/fi.po
  stock_inventory_lockdown/i18n/fr.po
  stock_inventory_lockdown/i18n/gl.po
  stock_inventory_lockdown/i18n/hr.po
  stock_inventory_lockdown/i18n/it.po
  stock_inventory_lockdown/i18n/nl_NL.po
  stock_inventory_lockdown/i18n/pt.po
  stock_inventory_lockdown/i18n/pt_BR.po
  stock_inventory_lockdown/i18n/ro.po
  stock_inventory_lockdown/i18n/sl.po
  stock_inventory_lockdown/i18n/stock_inventory_lockdown.pot
  stock_inventory_lockdown/i18n/tr.po
  stock_inventory_lockdown/i18n/tr_TR.po
  stock_inventory_lockdown/i18n/vi_VN.po
  stock_inventory_lockdown/i18n/zh_CN.po
  stock_inventory_lockdown/models/__init__.py
  stock_inventory_lockdown/models/stock_inventory.py
  stock_inventory_lockdown/models/stock_location.py
  stock_inventory_lockdown/models/stock_move.py
  stock_inventory_lockdown/readme/CONTRIBUTORS.rst
  stock_inventory_lockdown/readme/DESCRIPTION.rst
  stock_inventory_lockdown/readme/USAGE.rst
  stock_inventory_lockdown/static/description/icon.png
  stock_inventory_lockdown/static/description/index.html
  stock_inventory_lockdown/static/images/move_error.png
  stock_inventory_lockdown/tests/__init__.py
  stock_inventory_lockdown/tests/test_stock_inventory_lockdown.py
Labels: approved, bot is merging ⏳

#1605 [14.0][IMP] stock_request: Add domain to some fields to prevent deprecate methods with domain return
  stock_request/models/stock_request_abstract.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
  stock_request_kanban/views/stock_request_kanban_views.xml
Labels: enhancement, approved, bot is merging ⏳

#1609 [15.0][IMP] stock_request: Add domain to some fields to prevent deprecate methods with domain return
  stock_request/models/stock_request_abstract.py
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
  stock_request_kanban/views/stock_request_kanban_views.xml
Labels: enhancement, approved, bot is merging ⏳

#1499 [14.0][MIG] stock_request_mrp: Migration to 14.0
  setup/stock_request_mrp/odoo/addons/stock_request_mrp
  setup/stock_request_mrp/setup.py
  stock_available/tests/test_stock_available.py
  stock_available_immediately/tests/test_stock_available_immediately.py
  stock_orderpoint_manual_procurement/tests/test_stock_orderpoint_manual_procurement.py
  stock_orderpoint_manual_procurement_uom/tests/test_stock_orderpoint_manual_procurement.py
  stock_request/tests/test_stock_request.py
  stock_request_cancel_confirm/model/stock_request.py
  stock_request_cancel_confirm/model/stock_request_order.py
  stock_request_kanban/models/stock_inventory_kanban.py
  stock_request_mrp/README.rst
  stock_request_mrp/__init__.py
  stock_request_mrp/__manifest__.py
  stock_request_mrp/hooks.py
  stock_request_mrp/i18n/stock_request_mrp.pot
  stock_request_mrp/models/__init__.py
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/models/stock_request.py
  stock_request_mrp/models/stock_request_order.py
  stock_request_mrp/models/stock_rule.py
  stock_request_mrp/readme/CONTRIBUTORS.rst
  stock_request_mrp/readme/DESCRIPTION.rst
  stock_request_mrp/readme/ROADMAP.rst
  stock_request_mrp/readme/USAGE.rst
  stock_request_mrp/security/ir.model.access.csv
  stock_request_mrp/static/description/icon.png
  stock_request_mrp/static/description/index.html
  stock_request_mrp/tests/__init__.py
  stock_request_mrp/tests/test_stock_request_mrp.py
  stock_request_mrp/views/mrp_production_views.xml
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1435 [14.0][MIG] stock_quant_view_reservation
  setup/stock_quant_view_reservation/odoo/addons/stock_quant_view_reservation
  setup/stock_quant_view_reservation/setup.py
  stock_quant_view_reservation/README.rst
  stock_quant_view_reservation/__init__.py
  stock_quant_view_reservation/__manifest__.py
  stock_quant_view_reservation/i18n/stock_quant_view_reservation.pot
  stock_quant_view_reservation/models/__init__.py
  stock_quant_view_reservation/models/stock_quant.py
  stock_quant_view_reservation/readme/CONTRIBUTORS.rst
  stock_quant_view_reservation/readme/DESCRIPTION.rst
  stock_quant_view_reservation/readme/USAGE.rst
  stock_quant_view_reservation/static/description/icon.png
  stock_quant_view_reservation/static/description/index.html
  stock_quant_view_reservation/views/stock_move_line_views.xml
  stock_quant_view_reservation/views/stock_quant.xml
Labels: needs review, approved, migration, bot is merging ⏳, stale

#1596 [15.0][FIX] stock_move_location: stock_move_location_line_ids
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1577 [14.0][FIX] Stock Move Location: apply putaway rules
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location_line.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1532 [16.0][IMP] stock_move_auto_assign: reassing on move cancellation
  stock_move_auto_assign/models/stock_move.py
  stock_move_auto_assign/tests/test_auto_assign.py
Labels: enhancement, approved, ready to merge

#1615 [14.0][FIX] stock_request: Multi-company record rules
  stock_request/__manifest__.py
  stock_request/migrations/14.0.1.3.0/noupdate_changes.xml
  stock_request/migrations/14.0.1.3.0/post-migration.py
  stock_request/security/stock_request_security.xml
Labels: bot is merging ⏳

#1512 [15.0][ADD] stock_inventory
  setup/stock_inventory/odoo/addons/stock_inventory
  setup/stock_inventory/setup.py
  stock_inventory/README.rst
  stock_inventory/__init__.py
  stock_inventory/__manifest__.py
  stock_inventory/models/__init__.py
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_move_line.py
  stock_inventory/models/stock_quant.py
  stock_inventory/readme/CONTRIBUTORS.rst
  stock_inventory/readme/DESCRIPTION.rst
  stock_inventory/readme/USAGE.rst
  stock_inventory/security/ir.model.access.csv
  stock_inventory/tests/__init__.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/stock_inventory.xml
  stock_inventory/views/stock_move_line.xml
  stock_inventory/views/stock_quant.xml
Labels: bot is merging ⏳

#1618 [14.0][IMP] stock_request: Change the label string to make it consistent
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/views/stock_request_order_views.xml
Labels: approved, bot is merging ⏳

#1619 [14.0][FIX] stock_request: Change state fields to display translated by language
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
  stock_request_submit/i18n/es.po
  stock_request_submit/i18n/stock_request_submit.pot
  stock_request_submit/models/stock_request.py
Labels: approved, bot is merging ⏳

#1622 [15.0][FIX] stock_request: Change state fields to display translated by language
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/models/stock_request.py
  stock_request/models/stock_request_order.py
Labels: approved, bot is merging ⏳

#1623 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1469 [MIG] stock_request_mrp: Migration to 15.0
  setup/stock_request_mrp/odoo/addons/stock_request_mrp
  setup/stock_request_mrp/setup.py
  stock_request_mrp/README.rst
  stock_request_mrp/__init__.py
  stock_request_mrp/__manifest__.py
  stock_request_mrp/hooks.py
  stock_request_mrp/i18n/stock_request_mrp.pot
  stock_request_mrp/models/__init__.py
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/models/stock_request.py
  stock_request_mrp/models/stock_request_order.py
  stock_request_mrp/models/stock_rule.py
  stock_request_mrp/readme/CONTRIBUTORS.rst
  stock_request_mrp/readme/DESCRIPTION.rst
  stock_request_mrp/readme/ROADMAP.rst
  stock_request_mrp/readme/USAGE.rst
  stock_request_mrp/security/ir.model.access.csv
  stock_request_mrp/static/description/icon.png
  stock_request_mrp/static/description/index.html
  stock_request_mrp/tests/__init__.py
  stock_request_mrp/tests/test_stock_request_mrp.py
  stock_request_mrp/views/mrp_production_views.xml
  stock_request_mrp/views/stock_request_order_views.xml
  stock_request_mrp/views/stock_request_views.xml
Labels: needs review, migration, bot is merging ⏳, stale

#1617 [14.0][FIX] stock_request_mrp: Avoid copying the relationship to mrp.production when duplicating a record
  stock_request_mrp/models/stock_request.py
  stock_request_mrp/tests/test_stock_request_mrp.py
Labels: approved, ready to merge, bot is merging ⏳
