Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-10, with the labels that each got.

#1862 [14.0][FIX] stock_request_kanban: `image_small` -> `image_128`
  stock_request_kanban/views/stock_request_kanban_views.xml
Labels: bot is merging ⏳

#1864 [15.0][FIX] stock_request_kanban: `image_small` -> `image_128`
  stock_request_kanban/views/stock_request_kanban_views.xml
Labels: bot is merging ⏳

#1857 [16.0][MIG] stock_product_qty_by_packaging: Migrate to version 16.0
  setup/stock_product_qty_by_packaging/odoo/addons/stock_product_qty_by_packaging
  setup/stock_product_qty_by_packaging/setup.py
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__init__.py
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/i18n/stock_product_qty_by_packaging.pot
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/CREDITS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/icon.png
  stock_product_qty_by_packaging/static/description/index.html
  stock_product_qty_by_packaging/tests/__init__.py
  stock_product_qty_by_packaging/tests/test_stock.py
  stock_product_qty_by_packaging/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#1858 [14.0][IMP] stock_location_package_restriction: Change no restriction value
  stock_location_package_restriction/__manifest__.py
  stock_location_package_restriction/migrations/14.0.1.1.0/pre-migrate.py
  stock_location_package_restriction/models/stock_location.py
  stock_location_package_restriction/models/stock_move.py
  stock_location_package_restriction/tests/test_stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1865 [16.0][MIG] stock_inventory_count_to_zero: Migration to version 16.0
  setup/stock_inventory_count_to_zero/odoo/addons/stock_inventory_count_to_zero
  setup/stock_inventory_count_to_zero/setup.py
  stock_inventory_count_to_zero/README.rst
  stock_inventory_count_to_zero/__init__.py
  stock_inventory_count_to_zero/__manifest__.py
  stock_inventory_count_to_zero/i18n/es.po
  stock_inventory_count_to_zero/i18n/stock_inventory_count_to_zero.pot
  stock_inventory_count_to_zero/i18n/stock_request_count_to_zero.pot
  stock_inventory_count_to_zero/models/__init__.py
  stock_inventory_count_to_zero/models/stock_quant.py
  stock_inventory_count_to_zero/readme/CONTRIBUTORS.rst
  stock_inventory_count_to_zero/readme/DESCRIPTION.rst
  stock_inventory_count_to_zero/readme/USAGE.rst
  stock_inventory_count_to_zero/static/description/icon.png
  stock_inventory_count_to_zero/static/description/index.html
  stock_inventory_count_to_zero/tests/__init__.py
  stock_inventory_count_to_zero/tests/test_stock_inventory_count_to_zero.py
  stock_inventory_count_to_zero/wizards/__init__.py
  stock_inventory_count_to_zero/wizards/stock_request_count.py
Labels: approved, bot is merging ⏳

#1867 [16.0][IMP]stock_reserve: change parent from menu_action_stock_reservation
  stock_reserve/README.rst
  stock_reserve/view/stock_reserve.xml
Labels: approved, bot is merging ⏳

#1871 [15.0][IMP] stock-logistics-warehouse : test performance improvement
  stock_archive_constraint/tests/test_location_archive_constraint.py
  stock_lot_filter_available/tests/test_stock_lot_filter_available.py
  stock_move_location/tests/test_common.py
  stock_putaway_product_template/tests/test_stock_putaway_rule.py
  stock_quant_cost_info/tests/test_stock_quant_cost_info.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
Labels: bot is merging ⏳
