Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-08, with the labels that each got.

#1798 [IMP] stock_location_orderpoint:
  stock_location_orderpoint/models/stock_location_orderpoint.py
  stock_location_orderpoint/models/stock_move.py
  stock_location_orderpoint/views/stock_location_orderpoint_views.xml
Labels: enhancement, approved, bot is merging ⏳

#1812 [14.0][MIG] stock_removal_location_by_priority
  setup/stock_removal_location_by_priority/odoo/addons/stock_removal_location_by_priority
  setup/stock_removal_location_by_priority/setup.py
  stock_removal_location_by_priority/README.rst
  stock_removal_location_by_priority/__init__.py
  stock_removal_location_by_priority/__manifest__.py
  stock_removal_location_by_priority/i18n/de.po
  stock_removal_location_by_priority/i18n/es.po
  stock_removal_location_by_priority/i18n/fi.po
  stock_removal_location_by_priority/i18n/fr.po
  stock_removal_location_by_priority/i18n/it.po
  stock_removal_location_by_priority/i18n/pt_BR.po
  stock_removal_location_by_priority/i18n/ro.po
  stock_removal_location_by_priority/i18n/sl.po
  stock_removal_location_by_priority/i18n/stock_removal_location_by_priority.pot
  stock_removal_location_by_priority/i18n/zh_CN.po
  stock_removal_location_by_priority/init_hook.py
  stock_removal_location_by_priority/models/__init__.py
  stock_removal_location_by_priority/models/res_config_settings.py
  stock_removal_location_by_priority/models/stock_location.py
  stock_removal_location_by_priority/models/stock_quant.py
  stock_removal_location_by_priority/readme/CONFIGURE.rst
  stock_removal_location_by_priority/readme/CONTRIBUTORS.rst
  stock_removal_location_by_priority/readme/DESCRIPTION.rst
  stock_removal_location_by_priority/readme/USAGE.rst
  stock_removal_location_by_priority/security/stock_security.xml
  stock_removal_location_by_priority/static/description/icon.png
  stock_removal_location_by_priority/static/description/index.html
  stock_removal_location_by_priority/tests/__init__.py
  stock_removal_location_by_priority/tests/test_stock_removal_location_by_priority.py
  stock_removal_location_by_priority/views/res_config_settings_views.xml
  stock_removal_location_by_priority/views/stock_location_view.xml
Labels: approved, bot is merging ⏳

#1594 [15.0][MIG] stock_request_submit
  setup/stock_request_submit/odoo/addons/stock_request_submit
  setup/stock_request_submit/setup.py
  stock_request_submit/README.rst
  stock_request_submit/__init__.py
  stock_request_submit/__manifest__.py
  stock_request_submit/hooks.py
  stock_request_submit/i18n/es.po
  stock_request_submit/i18n/stock_request_submit.pot
  stock_request_submit/i18n/zh_CN.po
  stock_request_submit/models/__init__.py
  stock_request_submit/models/stock_request.py
  stock_request_submit/models/stock_request_order.py
  stock_request_submit/readme/CONTRIBUTORS.rst
  stock_request_submit/readme/DESCRIPTION.rst
  stock_request_submit/static/description/icon.png
  stock_request_submit/static/description/index.html
  stock_request_submit/tests/__init__.py
  stock_request_submit/tests/test_stock_request_submit.py
  stock_request_submit/views/stock_request_order_views.xml
  stock_request_submit/views/stock_request_views.xml
Labels: needs review, migration, bot is merging ⏳

#1818 [15.0][MIG] stock_procurement_group_hook: Migration to 15.0
  setup/stock_procurement_group_hook/odoo/addons/stock_procurement_group_hook
  setup/stock_procurement_group_hook/setup.py
  stock_procurement_group_hook/README.rst
  stock_procurement_group_hook/__init__.py
  stock_procurement_group_hook/__manifest__.py
  stock_procurement_group_hook/hooks.py
  stock_procurement_group_hook/i18n/stock_procurement_group_hook.pot
  stock_procurement_group_hook/models/__init__.py
  stock_procurement_group_hook/models/procurement_group.py
  stock_procurement_group_hook/readme/CONTRIBUTORS.rst
  stock_procurement_group_hook/readme/DESCRIPTION.rst
  stock_procurement_group_hook/static/description/icon.png
  stock_procurement_group_hook/static/description/index.html
Labels: approved, bot is merging ⏳

#1825 [14.0][IMP] stock_request_purchase: Change invisible attr of the action_view_stock_request action of purchase.order
  stock_request_purchase/models/purchase_order.py
  stock_request_purchase/views/purchase_order_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1824 [14.0][IMP] stock_request_mrp: Change invisible attr of the action_view_stock_request action of mrp.production
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/views/mrp_production_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1826 [15.0][IMP] stock_request_mrp: Change invisible attr of the action_view_stock_request action of mrp.production
  stock_request_mrp/models/mrp_production.py
  stock_request_mrp/views/mrp_production_views.xml
Labels: approved, bot is merging ⏳

#1827 [15.0][IMP] stock_request_purchase: Change invisible attr of the action_view_stock_request action of purchase.order
  stock_request_purchase/models/purchase_order.py
  stock_request_purchase/views/purchase_order_views.xml
Labels: approved, bot is merging ⏳

#1823 [MIG+REF] stock_move_packaging_qty: migrate to 16.0
  setup/stock_move_packaging_qty/odoo/addons/stock_move_packaging_qty
  setup/stock_move_packaging_qty/setup.py
  stock_move_packaging_qty/README.rst
  stock_move_packaging_qty/__init__.py
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/i18n/stock_move_packaging_qty.pot
  stock_move_packaging_qty/migrations/15.0.0/pre-migrate.py
  stock_move_packaging_qty/models/__init__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/readme/CONTRIBUTORS.rst
  stock_move_packaging_qty/readme/DESCRIPTION.rst
  stock_move_packaging_qty/static/description/icon.png
  stock_move_packaging_qty/static/description/index.html
  stock_move_packaging_qty/tests/__init__.py
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/stock_move_tree_view.xml
  stock_move_packaging_qty/views/stock_picking_form_view.xml
Labels: needs review, approved, bot is merging ⏳
