Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-12, with the labels that each got.

#1892 [DOCS] stock_move_location: improve usage instructions
  stock_move_location/README.rst
  stock_move_location/readme/CONTRIBUTORS.md
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/DESCRIPTION.md
  stock_move_location/readme/ROADMAP.md
  stock_move_location/readme/ROADMAP.rst
  stock_move_location/readme/USAGE.md
  stock_move_location/readme/USAGE.rst
  stock_move_location/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1901 [15.0][IMP] stock_move_location: Avoid check date expired in immediate relocation transfer
  stock_move_location/wizard/stock_move_location.py
Labels: approved, bot is merging ⏳

#1606 [15.0][IMP] stock_secondary_unit: Compatibility with product variants
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product_product.py
  stock_secondary_unit/models/product_template.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/models/stock_product_secondary_unit_mixin.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: needs review, bot is merging ⏳

#1860 [16.0] [MIG] stock_packaging_calculator_packaging_type + Rename stock_packaging_calculator_packaging_level
  setup/stock_packaging_calculator_packaging_level/odoo/addons/stock_packaging_calculator_packaging_level
  setup/stock_packaging_calculator_packaging_level/setup.py
  stock_packaging_calculator_packaging_level/README.rst
  stock_packaging_calculator_packaging_level/__init__.py
  stock_packaging_calculator_packaging_level/__manifest__.py
  stock_packaging_calculator_packaging_level/i18n/stock_packaging_calculator_packaging_type.pot
  stock_packaging_calculator_packaging_level/models/__init__.py
  stock_packaging_calculator_packaging_level/models/product.py
  stock_packaging_calculator_packaging_level/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator_packaging_level/readme/CONTRIBUTORS.rst
  stock_packaging_calculator_packaging_level/readme/CREDITS.rst
  stock_packaging_calculator_packaging_level/readme/DESCRIPTION.rst
  stock_packaging_calculator_packaging_level/static/description/icon.png
  stock_packaging_calculator_packaging_level/static/description/index.html
  stock_packaging_calculator_packaging_level/tests/__init__.py
  stock_packaging_calculator_packaging_level/tests/test_packaging_by_qty.py
Labels: needs review, approved, migration, bot is merging ⏳

#1875 [ADD][16.0] product_packaging_usability module
  product_packaging_usability/README.rst
  product_packaging_usability/__init__.py
  product_packaging_usability/__manifest__.py
  product_packaging_usability/models/__init__.py
  product_packaging_usability/models/product_packaging.py
  product_packaging_usability/readme/CONTRIBUTORS.rst
  product_packaging_usability/readme/DESCRIPTION.rst
  product_packaging_usability/static/description/icon.png
  product_packaging_usability/static/description/im1.png
  product_packaging_usability/static/description/im2.png
  product_packaging_usability/static/description/im3.png
  product_packaging_usability/static/description/index.html
  product_packaging_usability/tests/__init__.py
  product_packaging_usability/tests/test_module.py
  product_packaging_usability/views/product_packaging.xml
  setup/product_packaging_usability/odoo/addons/product_packaging_usability
  setup/product_packaging_usability/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1602 [14.0][FIX] stock_free_quantity, get only active variants to compute free_qty on template
  stock_free_quantity/models/product_template.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳, no stale

#1905 [13.0][ADD] stock_reserve_sale_mrp
  setup/stock_reserve_sale_mrp/odoo/addons/stock_reserve_sale_mrp
  setup/stock_reserve_sale_mrp/setup.py
  stock_reserve_sale_mrp/README.rst
  stock_reserve_sale_mrp/__init__.py
  stock_reserve_sale_mrp/__manifest__.py
  stock_reserve_sale_mrp/tests/__init__.py
  stock_reserve_sale_mrp/tests/test_stock_reserve_sale_mrp.py
  stock_reserve_sale_mrp/wizard/__init__.py
  stock_reserve_sale_mrp/wizard/sale_stock_reserve.py
Labels: approved, bot is merging ⏳
