Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-07, with the labels that each got.

#1774 [14.0][IMP] stock_location_orderpoint: index and view
  stock_location_orderpoint/models/stock_move.py
  stock_location_orderpoint/readme/CONFIGURE.rst
  stock_location_orderpoint/views/menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#1781 [15.0][IMP] stock_inventory: do not delete inv adjustment groups if in process or done
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_move_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1748 [16.0][mig] account_move_line_product: Migration to 16.0
  account_move_line_product/README.rst
  account_move_line_product/__init__.py
  account_move_line_product/__manifest__.py
  account_move_line_product/i18n/account_move_line_product.pot
  account_move_line_product/i18n/ca.po
  account_move_line_product/i18n/cs_CZ.po
  account_move_line_product/i18n/de.po
  account_move_line_product/i18n/el_GR.po
  account_move_line_product/i18n/es.po
  account_move_line_product/i18n/es_ES.po
  account_move_line_product/i18n/eu.po
  account_move_line_product/i18n/fi.po
  account_move_line_product/i18n/fr.po
  account_move_line_product/i18n/fr_CH.po
  account_move_line_product/i18n/fr_FR.po
  account_move_line_product/i18n/gl.po
  account_move_line_product/i18n/hr.po
  account_move_line_product/i18n/hr_HR.po
  account_move_line_product/i18n/it.po
  account_move_line_product/i18n/nl.po
  account_move_line_product/i18n/nl_NL.po
  account_move_line_product/i18n/pt.po
  account_move_line_product/i18n/pt_BR.po
  account_move_line_product/i18n/ro.po
  account_move_line_product/i18n/ru.po
  account_move_line_product/i18n/sl.po
  account_move_line_product/i18n/tr.po
  account_move_line_product/i18n/tr_TR.po
  account_move_line_product/i18n/vi_VN.po
  account_move_line_product/i18n/zh_CN.po
  account_move_line_product/readme/CONTRIBUTORS.rst
  account_move_line_product/readme/DESCRIPTION.rst
  account_move_line_product/static/description/icon.png
  account_move_line_product/static/description/index.html
  account_move_line_product/views/account_move_line_view.xml
  setup/account_move_line_product/odoo/addons/account_move_line_product
  setup/account_move_line_product/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1787 [15.0][FIX] stock_orderpoint_generator: fix test test_errors
  stock_orderpoint_generator/tests/test_orderpoint_generator.py
Labels: bot is merging ⏳

#1753 [15.0][MIG] stock_reserve_rule: Migration to 15.0.
  setup/stock_reserve_rule/odoo/addons/stock_reserve_rule
  setup/stock_reserve_rule/setup.py
  stock_reserve_rule/README.rst
  stock_reserve_rule/__init__.py
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/data/demo/product_demo.xml
  stock_reserve_rule/data/demo/stock_inventory_demo.xml
  stock_reserve_rule/data/demo/stock_location_demo.xml
  stock_reserve_rule/data/demo/stock_picking_demo.xml
  stock_reserve_rule/data/demo/stock_reserve_rule_demo.xml
  stock_reserve_rule/i18n/stock_reserve_rule.pot
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_picking_type.py
  stock_reserve_rule/models/stock_quant.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/readme/CONFIGURE.rst
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/readme/DESCRIPTION.rst
  stock_reserve_rule/readme/USAGE.rst
  stock_reserve_rule/security/ir.model.access.csv
  stock_reserve_rule/security/stock_reserve_rule_security.xml
  stock_reserve_rule/static/description/icon.png
  stock_reserve_rule/static/description/index.html
  stock_reserve_rule/tests/__init__.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_reserve_rule/views/stock_reserve_rule_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1225 [13.0][FIX] stock_reserve_rule: allow removal strategy based on lots
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1790 [14.0][IMP] stock_picking_volume: Move _get_volume_for_qty to product.product
  stock_picking_volume/models/__init__.py
  stock_picking_volume/models/product_product.py
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/tests/test_stock_picking_volume.py
  stock_picking_volume_packaging/models/__init__.py
  stock_picking_volume_packaging/models/product_product.py
  stock_picking_volume_packaging/tests/test_stock_move_volume.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1791 [14.0][FW] stock_reserve_rule: removal strategy based on lots and/or owner
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: approved, bot is merging ⏳

#1789 [FIX] stock_quant_manual_assign
  stock_quant_manual_assign/wizard/assign_manual_quants.py
  stock_quant_manual_assign/wizard/assign_manual_quants_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1801 [14.0][ADD] stock_procurement_group_hook
  setup/stock_procurement_group_hook/odoo/addons/stock_procurement_group_hook
  setup/stock_procurement_group_hook/setup.py
  stock_procurement_group_hook/README.rst
  stock_procurement_group_hook/__init__.py
  stock_procurement_group_hook/__manifest__.py
  stock_procurement_group_hook/hooks.py
  stock_procurement_group_hook/models/__init__.py
  stock_procurement_group_hook/models/procurement_group.py
  stock_procurement_group_hook/readme/CONTRIBUTORS.rst
  stock_procurement_group_hook/readme/DESCRIPTION.rst
  stock_procurement_group_hook/static/description/icon.png
  stock_procurement_group_hook/static/description/index.html
Labels: approved, bot is merging ⏳
