Repository OCA/stock-logistics-warehouse, pull requests merged in 2023-11, with the labels that each got.

#1877 [UPD] Copier update + fixes
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  stock_move_auto_assign/models/stock_move.py
  stock_move_auto_assign_auto_release/models/stock_move.py
Labels: bot is merging ⏳

#1843 FIX stock_move_common_dest: calling _compute_common_dest_move_ids on …
  stock_move_common_dest/models/stock_move.py
  stock_move_common_dest/tests/test_move_common_dest.py
Labels: approved, bot is merging ⏳

#1870 [14.0][IMP] stock_quant_manual_assign: add assign_manual_quants_action button on stock move form view
  stock_quant_manual_assign/views/stock_move_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1844 [14.0][FIX] stock_orderpoint_origin: correct procurement_group field for pickings
  stock_orderpoint_origin/models/procurement_group.py
Labels: approved, bot is merging ⏳

#1653 [16.0][ADD] stock_picking_product_interchangeable
  setup/stock_picking_product_interchangeable/odoo/addons/stock_picking_product_interchangeable
  setup/stock_picking_product_interchangeable/setup.py
  stock_picking_product_interchangeable/README.rst
  stock_picking_product_interchangeable/__init__.py
  stock_picking_product_interchangeable/__manifest__.py
  stock_picking_product_interchangeable/demo/product_demo.xml
  stock_picking_product_interchangeable/demo/stock_demo.xml
  stock_picking_product_interchangeable/models/__init__.py
  stock_picking_product_interchangeable/models/product.py
  stock_picking_product_interchangeable/models/stock_move.py
  stock_picking_product_interchangeable/models/stock_picking.py
  stock_picking_product_interchangeable/models/stock_picking_type.py
  stock_picking_product_interchangeable/readme/CONFIGURATION.rst
  stock_picking_product_interchangeable/readme/DESCRIPTION.rst
  stock_picking_product_interchangeable/readme/USAGE.rst
  stock_picking_product_interchangeable/tests/__init__.py
  stock_picking_product_interchangeable/tests/common.py
  stock_picking_product_interchangeable/tests/test_product.py
  stock_picking_product_interchangeable/tests/test_stock_picking.py
  stock_picking_product_interchangeable/views/product_views.xml
  stock_picking_product_interchangeable/views/stock_picking_type_views.xml
  stock_picking_product_interchangeable/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1881 [15.0][UPD] dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  stock_reserve_rule/models/stock_reserve_rule.py
Labels: approved, bot is merging ⏳

#1831 [14.0][IMP] stock_reserve_rule: add full bin strategy
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: enhancement, bot is merging ⏳

#1885 [15.0][IMP] stock_request: Add option to use stock available
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/models/res_company.py
  stock_request/models/res_config_settings.py
  stock_request/models/stock_request.py
  stock_request/tests/test_stock_request.py
  stock_request/views/res_config_settings_views.xml
Labels: enhancement, bot is merging ⏳

#1884 [14.0][FIX] stock_available_mrp: Use correct bom for computation
  stock_available_mrp/models/product_product.py
  stock_available_mrp/readme/CONTRIBUTORS.rst
  stock_available_mrp/tests/test_potential_qty.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1634 [FIX] stock_available_base_exclude_location: Fix excluded locations domains
  stock_available_base_exclude_location/models/product_product.py
Labels: enhancement, needs review, bot is merging ⏳, stale

#1796 [16.0][MIG] stock_demand_estimate_matrix: Migration to 16.0
  setup/stock_demand_estimate_matrix/odoo/addons/stock_demand_estimate_matrix
  setup/stock_demand_estimate_matrix/setup.py
  stock_demand_estimate_matrix/README.rst
  stock_demand_estimate_matrix/__init__.py
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/i18n/stock_demand_estimate_matrix.pot
  stock_demand_estimate_matrix/models/__init__.py
  stock_demand_estimate_matrix/models/date_range.py
  stock_demand_estimate_matrix/models/stock_demand_estimate.py
  stock_demand_estimate_matrix/readme/CONTRIBUTORS.rst
  stock_demand_estimate_matrix/readme/DESCRIPTION.rst
  stock_demand_estimate_matrix/readme/INSTALL.rst
  stock_demand_estimate_matrix/readme/USAGE.rst
  stock_demand_estimate_matrix/security/ir.model.access.csv
  stock_demand_estimate_matrix/static/description/icon.png
  stock_demand_estimate_matrix/static/description/index.html
  stock_demand_estimate_matrix/tests/__init__.py
  stock_demand_estimate_matrix/tests/test_stock_demand_estimate.py
  stock_demand_estimate_matrix/views/date_range.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/wizards/__init__.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet_line.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard_view.xml
Labels: needs review, migration, bot is merging ⏳

#1889 [FIX] stock_available_unreserved: qty_available_not_res not computed in all cases.
  stock_available_unreserved/models/product_template.py
Labels: approved, bot is merging ⏳

#1890 [16.0][IMP] stock_picking_product_interchangeable
  stock_picking_product_interchangeable/README.rst
  stock_picking_product_interchangeable/__manifest__.py
  stock_picking_product_interchangeable/readme/CONFIGURE.md
  stock_picking_product_interchangeable/readme/CONTEXT.md
  stock_picking_product_interchangeable/readme/CONTRIBUTORS.md
  stock_picking_product_interchangeable/readme/DESCRIPTION.md
  stock_picking_product_interchangeable/readme/DESCRIPTION.rst
  stock_picking_product_interchangeable/readme/ROADMAP.md
  stock_picking_product_interchangeable/readme/USAGE.md
  stock_picking_product_interchangeable/readme/USAGE.rst
  stock_picking_product_interchangeable/static/description/banner.png
  stock_picking_product_interchangeable/static/description/index.html
  stock_picking_product_interchangeable/static/img/new_quotation.png
  stock_picking_product_interchangeable/static/img/op_type_setting.png
  stock_picking_product_interchangeable/static/img/picking_with_substitutes.png
  stock_picking_product_interchangeable/static/img/product_form.png
  stock_picking_product_interchangeable/static/img/product_qty.png
Labels: bot is merging ⏳

#1893 [14.0][I18N] stock_pull_list: add translations to UserError
  stock_pull_list/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1894 [16.0][FIX] account_move_line_stock_info: use full form width
  account_move_line_stock_info/views/stock_move_view.xml
Labels: approved, bot is merging ⏳

#1708 [14.0][IMP] stock_helper: development_status -> Stable
  stock_helper/README.rst
  stock_helper/__manifest__.py
  stock_helper/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1896 [14.0][FIX] stock_request_analytic: Adding the correct groups to the views to avoid permissions errors
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/analytic_views.xml
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
Labels: approved, bot is merging ⏳

#1897 [15.0][FIX] stock_request_analytic: Adding the correct groups to the views to avoid permissions errors
  stock_request_analytic/tests/test_stock_request_analytic.py
  stock_request_analytic/views/analytic_views.xml
  stock_request_analytic/views/stock_request_order_views.xml
  stock_request_analytic/views/stock_request_views.xml
Labels: approved, bot is merging ⏳
