Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-11, with the labels that each got.

#2185 [15.0][UPD] stock_request*: explicitly assign maintainers
  stock_request/README.rst
  stock_request/__manifest__.py
  stock_request/static/description/index.html
  stock_request_analytic/README.rst
  stock_request_analytic/__manifest__.py
  stock_request_analytic/static/description/index.html
  stock_request_kanban/README.rst
  stock_request_kanban/__manifest__.py
  stock_request_kanban/static/description/index.html
  stock_request_mrp/README.rst
  stock_request_mrp/__manifest__.py
  stock_request_mrp/static/description/index.html
  stock_request_purchase/README.rst
  stock_request_purchase/__manifest__.py
  stock_request_purchase/static/description/index.html
  stock_request_tier_validation/README.rst
  stock_request_tier_validation/__manifest__.py
  stock_request_tier_validation/static/description/index.html
Labels: bot is merging ⏳

#2192 [15.0][FIX] stock_secondary_unit: Error when user try to select a secondary uom without product in sale order line
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1909 [15.0][FIX] stock_secondary_unit: Secondary uom qty is not updated when stock moves are merged
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/models/stock_rule.py
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#2193 [16][FIX] stock_secondary_unit: Error when user try to select a secondary uom without product in picking operations
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: bot is merging ⏳

#2194 [18.0][MIG] stock_warehouse_calendar: Migration to 18.0
  stock_warehouse_calendar/README.rst
  stock_warehouse_calendar/__init__.py
  stock_warehouse_calendar/__manifest__.py
  stock_warehouse_calendar/i18n/ca.po
  stock_warehouse_calendar/i18n/es.po
  stock_warehouse_calendar/i18n/it.po
  stock_warehouse_calendar/i18n/stock_warehouse_calendar.pot
  stock_warehouse_calendar/i18n/zh_CN.po
  stock_warehouse_calendar/models/__init__.py
  stock_warehouse_calendar/models/stock_rule.py
  stock_warehouse_calendar/models/stock_warehouse.py
  stock_warehouse_calendar/pyproject.toml
  stock_warehouse_calendar/readme/CONFIGURE.md
  stock_warehouse_calendar/readme/CONTRIBUTORS.md
  stock_warehouse_calendar/readme/DESCRIPTION.md
  stock_warehouse_calendar/readme/USAGE.md
  stock_warehouse_calendar/static/description/delay.gif
  stock_warehouse_calendar/static/description/icon.png
  stock_warehouse_calendar/static/description/index.html
  stock_warehouse_calendar/static/description/multi_step.gif
  stock_warehouse_calendar/static/description/warehouse_management.gif
  stock_warehouse_calendar/static/description/working_schedules.gif
  stock_warehouse_calendar/tests/__init__.py
  stock_warehouse_calendar/tests/test_stock_warehouse_calendar.py
  stock_warehouse_calendar/views/stock_warehouse_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2195 [15.0][FIX] stock_secondary_unit: Wrong secondary uom qty in extra move because is copied from origin
  stock_secondary_unit/models/stock_move.py
Labels: approved, bot is merging ⏳

#2180 [16.0][ADD] product_view_inventory_no_search_default_my_count
  product_view_inventory_no_search_default_my_count/README.rst
  product_view_inventory_no_search_default_my_count/__init__.py
  product_view_inventory_no_search_default_my_count/__manifest__.py
  product_view_inventory_no_search_default_my_count/models/__init__.py
  product_view_inventory_no_search_default_my_count/models/stock_quant.py
  product_view_inventory_no_search_default_my_count/readme/CONTEXT.rst
  product_view_inventory_no_search_default_my_count/readme/DESCRIPTION.rst
  product_view_inventory_no_search_default_my_count/static/description/index.html
  setup/product_view_inventory_no_search_default_my_count/odoo/addons/product_view_inventory_no_search_default_my_count
  setup/product_view_inventory_no_search_default_my_count/setup.py
Labels: needs review, approved, bot is merging ⏳

#2198 [14.0] Revert "[FIX] stock_request: Remove route_ids fields from requests"
  stock_request/models/stock_request_abstract.py
  stock_request/tests/test_stock_request.py
  stock_request/views/stock_request_order_views.xml
  stock_request/views/stock_request_views.xml
  stock_request_kanban/tests/test_kanban.py
  stock_request_kanban/views/stock_request_kanban_views.xml
Labels: bot is merging ⏳

#2201 [17.0][IMP] stock_warehouse_calendar: show only company compatible calendars
  stock_warehouse_calendar/models/stock_warehouse.py
Labels: approved, bot is merging ⏳

#2202 [18][FW][IMP] stock_warehouse_calendar: show only company compatible calendars
  stock_warehouse_calendar/models/stock_warehouse.py
Labels: bot is merging ⏳
