Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-02, with the labels that each got.

#1853 [14.0][ADD] stock_request_sequence_option
  setup/stock_request_sequence_option/odoo/addons/stock_request_sequence_option
  setup/stock_request_sequence_option/setup.py
  stock_request_sequence_option/README.rst
  stock_request_sequence_option/__init__.py
  stock_request_sequence_option/__manifest__.py
  stock_request_sequence_option/data/stock_request_sequence_option.xml
  stock_request_sequence_option/demo/stock_request_demo_options.xml
  stock_request_sequence_option/models/__init__.py
  stock_request_sequence_option/models/sequence_option.py
  stock_request_sequence_option/models/stock_request.py
  stock_request_sequence_option/models/stock_request_order.py
  stock_request_sequence_option/readme/CONTRIBUTORS.rst
  stock_request_sequence_option/readme/DESCRIPTION.rst
  stock_request_sequence_option/static/description/icon.png
  stock_request_sequence_option/static/description/index.html
  stock_request_sequence_option/tests/__init__.py
  stock_request_sequence_option/tests/test_stock_request_sequence_option.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1942 [15.0][FIX] stock_move_location: domain in multicompany
  stock_move_location/wizard/stock_move_location.py
Labels: approved, bot is merging ⏳

#1929 [14.0] [IMP] sale_stock_on_hand_popup: open in a popup
  sale_stock_on_hand_popup/README.rst
  sale_stock_on_hand_popup/__init__.py
  sale_stock_on_hand_popup/__manifest__.py
  sale_stock_on_hand_popup/models/__init__.py
  sale_stock_on_hand_popup/models/product.py
  sale_stock_on_hand_popup/models/product_product.py
  sale_stock_on_hand_popup/models/res_config_settings.py
  sale_stock_on_hand_popup/security/ir.model.access.csv
  sale_stock_on_hand_popup/security/security.xml
  sale_stock_on_hand_popup/static/description/index.html
  sale_stock_on_hand_popup/static/src/js/qty_at_date_widget.js
  sale_stock_on_hand_popup/static/src/js/stock_on_hand_widget.js
  sale_stock_on_hand_popup/static/src/xml/sale_stock.xml
  sale_stock_on_hand_popup/static/src/xml/stock_on_hand_widget.xml
  sale_stock_on_hand_popup/tests/test_sale_stock_on_hand_popup.py
  sale_stock_on_hand_popup/views/assets.xml
  sale_stock_on_hand_popup/views/res_config_settings_views.xml
  sale_stock_on_hand_popup/views/sale_order_views.xml
  sale_stock_on_hand_popup/wizards/__init__.py
  sale_stock_on_hand_popup/wizards/product_quant_wizard.py
  sale_stock_on_hand_popup/wizards/product_quant_wizard_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1948 [15.0][IMP] stock_secondary_unit: Make readonly secondary qty field in some states
  stock_secondary_unit/views/stock_move_views.xml
Labels: approved, bot is merging ⏳

#1950 [FIX] stock_mts_mto_rule: Don't use current company to create route
  stock_mts_mto_rule/data/stock_data.xml
Labels: bot is merging ⏳

#1680 [16.0] stock_picking_volume: Speedup install and avoid useless recompute
  stock_picking_volume/__init__.py
  stock_picking_volume/__manifest__.py
  stock_picking_volume/hooks.py
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/models/stock_picking.py
Labels: enhancement, needs review, bot is merging ⏳, stale
