Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-12, with the labels that each got.

#1997 [15.0][IMP]stock_cycle_count: several improvements
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/__init__.py
  stock_cycle_count/models/stock_cycle_count.py
  stock_cycle_count/models/stock_cycle_count_rule.py
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/models/stock_location.py
  stock_cycle_count/models/stock_move_line.py
  stock_cycle_count/models/stock_quant.py
  stock_cycle_count/models/stock_warehouse.py
  stock_cycle_count/security/security.xml
  stock_cycle_count/static/description/index.html
  stock_cycle_count/tests/test_stock_cycle_count.py
  stock_cycle_count/views/stock_cycle_count_view.xml
  stock_cycle_count/views/stock_inventory_view.xml
  stock_cycle_count/views/stock_move_line_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2206 [17.0] [MIG] stock_quant_reservation_info: Migration to 17.0
  stock_quant_reservation_info/README.rst
  stock_quant_reservation_info/__init__.py
  stock_quant_reservation_info/__manifest__.py
  stock_quant_reservation_info/i18n/it.po
  stock_quant_reservation_info/i18n/stock_quant_reservation_info.pot
  stock_quant_reservation_info/models/__init__.py
  stock_quant_reservation_info/models/stock_move_line.py
  stock_quant_reservation_info/models/stock_quant.py
  stock_quant_reservation_info/pyproject.toml
  stock_quant_reservation_info/readme/CONTRIBUTORS.md
  stock_quant_reservation_info/readme/DESCRIPTION.md
  stock_quant_reservation_info/readme/USAGE.md
  stock_quant_reservation_info/static/description/icon.png
  stock_quant_reservation_info/static/description/index.html
  stock_quant_reservation_info/views/stock_move_line.xml
  stock_quant_reservation_info/views/stock_quant.xml
Labels: needs review, migration, bot is merging ⏳

#2169 [16.0][IMP] stock_cycle_count: some improvements
  stock_cycle_count/__manifest__.py
  stock_cycle_count/models/__init__.py
  stock_cycle_count/models/stock_cycle_count.py
  stock_cycle_count/models/stock_cycle_count_rule.py
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/models/stock_location.py
  stock_cycle_count/models/stock_move_line.py
  stock_cycle_count/models/stock_quant.py
  stock_cycle_count/models/stock_warehouse.py
  stock_cycle_count/security/security.xml
  stock_cycle_count/static/description/index.html
  stock_cycle_count/tests/test_stock_cycle_count.py
  stock_cycle_count/views/stock_cycle_count_view.xml
  stock_cycle_count/views/stock_inventory_view.xml
  stock_cycle_count/views/stock_move_line_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2217 [16.0][MIG] stock_inventory_lockdown: Migration to 16.0
  setup/stock_inventory_lockdown/odoo/addons/stock_inventory_lockdown
  setup/stock_inventory_lockdown/setup.py
  stock_inventory_lockdown/README.rst
  stock_inventory_lockdown/__init__.py
  stock_inventory_lockdown/__manifest__.py
  stock_inventory_lockdown/i18n/ca.po
  stock_inventory_lockdown/i18n/cs_CZ.po
  stock_inventory_lockdown/i18n/de.po
  stock_inventory_lockdown/i18n/es.po
  stock_inventory_lockdown/i18n/es_ES.po
  stock_inventory_lockdown/i18n/es_MX.po
  stock_inventory_lockdown/i18n/fi.po
  stock_inventory_lockdown/i18n/fr.po
  stock_inventory_lockdown/i18n/gl.po
  stock_inventory_lockdown/i18n/hr.po
  stock_inventory_lockdown/i18n/it.po
  stock_inventory_lockdown/i18n/nl_NL.po
  stock_inventory_lockdown/i18n/pt.po
  stock_inventory_lockdown/i18n/pt_BR.po
  stock_inventory_lockdown/i18n/ro.po
  stock_inventory_lockdown/i18n/sl.po
  stock_inventory_lockdown/i18n/stock_inventory_lockdown.pot
  stock_inventory_lockdown/i18n/tr.po
  stock_inventory_lockdown/i18n/tr_TR.po
  stock_inventory_lockdown/i18n/vi_VN.po
  stock_inventory_lockdown/i18n/zh_CN.po
  stock_inventory_lockdown/models/__init__.py
  stock_inventory_lockdown/models/stock_inventory.py
  stock_inventory_lockdown/models/stock_location.py
  stock_inventory_lockdown/models/stock_move_line.py
  stock_inventory_lockdown/readme/CONTRIBUTORS.rst
  stock_inventory_lockdown/readme/DESCRIPTION.rst
  stock_inventory_lockdown/readme/USAGE.rst
  stock_inventory_lockdown/static/description/icon.png
  stock_inventory_lockdown/static/description/index.html
  stock_inventory_lockdown/static/images/move_error.png
  stock_inventory_lockdown/tests/__init__.py
  stock_inventory_lockdown/tests/test_stock_inventory_lockdown.py
Labels: needs review, approved, migration, bot is merging ⏳

#1966 [16.0][IMP] stock_inventory_discrepancy: add configuration for enabling discrepancy check
  stock_inventory_discrepancy/README.rst
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/models/__init__.py
  stock_inventory_discrepancy/models/res_company.py
  stock_inventory_discrepancy/models/res_config_settings.py
  stock_inventory_discrepancy/models/stock_quant.py
  stock_inventory_discrepancy/readme/CONFIGURE.rst
  stock_inventory_discrepancy/readme/DESCRIPTION.rst
  stock_inventory_discrepancy/static/description/index.html
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2220 [17.0][FIX] stock_helper: fix tests based on modules installed
  stock_helper/tests/test_location_source_from_route.py
Labels: approved, bot is merging ⏳

#2104 [16.0][MIG] stock_vlm_mgmt_kardex: Migration to 16.0
  setup/stock_vlm_mgmt_kardex/odoo/addons/stock_vlm_mgmt_kardex
  setup/stock_vlm_mgmt_kardex/setup.py
  stock_vlm_mgmt_kardex/README.rst
  stock_vlm_mgmt_kardex/__init__.py
  stock_vlm_mgmt_kardex/__manifest__.py
  stock_vlm_mgmt_kardex/models/__init__.py
  stock_vlm_mgmt_kardex/models/kardex_request.py
  stock_vlm_mgmt_kardex/models/stock_location.py
  stock_vlm_mgmt_kardex/readme/CONTRIBUTORS.rst
  stock_vlm_mgmt_kardex/readme/DESCRIPTION.rst
  stock_vlm_mgmt_kardex/static/description/index.html
Labels: bot is merging ⏳, stale

#2212 [17.0][MIG] stock_quant_reservation_info_mrp: Migration to 17.0
  stock_helper/tests/test_location_source_from_route.py
  stock_quant_reservation_info_mrp/README.rst
  stock_quant_reservation_info_mrp/__init__.py
  stock_quant_reservation_info_mrp/__manifest__.py
  stock_quant_reservation_info_mrp/i18n/it.po
  stock_quant_reservation_info_mrp/i18n/stock_quant_reservation_info_mrp.pot
  stock_quant_reservation_info_mrp/models/__init__.py
  stock_quant_reservation_info_mrp/models/stock_move_line.py
  stock_quant_reservation_info_mrp/pyproject.toml
  stock_quant_reservation_info_mrp/readme/CONTRIBUTORS.md
  stock_quant_reservation_info_mrp/readme/DESCRIPTION.md
  stock_quant_reservation_info_mrp/readme/USAGE.md
  stock_quant_reservation_info_mrp/static/description/icon.png
  stock_quant_reservation_info_mrp/static/description/index.html
  stock_quant_reservation_info_mrp/views/stock_move_line.xml
Labels: needs review, migration, bot is merging ⏳

#2221 [18.0][MIG] account_move_line_stock_info
  account_move_line_stock_info/README.rst
  account_move_line_stock_info/__init__.py
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/i18n/account_move_line_stock_info.pot
  account_move_line_stock_info/i18n/ar.po
  account_move_line_stock_info/i18n/bs.po
  account_move_line_stock_info/i18n/ca.po
  account_move_line_stock_info/i18n/cs.po
  account_move_line_stock_info/i18n/cs_CZ.po
  account_move_line_stock_info/i18n/de.po
  account_move_line_stock_info/i18n/en_GB.po
  account_move_line_stock_info/i18n/es.po
  account_move_line_stock_info/i18n/es_CR.po
  account_move_line_stock_info/i18n/es_EC.po
  account_move_line_stock_info/i18n/es_MX.po
  account_move_line_stock_info/i18n/fi.po
  account_move_line_stock_info/i18n/fr.po
  account_move_line_stock_info/i18n/fr_CH.po
  account_move_line_stock_info/i18n/gl.po
  account_move_line_stock_info/i18n/hr.po
  account_move_line_stock_info/i18n/hr_HR.po
  account_move_line_stock_info/i18n/hu.po
  account_move_line_stock_info/i18n/it.po
  account_move_line_stock_info/i18n/ja.po
  account_move_line_stock_info/i18n/lt.po
  account_move_line_stock_info/i18n/mk.po
  account_move_line_stock_info/i18n/mn.po
  account_move_line_stock_info/i18n/nb.po
  account_move_line_stock_info/i18n/nb_NO.po
  account_move_line_stock_info/i18n/nl.po
  account_move_line_stock_info/i18n/nl_BE.po
  account_move_line_stock_info/i18n/nl_NL.po
  account_move_line_stock_info/i18n/pt.po
  account_move_line_stock_info/i18n/pt_BR.po
  account_move_line_stock_info/i18n/pt_PT.po
  account_move_line_stock_info/i18n/ro.po
  account_move_line_stock_info/i18n/ru.po
  account_move_line_stock_info/i18n/sl.po
  account_move_line_stock_info/i18n/sv.po
  account_move_line_stock_info/i18n/tr.po
  account_move_line_stock_info/i18n/tr_TR.po
  account_move_line_stock_info/i18n/vi_VN.po
  account_move_line_stock_info/i18n/zh_CN.po
  account_move_line_stock_info/i18n/zh_TW.po
  account_move_line_stock_info/models/__init__.py
  account_move_line_stock_info/models/account_move_line.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/pyproject.toml
  account_move_line_stock_info/readme/CONTRIBUTORS.md
  account_move_line_stock_info/readme/DESCRIPTION.md
  account_move_line_stock_info/readme/USAGE.md
  account_move_line_stock_info/security/ir.model.access.csv
  account_move_line_stock_info/static/description/icon.png
  account_move_line_stock_info/static/description/index.html
  account_move_line_stock_info/tests/__init__.py
  account_move_line_stock_info/tests/test_account_move_line_stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
  account_move_line_stock_info/views/stock_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2204 [16.0][IMP] stock_product_qty_by_packaging: detailed_operation_tree view
  stock_product_qty_by_packaging/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#2078 [16.0][FIX] stock_location_zone: fix kind
  stock_location_zone/__manifest__.py
  stock_location_zone/models/stock_location.py
Labels: needs review, approved, bot is merging ⏳

#2211 [16.0][IMP] stock_location_product_restriction: Don't check zero quants
  stock_location_product_restriction/models/stock_location.py
  stock_location_product_restriction/models/stock_quant.py
  stock_location_product_restriction/tests/test_stock_location.py
  stock_location_product_restriction/tests/test_stock_move.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2200 [16.0][ADD] stock_location_pending_move
  setup/stock_location_pending_move/odoo/addons/stock_location_pending_move
  setup/stock_location_pending_move/setup.py
  stock_location_pending_move/README.rst
  stock_location_pending_move/__init__.py
  stock_location_pending_move/__manifest__.py
  stock_location_pending_move/models/__init__.py
  stock_location_pending_move/models/stock_location.py
  stock_location_pending_move/readme/CONFIGURE.md
  stock_location_pending_move/readme/CONTEXT.md
  stock_location_pending_move/readme/CONTRIBUTORS.md
  stock_location_pending_move/readme/DESCRIPTION.md
  stock_location_pending_move/readme/USAGE.md
  stock_location_pending_move/static/description/icon.png
  stock_location_pending_move/static/description/index.html
  stock_location_pending_move/static/description/pending_moves.png
  stock_location_pending_move/static/description/pending_moves_detail.png
  stock_location_pending_move/tests/__init__.py
  stock_location_pending_move/tests/test_location_pending_move.py
  stock_location_pending_move/views/stock_location.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
