Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-10, with the labels that each got.

#2165 [17.0][MIG] stock_location_zone
  stock_location_zone/README.rst
  stock_location_zone/__init__.py
  stock_location_zone/__manifest__.py
  stock_location_zone/i18n/es.po
  stock_location_zone/i18n/it.po
  stock_location_zone/i18n/stock_location_zone.pot
  stock_location_zone/i18n/zh_CN.po
  stock_location_zone/models/__init__.py
  stock_location_zone/models/stock_location.py
  stock_location_zone/pyproject.toml
  stock_location_zone/readme/CONTRIBUTORS.md
  stock_location_zone/readme/CREDITS.md
  stock_location_zone/readme/DESCRIPTION.md
  stock_location_zone/static/description/icon.png
  stock_location_zone/static/description/index.html
  stock_location_zone/tests/__init__.py
  stock_location_zone/tests/test_stock_location_zone.py
  stock_location_zone/views/stock_location.xml
Labels: needs review, approved, migration, ready to merge, merged 🎉

#1794 [MIG][16.0] stock_reserve_rule
  setup/stock_reserve_rule/odoo/addons/stock_reserve_rule
  setup/stock_reserve_rule/setup.py
  stock_reserve_rule/README.rst
  stock_reserve_rule/__init__.py
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/data/demo/product_demo.xml
  stock_reserve_rule/data/demo/stock_location_demo.xml
  stock_reserve_rule/data/demo/stock_picking_demo.xml
  stock_reserve_rule/data/demo/stock_reserve_rule_demo.xml
  stock_reserve_rule/i18n/stock_reserve_rule.pot
  stock_reserve_rule/models/__init__.py
  stock_reserve_rule/models/stock_move.py
  stock_reserve_rule/models/stock_picking_type.py
  stock_reserve_rule/models/stock_quant.py
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/readme/CONFIGURE.rst
  stock_reserve_rule/readme/CONTRIBUTORS.rst
  stock_reserve_rule/readme/DESCRIPTION.rst
  stock_reserve_rule/readme/USAGE.rst
  stock_reserve_rule/security/ir.model.access.csv
  stock_reserve_rule/security/stock_reserve_rule_security.xml
  stock_reserve_rule/static/description/icon.png
  stock_reserve_rule/static/description/index.html
  stock_reserve_rule/tests/__init__.py
  stock_reserve_rule/tests/test_reserve_rule.py
  stock_reserve_rule/views/stock_reserve_rule_views.xml
Labels: help wanted, needs fixing, approved, migration, bot is merging ⏳, stale

#2068 [16.0][MIG] stock_location_package_restriction
  setup/stock_location_package_restriction/odoo/addons/stock_location_package_restriction
  setup/stock_location_package_restriction/setup.py
  stock_location_package_restriction/README.rst
  stock_location_package_restriction/__init__.py
  stock_location_package_restriction/__manifest__.py
  stock_location_package_restriction/i18n/it.po
  stock_location_package_restriction/i18n/stock_location_package_restriction.pot
  stock_location_package_restriction/models/__init__.py
  stock_location_package_restriction/models/stock_location.py
  stock_location_package_restriction/models/stock_move.py
  stock_location_package_restriction/readme/CONTRIBUTORS.rst
  stock_location_package_restriction/readme/DESCRIPTION.rst
  stock_location_package_restriction/readme/USAGE.rst
  stock_location_package_restriction/static/description/icon.png
  stock_location_package_restriction/static/description/index.html
  stock_location_package_restriction/tests/__init__.py
  stock_location_package_restriction/tests/common.py
  stock_location_package_restriction/tests/test_stock_inventory.py
  stock_location_package_restriction/tests/test_stock_location.py
  stock_location_package_restriction/tests/test_stock_move.py
  stock_location_package_restriction/tests/test_stock_move_line.py
  stock_location_package_restriction/views/stock_location.xml
Labels: bot is merging ⏳

#2032 [14][FIX] stock_mts_mto_rule: Source location of initial rule
  stock_mts_mto_rule/models/stock_rule.py
  stock_mts_mto_rule/tests/common.py
  stock_mts_mto_rule/tests/test_mto_mts_route.py
Labels: approved, ready to merge, bot is merging ⏳

#1646 [16.0][ADD] stock_scrap_location_default
  setup/stock_scrap_location_default/odoo/addons/stock_scrap_location_default
  setup/stock_scrap_location_default/setup.py
  stock_scrap_location_default/README.rst
  stock_scrap_location_default/__init__.py
  stock_scrap_location_default/__manifest__.py
  stock_scrap_location_default/models/__init__.py
  stock_scrap_location_default/models/res_company.py
  stock_scrap_location_default/models/res_config_settings.py
  stock_scrap_location_default/models/stock_scrap.py
  stock_scrap_location_default/readme/CONFIGURE.rst
  stock_scrap_location_default/readme/CONTRIBUTORS.rst
  stock_scrap_location_default/readme/DESCRIPTION.rst
  stock_scrap_location_default/readme/ROADMAP.rst
  stock_scrap_location_default/static/description/icon.png
  stock_scrap_location_default/static/description/index.html
  stock_scrap_location_default/tests/__init__.py
  stock_scrap_location_default/tests/test_scrap_location_default.py
  stock_scrap_location_default/views/res_config_settings.xml
Labels: needs review, approved, bot is merging ⏳

#1917 [14.0][IMP] stock_helper: Getting closest warehouse for record set
  stock_helper/models/stock_location.py
Labels: bot is merging ⏳

#1985 16.0 mig stock secondary unit
  setup/stock_secondary_unit/odoo/addons/stock_secondary_unit
  setup/stock_secondary_unit/setup.py
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/fi.po
  stock_secondary_unit/i18n/it.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product_product.py
  stock_secondary_unit/models/product_template.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/models/stock_product_secondary_unit_mixin.py
  stock_secondary_unit/readme/CONTRIBUTORS.rst
  stock_secondary_unit/readme/DESCRIPTION.rst
  stock_secondary_unit/readme/USAGE.rst
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: bot is merging ⏳

#2007 [15.0][MIG] stock_location_position: Migration to 15.0
  setup/stock_location_position/odoo/addons/stock_location_position
  setup/stock_location_position/setup.py
  stock_location_position/README.rst
  stock_location_position/__init__.py
  stock_location_position/__manifest__.py
  stock_location_position/i18n/stock_location_position.pot
  stock_location_position/models/__init__.py
  stock_location_position/models/stock_location.py
  stock_location_position/readme/CONTRIBUTORS.rst
  stock_location_position/readme/CREDITS.rst
  stock_location_position/readme/DESCRIPTION.rst
  stock_location_position/static/description/icon.png
  stock_location_position/static/description/index.html
  stock_location_position/views/stock_location.xml
Labels: approved, bot is merging ⏳

#1923 [16][MIG] Migrate stock_warehouse_relationship
  setup/stock_warehouse_relationship/odoo/addons/stock_warehouse_relationship
  setup/stock_warehouse_relationship/setup.py
  stock_warehouse_relationship/README.rst
  stock_warehouse_relationship/__init__.py
  stock_warehouse_relationship/__manifest__.py
  stock_warehouse_relationship/i18n/fr.po
  stock_warehouse_relationship/i18n/stock_warehouse_relationship.pot
  stock_warehouse_relationship/models/__init__.py
  stock_warehouse_relationship/models/stock_move.py
  stock_warehouse_relationship/models/stock_move_line.py
  stock_warehouse_relationship/models/stock_picking.py
  stock_warehouse_relationship/models/stock_quant.py
  stock_warehouse_relationship/models/stock_quant_package.py
  stock_warehouse_relationship/readme/CONTRIBUTORS.rst
  stock_warehouse_relationship/readme/DESCRIPTION.rst
  stock_warehouse_relationship/static/description/index.html
  stock_warehouse_relationship/tests/__init__.py
  stock_warehouse_relationship/tests/test_warehouse_relationship.py
  stock_warehouse_relationship/views/stock_move.xml
  stock_warehouse_relationship/views/stock_move_line.xml
  stock_warehouse_relationship/views/stock_quant.xml
  stock_warehouse_relationship/views/stock_quant_package.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2075 [16.0][FIX] stock_location_product_restriction: Ensure restriction is alway…
  stock_location_product_restriction/i18n/fr.po
  stock_location_product_restriction/models/__init__.py
  stock_location_product_restriction/models/stock_location.py
  stock_location_product_restriction/models/stock_quant.py
  stock_location_product_restriction/tests/test_stock_location.py
  stock_location_product_restriction/tests/test_stock_move.py
Labels: needs review, approved, bot is merging ⏳

#2023 [15.0] [MIG] stock_search_supplierinfo_code: Migration to 15.0
  setup/stock_search_supplierinfo_code/odoo/addons/stock_search_supplierinfo_code
  setup/stock_search_supplierinfo_code/setup.py
  stock_search_supplierinfo_code/README.rst
  stock_search_supplierinfo_code/__init__.py
  stock_search_supplierinfo_code/__manifest__.py
  stock_search_supplierinfo_code/i18n/it.po
  stock_search_supplierinfo_code/i18n/stock_search_supplierinfo_code.pot
  stock_search_supplierinfo_code/readme/CONTRIBUTORS.rst
  stock_search_supplierinfo_code/readme/DESCRIPTION.rst
  stock_search_supplierinfo_code/static/description/icon.png
  stock_search_supplierinfo_code/static/description/index.html
  stock_search_supplierinfo_code/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#2151 [16.0][FIX] stock_picking_volume: pre_init_hook, replace column type from `numeric` to `double precision`
  stock_picking_volume/hooks.py
Labels: approved, ready to merge, bot is merging ⏳

#2171 [16.0][IMP] stock_secondary_unit: make the secondary unit and secondary quantity fields optional
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2097 [17.0][MIG] product route profile: Migration to 17.0
  product_route_profile/README.rst
  product_route_profile/__init__.py
  product_route_profile/__manifest__.py
  product_route_profile/hooks.py
  product_route_profile/i18n/fr.po
  product_route_profile/i18n/nl.po
  product_route_profile/i18n/product_route_profile.pot
  product_route_profile/models/__init__.py
  product_route_profile/models/product_template.py
  product_route_profile/models/route_profile.py
  product_route_profile/pyproject.toml
  product_route_profile/readme/CONTRIBUTORS.md
  product_route_profile/readme/DESCRIPTION.md
  product_route_profile/readme/ROADMAP.md
  product_route_profile/readme/USAGE.md
  product_route_profile/security/ir.model.access.csv
  product_route_profile/static/description/icon.png
  product_route_profile/static/description/icon.svg
  product_route_profile/static/description/index.html
  product_route_profile/tests/__init__.py
  product_route_profile/tests/test_product_route_profile.py
  product_route_profile/views/product_template.xml
  product_route_profile/views/route_profile.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2091 [16.0][ADD] stock_package_type_category
  setup/stock_package_type_category/odoo/addons/stock_package_type_category
  setup/stock_package_type_category/setup.py
  stock_package_type_category/README.rst
  stock_package_type_category/__init__.py
  stock_package_type_category/__manifest__.py
  stock_package_type_category/demo/stock_package_type_category.xml
  stock_package_type_category/models/__init__.py
  stock_package_type_category/models/stock_package_type.py
  stock_package_type_category/models/stock_package_type_category.py
  stock_package_type_category/readme/CONFIGURE.md
  stock_package_type_category/readme/CONTEXT.md
  stock_package_type_category/readme/CONTRIBUTORS.md
  stock_package_type_category/readme/DESCRIPTION.md
  stock_package_type_category/security/stock_package_type_category.xml
  stock_package_type_category/static/description/icon.png
  stock_package_type_category/static/description/index.html
  stock_package_type_category/tests/__init__.py
  stock_package_type_category/tests/test_stock_package_type_category.py
  stock_package_type_category/views/stock_package_type.xml
  stock_package_type_category/views/stock_package_type_category.xml
Labels: needs review, bot is merging ⏳

#1939 [14.0][FIX] product_route_profile fix view
  product_route_profile/tests/test_product_route_profile.py
  product_route_profile/views/product_template.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2173 [18.0][MIG] stock_packaging_calculator: Migration to 18.0
  stock_packaging_calculator/README.rst
  stock_packaging_calculator/__init__.py
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/i18n/it.po
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/pyproject.toml
  stock_packaging_calculator/readme/CONTRIBUTORS.md
  stock_packaging_calculator/readme/CREDITS.md
  stock_packaging_calculator/readme/DESCRIPTION.md
  stock_packaging_calculator/readme/ROADMAP.md
  stock_packaging_calculator/readme/USAGE.md
  stock_packaging_calculator/static/description/icon.png
  stock_packaging_calculator/static/description/index.html
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/models.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator/tests/test_product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/utils.py
  test-requirements.txt
Labels: needs review, approved, migration, bot is merging ⏳

#2174 [16.0][IMP] stock_picking_volume: add volume and uom to tree view
  stock_picking_volume/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#2177 [16.0][FIX] stock_secondary_unit: use @api.model_create_multi decorator in create method of StockMoveLine
  stock_secondary_unit/models/stock_move.py
Labels: enhancement, approved, bot is merging ⏳

#2175 [17.0][FW] [14.0][REF] s_packaging_calculator: remove unneeded &nbsp; constant
  stock_packaging_calculator/models/product.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2041 [17.0][MIG] stock_demand_estimate_matrix
  stock_demand_estimate_matrix/README.rst
  stock_demand_estimate_matrix/__init__.py
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/i18n/it.po
  stock_demand_estimate_matrix/i18n/stock_demand_estimate_matrix.pot
  stock_demand_estimate_matrix/models/__init__.py
  stock_demand_estimate_matrix/models/date_range.py
  stock_demand_estimate_matrix/models/stock_demand_estimate.py
  stock_demand_estimate_matrix/pyproject.toml
  stock_demand_estimate_matrix/readme/CONTRIBUTORS.md
  stock_demand_estimate_matrix/readme/DESCRIPTION.md
  stock_demand_estimate_matrix/readme/INSTALL.md
  stock_demand_estimate_matrix/readme/USAGE.md
  stock_demand_estimate_matrix/security/ir.model.access.csv
  stock_demand_estimate_matrix/static/description/icon.png
  stock_demand_estimate_matrix/static/description/index.html
  stock_demand_estimate_matrix/tests/__init__.py
  stock_demand_estimate_matrix/tests/test_stock_demand_estimate.py
  stock_demand_estimate_matrix/views/date_range.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/wizards/__init__.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet_line.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
