Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-08, with the labels that each got.

#2123 [17.0][MIG] stock_archive_constraint: Migration to 17.0
  stock_archive_constraint/README.rst
  stock_archive_constraint/__init__.py
  stock_archive_constraint/__manifest__.py
  stock_archive_constraint/i18n/es.po
  stock_archive_constraint/i18n/it.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/__init__.py
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/stock_location.py
  stock_archive_constraint/pyproject.toml
  stock_archive_constraint/readme/CONTRIBUTORS.md
  stock_archive_constraint/readme/DESCRIPTION.md
  stock_archive_constraint/readme/USAGE.md
  stock_archive_constraint/static/description/icon.png
  stock_archive_constraint/static/description/index.html
  stock_archive_constraint/tests/__init__.py
  stock_archive_constraint/tests/test_location_archive_constraint.py
Labels: approved, bot is merging ⏳

#2094 [16.0][MIG] base_product_merge : Migration to 16.0
  base_product_merge/README.rst
  base_product_merge/__init__.py
  base_product_merge/__manifest__.py
  base_product_merge/i18n/base_product_merge.pot
  base_product_merge/readme/CONFIGURE.rst
  base_product_merge/readme/CONTRIBUTORS.rst
  base_product_merge/readme/DESCRIPTION.rst
  base_product_merge/readme/USAGE.rst
  base_product_merge/security/ir.model.access.csv
  base_product_merge/security/res_groups.xml
  base_product_merge/static/description/icon.png
  base_product_merge/static/description/index.html
  base_product_merge/tests/__init__.py
  base_product_merge/tests/test_base_product_merge.py
  base_product_merge/wizard/__init__.py
  base_product_merge/wizard/base_product_merge.py
  base_product_merge/wizard/base_product_merge_view.xml
  requirements.txt
  setup/base_product_merge/odoo/addons/base_product_merge
  setup/base_product_merge/setup.py
Labels: approved, bot is merging ⏳

#2120 [15.0][FIX] stock_inventory: Resolve error when applying inventory with multiple adjustments in the same location for different products
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
Labels: approved, ready to merge, bot is merging ⏳

#2128 [16.0][FWP][FIX] stock_inventory:Resolve error when applying inventory with multiple adjustments in the same location
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
Labels: approved, bot is merging ⏳

#2133 [17.0][FWP][FIX] stock_inventory: Resolve error when applying inventory with multiple adjustments in the same location
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
Labels: approved, bot is merging ⏳

#2132 [17.0][MIG] base_product_merge: Migration to 17.0
  base_product_merge/README.rst
  base_product_merge/__init__.py
  base_product_merge/__manifest__.py
  base_product_merge/i18n/base_product_merge.pot
  base_product_merge/pyproject.toml
  base_product_merge/readme/CONFIGURE.md
  base_product_merge/readme/CONTRIBUTORS.md
  base_product_merge/readme/DESCRIPTION.md
  base_product_merge/readme/USAGE.md
  base_product_merge/security/ir.model.access.csv
  base_product_merge/security/res_groups.xml
  base_product_merge/static/description/icon.png
  base_product_merge/static/description/index.html
  base_product_merge/tests/__init__.py
  base_product_merge/tests/test_base_product_merge.py
  base_product_merge/wizard/__init__.py
  base_product_merge/wizard/base_product_merge.py
  base_product_merge/wizard/base_product_merge_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#2122 [14.0][IMP] stock_move_auto_assign_auto_release: Release release_ready moves together
  stock_move_auto_assign_auto_release/data/queue_job_function_data.xml
  stock_move_auto_assign_auto_release/models/product_product.py
  stock_move_auto_assign_auto_release/models/stock_move.py
  stock_move_auto_assign_auto_release/models/stock_picking.py
  stock_move_auto_assign_auto_release/readme/CONTRIBUTORS.rst
  stock_move_auto_assign_auto_release/tests/test_assign_auto_release.py
Labels: approved, ready to merge, bot is merging ⏳

#2137 [16.0][MIG] stock_quant_reservation_info
  setup/stock_quant_reservation_info/odoo/addons/stock_quant_reservation_info
  setup/stock_quant_reservation_info/setup.py
  stock_quant_reservation_info/README.rst
  stock_quant_reservation_info/__init__.py
  stock_quant_reservation_info/__manifest__.py
  stock_quant_reservation_info/i18n/it.po
  stock_quant_reservation_info/i18n/stock_quant_reservation_info.pot
  stock_quant_reservation_info/models/__init__.py
  stock_quant_reservation_info/models/stock_move_line.py
  stock_quant_reservation_info/models/stock_quant.py
  stock_quant_reservation_info/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info/readme/DESCRIPTION.rst
  stock_quant_reservation_info/readme/USAGE.rst
  stock_quant_reservation_info/static/description/icon.png
  stock_quant_reservation_info/static/description/index.html
  stock_quant_reservation_info/views/stock_move_line.xml
  stock_quant_reservation_info/views/stock_quant.xml
Labels: approved, bot is merging ⏳

#2138 [16.0][MIG] stock_quant_reservation_info_mrp
  setup/stock_quant_reservation_info_mrp/odoo/addons/stock_quant_reservation_info_mrp
  setup/stock_quant_reservation_info_mrp/setup.py
  stock_quant_reservation_info_mrp/README.rst
  stock_quant_reservation_info_mrp/__init__.py
  stock_quant_reservation_info_mrp/__manifest__.py
  stock_quant_reservation_info_mrp/i18n/it.po
  stock_quant_reservation_info_mrp/i18n/stock_quant_reservation_info_mrp.pot
  stock_quant_reservation_info_mrp/models/__init__.py
  stock_quant_reservation_info_mrp/models/stock_move_line.py
  stock_quant_reservation_info_mrp/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info_mrp/readme/DESCRIPTION.rst
  stock_quant_reservation_info_mrp/readme/USAGE.rst
  stock_quant_reservation_info_mrp/static/description/icon.png
  stock_quant_reservation_info_mrp/static/description/index.html
  stock_quant_reservation_info_mrp/views/stock_move_line.xml
Labels: approved, bot is merging ⏳

#2140 [16.0][FIX] stock_vlm_mgmt: location general inventory
  stock_vlm_mgmt/models/stock_location.py
  stock_vlm_mgmt/models/vlm_tray_cell_position_mixin.py
Labels: approved, bot is merging ⏳

#2059 [15.0][IMP] stock_inventory_discrepancy: Filter overdiscrepancy quants.
  stock_inventory_discrepancy/models/stock_quant.py
  stock_inventory_discrepancy/views/stock_quant_view.xml
Labels: approved, bot is merging ⏳

#2144 [15.0][FIX] stock_quant_reservation_info: fix location domain on action_reserved_moves
  stock_quant_reservation_info/models/stock_quant.py
Labels: bot is merging ⏳

#2143 [14.0][FIX] stock_quant_reservation_info: fix location domain on action_reserved_moves
  stock_quant_reservation_info/models/stock_quant.py
Labels: bot is merging ⏳
