Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-06, with the labels that each got.

#2065 [17.0][MIG] stock_removal_location_by_priority
  stock_removal_location_by_priority/README.rst
  stock_removal_location_by_priority/__init__.py
  stock_removal_location_by_priority/__manifest__.py
  stock_removal_location_by_priority/i18n/de.po
  stock_removal_location_by_priority/i18n/es.po
  stock_removal_location_by_priority/i18n/fi.po
  stock_removal_location_by_priority/i18n/fr.po
  stock_removal_location_by_priority/i18n/it.po
  stock_removal_location_by_priority/i18n/pt_BR.po
  stock_removal_location_by_priority/i18n/ro.po
  stock_removal_location_by_priority/i18n/sl.po
  stock_removal_location_by_priority/i18n/stock_removal_location_by_priority.pot
  stock_removal_location_by_priority/i18n/zh_CN.po
  stock_removal_location_by_priority/init_hook.py
  stock_removal_location_by_priority/models/__init__.py
  stock_removal_location_by_priority/models/res_config_settings.py
  stock_removal_location_by_priority/models/stock_location.py
  stock_removal_location_by_priority/models/stock_quant.py
  stock_removal_location_by_priority/pyproject.toml
  stock_removal_location_by_priority/readme/CONFIGURE.md
  stock_removal_location_by_priority/readme/CONTRIBUTORS.md
  stock_removal_location_by_priority/readme/DESCRIPTION.md
  stock_removal_location_by_priority/readme/USAGE.md
  stock_removal_location_by_priority/security/stock_security.xml
  stock_removal_location_by_priority/static/description/icon.png
  stock_removal_location_by_priority/static/description/index.html
  stock_removal_location_by_priority/tests/__init__.py
  stock_removal_location_by_priority/tests/test_stock_removal_location_by_priority.py
  stock_removal_location_by_priority/views/res_config_settings_views.xml
  stock_removal_location_by_priority/views/stock_location_view.xml
Labels: approved, bot is merging ⏳

#2064 [17.0][MIG] stock_inventory_discrepancy
  stock_inventory_discrepancy/README.rst
  stock_inventory_discrepancy/__init__.py
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/hooks.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/__init__.py
  stock_inventory_discrepancy/models/stock_location.py
  stock_inventory_discrepancy/models/stock_quant.py
  stock_inventory_discrepancy/models/stock_warehouse.py
  stock_inventory_discrepancy/pyproject.toml
  stock_inventory_discrepancy/readme/CONFIGURE.md
  stock_inventory_discrepancy/readme/CONTRIBUTORS.md
  stock_inventory_discrepancy/readme/DESCRIPTION.md
  stock_inventory_discrepancy/readme/USAGE.md
  stock_inventory_discrepancy/security/ir.model.access.csv
  stock_inventory_discrepancy/security/stock_inventory_discrepancy_security.xml
  stock_inventory_discrepancy/static/description/icon.png
  stock_inventory_discrepancy/static/description/index.html
  stock_inventory_discrepancy/tests/__init__.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_location_view.xml
  stock_inventory_discrepancy/views/stock_quant_view.xml
  stock_inventory_discrepancy/views/stock_warehouse_view.xml
  stock_inventory_discrepancy/wizards/__init__.py
  stock_inventory_discrepancy/wizards/confirm_discrepancy_wiz.py
  stock_inventory_discrepancy/wizards/confirm_discrepancy_wiz.xml
Labels: approved, bot is merging ⏳

#2069 [15.0][FIX] stock_inventory: warning on invalid tracking field
  stock_inventory/models/stock_inventory.py
Labels: approved, bot is merging ⏳

#2070 [FIX] stock_inventory: warning on invalid tracking field
  stock_inventory/models/stock_inventory.py
Labels: approved, bot is merging ⏳

#1959 [17.0][MIG] stock_helper
  stock_helper/README.rst
  stock_helper/__init__.py
  stock_helper/__manifest__.py
  stock_helper/i18n/hr.po
  stock_helper/i18n/it.po
  stock_helper/i18n/stock_helper.pot
  stock_helper/models/__init__.py
  stock_helper/models/stock_location.py
  stock_helper/pyproject.toml
  stock_helper/readme/CONTRIBUTORS.md
  stock_helper/readme/DESCRIPTION.md
  stock_helper/static/description/icon.png
  stock_helper/static/description/index.html
  stock_helper/tests/__init__.py
  stock_helper/tests/common.py
  stock_helper/tests/test_location_is_sublocation_of.py
  stock_helper/tests/test_location_source_from_route.py
Labels: approved, bot is merging ⏳

#2074 [11.0] Replace 'Camptocamp SA' with 'Camptocamp'
  stock_account_internal_move/__manifest__.py
  stock_putaway_method/__manifest__.py
  stock_putaway_product/__manifest__.py
  stock_putaway_same_location/__manifest__.py
Labels: enhancement

#2073 [12.0] Replace 'Camptocamp SA' with 'Camptocamp'
  stock_account_internal_move/__manifest__.py
  stock_putaway_method/__manifest__.py
Labels: enhancement

#1847 [14.0][FIX] stock_location_orderpoint_source_relocate
  stock_location_orderpoint/tests/common.py
  stock_location_orderpoint_source_relocate/__manifest__.py
  stock_location_orderpoint_source_relocate/models/__init__.py
  stock_location_orderpoint_source_relocate/models/stock_location_orderpoint.py
  stock_location_orderpoint_source_relocate/models/stock_move.py
  stock_location_orderpoint_source_relocate/readme/CONTRIBUTORS.rst
  stock_location_orderpoint_source_relocate/readme/DESCRIPTION.rst
  stock_location_orderpoint_source_relocate/tests/test_location_orderpoint.py
Labels: bot is merging ⏳, stale

#2081 [15.0][IMP] stock_cycle_count: preformance improvements
  stock_cycle_count/models/stock_cycle_count.py
  stock_cycle_count/models/stock_cycle_count_rule.py
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/models/stock_location.py
  stock_cycle_count/models/stock_warehouse.py
  stock_cycle_count/reports/report_stock_location_accuracy.py
  stock_cycle_count/tests/test_stock_cycle_count.py
Labels: approved, bot is merging ⏳

#1806 [16.0][MIG] stock_valuation_layer_total_value: Migration to 16.0 and modify test
  setup/stock_valuation_layer_total_value/odoo/addons/stock_valuation_layer_total_value
  setup/stock_valuation_layer_total_value/setup.py
  stock_valuation_layer_total_value/README.rst
  stock_valuation_layer_total_value/__init__.py
  stock_valuation_layer_total_value/__manifest__.py
  stock_valuation_layer_total_value/models/__init__.py
  stock_valuation_layer_total_value/models/stock_valuation_layer.py
  stock_valuation_layer_total_value/readme/CONTRIBUTORS.rst
  stock_valuation_layer_total_value/readme/DESCRIPTION.rst
  stock_valuation_layer_total_value/readme/USAGE.rst
  stock_valuation_layer_total_value/tests/__init__.py
  stock_valuation_layer_total_value/tests/test_stock_valuation_layer_total_value.py
  stock_valuation_layer_total_value/views/stock_valuation_layer.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2080 [15.0][IMP] stock_secondary_unit: make the secondary unit and secondary quantity fields optional
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: enhancement, approved, bot is merging ⏳

#2087 [16.0][FIX] stock_cycle_count: removed some asserts for AccessError, stock_inventory: security groups
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/tests/test_stock_cycle_count.py
  stock_inventory/security/ir.model.access.csv
Labels: enhancement, needs review, approved, bot is merging ⏳

#2088 [15.0][FIX] stock_cycle_count: removed some asserts for AccessError, stock_inventory: security groups
  stock_cycle_count/models/stock_inventory.py
  stock_cycle_count/tests/test_stock_cycle_count.py
  stock_inventory/security/ir.model.access.csv
Labels: bot is merging ⏳

#2084 [15.0][BKP][IMP] stock_inventory: various fixes
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/stock_inventory.xml
Labels: bot is merging ⏳

#2017 [16.0][IMP] stock_inventory: various fixes
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/stock_inventory.xml
Labels: approved, bot is merging ⏳, Pending to Fwport

#2021 [15.0][IMP] stock_inventory: be able to do adjustments in same location but for different products
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
Labels: approved, bot is merging ⏳

#2089 [16.0][IMP] stock_inventory: be able to do adjustments in same location but for different products
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
Labels: approved, bot is merging ⏳
