Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-07, with the labels that each got.

#2028 [15.0] [MIG] stock_quant_reservation_info: Migration to 15.0
  setup/stock_quant_reservation_info/odoo/addons/stock_quant_reservation_info
  setup/stock_quant_reservation_info/setup.py
  stock_quant_reservation_info/README.rst
  stock_quant_reservation_info/__init__.py
  stock_quant_reservation_info/__manifest__.py
  stock_quant_reservation_info/i18n/it.po
  stock_quant_reservation_info/i18n/stock_quant_reservation_info.pot
  stock_quant_reservation_info/models/__init__.py
  stock_quant_reservation_info/models/stock_move_line.py
  stock_quant_reservation_info/models/stock_quant.py
  stock_quant_reservation_info/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info/readme/DESCRIPTION.rst
  stock_quant_reservation_info/readme/USAGE.rst
  stock_quant_reservation_info/static/description/icon.png
  stock_quant_reservation_info/static/description/index.html
  stock_quant_reservation_info/views/stock_move_line.xml
  stock_quant_reservation_info/views/stock_quant.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2092 [17.0][UPD] stock_helper: bump development status
  stock_helper/__manifest__.py
Labels: bot is merging ⏳

#2093 [16.0][MIG] stock_pull_list
  setup/stock_pull_list/odoo/addons/stock_pull_list
  setup/stock_pull_list/setup.py
  stock_pull_list/README.rst
  stock_pull_list/__init__.py
  stock_pull_list/__manifest__.py
  stock_pull_list/data/data.xml
  stock_pull_list/data/stock_pull_list_sequence_data.xml
  stock_pull_list/i18n/it.po
  stock_pull_list/i18n/stock_pull_list.pot
  stock_pull_list/models/__init__.py
  stock_pull_list/models/stock_picking.py
  stock_pull_list/models/stock_picking_type.py
  stock_pull_list/readme/CONTRIBUTORS.rst
  stock_pull_list/readme/DESCRIPTION.rst
  stock_pull_list/readme/ROADMAP.rst
  stock_pull_list/readme/USAGE.rst
  stock_pull_list/security/ir.model.access.csv
  stock_pull_list/static/description/icon.png
  stock_pull_list/static/description/index.html
  stock_pull_list/tests/__init__.py
  stock_pull_list/tests/common.py
  stock_pull_list/tests/test_stock_pull_list.py
  stock_pull_list/views/stock_picking_views.xml
  stock_pull_list/wizards/__init__.py
  stock_pull_list/wizards/stock_pull_list_wizard.py
  stock_pull_list/wizards/stock_pull_list_wizard.xml
Labels: bot is merging ⏳

#2054 [15.0] [MIG] stock_quant_reservation_info_mrp: Migration to 15.0
  setup/stock_quant_reservation_info_mrp/odoo/addons/stock_quant_reservation_info_mrp
  setup/stock_quant_reservation_info_mrp/setup.py
  stock_quant_reservation_info_mrp/README.rst
  stock_quant_reservation_info_mrp/__init__.py
  stock_quant_reservation_info_mrp/__manifest__.py
  stock_quant_reservation_info_mrp/i18n/it.po
  stock_quant_reservation_info_mrp/i18n/stock_quant_reservation_info_mrp.pot
  stock_quant_reservation_info_mrp/models/__init__.py
  stock_quant_reservation_info_mrp/models/stock_move_line.py
  stock_quant_reservation_info_mrp/readme/CONTRIBUTORS.rst
  stock_quant_reservation_info_mrp/readme/DESCRIPTION.rst
  stock_quant_reservation_info_mrp/readme/USAGE.rst
  stock_quant_reservation_info_mrp/static/description/icon.png
  stock_quant_reservation_info_mrp/static/description/index.html
  stock_quant_reservation_info_mrp/views/stock_move_line.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2085 [17.0] [MIG] stock_inventory: Migration to 17.0
  stock_inventory/README.rst
  stock_inventory/__init__.py
  stock_inventory/__manifest__.py
  stock_inventory/i18n/es.po
  stock_inventory/i18n/fr.po
  stock_inventory/i18n/it.po
  stock_inventory/i18n/stock_inventory.pot
  stock_inventory/models/__init__.py
  stock_inventory/models/res_company.py
  stock_inventory/models/res_config_settings.py
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_move_line.py
  stock_inventory/models/stock_quant.py
  stock_inventory/pyproject.toml
  stock_inventory/readme/CONTRIBUTORS.md
  stock_inventory/readme/DESCRIPTION.md
  stock_inventory/readme/USAGE.md
  stock_inventory/security/ir.model.access.csv
  stock_inventory/security/security.xml
  stock_inventory/static/description/icon.png
  stock_inventory/static/description/index.html
  stock_inventory/tests/__init__.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/res_config_settings_view.xml
  stock_inventory/views/stock_inventory.xml
  stock_inventory/views/stock_move_line.xml
  stock_inventory/views/stock_quant.xml
Labels: approved, bot is merging ⏳

#2055 [17.0][MIG] stock_picking_volume
  stock_picking_volume/README.rst
  stock_picking_volume/__init__.py
  stock_picking_volume/__manifest__.py
  stock_picking_volume/hooks.py
  stock_picking_volume/i18n/it.po
  stock_picking_volume/i18n/stock_picking_volume.pot
  stock_picking_volume/models/__init__.py
  stock_picking_volume/models/product_product.py
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/models/stock_picking.py
  stock_picking_volume/pyproject.toml
  stock_picking_volume/readme/CONTRIBUTORS.md
  stock_picking_volume/readme/CREDITS.md
  stock_picking_volume/readme/DESCRIPTION.md
  stock_picking_volume/readme/USAGE.md
  stock_picking_volume/static/description/icon.png
  stock_picking_volume/static/description/index.html
  stock_picking_volume/tests/__init__.py
  stock_picking_volume/tests/test_stock_picking_volume.py
  stock_picking_volume/views/stock_move.xml
  stock_picking_volume/views/stock_picking.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2067 [17.0][MIG] stock_packaging_calculator: Migration to 17.0
  stock_packaging_calculator/README.rst
  stock_packaging_calculator/__init__.py
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/i18n/it.po
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/pyproject.toml
  stock_packaging_calculator/readme/CONTRIBUTORS.md
  stock_packaging_calculator/readme/DESCRIPTION.md
  stock_packaging_calculator/readme/ROADMAP.md
  stock_packaging_calculator/readme/USAGE.md
  stock_packaging_calculator/static/description/icon.png
  stock_packaging_calculator/static/description/index.html
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/models.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator/tests/test_product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/utils.py
  test-requirements.txt
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2101 [ADD] [16.0] stock_valuation_layer_inventory_filter
  setup/stock_valuation_layer_inventory_filter/odoo/addons/stock_valuation_layer_inventory_filter
  setup/stock_valuation_layer_inventory_filter/setup.py
  stock_valuation_layer_inventory_filter/README.rst
  stock_valuation_layer_inventory_filter/__init__.py
  stock_valuation_layer_inventory_filter/__manifest__.py
  stock_valuation_layer_inventory_filter/i18n/es.po
  stock_valuation_layer_inventory_filter/i18n/stock_valuation_layer_inventory_filter.pot
  stock_valuation_layer_inventory_filter/models/__init__.py
  stock_valuation_layer_inventory_filter/models/stock_valuation_layer.py
  stock_valuation_layer_inventory_filter/readme/CONTEXT.md
  stock_valuation_layer_inventory_filter/readme/CONTRIBUTORS.md
  stock_valuation_layer_inventory_filter/readme/DESCRIPTION.md
  stock_valuation_layer_inventory_filter/readme/USAGE.md
  stock_valuation_layer_inventory_filter/static/description/icon.png
  stock_valuation_layer_inventory_filter/static/description/index.html
  stock_valuation_layer_inventory_filter/views/stock_valuation_layer_view.xml
Labels: approved, bot is merging ⏳

#2102 [16.0][MIG] stock_vlm_mgmt: Migration to 16.0
  setup/stock_vlm_mgmt/odoo/addons/stock_vlm_mgmt
  setup/stock_vlm_mgmt/setup.py
  stock_vlm_mgmt/README.rst
  stock_vlm_mgmt/__init__.py
  stock_vlm_mgmt/__manifest__.py
  stock_vlm_mgmt/models/__init__.py
  stock_vlm_mgmt/models/stock_location.py
  stock_vlm_mgmt/models/stock_location_vlm_tray.py
  stock_vlm_mgmt/models/stock_location_vlm_tray_type.py
  stock_vlm_mgmt/models/stock_move_line.py
  stock_vlm_mgmt/models/stock_picking.py
  stock_vlm_mgmt/models/stock_quant.py
  stock_vlm_mgmt/models/stock_vlm_task.py
  stock_vlm_mgmt/models/vlm_tray_cell_position_mixin.py
  stock_vlm_mgmt/readme/CONTRIBUTORS.rst
  stock_vlm_mgmt/readme/DESCRIPTION.rst
  stock_vlm_mgmt/readme/ROADMAP.rst
  stock_vlm_mgmt/security/ir.model.access.csv
  stock_vlm_mgmt/static/description/index.html
  stock_vlm_mgmt/static/src/js/location_tray_matrix/stock_location_tray.esm.js
  stock_vlm_mgmt/static/src/js/location_tray_matrix/stock_location_tray.scss
  stock_vlm_mgmt/static/src/js/location_tray_matrix/stock_location_tray_views.xml
  stock_vlm_mgmt/static/src/js/vlm_request_button/vlm_request_views.esm.js
  stock_vlm_mgmt/static/src/js/vlm_request_button/vlm_request_views.xml
  stock_vlm_mgmt/static/src/scss/stock_vlm_mgmt.scss
  stock_vlm_mgmt/views/stock_location_tray_type_views.xml
  stock_vlm_mgmt/views/stock_location_views.xml
  stock_vlm_mgmt/views/stock_location_vlm_tray_views.xml
  stock_vlm_mgmt/views/stock_picking_views.xml
  stock_vlm_mgmt/views/stock_quant_views.xml
  stock_vlm_mgmt/views/stock_quant_vlm_views.xml
  stock_vlm_mgmt/views/stock_vlm_task_views.xml
  stock_vlm_mgmt/wizards/__init__.py
  stock_vlm_mgmt/wizards/stock_vlm_task_action.py
  stock_vlm_mgmt/wizards/stock_vlm_task_action_views.xml
Labels: approved, bot is merging ⏳

#1946 [17.0][MIG] stock_location_lockdown: Migration to 17.
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/i18n/es.po
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/it.po
  stock_location_lockdown/i18n/pt.po
  stock_location_lockdown/i18n/stock_location_lockdown.pot
  stock_location_lockdown/i18n/zh_CN.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/pyproject.toml
  stock_location_lockdown/readme/CONTRIBUTORS.md
  stock_location_lockdown/readme/DESCRIPTION.md
  stock_location_lockdown/readme/USAGE.md
  stock_location_lockdown/static/description/icon.png
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2107 [15.0][FIX] stock_orderpoint_move_link: database error when orderpoint_id is False
  stock_orderpoint_move_link/models/stock.py
Labels: approved, bot is merging ⏳

#2033 [15.0][FIX] stock_request: compute_move_ids
  stock_request/models/stock_request.py
  stock_request/tests/test_stock_request.py
Labels: approved, bot is merging ⏳

#2112 [15.0][IMP] stock_inventory: improve errors information when inventory is blocked
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/stock_inventory.xml
Labels: approved, bot is merging ⏳

#2118 [16.0][FWP][IMP] stock_inventory: improve errors information when inventory is blocked
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/stock_inventory.xml
Labels: bot is merging ⏳

#2115 [16.0] stock_move_location: Fix UI and add hook to filter quants
  stock_move_location/README.rst
  stock_move_location/readme/CONTRIBUTORS.md
  stock_move_location/readme/USAGE.md
  stock_move_location/static/description/index.html
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/views/stock_picking_type_views.xml
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
Labels: enhancement, approved, bot is merging ⏳

#2114 [16.0][ADD] stock_package_type_volume
  setup/stock_package_type_volume/odoo/addons/stock_package_type_volume
  setup/stock_package_type_volume/setup.py
  stock_package_type_volume/README.rst
  stock_package_type_volume/__init__.py
  stock_package_type_volume/__manifest__.py
  stock_package_type_volume/models/__init__.py
  stock_package_type_volume/models/stock_package_type.py
  stock_package_type_volume/readme/CONTRIBUTORS.rst
  stock_package_type_volume/readme/DESCRIPTION.rst
  stock_package_type_volume/static/description/index.html
  stock_package_type_volume/tests/__init__.py
  stock_package_type_volume/tests/test_stock_package_type_volume.py
  stock_package_type_volume/views/stock_package_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳
