Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-01, with the labels that each got.

#1861 [16.0][MIG] stock_inventory
  setup/stock_inventory/odoo/addons/stock_inventory
  setup/stock_inventory/setup.py
  stock_inventory/README.rst
  stock_inventory/__init__.py
  stock_inventory/__manifest__.py
  stock_inventory/i18n/stock_inventory.pot
  stock_inventory/models/__init__.py
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_move_line.py
  stock_inventory/models/stock_quant.py
  stock_inventory/readme/CONTRIBUTORS.rst
  stock_inventory/readme/DESCRIPTION.rst
  stock_inventory/readme/USAGE.rst
  stock_inventory/security/ir.model.access.csv
  stock_inventory/static/description/icon.png
  stock_inventory/static/description/index.html
  stock_inventory/tests/__init__.py
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/stock_inventory.xml
  stock_inventory/views/stock_move_line.xml
  stock_inventory/views/stock_quant.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1906 [MIG][17.0] scrap_reason_code: Migration to 17.0
  scrap_reason_code/README.rst
  scrap_reason_code/__init__.py
  scrap_reason_code/__manifest__.py
  scrap_reason_code/i18n/es.po
  scrap_reason_code/i18n/fr.po
  scrap_reason_code/i18n/it.po
  scrap_reason_code/i18n/scrap_reason_code.pot
  scrap_reason_code/models/__init__.py
  scrap_reason_code/models/reason_code.py
  scrap_reason_code/models/stock_move.py
  scrap_reason_code/models/stock_scrap.py
  scrap_reason_code/pyproject.toml
  scrap_reason_code/readme/CONFIGURE.md
  scrap_reason_code/readme/CONTRIBUTORS.md
  scrap_reason_code/readme/CREDITS.md
  scrap_reason_code/readme/DESCRIPTION.md
  scrap_reason_code/readme/ROADMAP.md
  scrap_reason_code/readme/USAGE.md
  scrap_reason_code/security/ir.model.access.csv
  scrap_reason_code/static/description/icon.png
  scrap_reason_code/static/description/index.html
  scrap_reason_code/tests/__init__.py
  scrap_reason_code/tests/test_scrap_reason_code.py
  scrap_reason_code/views/reason_code_view.xml
  scrap_reason_code/views/stock_move_views.xml
  scrap_reason_code/views/stock_scrap_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1902 [14.0][REF] s_packaging_calculator: remove unneeded &nbsp; constant
  stock_packaging_calculator/models/product.py
Labels: bot is merging ⏳

#1916 [14.0][ADD] sale_stock_on_hand_popup
  sale_stock_on_hand_popup/README.rst
  sale_stock_on_hand_popup/__init__.py
  sale_stock_on_hand_popup/__manifest__.py
  sale_stock_on_hand_popup/models/__init__.py
  sale_stock_on_hand_popup/models/product.py
  sale_stock_on_hand_popup/readme/CONTRIBUTORS.rst
  sale_stock_on_hand_popup/readme/DESCRIPTION.rst
  sale_stock_on_hand_popup/readme/USAGE.rst
  sale_stock_on_hand_popup/static/description/index.html
  sale_stock_on_hand_popup/static/src/js/qty_at_date_widget.js
  sale_stock_on_hand_popup/static/src/xml/sale_stock.xml
  sale_stock_on_hand_popup/tests/__init__.py
  sale_stock_on_hand_popup/tests/test_sale_stock_on_hand_popup.py
  sale_stock_on_hand_popup/views/sale_order_views.xml
  setup/sale_stock_on_hand_popup/odoo/addons/sale_stock_on_hand_popup
  setup/sale_stock_on_hand_popup/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1922 [15.0][FIX] stock_reserve: Change web_ribbon text to title to make it translatable
  stock_reserve/view/stock_reserve.xml
Labels: approved, bot is merging ⏳

#1926 [16.0][FIX] stock_reserve: Change web_ribbon text to title to make it translatable
  stock_reserve/view/stock_reserve.xml
Labels: approved, bot is merging ⏳
