Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-09, with the labels that each got.

#2108 [16.0] [MIG] stock_quant_expiration_date_tree: Migration to 16.0
  setup/stock_quant_expiration_date_tree/odoo/addons/stock_quant_expiration_date_tree
  setup/stock_quant_expiration_date_tree/setup.py
  stock_quant_expiration_date_tree/README.rst
  stock_quant_expiration_date_tree/__init__.py
  stock_quant_expiration_date_tree/__manifest__.py
  stock_quant_expiration_date_tree/i18n/es.po
  stock_quant_expiration_date_tree/i18n/stock_quant_expiration_date_tree.pot
  stock_quant_expiration_date_tree/models/__init__.py
  stock_quant_expiration_date_tree/models/stock_quant.py
  stock_quant_expiration_date_tree/readme/CONTRIBUTORS.rst
  stock_quant_expiration_date_tree/readme/DESCRIPTION.rst
  stock_quant_expiration_date_tree/static/description/icon.png
  stock_quant_expiration_date_tree/static/description/index.html
  stock_quant_expiration_date_tree/views/stock_quant.xml
Labels: approved, ready to merge, bot is merging ⏳

#2147 [16.0][FIX] stock_vlm_mgmt: error when creating new quant
  stock_vlm_mgmt/models/stock_quant.py
Labels: approved, ready to merge, bot is merging ⏳

#2150 [14.0][BACKPORT] stock_available_immediately_exclude_location
  setup/stock_available_immediately_exclude_location/odoo/addons/stock_available_immediately_exclude_location
  setup/stock_available_immediately_exclude_location/setup.py
  stock_available_immediately_exclude_location/README.rst
  stock_available_immediately_exclude_location/__init__.py
  stock_available_immediately_exclude_location/__manifest__.py
  stock_available_immediately_exclude_location/i18n/it.po
  stock_available_immediately_exclude_location/i18n/stock_available_immediately_exclude_location.pot
  stock_available_immediately_exclude_location/models/__init__.py
  stock_available_immediately_exclude_location/models/product_product.py
  stock_available_immediately_exclude_location/models/stock_location.py
  stock_available_immediately_exclude_location/readme/CONTRIBUTORS.rst
  stock_available_immediately_exclude_location/readme/DESCRIPTION.rst
  stock_available_immediately_exclude_location/static/description/icon.png
  stock_available_immediately_exclude_location/static/description/index.html
  stock_available_immediately_exclude_location/tests/__init__.py
  stock_available_immediately_exclude_location/tests/test_stock_exclude_location.py
  stock_available_immediately_exclude_location/views/stock_location.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2116 [16.0][IMP] stock_exception: button_validate
  stock_exception/models/stock.py
  stock_exception/tests/__init__.py
  stock_exception/tests/test_stock.py
Labels: approved, ready to merge, bot is merging ⏳

#2154 [14.0][MIG] stock_route_mto: backport from v16
  setup/stock_route_mto/odoo/addons/stock_route_mto
  setup/stock_route_mto/setup.py
  stock_route_mto/README.rst
  stock_route_mto/__init__.py
  stock_route_mto/__manifest__.py
  stock_route_mto/data/stock_route.xml
  stock_route_mto/i18n/it.po
  stock_route_mto/i18n/stock_route_mto.pot
  stock_route_mto/models/__init__.py
  stock_route_mto/models/stock_route.py
  stock_route_mto/readme/CONTRIBUTORS.rst
  stock_route_mto/readme/DESCRIPTION.rst
  stock_route_mto/readme/USAGE.rst
  stock_route_mto/static/description/icon.png
  stock_route_mto/static/description/index.html
  stock_route_mto/views/stock_route.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2158 [13.0][IMP] stock_available_unreserved: avoid warning when creating products
  stock_available_unreserved/models/product.py
Labels: enhancement, approved, bot is merging ⏳

#1955 [17.0][MIG] account_move_line_product
  account_move_line_product/README.rst
  account_move_line_product/__init__.py
  account_move_line_product/__manifest__.py
  account_move_line_product/i18n/account_move_line_product.pot
  account_move_line_product/i18n/ca.po
  account_move_line_product/i18n/cs_CZ.po
  account_move_line_product/i18n/de.po
  account_move_line_product/i18n/el_GR.po
  account_move_line_product/i18n/es.po
  account_move_line_product/i18n/es_ES.po
  account_move_line_product/i18n/eu.po
  account_move_line_product/i18n/fi.po
  account_move_line_product/i18n/fr.po
  account_move_line_product/i18n/fr_CH.po
  account_move_line_product/i18n/fr_FR.po
  account_move_line_product/i18n/gl.po
  account_move_line_product/i18n/hr.po
  account_move_line_product/i18n/hr_HR.po
  account_move_line_product/i18n/it.po
  account_move_line_product/i18n/nl.po
  account_move_line_product/i18n/nl_NL.po
  account_move_line_product/i18n/pt.po
  account_move_line_product/i18n/pt_BR.po
  account_move_line_product/i18n/ro.po
  account_move_line_product/i18n/ru.po
  account_move_line_product/i18n/sl.po
  account_move_line_product/i18n/tr.po
  account_move_line_product/i18n/tr_TR.po
  account_move_line_product/i18n/vi_VN.po
  account_move_line_product/i18n/zh_CN.po
  account_move_line_product/pyproject.toml
  account_move_line_product/readme/CONFIGURE.md
  account_move_line_product/readme/CONTRIBUTORS.md
  account_move_line_product/readme/DESCRIPTION.md
  account_move_line_product/static/description/icon.png
  account_move_line_product/static/description/index.html
  account_move_line_product/views/account_move_line_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2155 [15.0][MIG] stock_inventory_lockdown
  setup/stock_inventory_lockdown/odoo/addons/stock_inventory_lockdown
  setup/stock_inventory_lockdown/setup.py
  stock_inventory_lockdown/README.rst
  stock_inventory_lockdown/__init__.py
  stock_inventory_lockdown/__manifest__.py
  stock_inventory_lockdown/i18n/ca.po
  stock_inventory_lockdown/i18n/cs_CZ.po
  stock_inventory_lockdown/i18n/de.po
  stock_inventory_lockdown/i18n/es.po
  stock_inventory_lockdown/i18n/es_ES.po
  stock_inventory_lockdown/i18n/es_MX.po
  stock_inventory_lockdown/i18n/fi.po
  stock_inventory_lockdown/i18n/fr.po
  stock_inventory_lockdown/i18n/gl.po
  stock_inventory_lockdown/i18n/hr.po
  stock_inventory_lockdown/i18n/it.po
  stock_inventory_lockdown/i18n/nl_NL.po
  stock_inventory_lockdown/i18n/pt.po
  stock_inventory_lockdown/i18n/pt_BR.po
  stock_inventory_lockdown/i18n/ro.po
  stock_inventory_lockdown/i18n/sl.po
  stock_inventory_lockdown/i18n/stock_inventory_lockdown.pot
  stock_inventory_lockdown/i18n/tr.po
  stock_inventory_lockdown/i18n/tr_TR.po
  stock_inventory_lockdown/i18n/vi_VN.po
  stock_inventory_lockdown/i18n/zh_CN.po
  stock_inventory_lockdown/models/__init__.py
  stock_inventory_lockdown/models/stock_inventory.py
  stock_inventory_lockdown/models/stock_location.py
  stock_inventory_lockdown/models/stock_move_line.py
  stock_inventory_lockdown/readme/CONTRIBUTORS.rst
  stock_inventory_lockdown/readme/DESCRIPTION.rst
  stock_inventory_lockdown/readme/USAGE.rst
  stock_inventory_lockdown/static/description/icon.png
  stock_inventory_lockdown/static/description/index.html
  stock_inventory_lockdown/static/images/move_error.png
  stock_inventory_lockdown/tests/__init__.py
  stock_inventory_lockdown/tests/test_stock_inventory_lockdown.py
Labels: needs review, approved, migration, bot is merging ⏳

#2152 [14.0][IMP] stock_request_purchase: Cancel stock request when unlinking related purchase order lines
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved, bot is merging ⏳

#2134 [14.0][IMP] stock_request_purchase: Add context key to skip cancel purchase
  stock_request_purchase/models/stock_request.py
Labels: approved, bot is merging ⏳

#2135 [14.0][IMP] stock_request: Improve _check_qty constrain (moved to stock.request)
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/models/stock_request.py
  stock_request/models/stock_request_abstract.py
Labels: approved, bot is merging ⏳

#2163 [15.0][IMP] stock_request: Improve _check_qty constrain (moved to stock.request)
  stock_request/i18n/es.po
  stock_request/i18n/stock_request.pot
  stock_request/models/stock_request.py
  stock_request/models/stock_request_abstract.py
  stock_request_purchase/models/stock_request.py
Labels: approved, bot is merging ⏳

#2164 [15.0][IMP] stock_request_purchase: Cancel stock request when unlinking related purchase order lines
  stock_request_purchase/models/purchase_order_line.py
  stock_request_purchase/tests/test_stock_request_purchase.py
Labels: approved, bot is merging ⏳

#2161 [FIX] fix odoo traces
  base_product_merge/wizard/base_product_merge.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2167 [16.0][IMP] stock_quant_manual_assign: Improve readme
  stock_quant_manual_assign/readme/CONFIGURATION.md
  stock_quant_manual_assign/readme/CONFIGURATION.rst
  stock_quant_manual_assign/readme/CONTEXT.md
  stock_quant_manual_assign/readme/CONTRIBUTORS.md
  stock_quant_manual_assign/readme/DESCRIPTION.md
  stock_quant_manual_assign/readme/DESCRIPTION.rst
  stock_quant_manual_assign/readme/USAGE.md
  stock_quant_manual_assign/readme/USAGE.rst
  stock_quant_manual_assign/static/description/imagen1.png
  stock_quant_manual_assign/static/description/imagen2.png
  stock_quant_manual_assign/static/description/imagen3.png
  stock_quant_manual_assign/static/description/imagen4.png
Labels: approved, bot is merging ⏳

#2157 [16.0][FW] procurement_auto_create_group: partial ports of #1821
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/tests/test_auto_create.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2166 [17.0][MIG] stock_picking_volume_packaging
  stock_picking_volume_packaging/README.rst
  stock_picking_volume_packaging/__init__.py
  stock_picking_volume_packaging/__manifest__.py
  stock_picking_volume_packaging/i18n/it.po
  stock_picking_volume_packaging/i18n/stock_picking_volume_packaging.pot
  stock_picking_volume_packaging/models/__init__.py
  stock_picking_volume_packaging/models/product_product.py
  stock_picking_volume_packaging/pyproject.toml
  stock_picking_volume_packaging/readme/CONTRIBUTORS.md
  stock_picking_volume_packaging/readme/CREDITS.md
  stock_picking_volume_packaging/readme/DESCRIPTION.md
  stock_picking_volume_packaging/readme/USAGE.md
  stock_picking_volume_packaging/static/description/icon.png
  stock_picking_volume_packaging/static/description/index.html
  stock_picking_volume_packaging/tests/__init__.py
  stock_picking_volume_packaging/tests/test_stock_move_volume.py
Labels: needs review, approved, migration, bot is merging ⏳

#2162 [14.0][IMP] stock_location_warehouse: change development_status
  stock_location_warehouse/README.rst
  stock_location_warehouse/__manifest__.py
Labels: approved, bot is merging ⏳

#2160 [17.0][MIG] account_move_line_stock_info
  account_move_line_stock_info/README.rst
  account_move_line_stock_info/__init__.py
  account_move_line_stock_info/__manifest__.py
  account_move_line_stock_info/i18n/account_move_line_stock_info.pot
  account_move_line_stock_info/i18n/ar.po
  account_move_line_stock_info/i18n/bs.po
  account_move_line_stock_info/i18n/ca.po
  account_move_line_stock_info/i18n/cs.po
  account_move_line_stock_info/i18n/cs_CZ.po
  account_move_line_stock_info/i18n/de.po
  account_move_line_stock_info/i18n/en_GB.po
  account_move_line_stock_info/i18n/es.po
  account_move_line_stock_info/i18n/es_CR.po
  account_move_line_stock_info/i18n/es_EC.po
  account_move_line_stock_info/i18n/es_MX.po
  account_move_line_stock_info/i18n/fi.po
  account_move_line_stock_info/i18n/fr.po
  account_move_line_stock_info/i18n/fr_CH.po
  account_move_line_stock_info/i18n/gl.po
  account_move_line_stock_info/i18n/hr.po
  account_move_line_stock_info/i18n/hr_HR.po
  account_move_line_stock_info/i18n/hu.po
  account_move_line_stock_info/i18n/it.po
  account_move_line_stock_info/i18n/ja.po
  account_move_line_stock_info/i18n/lt.po
  account_move_line_stock_info/i18n/mk.po
  account_move_line_stock_info/i18n/mn.po
  account_move_line_stock_info/i18n/nb.po
  account_move_line_stock_info/i18n/nb_NO.po
  account_move_line_stock_info/i18n/nl.po
  account_move_line_stock_info/i18n/nl_BE.po
  account_move_line_stock_info/i18n/nl_NL.po
  account_move_line_stock_info/i18n/pt.po
  account_move_line_stock_info/i18n/pt_BR.po
  account_move_line_stock_info/i18n/pt_PT.po
  account_move_line_stock_info/i18n/ro.po
  account_move_line_stock_info/i18n/ru.po
  account_move_line_stock_info/i18n/sl.po
  account_move_line_stock_info/i18n/sv.po
  account_move_line_stock_info/i18n/tr.po
  account_move_line_stock_info/i18n/tr_TR.po
  account_move_line_stock_info/i18n/vi_VN.po
  account_move_line_stock_info/i18n/zh_CN.po
  account_move_line_stock_info/i18n/zh_TW.po
  account_move_line_stock_info/models/__init__.py
  account_move_line_stock_info/models/account_move_line.py
  account_move_line_stock_info/models/stock_move.py
  account_move_line_stock_info/pyproject.toml
  account_move_line_stock_info/readme/CONTRIBUTORS.md
  account_move_line_stock_info/readme/DESCRIPTION.md
  account_move_line_stock_info/readme/USAGE.md
  account_move_line_stock_info/security/ir.model.access.csv
  account_move_line_stock_info/static/description/icon.png
  account_move_line_stock_info/static/description/index.html
  account_move_line_stock_info/tests/__init__.py
  account_move_line_stock_info/tests/test_account_move_line_stock_move.py
  account_move_line_stock_info/views/account_move_line_view.xml
  account_move_line_stock_info/views/stock_move_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2148 [14.0][BACKPORT] [16.0] stock_picking_volume: Speedup install and avoid useless recompute
  stock_picking_volume/__init__.py
  stock_picking_volume/__manifest__.py
  stock_picking_volume/hooks.py
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#2062 [17.0] [MIG] stock_route_mto: Migration to 17.0
  stock_route_mto/README.rst
  stock_route_mto/__init__.py
  stock_route_mto/__manifest__.py
  stock_route_mto/data/stock_route.xml
  stock_route_mto/i18n/it.po
  stock_route_mto/i18n/stock_route_mto.pot
  stock_route_mto/models/__init__.py
  stock_route_mto/models/stock_route.py
  stock_route_mto/pyproject.toml
  stock_route_mto/readme/CONTRIBUTORS.md
  stock_route_mto/readme/DESCRIPTION.md
  stock_route_mto/readme/USAGE.md
  stock_route_mto/static/description/icon.png
  stock_route_mto/static/description/index.html
  stock_route_mto/views/stock_route.xml
Labels: needs review, approved, migration, bot is merging ⏳
