Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-03, with the labels that each got.

#1954 [16.0][FW] stock_picking_volume: multiple ports from 14.0
  stock_picking_volume/models/__init__.py
  stock_picking_volume/models/product_product.py
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/models/stock_picking.py
  stock_picking_volume/tests/test_stock_picking_volume.py
  stock_picking_volume_packaging/models/__init__.py
  stock_picking_volume_packaging/models/product_product.py
  stock_picking_volume_packaging/tests/test_stock_move_volume.py
Labels: approved, bot is merging ⏳

#1891 [MIG] stock_removal_location_by_priority: Migration to 16.0
  setup/stock_removal_location_by_priority/odoo/addons/stock_removal_location_by_priority
  setup/stock_removal_location_by_priority/setup.py
  stock_removal_location_by_priority/README.rst
  stock_removal_location_by_priority/__init__.py
  stock_removal_location_by_priority/__manifest__.py
  stock_removal_location_by_priority/i18n/de.po
  stock_removal_location_by_priority/i18n/es.po
  stock_removal_location_by_priority/i18n/fi.po
  stock_removal_location_by_priority/i18n/fr.po
  stock_removal_location_by_priority/i18n/it.po
  stock_removal_location_by_priority/i18n/pt_BR.po
  stock_removal_location_by_priority/i18n/ro.po
  stock_removal_location_by_priority/i18n/sl.po
  stock_removal_location_by_priority/i18n/stock_removal_location_by_priority.pot
  stock_removal_location_by_priority/i18n/zh_CN.po
  stock_removal_location_by_priority/init_hook.py
  stock_removal_location_by_priority/models/__init__.py
  stock_removal_location_by_priority/models/res_config_settings.py
  stock_removal_location_by_priority/models/stock_location.py
  stock_removal_location_by_priority/models/stock_quant.py
  stock_removal_location_by_priority/readme/CONFIGURE.rst
  stock_removal_location_by_priority/readme/CONTRIBUTORS.rst
  stock_removal_location_by_priority/readme/DESCRIPTION.rst
  stock_removal_location_by_priority/readme/USAGE.rst
  stock_removal_location_by_priority/security/stock_security.xml
  stock_removal_location_by_priority/static/description/icon.png
  stock_removal_location_by_priority/static/description/index.html
  stock_removal_location_by_priority/tests/__init__.py
  stock_removal_location_by_priority/tests/test_stock_removal_location_by_priority.py
  stock_removal_location_by_priority/views/res_config_settings_views.xml
  stock_removal_location_by_priority/views/stock_location_view.xml
Labels: question, needs review, approved, migration, ready to merge, bot is merging ⏳

#1910 [16.0] [MIG] stock_inventory_justification
  setup/stock_inventory_justification/odoo/addons/stock_inventory_justification
  setup/stock_inventory_justification/setup.py
  stock_inventory_justification/README.rst
  stock_inventory_justification/__init__.py
  stock_inventory_justification/__manifest__.py
  stock_inventory_justification/i18n/stock_inventory_justification.pot
  stock_inventory_justification/models/__init__.py
  stock_inventory_justification/models/stock_inventory_justification.py
  stock_inventory_justification/models/stock_move.py
  stock_inventory_justification/models/stock_move_line.py
  stock_inventory_justification/models/stock_quant.py
  stock_inventory_justification/readme/CONTRIBUTORS.rst
  stock_inventory_justification/readme/DESCRIPTION.rst
  stock_inventory_justification/readme/USAGE.rst
  stock_inventory_justification/security/acl_stock_inventory_justification.xml
  stock_inventory_justification/static/description/icon.png
  stock_inventory_justification/static/description/index.html
  stock_inventory_justification/tests/__init__.py
  stock_inventory_justification/tests/test_stock_inventory_justification.py
  stock_inventory_justification/views/stock_inventory_justification.xml
  stock_inventory_justification/views/stock_move_line.xml
  stock_inventory_justification/views/stock_quant.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1899 [16.0][IMP][FIX] stock_move_location: improve planned transfer
  stock_move_location/README.rst
  stock_move_location/readme/CONTRIBUTORS.md
  stock_move_location/static/description/index.html
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1845 [15.0][ADD] stock_valuation_layer_accounting_date
  setup/stock_valuation_layer_accounting_date/odoo/addons/stock_valuation_layer_accounting_date
  setup/stock_valuation_layer_accounting_date/setup.py
  stock_valuation_layer_accounting_date/README.rst
  stock_valuation_layer_accounting_date/__init__.py
  stock_valuation_layer_accounting_date/__manifest__.py
  stock_valuation_layer_accounting_date/hooks.py
  stock_valuation_layer_accounting_date/i18n/ja.po
  stock_valuation_layer_accounting_date/models/__init__.py
  stock_valuation_layer_accounting_date/models/stock_valuation_layer.py
  stock_valuation_layer_accounting_date/readme/CONTRIBUTORS.rst
  stock_valuation_layer_accounting_date/readme/DESCRIPTION.rst
  stock_valuation_layer_accounting_date/readme/USAGE.rst
  stock_valuation_layer_accounting_date/static/description/index.html
  stock_valuation_layer_accounting_date/tests/__init__.py
  stock_valuation_layer_accounting_date/tests/test_stock_valuation_layer_accounting_date.py
  stock_valuation_layer_accounting_date/views/stock_valuation_layer_views.xml
  stock_valuation_layer_accounting_date/wizard/__init__.py
  stock_valuation_layer_accounting_date/wizard/stock_quantity_history.py
  stock_valuation_layer_accounting_date/wizard/stock_quantity_history.xml
Labels: needs review, approved, bot is merging ⏳

#1686 [16.0][ADD] stock_valuation_layer_accounting_date
  setup/stock_valuation_layer_accounting_date/odoo/addons/stock_valuation_layer_accounting_date
  setup/stock_valuation_layer_accounting_date/setup.py
  stock_valuation_layer_accounting_date/README.rst
  stock_valuation_layer_accounting_date/__init__.py
  stock_valuation_layer_accounting_date/__manifest__.py
  stock_valuation_layer_accounting_date/hooks.py
  stock_valuation_layer_accounting_date/i18n/ja.po
  stock_valuation_layer_accounting_date/models/__init__.py
  stock_valuation_layer_accounting_date/models/stock_valuation_layer.py
  stock_valuation_layer_accounting_date/readme/CONTRIBUTORS.rst
  stock_valuation_layer_accounting_date/readme/DESCRIPTION.rst
  stock_valuation_layer_accounting_date/readme/USAGE.rst
  stock_valuation_layer_accounting_date/static/description/index.html
  stock_valuation_layer_accounting_date/tests/__init__.py
  stock_valuation_layer_accounting_date/tests/test_stock_valuation_layer_accounting_date.py
  stock_valuation_layer_accounting_date/views/stock_valuation_layer_views.xml
  stock_valuation_layer_accounting_date/wizard/__init__.py
  stock_valuation_layer_accounting_date/wizard/stock_quantity_history.py
  stock_valuation_layer_accounting_date/wizard/stock_quantity_history.xml
Labels: needs review, approved, bot is merging ⏳

#1533 [14.0][ADD] stock_inventory_tier_validation
  setup/stock_inventory_tier_validation/odoo/addons/stock_inventory_tier_validation
  setup/stock_inventory_tier_validation/setup.py
  stock_inventory_tier_validation/README.rst
  stock_inventory_tier_validation/__init__.py
  stock_inventory_tier_validation/__manifest__.py
  stock_inventory_tier_validation/models/__init__.py
  stock_inventory_tier_validation/models/stock_inventory.py
  stock_inventory_tier_validation/models/tier_definition.py
  stock_inventory_tier_validation/readme/CONFIGURE.rst
  stock_inventory_tier_validation/readme/CONTRIBUTORS.rst
  stock_inventory_tier_validation/readme/DESCRIPTION.rst
  stock_inventory_tier_validation/readme/INSTALL.rst
  stock_inventory_tier_validation/readme/USAGE.rst
  stock_inventory_tier_validation/static/description/icon.png
  stock_inventory_tier_validation/tests/__init__.py
  stock_inventory_tier_validation/tests/test_tier_validation.py
  stock_inventory_tier_validation/views/stock_inventory_views.xml
Labels: approved, bot is merging ⏳

#1793 [15.0][ADD] base_product_merge
  base_product_merge/README.rst
  base_product_merge/__init__.py
  base_product_merge/__manifest__.py
  base_product_merge/readme/CONFIGURE.rst
  base_product_merge/readme/CONTRIBUTORS.rst
  base_product_merge/readme/DESCRIPTION.rst
  base_product_merge/readme/USAGE.rst
  base_product_merge/security/ir.model.access.csv
  base_product_merge/security/res_groups.xml
  base_product_merge/tests/__init__.py
  base_product_merge/tests/test_base_product_merge.py
  base_product_merge/wizard/__init__.py
  base_product_merge/wizard/base_product_merge.py
  base_product_merge/wizard/base_product_merge_view.xml
  requirements.txt
  setup/base_product_merge/odoo/addons/base_product_merge
  setup/base_product_merge/setup.py
Labels: approved, bot is merging ⏳

#1772 [16.0][MIG] stock_picking_show_linked
  setup/stock_picking_show_linked/odoo/addons/stock_picking_show_linked
  setup/stock_picking_show_linked/setup.py
  stock_picking_show_linked/README.rst
  stock_picking_show_linked/__init__.py
  stock_picking_show_linked/__manifest__.py
  stock_picking_show_linked/i18n/stock_picking_show_linked.pot
  stock_picking_show_linked/models/__init__.py
  stock_picking_show_linked/models/stock_picking.py
  stock_picking_show_linked/readme/CONTRIBUTORS.rst
  stock_picking_show_linked/readme/DESCRIPTION.rst
  stock_picking_show_linked/static/description/icon.png
  stock_picking_show_linked/static/description/index.html
  stock_picking_show_linked/views/stock_picking.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1961 [IMP] stock_move_packaging_qty: shorter qty field label
  stock_move_packaging_qty/i18n/es.po
  stock_move_packaging_qty/i18n/stock_move_packaging_qty.pot
  stock_move_packaging_qty/models/stock_move.py
Labels: approved, bot is merging ⏳

#1969 [16.0][FIX] stock_move_location: correct method _get_putaway_strategy name
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location_line.py
Labels: approved, bot is merging ⏳

#1968 [15.0][FIX] stock_move_location: correct method _get_putaway_strategy name
  stock_move_location/tests/test_move_location.py
  stock_move_location/wizard/stock_move_location_line.py
Labels: approved, bot is merging ⏳

#1944 [14.0][IMP] stock_vertical_lift: filter notifications by screen
  stock_vertical_lift/models/vertical_lift_operation_base.py
  stock_vertical_lift/models/vertical_lift_operation_pick.py
  stock_vertical_lift/models/vertical_lift_operation_put.py
  stock_vertical_lift/models/vertical_lift_shuttle.py
  stock_vertical_lift/static/src/js/web_client.js
  stock_vertical_lift/views/stock_vertical_lift_templates.xml
  stock_vertical_lift_storage_type/models/vertical_lift_operation_put.py
Labels: enhancement, bot is merging ⏳
