Repository OCA/stock-logistics-warehouse, pull requests merged in 2024-05, with the labels that each got.

#2015 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  scrap_reason_code/models/stock_scrap.py
Labels: help wanted, needs review, bot is merging ⏳

#1986 [ADD] stock_move_location_purchase_uom
  setup/stock_move_location_purchase_uom/odoo/addons/stock_move_location_purchase_uom
  setup/stock_move_location_purchase_uom/setup.py
  stock_move_location_purchase_uom/README.rst
  stock_move_location_purchase_uom/__init__.py
  stock_move_location_purchase_uom/__manifest__.py
  stock_move_location_purchase_uom/readme/CONTRIBUTORS.rst
  stock_move_location_purchase_uom/readme/DESCRIPTION.rst
  stock_move_location_purchase_uom/static/description/index.html
  stock_move_location_purchase_uom/tests/__init__.py
  stock_move_location_purchase_uom/tests/test_move_location_purchase_uom.py
  stock_move_location_purchase_uom/wizard/__init__.py
  stock_move_location_purchase_uom/wizard/stock_move_location.py
Labels: approved, ready to merge, bot is merging ⏳

#2013 [16.0][IMP] stock_move_packaging_qty: Set packaging qty reserved when move assign
  stock_move_packaging_qty/README.rst
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/models/stock_move_line.py
  stock_move_packaging_qty/static/description/index.html
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/stock_move_line_view.xml
Labels: approved, bot is merging ⏳

#2026 [15.0][FIX] stock_move_purchase_uom: test typo
  stock_move_purchase_uom/tests/test_stock_move_line.py
Labels: bot is merging ⏳

#2029 [16.0][IMP] stock_inventory: various fixes
  stock_inventory/__manifest__.py
  stock_inventory/models/__init__.py
  stock_inventory/models/res_company.py
  stock_inventory/models/res_config_settings.py
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_quant.py
  stock_inventory/security/security.xml
  stock_inventory/tests/test_stock_inventory.py
  stock_inventory/views/res_config_settings_view.xml
  stock_inventory/views/stock_inventory.xml
Labels: approved, bot is merging ⏳

#2035 [16.0][FIX] stock_quant_manual_assign
  stock_quant_manual_assign/wizard/assign_manual_quants_view.xml
Labels: approved, bot is merging ⏳

#2020 [16.0][ADD] stock_reservation_date_show
  setup/stock_reservation_date_show/odoo/addons/stock_reservation_date_show
  setup/stock_reservation_date_show/setup.py
  stock_reservation_date_show/README.rst
  stock_reservation_date_show/__init__.py
  stock_reservation_date_show/__manifest__.py
  stock_reservation_date_show/readme/CONTRIBUTORS.rst
  stock_reservation_date_show/readme/DESCRIPTION.rst
  stock_reservation_date_show/static/description/icon.png
  stock_reservation_date_show/static/description/index.html
  stock_reservation_date_show/views/stock_move_views.xml
  stock_reservation_date_show/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2036 [14.0][FIX] stock_reserve: Set the correct _default_picking_type_id value
  stock_reserve/models/stock_reserve.py
Labels: approved, bot is merging ⏳

#2037 [15.0][FIX] stock_available_mrp: Fix test value
  stock_available_mrp/tests/test_potential_qty.py
Labels: approved, bot is merging ⏳

#1989 [15.0][IMP] stock_request: Change rounding method to HALF-UP in quantities computation
  stock_request/models/stock_request.py
  stock_request/models/stock_request_abstract.py
  stock_request/models/stock_request_allocation.py
  stock_request/tests/test_stock_request.py
Labels: approved, bot is merging ⏳, Pending to Fwport

#1919 [15.0][IMP] stock_request: add route_id to stock.request.order
  stock_request/models/stock_request_order.py
  stock_request/tests/test_stock_request.py
  stock_request/views/stock_request_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2043 [15.0][FIX] stock_reserve: Set the correct _default_picking_type_id value
  stock_reserve/model/stock_reserve.py
Labels: approved, bot is merging ⏳

#2044 [16.0][FIX] stock_reserve: Set the correct _default_picking_type_id value
  stock_reserve/model/stock_reserve.py
Labels: bot is merging ⏳

#1821 [ADD][14.0] procurement_auto_create_group_by_product
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/tests/test_auto_create.py
  procurement_auto_create_group_by_product/README.rst
  procurement_auto_create_group_by_product/__init__.py
  procurement_auto_create_group_by_product/__manifest__.py
  procurement_auto_create_group_by_product/models/__init__.py
  procurement_auto_create_group_by_product/models/procurement_group.py
  procurement_auto_create_group_by_product/models/product_product.py
  procurement_auto_create_group_by_product/models/stock_move.py
  procurement_auto_create_group_by_product/models/stock_rule.py
  procurement_auto_create_group_by_product/readme/CONFIGURE.rst
  procurement_auto_create_group_by_product/readme/CONTRIBUTORS.rst
  procurement_auto_create_group_by_product/readme/DESCRIPTION.rst
  procurement_auto_create_group_by_product/tests/__init__.py
  procurement_auto_create_group_by_product/tests/test_auto_create_by_product.py
  procurement_auto_create_group_by_product/views/procurement_group.xml
  procurement_auto_create_group_by_product/views/stock_rule.xml
  setup/procurement_auto_create_group_by_product/odoo/addons/procurement_auto_create_group_by_product
  setup/procurement_auto_create_group_by_product/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1965 [MIG] stock_exception: migration to 16.0
  setup/stock_exception/odoo/addons/stock_exception
  setup/stock_exception/setup.py
  stock_exception/README.rst
  stock_exception/__init__.py
  stock_exception/__manifest__.py
  stock_exception/data/stock_exception_data.xml
  stock_exception/i18n/es.po
  stock_exception/i18n/it.po
  stock_exception/i18n/stock_exception.pot
  stock_exception/models/__init__.py
  stock_exception/models/exception_rule.py
  stock_exception/models/stock.py
  stock_exception/models/stock_move.py
  stock_exception/readme/CONTRIBUTORS.rst
  stock_exception/readme/DESCRIPTION.rst
  stock_exception/security/ir.model.access.csv
  stock_exception/static/description/icon.png
  stock_exception/static/description/index.html
  stock_exception/views/stock_view.xml
  stock_exception/wizard/__init__.py
  stock_exception/wizard/stock_exception_confirm.py
  stock_exception/wizard/stock_exception_confirm_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2047 [15.0][FIX] stock_inventory: prevent error when applying inventory without quantities
  stock_inventory/models/stock_quant.py
Labels: approved, bot is merging ⏳

#2048 [16.0][FIX] stock_inventory: prevent error when applying inventory without quantities
  stock_inventory/models/stock_quant.py
Labels: bot is merging ⏳
