Repository OCA/stock-logistics-warehouse, pull requests merged in 2025-06, with the labels that each got.

#2328 [18.0][MIG] stock_location_children
  stock_location_children/README.rst
  stock_location_children/__init__.py
  stock_location_children/__manifest__.py
  stock_location_children/i18n/fr.po
  stock_location_children/i18n/it.po
  stock_location_children/i18n/stock_location_children.pot
  stock_location_children/models/__init__.py
  stock_location_children/models/stock_location.py
  stock_location_children/pyproject.toml
  stock_location_children/readme/CONTRIBUTORS.md
  stock_location_children/readme/DESCRIPTION.md
  stock_location_children/readme/USAGE.md
  stock_location_children/static/description/children.png
  stock_location_children/static/description/icon.png
  stock_location_children/static/description/index.html
  stock_location_children/tests/__init__.py
  stock_location_children/tests/test_stock_location_children.py
  stock_location_children/views/stock_location.xml
Labels: migration

#2362 [18.0][FIX] stock_location_bin_name: remove constraint on `location_name_format`
  stock_location_bin_name/models/stock_location.py
  stock_location_bin_name/tests/test_stock_location_bin_name.py
Labels: approved, merged 🎉

#2336 [18.0][MIG] stock_inventory_count_to_zero: Migration to 18.0
  stock_inventory_count_to_zero/README.rst
  stock_inventory_count_to_zero/__init__.py
  stock_inventory_count_to_zero/__manifest__.py
  stock_inventory_count_to_zero/i18n/es.po
  stock_inventory_count_to_zero/i18n/fr.po
  stock_inventory_count_to_zero/i18n/it.po
  stock_inventory_count_to_zero/i18n/stock_inventory_count_to_zero.pot
  stock_inventory_count_to_zero/i18n/stock_request_count_to_zero.pot
  stock_inventory_count_to_zero/models/__init__.py
  stock_inventory_count_to_zero/models/stock_quant.py
  stock_inventory_count_to_zero/pyproject.toml
  stock_inventory_count_to_zero/readme/CONTRIBUTORS.md
  stock_inventory_count_to_zero/readme/DESCRIPTION.md
  stock_inventory_count_to_zero/readme/USAGE.md
  stock_inventory_count_to_zero/static/description/icon.png
  stock_inventory_count_to_zero/static/description/index.html
  stock_inventory_count_to_zero/tests/__init__.py
  stock_inventory_count_to_zero/tests/test_stock_inventory_count_to_zero.py
  stock_inventory_count_to_zero/wizards/__init__.py
  stock_inventory_count_to_zero/wizards/stock_request_count.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2371 [18.0][MIG] stock_vertical_lift_server_env: Migration to 18.0
  stock_vertical_lift_server_env/README.rst
  stock_vertical_lift_server_env/__init__.py
  stock_vertical_lift_server_env/__manifest__.py
  stock_vertical_lift_server_env/i18n/it.po
  stock_vertical_lift_server_env/i18n/stock_vertical_lift_server_env.pot
  stock_vertical_lift_server_env/models/__init__.py
  stock_vertical_lift_server_env/models/vertical_lift_shuttle.py
  stock_vertical_lift_server_env/pyproject.toml
  stock_vertical_lift_server_env/readme/CONTRIBUTORS.md
  stock_vertical_lift_server_env/readme/DESCRIPTION.md
  stock_vertical_lift_server_env/static/description/icon.png
  stock_vertical_lift_server_env/static/description/index.html
Labels: approved, bot is merging ⏳

#2373 [16.0][FIX] stock_location_release_channel_restriction: it.po translation error
  stock_location_release_channel_restriction/i18n/it.po
Labels: bot is merging ⏳

#2366 [18.0][MIG] stock_move_packaging_qty
  stock_move_packaging_qty/README.rst
  stock_move_packaging_qty/__init__.py
  stock_move_packaging_qty/__manifest__.py
  stock_move_packaging_qty/hooks.py
  stock_move_packaging_qty/i18n/es.po
  stock_move_packaging_qty/i18n/it.po
  stock_move_packaging_qty/i18n/stock_move_packaging_qty.pot
  stock_move_packaging_qty/migrations/18.0.0/pre-migrate.py
  stock_move_packaging_qty/models/__init__.py
  stock_move_packaging_qty/models/stock_move.py
  stock_move_packaging_qty/models/stock_move_line.py
  stock_move_packaging_qty/pyproject.toml
  stock_move_packaging_qty/readme/CONTRIBUTORS.md
  stock_move_packaging_qty/readme/DESCRIPTION.md
  stock_move_packaging_qty/readme/ROADMAP.md
  stock_move_packaging_qty/static/description/icon.png
  stock_move_packaging_qty/static/description/index.html
  stock_move_packaging_qty/tests/__init__.py
  stock_move_packaging_qty/tests/test_stock_move_packaging_qty.py
  stock_move_packaging_qty/views/report_stock_picking.xml
  stock_move_packaging_qty/views/stock_move_line_view.xml
  stock_move_packaging_qty/views/stock_move_view.xml
  stock_move_packaging_qty/views/stock_picking_view.xml
Labels: approved, migration, bot is merging ⏳
