Repository OCA/stock-logistics-warehouse, pull requests merged in 2025-03, with the labels that each got.

#2281 [16.0][FIX] stock_picking_procure_method: Change SavepointCase to TransactionCase
  stock_location_package_restriction/tests/common.py
  stock_picking_procure_method/tests/test_stock_picking_procure_method.py
Labels: bot is merging ⏳

#2282 [17.0][FW] stock_picking_volume: multiple ports from 16.0
  stock_picking_volume/hooks.py
  stock_picking_volume/views/stock_picking.xml
Labels: bot is merging ⏳

#2269 [18.0] [MIG] stock_location_bin_name
  stock_location_bin_name/README.rst
  stock_location_bin_name/__init__.py
  stock_location_bin_name/__manifest__.py
  stock_location_bin_name/i18n/it.po
  stock_location_bin_name/i18n/stock_location_bin_name.pot
  stock_location_bin_name/models/__init__.py
  stock_location_bin_name/models/stock_location.py
  stock_location_bin_name/pyproject.toml
  stock_location_bin_name/readme/CONTRIBUTORS.md
  stock_location_bin_name/readme/CREDITS.md
  stock_location_bin_name/readme/DESCRIPTION.md
  stock_location_bin_name/static/description/icon.png
  stock_location_bin_name/static/description/index.html
  stock_location_bin_name/tests/__init__.py
  stock_location_bin_name/tests/test_stock_location_bin_name.py
  stock_location_bin_name/tests/test_stock_location_formatter.py
  stock_location_bin_name/views/stock_location.xml
Labels: approved, ready to merge, bot is merging ⏳

#2268 [14.0][FIX] stock_reserve_rule: favor largest package when reserving full packaging
  stock_reserve_rule/models/stock_reserve_rule.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: bot is merging ⏳

#2267 [18.0][MIG] stock_picking_supplier_ref: Migration to 18.0
  stock_picking_supplier_ref/README.rst
  stock_picking_supplier_ref/__init__.py
  stock_picking_supplier_ref/__manifest__.py
  stock_picking_supplier_ref/i18n/es.po
  stock_picking_supplier_ref/i18n/it.po
  stock_picking_supplier_ref/i18n/stock_picking_supplier_ref.pot
  stock_picking_supplier_ref/models/__init__.py
  stock_picking_supplier_ref/models/stock_picking.py
  stock_picking_supplier_ref/pyproject.toml
  stock_picking_supplier_ref/readme/CONTRIBUTORS.md
  stock_picking_supplier_ref/readme/DESCRIPTION.md
  stock_picking_supplier_ref/readme/HISTORY.md
  stock_picking_supplier_ref/readme/USAGE.md
  stock_picking_supplier_ref/static/description/icon.png
  stock_picking_supplier_ref/static/description/index.html
  stock_picking_supplier_ref/tests/__init__.py
  stock_picking_supplier_ref/tests/test_supplier_ref.py
  stock_picking_supplier_ref/views/stock_picking.xml
Labels: bot is merging ⏳

#2262 [18.0][MIG] stock_picking_product_assortment
  stock_picking_product_assortment/README.rst
  stock_picking_product_assortment/__init__.py
  stock_picking_product_assortment/__manifest__.py
  stock_picking_product_assortment/i18n/es.po
  stock_picking_product_assortment/i18n/stock_picking_product_assortment.pot
  stock_picking_product_assortment/models/__init__.py
  stock_picking_product_assortment/models/stock_picking.py
  stock_picking_product_assortment/pyproject.toml
  stock_picking_product_assortment/readme/CONFIGURE.md
  stock_picking_product_assortment/readme/CONTRIBUTORS.md
  stock_picking_product_assortment/readme/DESCRIPTION.md
  stock_picking_product_assortment/readme/USAGE.md
  stock_picking_product_assortment/static/description/icon.png
  stock_picking_product_assortment/static/description/index.html
  stock_picking_product_assortment/tests/__init__.py
  stock_picking_product_assortment/tests/test_stock_picking_product_assortment.py
  stock_picking_product_assortment/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#1992 [16][ADD] stock_inventory_quantity_history
  setup/stock_inventory_quantity_history/odoo/addons/stock_inventory_quantity_history
  setup/stock_inventory_quantity_history/setup.py
  stock_inventory_quantity_history/README.rst
  stock_inventory_quantity_history/__init__.py
  stock_inventory_quantity_history/__manifest__.py
  stock_inventory_quantity_history/models/__init__.py
  stock_inventory_quantity_history/models/stock_move_line.py
  stock_inventory_quantity_history/models/stock_quant.py
  stock_inventory_quantity_history/readme/CONTRIBUTORS.rst
  stock_inventory_quantity_history/readme/DESCRIPTION.rst
  stock_inventory_quantity_history/readme/USAGE.rst
  stock_inventory_quantity_history/static/description/index.html
  stock_inventory_quantity_history/tests/__init__.py
  stock_inventory_quantity_history/tests/test_inventory_quantity_history.py
  stock_inventory_quantity_history/views/stock_move_line_views.xml
Labels: needs review, approved, bot is merging ⏳

#2290 [18.0] [MIG] stock_picking_completion_info
  stock_picking_completion_info/README.rst
  stock_picking_completion_info/__init__.py
  stock_picking_completion_info/__manifest__.py
  stock_picking_completion_info/i18n/fr.po
  stock_picking_completion_info/i18n/it.po
  stock_picking_completion_info/i18n/stock_picking_completion_info.pot
  stock_picking_completion_info/models/__init__.py
  stock_picking_completion_info/models/stock_picking.py
  stock_picking_completion_info/pyproject.toml
  stock_picking_completion_info/readme/CONTRIBUTORS.md
  stock_picking_completion_info/readme/DESCRIPTION.md
  stock_picking_completion_info/static/description/icon.png
  stock_picking_completion_info/static/description/index.html
  stock_picking_completion_info/tests/__init__.py
  stock_picking_completion_info/tests/test_stock_picking_completion_info.py
  stock_picking_completion_info/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#2294 [18.0][IMP] stock_packaging_calculator: transitional module to install `product_packaging_calculator`
  requirements.txt
  stock_packaging_calculator/README.rst
  stock_packaging_calculator/__init__.py
  stock_packaging_calculator/__manifest__.py
  stock_packaging_calculator/i18n/it.po
  stock_packaging_calculator/i18n/stock_packaging_calculator.pot
  stock_packaging_calculator/models/__init__.py
  stock_packaging_calculator/models/product.py
  stock_packaging_calculator/models/product_qty_by_packaging_mixin.py
  stock_packaging_calculator/readme/CREDITS.md
  stock_packaging_calculator/readme/DESCRIPTION.md
  stock_packaging_calculator/readme/ROADMAP.md
  stock_packaging_calculator/readme/USAGE.md
  stock_packaging_calculator/static/description/index.html
  stock_packaging_calculator/tests/__init__.py
  stock_packaging_calculator/tests/common.py
  stock_packaging_calculator/tests/models.py
  stock_packaging_calculator/tests/test_packaging_calc.py
  stock_packaging_calculator/tests/test_pkg_qty_str.py
  stock_packaging_calculator/tests/test_product_qty_by_packaging_mixin.py
  stock_packaging_calculator/tests/utils.py
Labels: bot is merging ⏳

#2300 [16.0] Remove warnings in tests
  stock_cycle_count/tests/test_stock_cycle_count.py
  stock_location_children/tests/test_stock_location_children.py
  stock_location_pending_move/tests/test_location_pending_move.py
  stock_move_auto_assign_auto_release/tests/test_assign_auto_release.py
  stock_picking_volume/tests/test_stock_picking_volume.py
  stock_quant_safe_inventory/tests/test_safe_inventory.py
  stock_reserve_rule/tests/test_reserve_rule.py
Labels: enhancement, bot is merging ⏳

#2298 [18.0][MIG] stock_demand_estimate_matrix
  stock_demand_estimate_matrix/README.rst
  stock_demand_estimate_matrix/__init__.py
  stock_demand_estimate_matrix/__manifest__.py
  stock_demand_estimate_matrix/i18n/it.po
  stock_demand_estimate_matrix/i18n/stock_demand_estimate_matrix.pot
  stock_demand_estimate_matrix/models/__init__.py
  stock_demand_estimate_matrix/models/date_range.py
  stock_demand_estimate_matrix/models/stock_demand_estimate.py
  stock_demand_estimate_matrix/pyproject.toml
  stock_demand_estimate_matrix/readme/CONTRIBUTORS.md
  stock_demand_estimate_matrix/readme/DESCRIPTION.md
  stock_demand_estimate_matrix/readme/INSTALL.md
  stock_demand_estimate_matrix/readme/USAGE.md
  stock_demand_estimate_matrix/security/ir.model.access.csv
  stock_demand_estimate_matrix/static/description/icon.png
  stock_demand_estimate_matrix/static/description/index.html
  stock_demand_estimate_matrix/tests/__init__.py
  stock_demand_estimate_matrix/tests/test_stock_demand_estimate.py
  stock_demand_estimate_matrix/views/date_range.xml
  stock_demand_estimate_matrix/views/stock_demand_estimate_view.xml
  stock_demand_estimate_matrix/wizards/__init__.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_sheet_line.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard.py
  stock_demand_estimate_matrix/wizards/stock_demand_estimate_wizard_view.xml
Labels: approved, bot is merging ⏳

#2283 [18.0][MIG] stock_helper: Migration to 18.0. (split feature to stock_route_location_source)
  stock_route_location_source/README.rst
  stock_route_location_source/__init__.py
  stock_route_location_source/__manifest__.py
  stock_route_location_source/models/__init__.py
  stock_route_location_source/models/stock_route.py
  stock_route_location_source/pyproject.toml
  stock_route_location_source/readme/CONTRIBUTORS.md
  stock_route_location_source/readme/DESCRIPTION.md
  stock_route_location_source/static/description/icon.png
  stock_route_location_source/static/description/index.html
  stock_route_location_source/tests/__init__.py
  stock_route_location_source/tests/test_get_source_location.py
Labels: approved, ready to merge, bot is merging ⏳

#2295 [18.0][MIG] stock_inventory_discrepancy: Migration to version 18.0
  stock_inventory_discrepancy/README.rst
  stock_inventory_discrepancy/__init__.py
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/hooks.py
  stock_inventory_discrepancy/i18n/cs_CZ.po
  stock_inventory_discrepancy/i18n/de.po
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/es_ES.po
  stock_inventory_discrepancy/i18n/fr.po
  stock_inventory_discrepancy/i18n/fr_FR.po
  stock_inventory_discrepancy/i18n/hr.po
  stock_inventory_discrepancy/i18n/it.po
  stock_inventory_discrepancy/i18n/nl.po
  stock_inventory_discrepancy/i18n/nl_NL.po
  stock_inventory_discrepancy/i18n/pt_BR.po
  stock_inventory_discrepancy/i18n/sl.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/i18n/tr_TR.po
  stock_inventory_discrepancy/i18n/zh_CN.po
  stock_inventory_discrepancy/models/__init__.py
  stock_inventory_discrepancy/models/stock_location.py
  stock_inventory_discrepancy/models/stock_quant.py
  stock_inventory_discrepancy/models/stock_warehouse.py
  stock_inventory_discrepancy/pyproject.toml
  stock_inventory_discrepancy/readme/CONFIGURE.md
  stock_inventory_discrepancy/readme/CONTRIBUTORS.md
  stock_inventory_discrepancy/readme/DESCRIPTION.md
  stock_inventory_discrepancy/readme/USAGE.md
  stock_inventory_discrepancy/security/ir.model.access.csv
  stock_inventory_discrepancy/security/stock_inventory_discrepancy_security.xml
  stock_inventory_discrepancy/static/description/icon.png
  stock_inventory_discrepancy/static/description/index.html
  stock_inventory_discrepancy/tests/__init__.py
  stock_inventory_discrepancy/tests/test_inventory_discrepancy.py
  stock_inventory_discrepancy/views/stock_location_view.xml
  stock_inventory_discrepancy/views/stock_quant_view.xml
  stock_inventory_discrepancy/views/stock_warehouse_view.xml
  stock_inventory_discrepancy/wizards/__init__.py
  stock_inventory_discrepancy/wizards/confirm_discrepancy_wiz.py
  stock_inventory_discrepancy/wizards/confirm_discrepancy_wiz.xml
Labels: approved, bot is merging ⏳

#2034 [17.0][MIG] stock_picking_show_linked : Migration to 17.0
  stock_picking_show_linked/README.rst
  stock_picking_show_linked/__init__.py
  stock_picking_show_linked/__manifest__.py
  stock_picking_show_linked/i18n/it.po
  stock_picking_show_linked/i18n/stock_picking_show_linked.pot
  stock_picking_show_linked/models/__init__.py
  stock_picking_show_linked/models/stock_picking.py
  stock_picking_show_linked/pyproject.toml
  stock_picking_show_linked/readme/CONTRIBUTORS.md
  stock_picking_show_linked/readme/DESCRIPTION.md
  stock_picking_show_linked/static/description/icon.png
  stock_picking_show_linked/static/description/index.html
  stock_picking_show_linked/views/stock_picking.xml
Labels: approved, bot is merging ⏳
