Repository OCA/stock-logistics-warehouse, pull requests merged in 2025-07, with the labels that each got.

#2380 [18.0][FIX] stock_warehouse_out_pull: Added tagged in test case
  stock_warehouse_out_pull/tests/test_delivery_steps.py
Labels: bot is merging ⏳

#2367 [FIX] stock_location_fill_state: Consider a being emptied location as being filled
  stock_location_fill_state/models/stock_location.py
  stock_location_fill_state/tests/test_location_fill_state.py
Labels: enhancement, bot is merging ⏳

#2387 [DOC] Improve README for stock_route_location_source
  stock_route_location_source/readme/CONTRIBUTORS.md
  stock_route_location_source/readme/DESCRIPTION.md
Labels: enhancement, approved, bot is merging ⏳

#2384 [FIX] stock_picking_supplier_ref: clarify label and help text for supplier_reference field
  stock_picking_supplier_ref/i18n/es.po
  stock_picking_supplier_ref/i18n/stock_picking_supplier_ref.pot
  stock_picking_supplier_ref/models/stock_picking.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#2390 [18.0][IMP] stock_picking_volume: Add hooks
  stock_picking_volume/models/stock_move.py
  stock_picking_volume/models/stock_picking.py
Labels: bot is merging ⏳

#2395 [16.0][FIX] stock_cycle_count: fix multiple issues in location accuracy report
  stock_cycle_count/reports/report_stock_location_accuracy.py
  stock_cycle_count/reports/stock_cycle_count_report.xml
  stock_cycle_count/reports/stock_location_accuracy_report.xml
Labels: bot is merging ⏳

#2398 [15.0][FIX] stock_cycle_count: fix multiple issues in location accuracy report
  stock_cycle_count/reports/report_stock_location_accuracy.py
  stock_cycle_count/reports/stock_cycle_count_report.xml
  stock_cycle_count/reports/stock_location_accuracy_report.xml
Labels: bot is merging ⏳
