Repository OCA/stock-logistics-warehouse, pull requests merged in 2025-01, with the labels that each got.

#2233 [15.0][FIX] stock_move_location: prevent putaway rules when we don't need them
  stock_move_location/wizard/stock_move_location.py
Labels: approved, bot is merging ⏳

#2237 [17.0][FIX] stock_inventory: Remove state in fields
  stock_inventory/models/stock_inventory.py
Labels: approved, bot is merging ⏳

#2159 [16.0][FIX] stock_valuation_layer_accounting_date: prevent tests failed for some timezone
  stock_valuation_layer_accounting_date/tests/test_stock_valuation_layer_accounting_date.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2199 [16.0][MIG] product_route_profile
  product_route_profile/README.rst
  product_route_profile/__init__.py
  product_route_profile/__manifest__.py
  product_route_profile/hooks.py
  product_route_profile/i18n/fr.po
  product_route_profile/i18n/it.po
  product_route_profile/i18n/nl.po
  product_route_profile/i18n/product_route_profile.pot
  product_route_profile/models/__init__.py
  product_route_profile/models/product_template.py
  product_route_profile/models/route_profile.py
  product_route_profile/readme/CONTRIBUTORS.rst
  product_route_profile/readme/DESCRIPTION.rst
  product_route_profile/readme/ROADMAP.rst
  product_route_profile/readme/USAGE.rst
  product_route_profile/security/ir.model.access.csv
  product_route_profile/static/description/icon.png
  product_route_profile/static/description/icon.svg
  product_route_profile/static/description/index.html
  product_route_profile/tests/__init__.py
  product_route_profile/tests/test_product_route_profile.py
  product_route_profile/views/product_template.xml
  product_route_profile/views/route_profile.xml
  setup/product_route_profile/odoo/addons/product_route_profile
  setup/product_route_profile/setup.py
Labels: approved, bot is merging ⏳

#2121 [17.0][MIG] stock_secondary_unit: Migration to 17.0
  stock_secondary_unit/README.rst
  stock_secondary_unit/__init__.py
  stock_secondary_unit/__manifest__.py
  stock_secondary_unit/i18n/es.po
  stock_secondary_unit/i18n/fi.po
  stock_secondary_unit/i18n/it.po
  stock_secondary_unit/i18n/stock_secondary_unit.pot
  stock_secondary_unit/i18n/zh_CN.po
  stock_secondary_unit/models/__init__.py
  stock_secondary_unit/models/product_product.py
  stock_secondary_unit/models/product_template.py
  stock_secondary_unit/models/stock_move.py
  stock_secondary_unit/models/stock_product_secondary_unit_mixin.py
  stock_secondary_unit/pyproject.toml
  stock_secondary_unit/readme/CONTRIBUTORS.md
  stock_secondary_unit/readme/DESCRIPTION.md
  stock_secondary_unit/readme/USAGE.md
  stock_secondary_unit/report/report_deliveryslip.xml
  stock_secondary_unit/static/description/icon.png
  stock_secondary_unit/static/description/index.html
  stock_secondary_unit/tests/__init__.py
  stock_secondary_unit/tests/test_stock_secondary_unit.py
  stock_secondary_unit/views/product_views.xml
  stock_secondary_unit/views/stock_move_views.xml
  stock_secondary_unit/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2222 [14.0][IMP] stock_location_last_inventory_date: Make last_inventory_date storeable
  stock_location_last_inventory_date/__init__.py
  stock_location_last_inventory_date/__manifest__.py
  stock_location_last_inventory_date/hooks.py
  stock_location_last_inventory_date/migrations/14.0.2.0.0/post-migration.py
  stock_location_last_inventory_date/models/__init__.py
  stock_location_last_inventory_date/models/stock_inventory.py
  stock_location_last_inventory_date/models/stock_location.py
  stock_location_last_inventory_date/readme/CONTRIBUTORS.rst
  stock_location_last_inventory_date/tests/test_stock_location.py
Labels: approved, ready to merge, bot is merging ⏳

#2245 [18.0][MIG] stock_archive_constraint: Migration to 18.0
  stock_archive_constraint/README.rst
  stock_archive_constraint/__init__.py
  stock_archive_constraint/__manifest__.py
  stock_archive_constraint/i18n/es.po
  stock_archive_constraint/i18n/it.po
  stock_archive_constraint/i18n/stock_archive_constraint.pot
  stock_archive_constraint/models/__init__.py
  stock_archive_constraint/models/product_product.py
  stock_archive_constraint/models/stock_location.py
  stock_archive_constraint/pyproject.toml
  stock_archive_constraint/readme/CONTRIBUTORS.md
  stock_archive_constraint/readme/DESCRIPTION.md
  stock_archive_constraint/readme/USAGE.md
  stock_archive_constraint/static/description/icon.png
  stock_archive_constraint/static/description/index.html
  stock_archive_constraint/tests/__init__.py
  stock_archive_constraint/tests/test_location_archive_constraint.py
Labels: approved, bot is merging ⏳

#2238 [ADD] stock_lot_multi_image: New module
  setup/stock_lot_multi_image/odoo/addons/stock_lot_multi_image
  setup/stock_lot_multi_image/setup.py
  stock_lot_multi_image/README.rst
  stock_lot_multi_image/__init__.py
  stock_lot_multi_image/__manifest__.py
  stock_lot_multi_image/models/__init__.py
  stock_lot_multi_image/models/stock_lot.py
  stock_lot_multi_image/readme/CONTEXT.md
  stock_lot_multi_image/readme/DESCRIPTION.md
  stock_lot_multi_image/readme/USAGE.md
  stock_lot_multi_image/static/description/icon.png
  stock_lot_multi_image/static/description/index.html
  stock_lot_multi_image/static/description/usage.png
  stock_lot_multi_image/views/stock_lot_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2228 [18.0][MIG] stock_location_zone: Migration to 18.0
  stock_location_zone/README.rst
  stock_location_zone/__init__.py
  stock_location_zone/__manifest__.py
  stock_location_zone/i18n/es.po
  stock_location_zone/i18n/it.po
  stock_location_zone/i18n/stock_location_zone.pot
  stock_location_zone/i18n/zh_CN.po
  stock_location_zone/models/__init__.py
  stock_location_zone/models/stock_location.py
  stock_location_zone/pyproject.toml
  stock_location_zone/readme/CONTRIBUTORS.md
  stock_location_zone/readme/CREDITS.md
  stock_location_zone/readme/DESCRIPTION.md
  stock_location_zone/static/description/icon.png
  stock_location_zone/static/description/index.html
  stock_location_zone/tests/__init__.py
  stock_location_zone/tests/test_stock_location_zone.py
  stock_location_zone/views/stock_location.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2190 [16.0][MIG] stock_location_children
  setup/stock_location_children/odoo/addons/stock_location_children
  setup/stock_location_children/setup.py
  stock_location_children/README.rst
  stock_location_children/__init__.py
  stock_location_children/__manifest__.py
  stock_location_children/i18n/it.po
  stock_location_children/i18n/stock_location_children.pot
  stock_location_children/models/__init__.py
  stock_location_children/models/stock_location.py
  stock_location_children/readme/CONTRIBUTORS.rst
  stock_location_children/readme/DESCRIPTION.rst
  stock_location_children/readme/USAGE.rst
  stock_location_children/static/description/children.png
  stock_location_children/static/description/icon.png
  stock_location_children/static/description/index.html
  stock_location_children/tests/__init__.py
  stock_location_children/tests/test_stock_location_children.py
  stock_location_children/views/stock_location.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2243 [18.0][MIG] stock_location_empty: Migration to 18.0
  stock_location_empty/README.rst
  stock_location_empty/__init__.py
  stock_location_empty/__manifest__.py
  stock_location_empty/i18n/de.po
  stock_location_empty/i18n/fr.po
  stock_location_empty/i18n/it.po
  stock_location_empty/i18n/stock_location_empty.pot
  stock_location_empty/models/__init__.py
  stock_location_empty/models/stock_location.py
  stock_location_empty/pyproject.toml
  stock_location_empty/readme/CONTRIBUTORS.md
  stock_location_empty/readme/CREDITS.md
  stock_location_empty/readme/DESCRIPTION.md
  stock_location_empty/static/description/icon.png
  stock_location_empty/static/description/index.html
  stock_location_empty/tests/__init__.py
  stock_location_empty/tests/test_stock_location_empty.py
  stock_location_empty/views/stock.xml
Labels: approved, bot is merging ⏳
