Repository OCA/stock-logistics-warehouse, pull requests merged in 2025-05, with the labels that each got.

#2288 [18.0][MIG] stock_product_qty_by_packaging
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/__init__.py
  stock_product_qty_by_packaging/__manifest__.py
  stock_product_qty_by_packaging/i18n/fr.po
  stock_product_qty_by_packaging/i18n/it.po
  stock_product_qty_by_packaging/i18n/stock_product_qty_by_packaging.pot
  stock_product_qty_by_packaging/models/__init__.py
  stock_product_qty_by_packaging/models/stock_move.py
  stock_product_qty_by_packaging/models/stock_move_line.py
  stock_product_qty_by_packaging/models/stock_quant.py
  stock_product_qty_by_packaging/pyproject.toml
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/CREDITS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/icon.png
  stock_product_qty_by_packaging/static/description/index.html
  stock_product_qty_by_packaging/tests/__init__.py
  stock_product_qty_by_packaging/tests/test_stock.py
  stock_product_qty_by_packaging/views/stock_picking.xml
Labels: migration, bot is merging ⏳

#2232 [16.0][IMP] stock_inventory_discrepancy: better inheritance
  stock_inventory_discrepancy/__init__.py
  stock_inventory_discrepancy/__manifest__.py
  stock_inventory_discrepancy/hooks.py
  stock_inventory_discrepancy/models/stock_quant.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2327 [18.0][MIG] stock_storage_category_capacity_name: Migration to 18.0
  stock_storage_category_capacity_name/README.rst
  stock_storage_category_capacity_name/__init__.py
  stock_storage_category_capacity_name/__manifest__.py
  stock_storage_category_capacity_name/i18n/it.po
  stock_storage_category_capacity_name/i18n/stock_storage_category_capacity_name.pot
  stock_storage_category_capacity_name/models/__init__.py
  stock_storage_category_capacity_name/models/stock_storage_category_capacity.py
  stock_storage_category_capacity_name/pyproject.toml
  stock_storage_category_capacity_name/readme/CONTRIBUTORS.rst
  stock_storage_category_capacity_name/readme/DESCRIPTION.rst
  stock_storage_category_capacity_name/static/description/icon.png
  stock_storage_category_capacity_name/static/description/index.html
  stock_storage_category_capacity_name/tests/__init__.py
  stock_storage_category_capacity_name/tests/test_capacity_name.py
Labels: migration, bot is merging ⏳

#2303 [IMP] [16.0] stock_inventory_discrepancy: UI improvements
  stock_inventory_discrepancy/README.rst
  stock_inventory_discrepancy/i18n/es.po
  stock_inventory_discrepancy/i18n/stock_inventory_discrepancy.pot
  stock_inventory_discrepancy/readme/CONFIGURE.rst
  stock_inventory_discrepancy/static/description/index.html
  stock_inventory_discrepancy/views/res_config_settings_view.xml
  stock_inventory_discrepancy/views/stock_location_view.xml
  stock_inventory_discrepancy/views/stock_quant_view.xml
  stock_inventory_discrepancy/views/stock_warehouse_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2332 [18.0][MIG] stock_quant_reservation_info: Migration to version 18.0
  stock_quant_reservation_info/README.rst
  stock_quant_reservation_info/__init__.py
  stock_quant_reservation_info/__manifest__.py
  stock_quant_reservation_info/i18n/it.po
  stock_quant_reservation_info/i18n/stock_quant_reservation_info.pot
  stock_quant_reservation_info/models/__init__.py
  stock_quant_reservation_info/models/stock_move_line.py
  stock_quant_reservation_info/models/stock_quant.py
  stock_quant_reservation_info/pyproject.toml
  stock_quant_reservation_info/readme/CONTRIBUTORS.md
  stock_quant_reservation_info/readme/DESCRIPTION.md
  stock_quant_reservation_info/readme/USAGE.md
  stock_quant_reservation_info/static/description/icon.png
  stock_quant_reservation_info/static/description/index.html
  stock_quant_reservation_info/views/stock_move_line.xml
  stock_quant_reservation_info/views/stock_quant.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2318 [18.0][MIG] stock_quant_reservation_info_mrp: Migration to 18.0
  stock_quant_reservation_info_mrp/README.rst
  stock_quant_reservation_info_mrp/__init__.py
  stock_quant_reservation_info_mrp/__manifest__.py
  stock_quant_reservation_info_mrp/i18n/it.po
  stock_quant_reservation_info_mrp/i18n/stock_quant_reservation_info_mrp.pot
  stock_quant_reservation_info_mrp/models/__init__.py
  stock_quant_reservation_info_mrp/models/stock_move_line.py
  stock_quant_reservation_info_mrp/pyproject.toml
  stock_quant_reservation_info_mrp/readme/CONTRIBUTORS.md
  stock_quant_reservation_info_mrp/readme/DESCRIPTION.md
  stock_quant_reservation_info_mrp/readme/USAGE.md
  stock_quant_reservation_info_mrp/static/description/icon.png
  stock_quant_reservation_info_mrp/static/description/index.html
  stock_quant_reservation_info_mrp/views/stock_move_line.xml
Labels: approved, bot is merging ⏳

#2340 [18.0][FIX] pre-commit fix
  stock_product_qty_by_packaging/README.rst
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.md
  stock_product_qty_by_packaging/readme/CONTRIBUTORS.rst
  stock_product_qty_by_packaging/readme/CREDITS.md
  stock_product_qty_by_packaging/readme/CREDITS.rst
  stock_product_qty_by_packaging/readme/DESCRIPTION.md
  stock_product_qty_by_packaging/readme/DESCRIPTION.rst
  stock_product_qty_by_packaging/static/description/index.html
  stock_storage_category_capacity_name/README.rst
  stock_storage_category_capacity_name/readme/CONTRIBUTORS.md
  stock_storage_category_capacity_name/readme/CONTRIBUTORS.rst
  stock_storage_category_capacity_name/readme/DESCRIPTION.md
  stock_storage_category_capacity_name/readme/DESCRIPTION.rst
  stock_storage_category_capacity_name/static/description/index.html
Labels: bot is merging ⏳

#2209 [18.0][MIG] stock_location_lockdown: Migration to 18.0.
  stock_location_lockdown/README.rst
  stock_location_lockdown/__init__.py
  stock_location_lockdown/__manifest__.py
  stock_location_lockdown/i18n/es.po
  stock_location_lockdown/i18n/fr.po
  stock_location_lockdown/i18n/it.po
  stock_location_lockdown/i18n/pt.po
  stock_location_lockdown/i18n/stock_location_lockdown.pot
  stock_location_lockdown/i18n/zh_CN.po
  stock_location_lockdown/models/__init__.py
  stock_location_lockdown/models/stock_location.py
  stock_location_lockdown/models/stock_quant.py
  stock_location_lockdown/pyproject.toml
  stock_location_lockdown/readme/CONTRIBUTORS.md
  stock_location_lockdown/readme/DESCRIPTION.md
  stock_location_lockdown/readme/USAGE.md
  stock_location_lockdown/static/description/icon.png
  stock_location_lockdown/static/description/index.html
  stock_location_lockdown/tests/__init__.py
  stock_location_lockdown/tests/test_block_stock_location_entrance.py
  stock_location_lockdown/views/stock_location.xml
Labels: migration, bot is merging ⏳

#2136 [17.0] [MIG] procurement_auto_create_group: Migration to 17.0
  procurement_auto_create_group/README.rst
  procurement_auto_create_group/__init__.py
  procurement_auto_create_group/__manifest__.py
  procurement_auto_create_group/i18n/ca.po
  procurement_auto_create_group/i18n/cs_CZ.po
  procurement_auto_create_group/i18n/de.po
  procurement_auto_create_group/i18n/es.po
  procurement_auto_create_group/i18n/es_MX.po
  procurement_auto_create_group/i18n/fr.po
  procurement_auto_create_group/i18n/hr.po
  procurement_auto_create_group/i18n/it.po
  procurement_auto_create_group/i18n/procurement_auto_create_group.pot
  procurement_auto_create_group/i18n/pt_BR.po
  procurement_auto_create_group/i18n/pt_PT.po
  procurement_auto_create_group/i18n/ro.po
  procurement_auto_create_group/i18n/sk.po
  procurement_auto_create_group/i18n/sl.po
  procurement_auto_create_group/i18n/tr_TR.po
  procurement_auto_create_group/i18n/vi_VN.po
  procurement_auto_create_group/i18n/zh_CN.po
  procurement_auto_create_group/models/__init__.py
  procurement_auto_create_group/models/procurement_group.py
  procurement_auto_create_group/models/stock_rule.py
  procurement_auto_create_group/pyproject.toml
  procurement_auto_create_group/readme/CONFIGURE.md
  procurement_auto_create_group/readme/CONTRIBUTORS.md
  procurement_auto_create_group/readme/DESCRIPTION.md
  procurement_auto_create_group/readme/USAGE.md
  procurement_auto_create_group/static/description/icon.png
  procurement_auto_create_group/static/description/index.html
  procurement_auto_create_group/tests/__init__.py
  procurement_auto_create_group/tests/test_auto_create.py
  procurement_auto_create_group/views/procurement_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2188 [16.0][ADD] stock_location_fill_state
  setup/stock_location_fill_state/odoo/addons/stock_location_fill_state
  setup/stock_location_fill_state/setup.py
  stock_location_fill_state/README.rst
  stock_location_fill_state/__init__.py
  stock_location_fill_state/__manifest__.py
  stock_location_fill_state/i18n/fr.po
  stock_location_fill_state/models/__init__.py
  stock_location_fill_state/models/stock_location.py
  stock_location_fill_state/readme/CONTEXT.md
  stock_location_fill_state/readme/CONTRIBUTORS.md
  stock_location_fill_state/readme/DESCRIPTION.md
  stock_location_fill_state/readme/USAGE.md
  stock_location_fill_state/static/description/fill_state.png
  stock_location_fill_state/static/description/icon.png
  stock_location_fill_state/static/description/index.html
  stock_location_fill_state/tests/__init__.py
  stock_location_fill_state/tests/test_location_fill_state.py
  stock_location_fill_state/views/stock_location.xml
Labels: needs review, approved, bot is merging ⏳, no stale

#2348 [15.0][FIX] stock_inventory: string attribute duplicated in field count_stock_quants_string
  stock_inventory/models/stock_inventory.py
Labels: approved, bot is merging ⏳

#2350 [15.0][FIX] stock_reserve_rule: remove deprecated demo data
  stock_reserve_rule/__manifest__.py
  stock_reserve_rule/data/demo/stock_inventory_demo.xml
  stock_reserve_rule/static/description/index.html
Labels: approved, bot is merging ⏳

#2330 [18.0][MIG] stock_route_mto
  stock_route_mto/README.rst
  stock_route_mto/__init__.py
  stock_route_mto/__manifest__.py
  stock_route_mto/data/stock_route.xml
  stock_route_mto/hooks.py
  stock_route_mto/i18n/it.po
  stock_route_mto/i18n/stock_route_mto.pot
  stock_route_mto/models/__init__.py
  stock_route_mto/models/stock_route.py
  stock_route_mto/pyproject.toml
  stock_route_mto/readme/CONTRIBUTORS.md
  stock_route_mto/readme/DESCRIPTION.md
  stock_route_mto/readme/USAGE.md
  stock_route_mto/static/description/icon.png
  stock_route_mto/static/description/index.html
  stock_route_mto/views/stock_route.xml
Labels: approved, bot is merging ⏳

#1775 [15.0][MIG] product_route_profile
  product_route_profile/README.rst
  product_route_profile/__init__.py
  product_route_profile/__manifest__.py
  product_route_profile/hooks.py
  product_route_profile/i18n/fr.po
  product_route_profile/i18n/nl.po
  product_route_profile/i18n/product_route_profile.pot
  product_route_profile/models/__init__.py
  product_route_profile/models/product_template.py
  product_route_profile/models/route_profile.py
  product_route_profile/readme/CONTRIBUTORS.rst
  product_route_profile/readme/DESCRIPTION.rst
  product_route_profile/readme/ROADMAP.rst
  product_route_profile/readme/USAGE.rst
  product_route_profile/security/ir.model.access.csv
  product_route_profile/static/description/icon.png
  product_route_profile/static/description/icon.svg
  product_route_profile/static/description/index.html
  product_route_profile/tests/__init__.py
  product_route_profile/tests/test_product_route_profile.py
  product_route_profile/views/product_template.xml
  product_route_profile/views/route_profile.xml
  setup/product_route_profile/odoo/addons/product_route_profile
  setup/product_route_profile/setup.py
Labels: approved, stale

#2353 [18.0][ADD] stock_warehouse_out_pull: restore pull rules for multi-steps delivery route
  stock_warehouse_out_pull/README.rst
  stock_warehouse_out_pull/__init__.py
  stock_warehouse_out_pull/__manifest__.py
  stock_warehouse_out_pull/models/__init__.py
  stock_warehouse_out_pull/models/stock_warehouse.py
  stock_warehouse_out_pull/pyproject.toml
  stock_warehouse_out_pull/readme/CONFIGURE.md
  stock_warehouse_out_pull/readme/CONTRIBUTORS.md
  stock_warehouse_out_pull/readme/DESCRIPTION.md
  stock_warehouse_out_pull/static/description/index.html
  stock_warehouse_out_pull/tests/__init__.py
  stock_warehouse_out_pull/tests/test_delivery_steps.py
  stock_warehouse_out_pull/views/stock_warehouse.xml
Labels: approved, ready to merge, bot is merging ⏳

#2354 [15.0][IMP] stock_inventory_lockdown: add hook to decide what locations are excluded from the lockdown
  stock_inventory_lockdown/models/stock_move_line.py
Labels: approved, ready to merge, bot is merging ⏳
