Repository OCA/stock-logistics-warehouse, pull requests merged in 2025-08, with the labels that each got.

#2382 [MIG][18.0] stock_picking_volume_packaging
  stock_picking_volume_packaging/README.rst
  stock_picking_volume_packaging/__init__.py
  stock_picking_volume_packaging/__manifest__.py
  stock_picking_volume_packaging/i18n/it.po
  stock_picking_volume_packaging/i18n/stock_picking_volume_packaging.pot
  stock_picking_volume_packaging/models/__init__.py
  stock_picking_volume_packaging/models/product_product.py
  stock_picking_volume_packaging/pyproject.toml
  stock_picking_volume_packaging/readme/CONTRIBUTORS.md
  stock_picking_volume_packaging/readme/CREDITS.md
  stock_picking_volume_packaging/readme/DESCRIPTION.md
  stock_picking_volume_packaging/readme/USAGE.md
  stock_picking_volume_packaging/static/description/icon.png
  stock_picking_volume_packaging/static/description/index.html
  stock_picking_volume_packaging/tests/__init__.py
  stock_picking_volume_packaging/tests/test_stock_move_volume.py
Labels: needs review, migration, bot is merging ⏳

#2409 [18.0][IMP] stock_inventory: do not delete inv adjustment groups if in process or done + index
  stock_inventory/models/stock_inventory.py
  stock_inventory/models/stock_move_line.py
Labels: bot is merging ⏳

#2416 [18.0][MIG] stock_move_purchase_uom: Migration to 18.0
  stock_move_purchase_uom/README.rst
  stock_move_purchase_uom/__init__.py
  stock_move_purchase_uom/__manifest__.py
  stock_move_purchase_uom/i18n/stock_move_purchase_uom.pot
  stock_move_purchase_uom/models/__init__.py
  stock_move_purchase_uom/models/stock_move.py
  stock_move_purchase_uom/models/stock_move_line.py
  stock_move_purchase_uom/models/stock_picking_type.py
  stock_move_purchase_uom/pyproject.toml
  stock_move_purchase_uom/readme/CONTRIBUTORS.md
  stock_move_purchase_uom/readme/DESCRIPTION.md
  stock_move_purchase_uom/static/description/icon.png
  stock_move_purchase_uom/static/description/index.html
  stock_move_purchase_uom/tests/__init__.py
  stock_move_purchase_uom/tests/test_common.py
  stock_move_purchase_uom/tests/test_stock_move.py
  stock_move_purchase_uom/tests/test_stock_move_line.py
  stock_move_purchase_uom/tests/test_stock_move_purchase_uom.py
  stock_move_purchase_uom/views/stock_picking_type_views.xml
Labels: approved, bot is merging ⏳
